// Modèles — éducation, voyage, musique, culture, famille, animaux, enfance.
//
// Les occasions de la vie associative et personnelle : une réunion de rentrée,
// un départ, un spectacle, un faire-part, une adoption. Ce sont des supports
// qu'on fait une fois et qu'on veut réussir du premier coup — les contenus
// sont donc écrits complets, avec les mentions qu'on oublie toujours.

import type { Row } from "./design-templates";

export const ROWS_VIE: Row[] = [

  /* ══════════ Éducation & association ══════════ */

  ["fiche", "a4", "clair", "Éducation & association", "Fiche de révision", { titre: "Le théorème\nde Thalès", meta: "Classe de 3e — géométrie — durée 20 min", sur: "À RETENIR", sous: "MÉTHODE", items: ["Deux droites sécantes coupées par deux parallèles", "Les rapports de longueurs sont égaux", "La réciproque permet de prouver un parallélisme", "Repérer la configuration : papillon ou triangle", "Écrire les trois rapports dans le bon ordre", "Vérifier l'alignement avant de conclure"] }],
  ["fiche", "a4", "froid", "Éducation & association", "Fiche de méthode", { titre: "Réussir\nune dissertation", meta: "Seconde et première — 4 heures d'épreuve", sur: "LES ÉTAPES", sous: "LES PIÈGES", items: ["Analyser le sujet, mot par mot, 15 min", "Trouver trois axes, pas deux", "Rédiger l'introduction au brouillon", "Réciter le cours sans répondre", "Oublier de définir les termes", "Bâcler la conclusion faute de temps"] }],
  ["fiche", "a4", "nature", "Éducation & association", "Fiche de sciences", { titre: "La photosynthèse\nen dix lignes", meta: "Cycle 4 — SVT — schéma au dos", sur: "CE QU'IL FAUT SAVOIR", sous: "ERREURS COURANTES", items: ["La plante capte le dioxyde de carbone", "Elle produit du dioxygène et du glucose", "La lumière fournit l'énergie nécessaire", "Croire que la plante « respire » l'inverse", "Oublier que la respiration existe aussi", "Confondre chlorophylle et chloroplaste"] }],
  ["tableau", "a4", "clair", "Éducation & association", "Emploi du temps", { titre: "Emploi\ndu temps", sous: "Classe de 4e B — second trimestre.", sur: "JOUR|MATIN / APRÈS-MIDI", items: ["Lundi|Maths, français / Histoire, EPS", "Mardi|Anglais, SVT / Techno, arts", "Mercredi|Maths, physique / —", "Jeudi|Français, anglais / SVT, musique", "Vendredi|Histoire, maths / EPS, vie de classe", "Permanence|Mardi et jeudi, 16 h – 17 h"], meta: "Modifications affichées à l'entrée du bâtiment B" }],
  ["calendrier", "a4", "vif", "Éducation & association", "Réunion de rentrée", { sur: "JEUDI 10 SEPTEMBRE", gros: "10", titre: "Réunion\nde rentrée", items: ["18 h, salle polyvalente", "Présentation de l'équipe enseignante", "Organisation de l'année et sorties", "Verre de l'amitié offert à 19 h 30"] }],
  ["calendrier", "a4", "chaud", "Éducation & association", "Assemblée générale", { sur: "SAMEDI 20 JUIN", gros: "20", titre: "Assemblée\ngénérale", items: ["10 h, maison de quartier", "Rapport moral et financier", "Vote du budget 2027", "Renouvellement du bureau"] }],
  ["sommaire", "a4", "clair", "Éducation & association", "Ordre du jour", { sur: "Assemblée générale", titre: "Ordre\ndu jour", items: ["Émargement et pouvoirs|10 h", "Rapport moral|10 h 15", "Rapport financier|10 h 45", "Vote du budget|11 h 15", "Élection du bureau|11 h 45", "Questions diverses|12 h 15"], meta: "Chaque adhérent dispose d'une voix — deux pouvoirs maximum par personne" }],
  ["grille", "a4", "clair", "Éducation & association", "Ateliers proposés", { titre: "Nos ateliers\nde l'année", sous: "Toute l'année, pour tous les âges", items: ["Théâtre", "Poterie", "Guitare", "Dessin", "Danse", "Échecs"], meta: "Inscriptions du 1er au 30 juin — adhésion annuelle 25 €" }],
  ["tarif", "a4", "froid", "Éducation & association", "Cotisation annuelle", { sur: "ADHÉSION 2026-2027", gros: "25 €", sous: "par an et par personne", items: ["Accès à tous les ateliers", "Assurance comprise", "Tarif réduit 12 € pour les étudiants", "Gratuit à partir du troisième enfant", "Aide de la mairie possible"], cta: "S'inscrire en permanence" }],
  ["recrute", "a4", "froid", "Éducation & association", "Appel à bénévoles", { sur: "APPEL À BÉNÉVOLES", titre: "Deux heures\npar semaine\nsuffisent", sous: "Accompagnement scolaire — du lundi au jeudi, 17 h à 19 h", items: ["Aucun diplôme requis", "Formation assurée par l'association", "Frais de déplacement remboursés"], meta: "Renseignements : benevoles@association.fr" }],
  ["typo", "a3", "vif", "Éducation & association", "Affiche bénévolat", { titre: "ON A\nBESOIN\nDE VOUS", sous: "Six bénévoles manquent pour tenir la saison. Deux heures par semaine suffisent.", meta: "PERMANENCE LE SAMEDI, 10 H – 12 H" }],
  ["equipe", "a4", "clair", "Éducation & association", "Le bureau", { titre: "Le bureau\nde l'association", sous: "Élu en assemblée générale du 12 avril 2026.", items: ["Sofia|Présidente", "Noé|Trésorier", "Aline|Secrétaire", "Marc|Vice-président"] }],
  ["etapes", "a4", "froid", "Éducation & association", "Comment s'inscrire", { titre: "S'inscrire\nen quatre étapes", sous: "Comptez dix minutes, pièces en main.", items: ["Le dossier|À retirer en permanence ou à télécharger.", "Les pièces|Justificatif de domicile et attestation d'assurance.", "Le règlement|Chèque, espèces ou aide de la mairie.", "La confirmation|Envoyée sous une semaine par e-mail."] }],
  ["checklist", "a4", "clair", "Éducation & association", "Liste de fournitures", { sur: "Rentrée 2026", titre: "Fournitures\nde 6e", items: ["Un cahier grand format par matière", "Une trousse complète, deux stylos par couleur", "Une calculatrice collège", "Un compas, une équerre, un rapporteur", "Un agenda, pas un cahier de textes", "Une clé USB de 8 Go minimum", "Une tenue de sport en sac séparé"], meta: "Liste établie par l'équipe pédagogique — aucun achat de marque imposé" }],
  ["faq", "a4", "clair", "Éducation & association", "Questions des parents", { sur: "Vous nous demandez", titre: "Quatre réponses\navant la rentrée", items: ["Quels horaires ?|8 h 30 à 16 h 30, garderie de 7 h 30 à 18 h 30.", "Comment inscrire à la cantine ?|En ligne, avant le 25 du mois précédent.", "Que faire en cas d'absence ?|Prévenir avant 9 h, justificatif au retour.", "Y a-t-il des aides ?|Quotient familial appliqué, dossier en mairie."], meta: "Secrétariat : 05 56 00 00 00, de 8 h à 17 h" }],
  ["horaires", "a4", "terre", "Éducation & association", "Horaires de la médiathèque", { sur: "Médiathèque", titre: "Horaires", items: ["Lundi|Fermé", "Mardi|14 h – 18 h", "Mercredi|10 h – 18 h", "Jeudi|14 h – 18 h", "Vendredi|14 h – 19 h", "Samedi|10 h – 17 h"], meta: "GRATUIT POUR LES MOINS DE 18 ANS — INSCRIPTION AVEC UN JUSTIFICATIF" }],
  ["certificat", "paysage", "chic", "Éducation & association", "Diplôme de fin d'année", { sur: "DIPLÔME", titre: "Camille Durand", auteur: "Sofia Bernard, présidente", sous: "a suivi l'atelier théâtre pendant toute l'année scolaire et participé au spectacle de fin d'année.", meta: "BORDEAUX, LE 21 JUIN 2026" }],
  ["progression", "a4", "vif", "Éducation & association", "Collecte en cours", { sur: "Collecte", titre: "Pour équiper\nla salle", gros: "64", sous: "Il manque 1 800 € pour le nouveau plancher de danse.", meta: "PARTICIPER : CAGNOTTE EN LIGNE OU EN PERMANENCE" }],
  ["stats", "a4", "tech", "Éducation & association", "Bilan de l'année", { sur: "Année 2025-2026", titre: "L'année\nen trois chiffres", items: ["186|adhérents", "12|ateliers", "38|bénévoles"], meta: "Rapport complet remis en assemblée générale" }],
  ["chrono", "a4", "chic", "Éducation & association", "Calendrier scolaire", { titre: "L'année\nen quatre temps", sous: "Les rendez-vous à ne pas manquer.", items: ["Sept.|Réunion de rentrée.", "Déc.|Spectacle de Noël.", "Mars|Portes ouvertes.", "Juin|Fête de fin d'année."], meta: "Dates précises communiquées un mois à l'avance" }],
  ["question", "carre", "clair", "Éducation & association", "Consultation des adhérents", { sur: "Consultation", titre: "Quels horaires\nvous arrangeraient\npour les ateliers ?", sous: "Répondez au questionnaire avant le 30 mai, votre avis décide du planning." }],
  ["contact", "a5", "clair", "Éducation & association", "Coordonnées de l'association", { sur: "Nous joindre", titre: "L'association\nen pratique", sous: "Permanence tous les samedis matin.", items: ["05 56 00 00 00", "contact@association.fr", "Maison de quartier, 4 place du Marché", "Permanence : samedi 10 h – 12 h"], meta: "Association loi 1901 — RNA W000000000" }],

  /* ══════════ Voyage & saison ══════════ */

  ["grille", "pin", "froid", "Voyage & saison", "Itinéraire en six étapes", { titre: "La Sicile\nen six étapes", sous: "Deux semaines, en voiture, hors août", items: ["Palerme", "Cefalù", "Etna", "Taormine", "Syracuse", "Agrigente"], meta: "Itinéraire détaillé, budget et hébergements sur le blog" }],
  ["grille", "pin", "nature", "Voyage & saison", "Six randonnées", { titre: "Six randonnées\nfaciles", sous: "Moins de 400 m de dénivelé, toutes balisées", items: ["Cap Ferret", "Dune du Pilat", "Vallée du Ciron", "Étangs de Hostens", "Bords de Dordogne", "Forêt de la Double"], meta: "Traces GPX téléchargeables — durée 2 h à 4 h" }],
  ["fiche", "pin", "chaud", "Voyage & saison", "Fiche destination", { titre: "Partir\nen Sicile", meta: "Meilleure période : mai-juin et septembre — 2 semaines", sur: "À PRÉVOIR", sous: "SUR PLACE", items: ["Voiture de location réservée d'avance", "Crème solaire indice élevé", "Chaussures fermées pour l'Etna", "Réserver l'Etna deux jours avant", "Éviter la côte en août", "Privilégier les routes intérieures"] }],
  ["checklist", "pin", "clair", "Voyage & saison", "Valise pour une semaine", { sur: "Une semaine, un bagage cabine", titre: "Ce qu'il faut\nvraiment", items: ["Cinq hauts, trois bas, une veste", "Une paire de chaussures en plus, pas deux", "Trousse de toilette en format cabine", "Adaptateur et batterie externe", "Copies numériques des documents", "Un sac pliable pour le retour", "Une trousse à pharmacie minimale"], meta: "Testé sur six voyages : rien n'a manqué" }],
  ["chrono", "large", "froid", "Voyage & saison", "Programme de séjour", { titre: "Quatre jours,\nquatre villes", sous: "Un rythme tenable, sans course.", items: ["J1|Arrivée et vieille ville.", "J2|Musée et bord de mer.", "J3|Excursion en montagne.", "J4|Marché puis départ."], meta: "Détail des trajets et des horaires dans le carnet complet" }],
  ["frise", "pin", "chic", "Voyage & saison", "Carnet de route", { titre: "Trois jours\nsans téléphone", sous: "Un refuge, deux cols, et le silence qui va avec.", items: ["Jour 1|La main cherche la poche toutes les dix minutes.", "Jour 2|Elle oublie.", "Jour 3|On regarde vraiment le paysage.", "Retour|Impression d'avoir gagné du temps.", "Depuis|Le téléphone reste au fond du sac."], meta: "Récit complet et itinéraire sur le blog" }],
  ["montagne", "pin", "nature", "Voyage & saison", "Épingle randonnée", { sur: "Itinéraire", titre: "Le tour\ndes lacs\nen trois jours", sous: "38 kilomètres, 1 900 m de dénivelé, deux refuges gardés.", meta: "RÉSERVATION DES REFUGES INDISPENSABLE" }],
  ["vagues", "pin", "froid", "Voyage & saison", "Épingle bord de mer", { sur: "Bassin d'Arcachon", titre: "Cinq plages\nsans monde\nen juillet", sous: "Accès à pied, parking gratuit, aucune buvette.", meta: "COORDONNÉES GPS DANS L'ARTICLE" }],
  ["soleil", "carre", "chaud", "Voyage & saison", "Ouverture de saison", { sur: "Ouverture", titre: "La saison\ncommence", sous: "Camping ouvert du 1er avril au 30 octobre, réservations en ligne.", meta: "TARIFS INCHANGÉS DEPUIS 2024" }],
  ["calendrier", "carre", "nature", "Voyage & saison", "Date d'ouverture", { sur: "MERCREDI 1ER AVRIL", gros: "01", titre: "Le camping\nrouvre", items: ["Tous les jours de 8 h à 20 h", "Location de vélos sur place", "Terrasse et snack ouverts", "Animaux acceptés, tenus en laisse"] }],
  ["ruban", "carre", "chaud", "Voyage & saison", "Fermeture annuelle", { sur: "Information", titre: "FERMÉ", sous: "Fermeture annuelle du 1er au 21 août. Réouverture le 22 à 8 h.", meta: "MERCI DE VOTRE COMPRÉHENSION" }],
  ["tableau", "a4", "clair", "Voyage & saison", "Tarifs de location", { titre: "Tarifs\n2026", sous: "Par nuit, taxe de séjour non comprise.", sur: "PÉRIODE|EMPLACEMENT / MOBIL-HOME", items: ["Avril – juin|18 € / 62 €", "Juillet|26 € / 94 €", "Août|29 € / 108 €", "Septembre|20 € / 68 €", "Octobre|16 € / 55 €", "Semaine (7 nuits)|-10 %"], meta: "Taxe de séjour : 0,80 € par nuit et par adulte" }],
  ["horaires", "a5", "terre", "Voyage & saison", "Horaires de l'accueil", { sur: "Accueil du camping", titre: "Horaires", items: ["Avril – juin|9 h – 12 h · 15 h – 19 h", "Juillet – août|8 h – 20 h, sans interruption", "Septembre – octobre|9 h – 12 h · 15 h – 18 h", "Arrivées|À partir de 15 h", "Départs|Avant 11 h"], meta: "ARRIVÉE TARDIVE POSSIBLE, PRÉVENIR AVANT 18 H" }],
  ["equipe", "carre", "clair", "Voyage & saison", "L'équipe du camping", { titre: "L'équipe\nvous accueille", sous: "D'avril à octobre, toujours les mêmes.", items: ["Camille|Accueil", "Noé|Animations", "Aline|Snack", "Marc|Entretien"] }],
  ["faq", "a4", "clair", "Voyage & saison", "Questions des vacanciers", { sur: "Avant de réserver", titre: "Quatre réponses\nutiles", items: ["Les animaux sont-ils acceptés ?|Oui, tenus en laisse, 3 € par nuit.", "Y a-t-il le wifi ?|À l'accueil et au snack, gratuit.", "Peut-on arriver tard ?|Oui, prévenez avant 18 h, on laisse la clé.", "Quelle est la politique d'annulation ?|Gratuite jusqu'à 15 jours avant."], meta: "05 56 00 00 00 — camping@exemple.fr" }],
  ["typo", "story", "froid", "Voyage & saison", "Compte à rebours vacances", { titre: "J-7", sous: "Avant trois semaines sans réveil.", meta: "Valises presque prêtes" }],
  ["polaroid", "carre", "terre", "Voyage & saison", "Souvenir de voyage", { sur: "Carnet", titre: "Le marché\ndu mardi matin", emoji: "🧺", meta: "Sarlat, 8 h 10" }],
  ["question", "story", "chaud", "Voyage & saison", "Question de voyageur", { sur: "Dilemme de départ", titre: "Sac à dos\nou valise\nà roulettes ?", sous: "Ça dépend surtout du sol, pas du poids." }],
  ["magazine", "pin", "chic", "Voyage & saison", "Couverture de carnet", { sur: "CARNET", meta: "SICILE — MAI 2026", titre: "Deux\nsemaines\nau sud", sous: "Six cents kilomètres, quatorze jours, et pas une réservation d'avance.", items: ["Ce que l'on a payé, vraiment", "Trois villages à ne pas manquer", "Ce qu'on referait autrement"] }],

  /* ══════════ Podcast & musique ══════════ */

  ["couverture", "pod", "sombre", "Podcast & musique", "Pochette de podcast", { sur: "Podcast", titre: "Les gens\nqui font", sous: "Des métiers racontés par ceux qui les exercent. Un épisode par semaine.", auteur: "Animé par Sofia Bernard" }],
  ["couverture", "pod", "chaud", "Podcast & musique", "Pochette conversation", { sur: "Épisode 12", titre: "Se lancer\nà quarante ans", sous: "Reconversion, doutes, et ce que personne ne dit sur l'argent.", auteur: "Avec Marc Vidal, ancien cadre devenu boulanger" }],
  ["disque", "pod", "vif", "Podcast & musique", "Pochette ronde", { sur: "Nouveau", titre: "Saison 3", sous: "Douze épisodes, un par semaine, dès le 6 septembre.", meta: "SUR TOUTES LES PLATEFORMES" }],
  ["neon", "pod", "tech", "Podcast & musique", "Pochette néon", { gros: "S3", titre: "La saison trois commence", sous: "Toujours le jeudi, toujours sans montage." }],
  ["playlist", "carre", "sombre", "Podcast & musique", "Liste d'épisodes", { emoji: "🎙️", titre: "Par où\ncommencer", sous: "Six épisodes pour comprendre la série", items: ["Le boulanger|41:12", "La juge|38:44", "Le berger|52:03", "La sage-femme|46:19", "Le libraire|33:57", "La routière|49:28"], meta: "Tous les épisodes sur lesgensquifont.fr" }],
  ["playlist", "carre", "vif", "Podcast & musique", "Liste de morceaux", { emoji: "🎵", titre: "Premier\nalbum", sous: "Six titres, enregistrés en trois jours", items: ["Rue des Halles|3:42", "Marée basse|4:18", "Contre-jour|2:55", "Lundi gris|5:07", "Dernier client|3:29", "On ferme|6:11"], meta: "Disponible en vinyle et en numérique" }],
  ["evenement", "a3", "sombre", "Podcast & musique", "Affiche de concert", { sur: "En concert", titre: "Trio\nAubépine", meta: "VENDREDI 12 JUIN — 20 H 30", sous: "Salle des Fêtes, place du Marché", cta: "Prévente 12 € — sur place 15 €" }],
  ["billet", "billet", "sombre", "Podcast & musique", "Billet de concert", { sur: "BILLET", titre: "TRIO AUBÉPINE", gros: "12€", meta: "VEN. 12 JUIN — 20 H 30", sous: "Placement libre — ouverture des portes 19 h 45 — non remboursable" }],
  ["chrono", "carre", "chic", "Podcast & musique", "Dates de tournée", { titre: "Quatre dates\nau printemps", sous: "Billetterie ouverte le 1er mars.", items: ["12 avril|Bordeaux.", "19 avril|Toulouse.", "26 avril|Lyon.", "3 mai|Nantes."], meta: "Salles et horaires détaillés sur le site" }],
  ["sceau", "carre", "chic", "Podcast & musique", "Sceau d'album", { sur: "PREMIER ALBUM", gros: "2026", meta: "ENREGISTRÉ EN TROIS JOURS", titre: "Trio Aubépine", sous: "Six titres, aucun retour en studio." }],
  ["stats", "carre", "tech", "Podcast & musique", "Bilan de saison", { sur: "Saison 2", titre: "Une saison\nen trois chiffres", items: ["24|épisodes", "180 h|d'entretiens", "0|publicité"], meta: "Le podcast reste financé uniquement par ses auditeurs" }],
  ["carrousel", "carre", "tech", "Podcast & musique", "Extrait d'épisode", { meta: "EXTRAIT", sur: "Épisode 12", titre: "« J'ai fait\nmes comptes\navant de\ndémissionner »", sous: "Quinze mois d'économies, un budget écrit, et une date limite. Sans ça, il dit qu'il n'aurait pas tenu.", cta: "Épisode complet en bio" }],
  ["bulle", "carre", "pastel", "Podcast & musique", "Citation d'invité", { sur: "Épisode 12", titre: "« On ne se reconvertit pas par passion. On se reconvertit parce qu'on ne tient plus. »", auteur: "Marc Vidal, boulanger", sous: "Ancien cadre, reconverti à 41 ans" }],
  ["progression", "carre", "vif", "Podcast & musique", "Financement participatif", { sur: "Financement", titre: "Le deuxième\nalbum", gros: "71", sous: "Il manque 2 900 € pour financer le pressage vinyle.", meta: "CAGNOTTE OUVERTE JUSQU'AU 30 JUIN" }],
  ["recrute", "carre", "froid", "Podcast & musique", "Recherche de musicien", { sur: "ON CHERCHE", titre: "Un batteur\nou une batteuse", sous: "Répétitions le mardi soir — Bordeaux — répertoire original", items: ["Local de répétition équipé", "Quatre dates déjà calées", "Aucun niveau minimum exigé"], meta: "Écrivez à trio@exemple.fr" }],

  /* ══════════ Culture & spectacle ══════════ */

  ["evenement", "a3", "chic", "Culture & spectacle", "Affiche de théâtre", { sur: "Création", titre: "Les Justes", meta: "DU 14 AU 18 NOVEMBRE — 20 H 30", sous: "Théâtre municipal — durée 1 h 45 sans entracte", cta: "Tarif plein 18 € — réduit 12 € — moins de 26 ans 8 €" }],
  ["evenement", "a3", "sombre", "Culture & spectacle", "Affiche de danse", { sur: "Danse contemporaine", titre: "Corps\ncommuns", meta: "VENDREDI 12 DÉCEMBRE — 20 H", sous: "Compagnie du Port — sept danseurs", cta: "Rencontre avec l'équipe après la représentation" }],
  ["magazine", "a3", "chic", "Culture & spectacle", "Programme de saison", { sur: "SAISON", meta: "2026-2027 — THÉÂTRE MUNICIPAL", titre: "Vingt-\nquatre\nsoirs", sous: "Théâtre, danse et musique, une saison construite avec le public.", items: ["Douze spectacles, six créations", "Abonnement dès 60 €", "Tarif unique moins de 26 ans"] }],
  ["sommaire", "a4", "clair", "Culture & spectacle", "Programme détaillé", { sur: "Saison 2026-2027", titre: "Le programme", items: ["Quatuor à cordes|10 oct.", "Les Justes|14 nov.", "Corps communs|12 déc.", "Trio Aubépine|16 janv.", "Création jeune public|13 févr.", "Bal de clôture|20 mars"], meta: "Billetterie ouverte le 1er septembre — 05 56 00 00 00" }],
  ["tableau", "a4", "clair", "Culture & spectacle", "Grille tarifaire", { titre: "Tarifs\net abonnements", sous: "Sur présentation d'un justificatif.", sur: "TARIF|MONTANT", items: ["Plein|18 €", "Réduit|12 €", "Moins de 26 ans|8 €", "Abonnement 4 spectacles|56 €", "Abonnement 6 spectacles|78 €", "Groupe (dès 10)|10 € / personne"], meta: "Placement libre — ouverture des portes 30 minutes avant" }],
  ["coins", "a3", "chic", "Culture & spectacle", "Affiche d'exposition", { sur: "Exposition", titre: "Traces", sous: "Trente ans de photographies argentiques, tirages d'époque.", meta: "GALERIE DU PORT — DU 3 AVRIL AU 30 MAI — ENTRÉE LIBRE" }],
  ["cadre", "a5", "chic", "Culture & spectacle", "Carton de vernissage", { sur: "Vernissage", titre: "Traces", sous: "En présence de l'auteur. Un verre sera servi à partir de 18 h 30.", meta: "VENDREDI 3 AVRIL — GALERIE DU PORT, 8 QUAI VAUBAN" }],
  ["horaires", "a4", "terre", "Culture & spectacle", "Horaires de la galerie", { sur: "Galerie", titre: "Horaires\net accès", items: ["Lundi – mardi|Fermé", "Mercredi – vendredi|14 h – 19 h", "Samedi|11 h – 19 h", "Dimanche|14 h – 18 h", "Visites guidées|Samedi 15 h"], meta: "ENTRÉE LIBRE — ACCÈS PMR PAR LA COUR" }],
  ["equipe", "a4", "clair", "Culture & spectacle", "La compagnie", { titre: "La compagnie\ndu Port", sous: "Sept personnes, une création par an.", items: ["Sofia|Mise en scène", "Marc|Scénographie", "Aline|Lumières", "Noé|Son"] }],
  ["certificat", "paysage", "sombre", "Culture & spectacle", "Prix de concours", { sur: "PREMIER PRIX", titre: "Aline Roux", auteur: "Le jury du concours", sous: "s'est vu décerner le premier prix du concours amateur, catégorie noir et blanc.", meta: "FESTIVAL DES HALLES — JUILLET 2026" }],
  ["citation", "carre", "chic", "Culture & spectacle", "Citation de presse", { titre: "« Une heure\nquarante-cinq\nsans un temps\nmort. »", auteur: "Le Journal du Sud-Ouest", sous: "À propos des Justes, novembre 2026" }],
  ["notation", "carre", "clair", "Culture & spectacle", "Avis de spectateur", { gros: "5/5", sur: "sur 128 avis de spectateurs", titre: "On sort de là sans savoir quoi dire, et on en parle encore trois jours après.", auteur: "Camille D.", meta: "Avis recueilli à la sortie — novembre 2026" }],
  ["progression", "carre", "vif", "Culture & spectacle", "Places restantes", { sur: "Billetterie", titre: "Il reste\npeu de places", gros: "88", sous: "Douze pour cent des places encore disponibles pour la première.", meta: "RÉSERVATION EN LIGNE OU AU 05 56 00 00 00" }],
  ["ruban", "carre", "chaud", "Culture & spectacle", "Représentation complète", { sur: "Merci", titre: "COMPLET", sous: "La représentation du samedi affiche complet. Une date supplémentaire est ouverte le dimanche.", meta: "BILLETTERIE : 05 56 00 00 00" }],

  /* ══════════ Mariage & famille ══════════ */

  ["arche", "a5", "chic", "Mariage & famille", "Faire-part de mariage", { sur: "Nous nous marions", titre: "Sofia\n& Marc", sous: "Le samedi 12 septembre 2026, à partir de 16 h, au domaine de la Combe.", meta: "RÉPONSE SOUHAITÉE AVANT LE 1ER AOÛT" }],
  ["cadre", "a5", "pastel", "Mariage & famille", "Faire-part sobre", { sur: "Save the date", titre: "12.09.2026", sous: "Sofia et Marc se marient. L'invitation officielle suivra, gardez la date.", meta: "DOMAINE DE LA COMBE — SAINT-ÉMILION" }],
  ["monogramme", "a5", "chic", "Mariage & famille", "Monogramme des mariés", { gros: "S&M", titre: "Sofia & Marc", sous: "12 SEPTEMBRE 2026" }],
  ["frise", "a5", "chic", "Mariage & famille", "Déroulé de la journée", { titre: "Le déroulé\nde la journée", sous: "Rien d'obligatoire, tout est fléché.", items: ["16 h|Cérémonie sous les chênes.", "17 h 30|Vin d'honneur.", "20 h|Dîner servi à table.", "22 h 30|Ouverture du bal.", "2 h|Soupe à l'oignon."], meta: "Voiturier assuré jusqu'à 3 h — navette vers le centre à 1 h" }],
  ["menu", "a5", "chic", "Mariage & famille", "Menu de mariage", { sur: "Menu", titre: "Dîner du 12 septembre", items: ["Velouté de courge, huile de noisette|Entrée", "Saint-jacques poêlées, purée de céleri|Poisson", "Filet de bœuf, jus corsé, légumes anciens|Viande", "Fromages affinés de la région|Fromage", "Pièce montée, fruits rouges|Dessert"], meta: "Menus végétarien et sans gluten disponibles — signalés au service" }],
  ["billet", "billet", "chic", "Mariage & famille", "Marque-place", { sur: "TABLE 4", titre: "CAMILLE DURAND", gros: "04", meta: "12 SEPTEMBRE 2026", sous: "Menu adapté signalé au service" }],
  ["tableau", "a4", "chic", "Mariage & famille", "Plan de table", { titre: "Plan\nde table", sous: "Cinq tables de huit, une table d'enfants.", sur: "TABLE|INVITÉS", items: ["1 — Chênes|Familles proches", "2 — Vignes|Amis d'enfance", "3 — Port|Collègues de Sofia", "4 — Halles|Collègues de Marc", "5 — Combe|Voisins et amis", "6 — Enfants|Moins de 12 ans"], meta: "Plan affiché à l'entrée de la salle" }],
  ["checklist", "a4", "clair", "Mariage & famille", "Check-list des mariés", { sur: "J-30", titre: "Ce qu'il reste\nà faire", items: ["Confirmer le nombre définitif au traiteur", "Récupérer les alliances", "Valider le plan de table", "Confirmer la navette du soir", "Préparer les discours, vraiment", "Prévoir un parapluie par table", "Désigner qui range le lendemain"], meta: "Le reste attendra, et personne ne s'en apercevra" }],
  ["cadre", "a5", "pastel", "Mariage & famille", "Faire-part de naissance", { sur: "Elle est là", titre: "Camille", sous: "Née le 3 avril 2026 à 6 h 12, 3,2 kg, et déjà une opinion sur tout.", meta: "SOFIA ET MARC BERTHIER" }],
  ["pois", "a5", "pastel", "Mariage & famille", "Faire-part de baptême", { sur: "Baptême", titre: "Camille", sous: "Le samedi 20 juin 2026 à 11 h, église Saint-Louis, suivi d'un déjeuner.", meta: "RÉPONSE SOUHAITÉE AVANT LE 1ER JUIN" }],
  ["cadre", "a5", "chic", "Mariage & famille", "Carte de remerciement", { sur: "Merci", titre: "Pour votre\nprésence", sous: "Votre venue a rendu cette journée plus douce. Nous ne l'oublierons pas.", meta: "SOFIA ET MARC — SEPTEMBRE 2026" }],
  ["calendrier", "a5", "vif", "Mariage & famille", "Invitation anniversaire", { sur: "SAMEDI 6 JUIN", gros: "06", titre: "Les 40 ans\nde Marc", items: ["À partir de 19 h, chez nous", "Barbecue, apportez ce que vous voulez boire", "Il ne sait rien, arrivez avant 19 h", "Réponse par message avant le 1er juin"] }],
  ["pois", "carre", "pastel", "Mariage & famille", "Invitation goûter", { sur: "Anniversaire", titre: "Camille\na 5 ans", sous: "Mercredi 14 mai, de 15 h à 18 h, au parc du Port. Repli à la maison si pluie.", meta: "RÉPONSE PAR MESSAGE AVANT LE 10 MAI" }],
  ["sceau", "carre", "chic", "Mariage & famille", "Cachet des mariés", { sur: "SOFIA & MARC", gros: "S&M", meta: "12.09.2026", titre: "Merci d'être venus", sous: "Chaque enveloppe a été cachetée à la main." }],
  ["progression", "carre", "pastel", "Mariage & famille", "Compte à rebours", { sur: "Avant le grand jour", titre: "Plus que\ntrente jours", gros: "92", sous: "Il reste le plan de table, les alliances, et beaucoup de sommeil à rattraper.", meta: "12 SEPTEMBRE 2026" }],

  /* ══════════ Animaux ══════════ */

  ["fiche", "a4", "nature", "Animaux", "Fiche d'adoption", { titre: "Roux,\nchat européen,\n3 ans", meta: "Identifié, vacciné, stérilisé — adoption 120 €", sur: "SON CARACTÈRE", sous: "CE QU'IL LUI FAUT", items: ["Câlin mais indépendant", "S'entend avec les autres chats", "Peur des enfants très jeunes", "Un accès extérieur sécurisé", "Une maison calme", "Pas de chien"] }],
  ["fiche", "a4", "chaud", "Animaux", "Fiche chien à l'adoption", { titre: "Nougat,\ncroisé berger,\n5 ans", meta: "Identifié, vacciné, castré — adoption 250 €", sur: "SON CARACTÈRE", sous: "CE QU'IL LUI FAUT", items: ["Doux, très attaché à l'humain", "Marche bien en laisse", "Aboie quand il reste seul longtemps", "Un jardin clôturé d'1,60 m", "Deux sorties longues par jour", "Une présence en journée"] }],
  ["polaroid", "carre", "pastel", "Animaux", "Portrait à l'adoption", { sur: "À adopter", titre: "Roux attend\ndepuis 8 mois", emoji: "🐱", meta: "Refuge du Port — 05 56 00 00 00" }],
  ["progression", "carre", "vif", "Animaux", "Collecte pour le refuge", { sur: "Collecte d'hiver", titre: "Pour chauffer\nle chenil", gros: "58", sous: "Il manque 2 100 € avant les premières gelées.", meta: "DONS EN LIGNE OU AU REFUGE" }],
  ["tableau", "a4", "clair", "Animaux", "Tarifs vétérinaires", { titre: "Nos tarifs", sous: "Prix TTC, consultation comprise sauf mention contraire.", sur: "ACTE|TARIF", items: ["Consultation|42 €", "Vaccination annuelle|65 €", "Identification par puce|58 €", "Stérilisation chatte|140 €", "Castration chat|85 €", "Urgence de nuit|+ 60 €"], meta: "Facilités de paiement possibles — nous en parler avant l'intervention" }],
  ["horaires", "a5", "nature", "Animaux", "Horaires du cabinet vétérinaire", { sur: "Cabinet vétérinaire", titre: "Horaires", items: ["Lundi – vendredi|9 h – 12 h · 14 h – 19 h", "Samedi|9 h – 12 h", "Dimanche|Urgences uniquement", "Urgences|24 h / 24 au 05 56 00 00 01"], meta: "CONSULTATIONS SUR RENDEZ-VOUS — URGENCES SANS RENDEZ-VOUS" }],
  ["checklist", "a4", "clair", "Animaux", "Avant d'adopter", { sur: "Réfléchir avant", titre: "Sept questions\nà se poser", items: ["Qui s'en occupe pendant les vacances ?", "Le budget vétérinaire est-il prévu ?", "Combien d'heures seul par jour ?", "Le logement le permet-il, bail compris ?", "Quelqu'un est-il allergique ?", "L'engagement est de quinze ans", "Que se passe-t-il si je déménage ?"], meta: "Un abandon sur deux vient d'une question non posée avant" }],
  ["liste", "a4", "nature", "Animaux", "Conseils de saison", { sur: "Été", titre: "Cinq réflexes\nquand il fait\nchaud", items: ["Jamais dans une voiture, même à l'ombre", "Promenade avant 9 h et après 20 h", "Vérifier la température du bitume à la main", "Eau fraîche renouvelée trois fois par jour", "Ne jamais raser un chien à poil double"], meta: "En cas de coup de chaleur, appelez immédiatement" }],
  ["faq", "a4", "clair", "Animaux", "Questions d'adoptants", { sur: "Adoption", titre: "Quatre réponses\nfranches", items: ["Puis-je adopter en appartement ?|Oui, selon l'animal. On en discute ensemble.", "Y a-t-il une période d'essai ?|Quinze jours, et un retour reste possible après.", "Que comprend le prix ?|Identification, vaccins, stérilisation, bilan de santé.", "Faites-vous des visites ?|Oui, une avant et une un mois après."], meta: "Refuge du Port — 05 56 00 00 00" }],
  ["evenement", "a3", "chaud", "Animaux", "Journée portes ouvertes du refuge", { sur: "Portes ouvertes", titre: "Venez\nles rencontrer", meta: "DIMANCHE 17 MAI — 10 H À 18 H", sous: "Refuge du Port, route de Bassens", cta: "Entrée libre — buvette au profit du refuge" }],
  ["recrute", "a4", "froid", "Animaux", "Appel aux familles d'accueil", { sur: "NOUS CHERCHONS", titre: "Des familles\nd'accueil", sous: "Quelques semaines à quelques mois — tous secteurs", items: ["Nourriture et frais vétérinaires pris en charge", "Accompagnement par un bénévole référent", "Aucune obligation d'adopter ensuite"], meta: "Candidatures : accueil@refugeduport.fr" }],
  ["temoignage", "carre", "pastel", "Animaux", "Témoignage d'adoptant", { emoji: "🐾", titre: "« On venait voir. On est repartis avec Nougat, et c'était la bonne décision. »", auteur: "Famille Roux", sous: "Adoption de mars 2026" }],

  /* ══════════ Enfance & jeunesse ══════════ */

  ["pois", "a4", "pastel", "Enfance & jeunesse", "Affiche d'atelier enfants", { sur: "Bibliothèque municipale", titre: "L'heure\ndu conte", sous: "Tous les mercredis à 15 h, pour les 3 à 7 ans, accompagnés d'un adulte.", meta: "ENTRÉE LIBRE — SANS INSCRIPTION" }],
  ["rayures", "a3", "vif", "Enfance & jeunesse", "Affiche de kermesse", { sur: "École Jean Moulin", titre: "GRANDE\nKERMESSE", sous: "Jeux, stands, tombola et barbecue. Bénéfices reversés à la coopérative scolaire.", meta: "SAMEDI 21 JUIN — 11 H À 18 H" }],
  ["calendrier", "a4", "vif", "Enfance & jeunesse", "Stage de vacances", { sur: "DU 20 AU 24 JUILLET", gros: "20", titre: "Stage\nmulti-activités", items: ["De 9 h à 17 h, garderie dès 8 h", "Pour les 6 à 11 ans", "120 € la semaine, repas compris", "Vingt places, inscription en mairie"] }],
  ["tableau", "a4", "clair", "Enfance & jeunesse", "Planning du centre de loisirs", { titre: "Planning\nde la semaine", sous: "Vacances de printemps — 6 à 11 ans.", sur: "JOUR|ACTIVITÉ", items: ["Lundi|Grand jeu dans le parc", "Mardi|Atelier cuisine", "Mercredi|Sortie piscine", "Jeudi|Land art en forêt", "Vendredi|Spectacle des enfants", "Chaque jour|Temps calme après le repas"], meta: "Prévoir une casquette, une gourde et une tenue qui peut se salir" }],
  ["checklist", "a4", "clair", "Enfance & jeunesse", "Trousseau de colonie", { sur: "Séjour d'une semaine", titre: "Le trousseau", items: ["Sept tenues complètes, marquées au nom", "Une tenue de pluie et des bottes", "Un maillot de bain et une serviette", "Une trousse de toilette complète", "Un sac de couchage et un drap-housse", "Une lampe de poche", "Un livre, un jeu de cartes, pas d'écran"], meta: "Tout doit être marqué — le linge non marqué finit toujours par disparaître" }],
  ["faq", "a4", "clair", "Enfance & jeunesse", "Questions des parents", { sur: "Avant le séjour", titre: "Quatre réponses\nrassurantes", items: ["Puis-je appeler mon enfant ?|Un créneau chaque soir de 18 h à 19 h.", "Et s'il ne mange pas de tout ?|Les régimes sont notés à l'inscription et respectés.", "Qui encadre ?|Un animateur pour huit enfants, tous diplômés.", "Que faire en cas de problème ?|Nous appelons immédiatement, jamais après coup."], meta: "Direction du séjour : 06 00 00 00 00, joignable 24 h/24" }],
  ["etapes", "a4", "vif", "Enfance & jeunesse", "Règles de vie", { titre: "Nos quatre\nrègles de vie", sous: "Elles tiennent en quatre phrases, et on s'y tient.", items: ["On se respecte|Aucune moquerie, aucune violence, jamais.", "On prévient|On dit toujours à un adulte où l'on va.", "On range|Ce qu'on sort, on le remet.", "On participe|Chacun aide, à son rythme."] }],
  ["grille", "a4", "pastel", "Enfance & jeunesse", "Six activités", { titre: "Six activités\nau choix", sous: "Une inscription par trimestre", items: ["Poterie", "Théâtre", "Cirque", "Danse", "Échecs", "Nature"], meta: "Inscriptions en mairie — 60 € le trimestre, quotient familial appliqué" }],
  ["certificat", "paysage", "vif", "Enfance & jeunesse", "Diplôme du jeune participant", { sur: "DIPLÔME", titre: "Camille Durand", auteur: "L'équipe d'animation", sous: "a participé au séjour d'été avec courage, bonne humeur, et une vraie capacité à ranger sa tente.", meta: "JUILLET 2026 — CENTRE DE LA COMBE" }],
  ["progression", "carre", "vif", "Enfance & jeunesse", "Compte à rebours vacances", { sur: "Avant le départ", titre: "Plus que\ncinq jours", gros: "85", sous: "Trousseau marqué, fiche sanitaire rendue, il ne manque que le sac de couchage.", meta: "RENDEZ-VOUS SAMEDI 8 H, DEVANT L'ÉCOLE" }],
  ["contact", "a5", "clair", "Enfance & jeunesse", "Contacts du centre", { sur: "Nous joindre", titre: "En cas\nde besoin", sous: "Une personne d'astreinte, jour et nuit, pendant tout le séjour.", items: ["Direction : 06 00 00 00 00", "Centre : 05 56 00 00 00", "Appels enfants : 18 h – 19 h", "urgence@centre-combe.fr"], meta: "Centre de la Combe — 33 Saint-Émilion" }],
  ["horaires", "a5", "clair", "Enfance & jeunesse", "Horaires de la garderie", { sur: "Garderie périscolaire", titre: "Horaires", items: ["Matin|7 h 30 – 8 h 20", "Midi|11 h 45 – 13 h 20", "Soir|16 h 30 – 18 h 30", "Mercredi|7 h 30 – 18 h 30", "Vacances|Centre de loisirs"], meta: "TOUT RETARD APRÈS 18 H 30 EST FACTURÉ — MERCI DE PRÉVENIR" }],

];
