// Modèles — documents, présentations et supports imprimés.
//
// Ce qui se signe, se classe ou se projette : notes, rapports, procédures,
// diapositives, affichages obligatoires. Ces documents sont rarement beaux et
// souvent urgents ; les avoir déjà structurés — avec les mentions légales et
// les colonnes au bon endroit — évite de les refaire à chaque fois.

import type { Row } from "./design-templates";

export const ROWS_DOC: Row[] = [

  /* ══════════ CV & document — courriers et formulaires ══════════ */

  ["entete", "a4", "clair", "CV & document", "Courrier de résiliation", { titre: "Sofia Bernard", sur: "Courrier recommandé", sous: "12 rue du Marché\n33000 Bordeaux\n06 00 00 00 00", meta: "OBJET : RÉSILIATION DU CONTRAT N° ____________", items: ["Madame, Monsieur,", "Je vous informe de ma décision de résilier le contrat référencé ci-dessus, conformément aux conditions générales et au délai de préavis applicable.", "Je vous remercie de bien vouloir m'adresser une confirmation écrite de cette résiliation, ainsi que le décompte définitif.", "Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées."], cta: "Fait à Bordeaux, le ____ / ____ / ______ — Signature" }],
  ["entete", "a4", "clair", "CV & document", "Courrier de réclamation", { titre: "Sofia Bernard", sur: "Réclamation", sous: "12 rue du Marché\n33000 Bordeaux\n06 00 00 00 00", meta: "OBJET : RÉCLAMATION — COMMANDE N° ____________", items: ["Madame, Monsieur,", "Le ____ / ____ / ______, j'ai passé la commande référencée ci-dessus. À ce jour, elle n'a pas été livrée dans les conditions annoncées.", "Je vous demande de bien vouloir procéder à ____________ dans un délai de quinze jours. À défaut, je me réserve la possibilité de saisir le médiateur de la consommation.", "Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées."], cta: "Pièces jointes : copie de la commande, copie du justificatif de paiement" }],
  ["entete", "a4", "clair", "CV & document", "Courrier de demande de congé", { titre: "Sofia Bernard", sur: "Demande de congé", sous: "Service des opérations\nPoste n° 0000", meta: "OBJET : DEMANDE DE CONGÉS PAYÉS", items: ["Madame, Monsieur,", "Je souhaite poser mes congés payés du ____ / ____ / ______ au ____ / ____ / ______, soit ______ jours ouvrés.", "La continuité du service est assurée par ____________, qui a été informée et a donné son accord.", "Je vous remercie par avance de votre retour.", "Cordialement,"], cta: "Accord du responsable — date et signature" }],
  ["entete", "a4", "chic", "CV & document", "Courrier de candidature spontanée", { titre: "Marc Vidal", sur: "Candidature spontanée", sous: "06 00 00 00 00\nmarc@exemple.fr\nBordeaux", meta: "OBJET : CANDIDATURE SPONTANÉE", items: ["Madame, Monsieur,", "Votre atelier est le seul de la région à travailler encore le bois massif en série courte. C'est précisément ce que je cherche, et ce que je sais faire depuis douze ans.", "J'ai dirigé un atelier de quatre personnes, géré les devis comme les chantiers, et formé trois apprentis dont deux exercent aujourd'hui à leur compte.", "Je serais heureux d'en discuter, même sans poste ouvert dans l'immédiat.", "Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées."], cta: "Bordeaux, le ____ / ____ / ______" }],
  ["tableau", "a4", "clair", "CV & document", "Note de frais — Date et objet|montant", { titre: "Note de frais\n— avril 2026", sous: "Justificatifs joints, numérotés dans l'ordre.", sur: "DATE ET OBJET|MONTANT TTC", items: ["03/04 — Train Bordeaux-Paris|142,00 €", "03/04 — Repas client|48,50 €", "04/04 — Hôtel, une nuit|118,00 €", "12/04 — Péage et carburant|76,20 €", "22/04 — Fournitures|34,90 €", "Total|419,60 €"], meta: "Remboursement demandé sur le compte habituel — signature du responsable requise" }],
  ["tableau", "a4", "clair", "CV & document", "Bon de commande", { titre: "Bon de commande\nn° BC-2026-0184", sous: "Émis le 12 avril 2026 — livraison souhaitée avant le 30 avril.", sur: "RÉFÉRENCE|QUANTITÉ ET PRIX", items: ["Papier A4 80 g, ramette|20 — 78,00 €", "Toner noir compatible|4 — 156,00 €", "Classeurs à levier|30 — 96,00 €", "Enveloppes C4, boîte|5 — 42,50 €", "Total HT|372,50 €", "Total TTC|447,00 €"], meta: "Livraison au 12 rue du Marché — facture à adresser au service comptable" }],
  ["tableau", "a4", "clair", "CV & document", "Bon de livraison", { titre: "Bon de livraison\nn° BL-2026-0184", sous: "Livré le ____ / ____ / ______ — à signer à réception.", sur: "DÉSIGNATION|QUANTITÉ", items: ["Escalier chêne, marches|14", "Limons, paire|1", "Rampe, mètres linéaires|4", "Balustres|22", "Visserie, sachets|3", "Notice de pose|1"], meta: "Réserves à formuler par écrit dans les 48 heures — nom, date et signature du réceptionnaire" }],
  ["cadre", "a4", "clair", "CV & document", "Attestation de présence", { sur: "Attestation", titre: "Attestation\nde présence", sous: "Je soussignée Sofia Bernard, responsable des opérations, atteste que ____________ était présent·e dans nos locaux le ____ / ____ / ______, de ______ h à ______ h.", meta: "FAIT À BORDEAUX, LE ____ / ____ / ______ — SIGNATURE ET CACHET" }],
  ["cadre", "a4", "clair", "CV & document", "Autorisation parentale", { sur: "Autorisation", titre: "Autorisation\nparentale", sous: "Je soussigné·e ____________, responsable légal·e de ____________, autorise mon enfant à participer à la sortie du ____ / ____ / ______ et au transport organisé à cette occasion.", meta: "SIGNATURE PRÉCÉDÉE DE LA MENTION « LU ET APPROUVÉ »" }],
  ["cadre", "a4", "clair", "CV & document", "Décharge de responsabilité", { sur: "Décharge", titre: "Décharge\nde responsabilité", sous: "Je soussigné·e ____________ reconnais avoir été informé·e des risques liés à l'activité et déclare y participer en connaissance de cause, sous ma propre responsabilité.", meta: "CETTE DÉCHARGE NE COUVRE PAS LES FAUTES DE L'ORGANISATEUR" }],
  ["colonnes", "a4", "clair", "CV & document", "Rapport de visite", { sur: "Rapport de visite", titre: "Visite\ndu 12 avril\n2026", sous: "Site de Bordeaux — présents : S. Bernard, M. Vidal.", items: ["La visite a porté sur l'organisation du poste de préparation. Le flux actuel oblige les préparateurs à traverser l'atelier deux fois par commande, soit environ quatre cents mètres par jour et par personne. Le réagencement proposé supprime l'un des deux trajets.", "Aucun point de sécurité n'appelle d'action immédiate. Deux extincteurs arrivent à échéance de contrôle en septembre, et le marquage au sol de l'allée centrale devra être repris avant l'hiver."], meta: "RAPPORT ÉTABLI LE 13 AVRIL 2026 — DIFFUSION : DIRECTION, RESPONSABLE DE SITE" }],
  ["colonnes", "a4", "chic", "CV & document", "Note de synthèse", { sur: "Note de synthèse", titre: "Faut-il\ninternaliser\nla logistique ?", sous: "Éléments d'arbitrage, à décider avant le 30 juin.", items: ["L'externalisation coûte aujourd'hui 148 000 € par an pour un volume de 4 200 expéditions. Internaliser reviendrait à 96 000 € de charges directes, auxquelles s'ajoutent 40 000 € d'investissement initial amortis sur cinq ans, soit 104 000 € annuels.", "L'écart de 44 000 € est réel mais suppose de recruter deux personnes et d'assumer les pics de novembre et décembre, aujourd'hui absorbés par le prestataire. La décision se joue donc moins sur le coût que sur notre capacité à gérer la saisonnalité."], meta: "NOTE ÉTABLIE PAR S. BERNARD — 12 AVRIL 2026" }],
  ["sommaire", "a4", "clair", "CV & document", "Sommaire de dossier", { sur: "Dossier", titre: "Sommaire", items: ["Note de synthèse|2", "Chiffres et hypothèses|5", "Scénario A — externalisation|11", "Scénario B — internalisation|17", "Comparaison|24", "Annexes et devis|28"], meta: "Dossier de 34 pages — version du 12 avril 2026" }],
  ["chapitre", "a4", "tech", "CV & document", "Ouverture de partie", { gros: "III", sur: "Partie", titre: "Scénario B :\ninternaliser", sous: "Coûts directs, investissement, recrutements et risques opérationnels, chiffrés sur cinq ans.", meta: "PAGES 17 À 23" }],

  /* ══════════ Présentation — suite ══════════ */

  ["couverture", "slide", "tech", "Présentation", "Ouverture de comité produit", { sur: "Comité produit", titre: "Feuille\nde route\n2027", sous: "Ce qui sort, ce qui glisse, ce qu'on arrête. Trois décisions attendues.", auteur: "Sofia Bernard — 12 novembre 2026" }],
  ["couverture", "diapo43", "sombre", "Présentation", "Ouverture de bilan", { sur: "Bilan annuel", titre: "L'année\n2026", sous: "Activité, comptes, effectifs et perspectives, en quarante minutes.", auteur: "Direction générale — 15 janvier 2027" }],
  ["sommaire", "diapo43", "clair", "Présentation", "Sommaire 4/3", { sur: "Au programme", titre: "Ce qu'on\nva voir", items: ["L'année en chiffres|3", "Ce qui a bien marché|9", "Ce qui n'a pas marché|15", "Les trois arbitrages|21", "Calendrier 2027|27", "Questions|33"], meta: "Quarante minutes, questions comprises" }],
  ["stats", "diapo43", "tech", "Présentation", "Trois indicateurs", { sur: "Année 2026", titre: "Trois chiffres\nqui résument\nl'année", items: ["+18 %|de chiffre d'affaires", "-32 %|de délai moyen", "0|départ subi"], meta: "À périmètre constant, hors cession de l'activité Nord" }],
  ["tableau", "diapo43", "clair", "Présentation", "Tableau de bord", { titre: "Tableau\nde bord", sous: "Écarts au budget, arrêtés au 31 décembre.", sur: "INDICATEUR|RÉALISÉ / BUDGET", items: ["Chiffre d'affaires|4 830 / 4 500", "Marge brute|38 % / 41 %", "Effectif moyen|38 / 36", "Délai moyen|8 j / 10 j", "Satisfaction|4,7 / 4,5", "Trésorerie|+ 420 k€ / + 300 k€"], meta: "Chiffres non audités — rapport définitif en mars" }],
  ["comparatif", "diapo43", "froid", "Présentation", "Deux options d'arbitrage", { titre: "Internaliser\nou continuer", sur: "EXTERNALISÉ", cta: "INTERNALISÉ", items: ["148 k€ par an|104 k€ par an", "Aucun recrutement|Deux recrutements", "Pics absorbés|Pics à gérer", "Aucun investissement|40 k€ initiaux", "Dépendance forte|Maîtrise complète"], meta: "Décision demandée avant le 30 juin" }],
  ["etapes", "diapo43", "froid", "Présentation", "Plan d'action", { titre: "Le plan\nen quatre temps", sous: "Chaque étape a un responsable et une date.", items: ["Décider|Comité du 30 juin, arbitrage écrit.", "Préparer|Recrutements et local, juillet-août.", "Basculer|Septembre, en parallèle un mois.", "Vérifier|Bilan à trois mois, sans complaisance."] }],
  ["frise", "diapo43", "chic", "Présentation", "Calendrier de projet", { titre: "Le calendrier\n2027", sous: "Cinq jalons, tous datés.", items: ["Janvier|Validation du budget.", "Mars|Recrutements lancés.", "Juin|Décision logistique.", "Septembre|Bascule.", "Décembre|Bilan."], meta: "Point d'avancement mensuel en comité de direction" }],
  ["question", "diapo43", "sombre", "Présentation", "Diapositive de question", { sur: "La vraie question", titre: "Voulons-nous\ngrossir\nou tenir ?", sous: "Les trois arbitrages qui suivent découlent de cette seule réponse." }],
  ["avantages", "diapo43", "froid", "Présentation", "Trois recommandations", { titre: "Ce que nous\nrecommandons", sous: "Classé par effet attendu, pas par facilité.", items: ["Internaliser la logistique|-44 k€ par an, deux recrutements.", "Fermer l'activité Nord|Déficitaire depuis 2024, sortie en six mois.", "Décaler Lyon|Six mois, le temps de stabiliser."], meta: "Chiffrage détaillé en annexe, pages 28 à 34" }],
  ["typo", "diapo43", "vif", "Présentation", "Message unique 4/3", { titre: "ON ARRÊTE\nL'ACTIVITÉ\nNORD", sous: "Décision proposée au vote, effet au 31 décembre.", meta: "Détail pages 19 à 23" }],
  ["mosaique", "diapo43", "pastel", "Présentation", "Clôture 4/3", { titre: "Merci", sous: "Questions, objections, désaccords : c'est le moment." }],
  ["colonnes", "diapo43", "clair", "Présentation", "Diapositive de contexte", { sur: "Contexte", titre: "Où on\nen est\nvraiment", sous: "En deux paragraphes, avant d'entrer dans les chiffres.", items: ["L'année a été bonne, mais la croissance vient presque entièrement de la vente en ligne, qui pèse désormais quarante pour cent du chiffre d'affaires contre vingt-huit l'an dernier. C'est une force immédiate et une fragilité à trois ans.", "Dans le même temps, deux activités historiques stagnent et une décroît. Aucune décision n'a été prise à leur sujet depuis deux exercices. C'est l'objet principal de cette réunion."], meta: "COMITÉ DE DIRECTION — 15 JANVIER 2027" }],
  ["chapitre", "diapo43", "tech", "Présentation", "Séparateur 4/3", { gros: "03", sur: "Partie", titre: "Les trois\narbitrages", sous: "Chacun est chiffré, chacun engage l'exercice suivant.", meta: "PAGES 21 À 26" }],
  ["duo", "diapo43", "vif", "Présentation", "Deux chiffres 4/3", { gros: "2026", items: ["+18 %|de chiffre d'affaires", "-4 pts|de marge brute"] }],
  ["progression", "diapo43", "vif", "Présentation", "Avancement 4/3", { sur: "Projet logistique", titre: "Où on\nen est", gros: "45", sous: "Local signé, recrutements non lancés, bascule décalée à septembre.", meta: "PROCHAIN POINT : 15 MAI" }],
  ["citation", "diapo43", "chic", "Présentation", "Citation 4/3", { titre: "« Un plan\nsans date\nn'est pas\nun plan. »", auteur: "Règle interne, depuis 2022", sous: "Affichée en salle de réunion" }],
  ["liste", "diapo43", "clair", "Présentation", "Points de vigilance 4/3", { sur: "À surveiller", titre: "Cinq points\nde vigilance", items: ["La concentration du chiffre d'affaires sur un canal", "Deux activités sans décision depuis deux ans", "Le budget formation consommé à 90 %", "La dépendance au prestataire logistique", "Aucun successeur identifié sur deux postes clés"], meta: "Détail chiffré en annexe" }],

  /* ══════════ Impression & affiche — signalétique ══════════ */

  ["cadre", "a4", "clair", "Impression & affiche", "Affichette « ouvert »", { sur: "Bienvenue", titre: "Nous sommes\nouverts", sous: "Entrez, poussez la porte, elle est parfois dure.", meta: "DU MARDI AU SAMEDI — 10 H À 19 H" }],
  ["cadre", "a4", "chaud", "Impression & affiche", "Affichette « fermé »", { sur: "Désolé", titre: "Fermé\npour le moment", sous: "Nous revenons dans quelques minutes. Merci de patienter ou de repasser.", meta: "05 56 00 00 00" }],
  ["cadre", "a5", "clair", "Impression & affiche", "Affichette de sens de circulation", { sur: "Merci", titre: "Entrée\npar ici", sous: "Sortie de l'autre côté du bâtiment, par la cour.", meta: "ACCÈS PMR PAR LA COUR" }],
  ["cadre", "a5", "clair", "Impression & affiche", "Affichette de règle de salle", { sur: "Merci de", titre: "Laisser la salle\ncomme vous\nl'avez trouvée", sous: "Chaises rangées, fenêtres fermées, lumières éteintes, poubelles vidées dans le local.", meta: "LE TROUSSEAU SE DÉPOSE DANS LA BOÎTE À L'ENTRÉE" }],
  ["cadre", "a4", "chaud", "Impression & affiche", "Affichette de sécurité", { sur: "Sécurité", titre: "En cas\nd'évacuation", sous: "Sortie par la cour. Point de rassemblement sur le parking. Ne jamais utiliser l'ascenseur. Le responsable compte les présents.", meta: "EXERCICE D'ÉVACUATION DEUX FOIS PAR AN" }],
  ["cadre", "a4", "clair", "Impression & affiche", "Affichage de médiation", { sur: "Information consommateur", titre: "Médiation\nde la\nconsommation", sous: "En cas de litige non résolu, vous pouvez saisir gratuitement le médiateur de la consommation dont nous relevons, dans un délai d'un an à compter de la réclamation écrite.", meta: "COORDONNÉES DU MÉDIATEUR AFFICHÉES EN CAISSE" }],
  ["cadre", "a4", "clair", "Impression & affiche", "Affichage des prix", { sur: "Affichage obligatoire", titre: "Nos prix\nsont affichés", sous: "Tous nos tarifs sont indiqués toutes taxes comprises, service compris. Un devis écrit est remis gratuitement pour toute prestation supérieure à 150 €.", meta: "ARRÊTÉ DU 3 DÉCEMBRE 1987 — MISE À JOUR JANVIER 2026" }],
  ["typo", "bandeau", "vif", "Impression & affiche", "Kakémono d'accueil", { titre: "BIENVENUE\nCHEZ NOUS", sous: "Atelier ouvert du mardi au samedi, visites libres.", meta: "4 RUE DES FORGES — BORDEAUX" }],
  ["banniere", "bandeau", "froid", "Impression & affiche", "Kakémono de salon", { gros: "→", titre: "Venez voir comment c'est fabriqué", sous: "Démonstrations toutes les heures sur le stand, sans inscription.", cta: "Stand B14 — allée centrale" }],
  ["souligne", "bandeau", "clair", "Impression & affiche", "Kakémono trois mots", { sur: "Notre façon de faire", titre: "Simple.\nSolide.\nRéparable.", sous: "Trois critères avant de sortir un produit. Aucun n'est négociable.", meta: "atelierberthier.fr" }],
  ["ecusson", "affiche", "terre", "Impression & affiche", "Affiche emblème", { gros: "AB", meta: "DEPUIS 2006", titre: "Atelier Berthier", sous: "Menuiserie et agencement, Bordeaux" }],
  ["sceau", "affiche", "chic", "Impression & affiche", "Affiche label", { sur: "FAIT MAIN", gros: "100%", meta: "BORDEAUX", titre: "Rien n'est sous-traité", sous: "Visite de l'atelier possible sur rendez-vous." }],

];
