// Modèles — classés par besoin de communication.
//
// Les séries précédentes partent d'un métier. Celle-ci part du message :
// annoncer une hausse de prix, corriger une erreur, remercier, prévenir d'une
// fermeture, lancer un parrainage. Ce sont les publications qu'on écrit dans
// l'urgence et qu'on rate le plus souvent — les avoir déjà rédigées vaut
// mieux que d'avoir une belle mise en page vide.

import type { Row } from "./design-templates";

export const ROWS_BESOINS: Row[] = [

  /* ══════════ Annoncer une hausse, un changement, une règle ══════════ */

  ["colonnes", "carre", "clair", "Commerce & promotion", "Annonce de hausse de prix", { sur: "Transparence", titre: "Nos prix\naugmentent\nde 4 %", sous: "Au 1er septembre. Voilà pourquoi, en deux paragraphes.", items: ["Le prix de nos matières a augmenté de dix-huit pour cent en deux ans, et les salaires de l'atelier de six pour cent. Nous avons absorbé l'essentiel pendant dix-huit mois en réduisant notre marge. Ce n'est plus tenable sans rogner sur la qualité, ce que nous refusons.", "Quatre pour cent, c'est un euro quatre-vingts sur notre pièce la plus vendue. Les commandes passées avant le 31 août restent à l'ancien prix, y compris si l'expédition a lieu après."], meta: "L'ÉQUIPE — 12 JUILLET 2026" }],
  ["colonnes", "large", "froid", "Web & e-mail", "Changement de conditions", { sur: "Information", titre: "Ce qui change\nau 1er janvier", sous: "Trois modifications, aucune n'augmente ce que vous payez.", items: ["Le délai de rétractation passe de quatorze à trente jours. C'est plus que ce que la loi exige, et cela s'applique aussi aux commandes déjà passées et non encore livrées.", "Les frais de retour deviennent gratuits sans condition de montant. En contrepartie, les retours sont désormais limités à cinq articles par commande, ce qui couvre l'immense majorité des cas."], meta: "CONDITIONS COMPLÈTES SUR EXEMPLE.FR/CGV" }],
  ["cadre", "a4", "clair", "Commerce & promotion", "Affichage d'un changement de tarif", { sur: "Information clientèle", titre: "Nouveaux\ntarifs au\n1er septembre", sous: "Nos prix augmentent de quatre pour cent en moyenne. Les devis signés avant cette date restent valables trois mois.", meta: "GRILLE COMPLÈTE DISPONIBLE EN CAISSE" }],
  ["ruban", "carre", "chaud", "Commerce & promotion", "Rupture de stock", { sur: "Information", titre: "RUPTURE", sous: "Le modèle est en rupture jusqu'au 15 juin. Les commandes en cours sont honorées en priorité.", meta: "ALERTE STOCK DISPONIBLE SUR LA FICHE PRODUIT" }],
  ["centre", "carre", "sombre", "Commerce & promotion", "Erreur corrigée", { sur: "Rectificatif", titre: "Nous nous\nsommes trompés", sous: "Le tarif affiché hier était erroné. Toute commande passée à ce prix sera honorée." }],
  ["colonnes", "carre", "chic", "Instagram", "Excuses publiques", { sur: "Mise au point", titre: "On a mal\ngéré\nla semaine\ndernière", sous: "Trois cents commandes en retard, et des réponses trop lentes.", items: ["Une panne de notre logiciel de préparation nous a fait perdre deux jours. Nous n'avons prévenu personne pendant quarante-huit heures, en espérant rattraper. C'était une erreur : il fallait le dire tout de suite.", "Toutes les commandes concernées partent aujourd'hui, avec les frais de port remboursés. Vous n'avez rien à faire, le remboursement arrive sous cinq jours."], meta: "L'ÉQUIPE — 12 AVRIL 2026" }],
  ["cadre", "a5", "clair", "Immobilier & services", "Avis de travaux", { sur: "Avis aux riverains", titre: "Travaux\ndu 3 au 21 juin", sous: "Réfection de la façade côté rue. L'accès piéton est maintenu, les nuisances sonores sont limitées à 8 h – 17 h en semaine.", meta: "CONTACT CHANTIER : 06 00 00 00 00" }],
  ["cadre", "a5", "chaud", "Immobilier & services", "Coupure d'eau", { sur: "Avis", titre: "Coupure d'eau\nmardi 12 mai", sous: "De 9 h à 13 h, pour intervention sur le réseau. Pensez à remplir de quoi boire et cuisiner.", meta: "SYNDIC — 05 56 00 00 00" }],
  ["demi", "carre", "sombre", "Commerce & promotion", "Annonce de déménagement", { sur: "Information", gros: "ON\nDÉMÉNAGE", titre: "Nouvelle adresse au 4 rue des Forges", sous: "Deux fois plus grand, à cinq minutes à pied de l'ancienne boutique.", meta: "FERMETURE DU 3 AU 10 JUIN" }],
  ["ruban", "large", "chaud", "Restauration & café", "Fermeture pour travaux", { sur: "Information", titre: "TRAVAUX", sous: "Fermé du 6 au 20 janvier pour rénovation de la salle. Réouverture le 21 à midi.", meta: "LA CARTE ÉVOLUE AUSSI, VENEZ VOIR" }],

  /* ══════════ Remercier, célébrer, marquer un cap ══════════ */

  ["mosaique", "carre", "pastel", "Instagram", "Merci simple", { titre: "Merci", sous: "Pour cette année, et pour toutes les commandes qui l'ont remplie." }],
  ["chiffre", "carre", "vif", "Instagram", "Cap des mille clients", { sur: "Cap franchi", gros: "1 000", titre: "clients depuis l'ouverture", sous: "Mille personnes qui ont fait confiance à un atelier de deux personnes.", cta: "Merci, sincèrement" }],
  ["chiffre", "carre", "chic", "Commerce & promotion", "Dixième anniversaire", { sur: "Dix ans", gros: "10", titre: "ans, et toujours la même adresse", sous: "Dix ans jour pour jour. Toute la semaine, un cadeau pour chaque achat.", cta: "Du 12 au 18 mai" }],
  ["ruban", "carre", "vif", "Commerce & promotion", "Anniversaire de l'atelier", { sur: "Cinq ans", titre: "MERCI", sous: "Cinq ans d'atelier, quatre mille commandes, et zéro publicité payante.", meta: "-15 % TOUTE LA SEMAINE" }],
  ["stats", "large", "tech", "Instagram", "Bilan de l'année", { sur: "Bilan 2026", titre: "Ce que vous\navez rendu\npossible", items: ["4 120|commandes", "2|emplois créés", "0|invendu jeté"], meta: "Bilan complet publié sur notre site chaque janvier" }],
  ["cadre", "a5", "chic", "Carte & papeterie", "Carte de remerciement client", { sur: "Merci", titre: "Pour votre\nconfiance", sous: "Votre commande a été préparée à la main, dans notre atelier de Bordeaux. Nous espérons qu'elle vous plaira.", meta: "SOFIA ET MARC — ATELIER AUBÉPINE" }],
  ["bulle", "carre", "pastel", "Instagram", "Message d'un client", { sur: "Reçu ce matin", titre: "« Ça fait cinq ans que je commande chez vous. Je voulais juste vous le dire. »", auteur: "Camille D.", sous: "Cliente depuis 2021" }],
  ["mosaique", "large", "chaud", "Facebook", "Merci après un événement", { titre: "Merci\npour hier", sous: "Quatre mille personnes, zéro incident, et une buvette dévalisée." }],
  ["sceau", "carre", "chic", "Marque & logo", "Sceau d'anniversaire", { sur: "DEPUIS 2016", gros: "10", meta: "ANS", titre: "Atelier Aubépine", sous: "Même adresse, même équipe, même exigence." }],
  ["certificat", "paysage", "chic", "Éducation & association", "Diplôme du bénévole", { sur: "REMERCIEMENTS", titre: "Marc Vidal", auteur: "Le conseil d'administration", sous: "pour dix années de bénévolat, de montages de chapiteau et de permanences le dimanche matin.", meta: "ASSEMBLÉE GÉNÉRALE DU 20 JUIN 2026" }],

  /* ══════════ Recruter, intégrer, dire au revoir ══════════ */

  ["recrute", "carre", "vif", "Emploi & recrutement", "Offre en boutique", { sur: "ON RECRUTE", titre: "Vendeur ou\nvendeuse", sous: "CDI 30 h — Bordeaux centre — dès juin", items: ["Samedi travaillé, lundi de repos", "Prime sur les objectifs collectifs", "Formation produit de trois semaines"], meta: "Déposez votre CV en boutique, on répond toujours" }],
  ["recrute", "carre", "froid", "Emploi & recrutement", "Offre saisonnière", { sur: "SAISON D'ÉTÉ", titre: "Six postes\nà pourvoir", sous: "Juillet et août — camping de la Combe — logement possible", items: ["Accueil, snack, ménage, animation", "Salaire au-dessus du SMIC hôtelier", "Logement sur place à 80 € le mois"], meta: "Candidatures : emploi@campingcombe.fr" }],
  ["recrute", "carre", "tech", "Emploi & recrutement", "Offre en alternance", { sur: "ALTERNANCE", titre: "Un ou une\nalternant·e\nen communication", sous: "Rentrée septembre 2026 — Bordeaux — BTS ou licence", items: ["Un tuteur dédié, présent", "Missions réelles, pas de café", "Embauche envisagée à la fin"], meta: "Candidatures : emploi@exemple.fr" }],
  ["equipe", "large", "clair", "Emploi & recrutement", "Arrivées du trimestre", { titre: "Quatre\narrivées\nce trimestre", sous: "Et un vrai plan d'intégration pour chacun.", items: ["Sofia|Opérations", "Marc|Atelier", "Aline|Clients", "Noé|Logistique"] }],
  ["bulle", "carre", "chic", "Emploi & recrutement", "Départ d'un collaborateur", { sur: "Après huit ans", titre: "« Je pars, mais je reste dans le coin. Merci pour tout. »", auteur: "Marc Vidal", sous: "Chef d'atelier de 2018 à 2026" }],
  ["centre", "carre", "chic", "Emploi & recrutement", "Annonce de départ", { sur: "Après huit ans", titre: "Marc\nnous quitte", sous: "Il ouvre son propre atelier à trois rues d'ici. Allez le voir." }],
  ["checklist", "a4", "clair", "Emploi & recrutement", "Premier jour", { sur: "Intégration", titre: "Le programme\ndu premier jour", items: ["9 h — Accueil et visite des locaux", "10 h — Comptes et matériel", "11 h — Point avec le tuteur", "12 h 30 — Déjeuner avec l'équipe", "14 h — Première mission, simple", "16 h — Rencontre des autres services", "17 h — Bilan de la journée"], meta: "Aucune formation le premier jour : on observe, c'est déjà beaucoup" }],
  ["faq", "a4", "clair", "Emploi & recrutement", "Questions sur le poste", { sur: "Le poste en clair", titre: "Quatre réponses\nqu'on ne\nvous donnera\npas ailleurs", items: ["Le salaire ?|32 à 36 k€ selon expérience, annoncé, pas négocié à l'arrache.", "Les horaires ?|35 h, aucune astreinte, aucun week-end.", "Le télétravail ?|Deux jours, dès la première semaine.", "L'évolution ?|Grille interne publique, révisée chaque janvier."], meta: "emploi@exemple.fr — réponse sous cinq jours ouvrés" }],

  /* ══════════ Inviter, convoquer, rappeler une date ══════════ */

  ["calendrier", "a5", "vif", "Événement", "Convocation à une réunion", { sur: "MARDI 12 MAI", gros: "12", titre: "Réunion\nde copropriété", items: ["18 h 30, salle des fêtes", "Vote du budget et des travaux", "Pouvoirs acceptés, deux maximum", "Ordre du jour joint à cette convocation"] }],
  ["calendrier", "a5", "froid", "Événement", "Rappel de rendez-vous", { sur: "JEUDI 4 JUIN", gros: "04", titre: "Votre\nrendez-vous", items: ["14 h 30, 12 rue du Marché", "Prévoir 45 minutes", "Apporter les documents demandés", "Prévenir 24 h avant en cas d'empêchement"] }],
  ["sablier", "carre", "sombre", "Événement", "Rappel d'échéance", { sur: "PLUS QUE 5 JOURS", titre: "Les inscriptions\nferment lundi", sous: "Après, la liste d'attente prend le relais, sans garantie de place.", meta: "INSCRIPTION EN LIGNE OU EN PERMANENCE" }],
  ["progression", "carre", "vif", "Événement", "Places restantes", { sur: "Inscriptions", titre: "Il reste\nhuit places", gros: "84", sous: "Sur cinquante. Les inscriptions ferment le 30 mai, ou avant si c'est complet.", meta: "INSCRIPTION EN DEUX MINUTES" }],
  ["cadre", "a5", "chic", "Événement", "Invitation professionnelle", { sur: "Vous êtes convié", titre: "Petit-déjeuner\nprofessionnel", sous: "Une heure d'échanges sur la reprise d'entreprise, avec trois témoignages.", meta: "JEUDI 18 JUIN — 8 H 30 — CHAMBRE DE COMMERCE" }],
  ["arche", "a5", "pastel", "Événement", "Invitation à une inauguration", { sur: "Inauguration", titre: "Le nouvel\natelier", sous: "Venez voir où nous travaillons désormais. Visites toutes les heures, café offert.", meta: "SAMEDI 14 JUIN — 10 H À 19 H — 4 RUE DES FORGES" }],
  ["billet", "billet", "chic", "Événement", "Carton d'invitation", { sur: "INVITATION", titre: "VERNISSAGE — TRACES", gros: "2", meta: "VENDREDI 3 AVRIL — 18 H 30", sous: "Valable pour deux personnes — galerie du Port, 8 quai Vauban" }],

  /* ══════════ Expliquer, former, transmettre ══════════ */

  ["etapes", "a4", "froid", "Web & e-mail", "Créer son compte", { titre: "Créer\nvotre compte", sous: "Trois minutes, aucune information inutile demandée.", items: ["L'adresse|Une adresse e-mail valide suffit.", "Le mot de passe|Douze caractères minimum, jamais réutilisé.", "La vérification|Un lien arrive sous une minute.", "C'est fait|Vous pouvez commander, l'adresse se saisit après."] }],
  ["etapes", "a4", "clair", "Commerce & promotion", "Retourner un article", { titre: "Retourner\nun article", sous: "Trente jours, sans avoir à se justifier.", items: ["Prévenir|Un message suffit, pas de formulaire.", "Emballer|Dans le carton d'origine si possible.", "Expédier|Étiquette prépayée fournie par nos soins.", "Être remboursé|Sous cinq jours après réception."] }],
  ["faq", "a4", "clair", "Web & e-mail", "Questions de sécurité de compte", { sur: "Sécurité", titre: "Quatre réponses\nsur vos données", items: ["Où sont mes données ?|Hébergées en France, chez un prestataire certifié.", "Sont-elles revendues ?|Jamais, à personne, sous aucune forme.", "Comment les supprimer ?|Un bouton dans votre compte, effet immédiat.", "Et mes commandes passées ?|Conservées dix ans, obligation comptable."], meta: "Politique de confidentialité complète sur exemple.fr/donnees" }],
  ["fiche", "a4", "clair", "Éducation & association", "Fiche pratique de démarche", { titre: "Renouveler\nsa carte d'identité", meta: "Délai actuel : 6 à 10 semaines selon les communes", sur: "À PRÉPARER", sous: "PIÈGES COURANTS", items: ["Photo d'identité de moins de six mois", "Justificatif de domicile récent", "Ancienne carte, même périmée", "Prendre rendez-vous trop tard", "Photo aux normes non respectées", "Oublier le timbre en cas de perte"] }],
  ["checklist", "a4", "clair", "Éducation & association", "Check-list de démarche", { sur: "Déclaration d'association", titre: "Les pièces\nà réunir", items: ["Statuts signés par deux membres du bureau", "Procès-verbal de l'assemblée constitutive", "Liste des dirigeants avec coordonnées", "Formulaire Cerfa 13973", "Formulaire Cerfa 13971 pour la liste", "Adresse du siège social", "Un objet clair, écrit en une phrase"], meta: "Publication au Journal officiel gratuite depuis 2020" }],
  ["recette", "a4", "clair", "Éducation & association", "Méthode expliquée", { titre: "Organiser\nune assemblée\ngénérale", meta: "PRÉVOIR 6 SEMAINES — 2 H DE RÉUNION", sur: "IL FAUT", cta: "ON PROCÈDE", items: ["Les statuts à jour", "La liste des adhérents à jour", "Les comptes arrêtés", "Une salle et un ordre du jour", "Convoquer quinze jours avant, par écrit.", "Vérifier le quorum à l'ouverture.", "Voter chaque rapport séparément.", "Rédiger le procès-verbal le jour même."], sous: "Un procès-verbal écrit une semaine après ne ressemble jamais à ce qui s'est dit." }],
  ["diapo", "slide", "clair", "Présentation", "Explication en quatre points", { sur: "Comment ça marche", titre: "Le principe,\nen quatre points", items: ["Chaque demande crée un ticket, automatiquement", "Le ticket est attribué en moins de dix minutes", "Toute réponse est tracée et horodatée", "Un ticket sans réponse à 4 h remonte au responsable"], sous: "Aucune de ces étapes ne demande de saisie manuelle.", meta: "Documentation interne, avril 2026" }],
  ["chapitre", "a4", "chic", "CV & document", "Ouverture de guide", { gros: "01", sur: "Guide", titre: "Avant\nde commencer", sous: "Ce que ce guide couvre, ce qu'il ne couvre pas, et combien de temps il vous prendra.", meta: "PAGES 3 À 7" }],
  ["sommaire", "a4", "clair", "CV & document", "Sommaire de guide", { sur: "Guide pratique", titre: "Sommaire", items: ["Avant de commencer|3", "Les pièces à réunir|8", "La démarche, étape par étape|14", "Les délais réels|26", "Que faire en cas de refus|31", "Contacts utiles|38"], meta: "Guide mis à jour en avril 2026 — 42 pages" }],

  /* ══════════ Vendre : parrainage, fidélité, avis ══════════ */

  ["coupon", "carre", "vif", "Commerce & promotion", "Offre de parrainage", { gros: "-15 €", sur: "PARRAINAGE", titre: "Pour vous et pour la personne parrainée", sous: "Quinze euros pour elle sur sa première commande, quinze euros pour vous sur la suivante.", meta: "VOTRE CODE : PARRAIN-0000", cta: "Sans limite de filleuls" }],
  ["cartes", "large", "clair", "Commerce & promotion", "Programme de fidélité", { titre: "Trois paliers,\naucune carte\nà perdre", sous: "Tout est rattaché à votre e-mail.", items: ["Dès 100 €|-5 % en permanence.", "Dès 300 €|-10 % et livraison offerte.", "Dès 600 €|-15 % et accès aux ventes privées."] }],
  ["progression", "carre", "chaud", "Commerce & promotion", "Avancement de fidélité", { sur: "Votre fidélité", titre: "Plus que\n40 euros", gros: "87", sous: "Avant de passer au palier suivant : -10 % en permanence et livraison offerte.", meta: "VOTRE SOLDE EST VISIBLE DANS VOTRE COMPTE" }],
  ["question", "carre", "clair", "Commerce & promotion", "Demande d'avis", { sur: "Deux minutes", titre: "Votre commande\nvous a-t-elle\nplu ?", sous: "Un avis, même court, aide plus que vous ne le croyez un atelier de deux personnes." }],
  ["notation", "large", "clair", "Commerce & promotion", "Avis mis en avant", { gros: "4,9", sur: "sur 1 240 avis vérifiés", titre: "Emballage soigné, produit conforme, et une vraie personne au téléphone quand j'ai appelé un samedi.", auteur: "Marc T.", meta: "Avis collecté par un tiers indépendant — avril 2026" }],
  ["cartecadeau", "carre", "chic", "Commerce & promotion", "Carte cadeau à imprimer", { sur: "Carte cadeau", gros: "75 €", titre: "À imprimer, à plier, à offrir", meta: "CODE : 0000 0000 0000", sous: "Valable deux ans, utilisable en plusieurs fois, en boutique et en ligne." }],
  ["etiquette", "etiq", "vif", "Commerce & promotion", "Étiquette de promotion", { sur: "PRIX BARRÉ", gros: "-30%", titre: "Sur la seconde pièce,\nau choix", sous: "Cumulable avec la carte de fidélité, jusqu'à dimanche.", meta: "OFFRE VALABLE EN BOUTIQUE" }],

  /* ══════════ Rassurer : garanties, sécurité, conformité ══════════ */

  ["avantages", "large", "froid", "Commerce & promotion", "Trois garanties affichées", { titre: "Trois garanties,\nécrites", sous: "Elles figurent sur chaque facture, pas dans une page cachée.", items: ["Garantie 5 ans|Pièces et main-d'œuvre, sans condition d'usage.", "Réparation à vie|Après cinq ans, au prix des pièces.", "Retour 30 jours|Sans justification, frais à notre charge."], meta: "Conditions intégrales sur exemple.fr/garanties" }],
  ["cadre", "a4", "clair", "Web & e-mail", "Mention de conformité", { sur: "Conformité", titre: "Vos données\nrestent\nen France", sous: "Hébergement chez un prestataire certifié, chiffrement au repos et en transit, aucune revente à des tiers, suppression sur simple demande.", meta: "DÉLÉGUÉ À LA PROTECTION DES DONNÉES : DPO@EXEMPLE.FR" }],
  ["sceau", "carre", "nature", "Commerce & promotion", "Label affiché", { sur: "FABRIQUÉ EN FRANCE", gros: "100%", meta: "ATELIER DE BORDEAUX", titre: "Rien n'est sous-traité", sous: "Visite de l'atelier possible sur rendez-vous." }],
  ["tableau", "a4", "clair", "Commerce & promotion", "Traçabilité produit", { titre: "D'où vient\nce produit", sous: "Chaque étape, chaque lieu, sans arrondi.", sur: "ÉTAPE|LIEU", items: ["Culture du lin|Normandie", "Filature|Nord", "Tissage|Belgique", "Teinture|Portugal", "Confection|Bordeaux", "Expédition|Bordeaux"], meta: "Distance totale parcourue : 2 340 km — détail sur demande" }],
  ["comparatif", "a4", "clair", "Commerce & promotion", "Ce qu'on fait et ne fait pas", { titre: "Ce qu'on fait,\nce qu'on refuse", sur: "ON REFUSE", cta: "ON FAIT", items: ["Les promotions permanentes|Deux soldes par an, comme la loi le prévoit", "Les matières synthétiques|Lin, chanvre, coton bio, laine", "La sous-traitance lointaine|Tout en Europe, traçable", "Les prix barrés gonflés|Un prix, toute l'année", "Les fausses urgences|Aucun compte à rebours artificiel"], meta: "Ces choix nous coûtent des ventes. Ils nous en font gagner d'autres." }],

  /* ══════════ Informer en interne ══════════ */

  ["cadre", "a4", "clair", "CV & document", "Note de service", { sur: "Note de service", titre: "Nouveaux\nhoraires\nd'été", sous: "Du 1er juillet au 31 août, l'atelier ferme à 16 h le vendredi. Les heures sont reportées du lundi au jeudi.", meta: "DIFFUSÉE LE 12 JUIN 2026 — APPLICABLE AU 1ER JUILLET" }],
  ["tableau", "a4", "clair", "CV & document", "Planning d'équipe", { titre: "Planning\nde la semaine", sous: "Semaine 24 — modifications signalées la veille.", sur: "PERSONNE|SEMAINE", items: ["Sofia|Bureau, lun. à ven.", "Marc|Atelier, lun. à jeu.", "Aline|Clients, mar. à sam.", "Noé|Logistique, lun. à ven.", "Camille|Congés", "Astreinte|Marc, jusqu'à dimanche"], meta: "Toute modification passe par le tableau, pas par un message privé" }],
  ["checklist", "a4", "clair", "CV & document", "Procédure d'ouverture", { sur: "Ouverture du magasin", titre: "Les sept\nvérifications", items: ["Désarmer l'alarme, noter l'heure", "Vérifier le fond de caisse", "Allumer la vitrine et l'enseigne", "Contrôler les températures des frigos", "Sortir les nouveautés en rayon", "Vérifier les dates courtes", "Ouvrir à l'heure, pas cinq minutes après"], meta: "À signer chaque matin sur le cahier de bord" }],
  ["cadre", "a4", "chaud", "CV & document", "Consigne de sécurité", { sur: "Sécurité", titre: "En cas\nd'évacuation", sous: "Sortie par la cour, point de rassemblement sur le parking. Ne jamais utiliser l'ascenseur. Le responsable compte les présents.", meta: "EXERCICE D'ÉVACUATION : DEUX FOIS PAR AN" }],
  ["frise", "a4", "chic", "CV & document", "Rétroplanning", { titre: "Rétroplanning\ndu lancement", sous: "Du 1er mai au 15 septembre.", items: ["1er mai|Validation du produit.", "1er juin|Photos et fiches produit.", "1er juillet|Mise en ligne cachée.", "1er septembre|Ouverture des précommandes.", "15 sept.|Lancement public."], meta: "Chaque jalon a un responsable nommé et une date ferme" }],
  ["progression", "slide", "vif", "Présentation", "Avancement de chantier interne", { sur: "Projet de refonte", titre: "Où on\nen est", gros: "55", sous: "Deux lots livrés sur quatre. Le troisième glisse de deux semaines, le dernier tient.", meta: "PROCHAIN POINT : MARDI 12 MAI" }],
  ["duo", "slide", "tech", "Présentation", "Deux indicateurs internes", { gros: "T2", items: ["-32 %|de délai moyen", "+4 pts|de satisfaction"] }],
  ["score", "slide", "vif", "Présentation", "Objectif contre réalisé", { sur: "TRIMESTRE 2", items: ["Objectif", "Réalisé"], gros: "100-118", titre: "Objectif dépassé de dix-huit points", meta: "À PÉRIMÈTRE CONSTANT" }],

];
