// Modèles — tech, finance, juridique, emploi, web et e-mail.
//
// Ici la communication sert à expliquer une offre, un chiffre ou une règle.
// Les contenus sont écrits comme on rédige une note interne qui doit être
// comprise du premier coup : phrases courtes, chiffres datés, aucune formule
// creuse. Ce sont ces textes-là qu'on remplace le plus vite par les siens.

import type { Row } from "./design-templates";

export const ROWS_PRO: Row[] = [

  /* ══════════ Tech & startup ══════════ */

  ["panneau", "large", "tech", "Tech & startup", "Présentation produit", { gros: "01", sur: "Nouvelle version", titre: "Tout tient\ndans une\nseule vue", sous: "Le tableau de bord regroupe enfin les trois écrans que vous ouvriez en parallèle.", meta: "Disponible pour tous les comptes dès aujourd'hui" }],
  ["cartes", "large", "tech", "Tech & startup", "Trois plans tarifaires", { titre: "Trois plans,\naucune surprise", sous: "Changez ou arrêtez à tout moment, au prorata.", items: ["Solo|9 €/mois, un utilisateur, tout l'essentiel.", "Équipe|29 €/mois, jusqu'à dix personnes.", "Entreprise|Sur devis, hébergement dédié."] }],
  ["tarif", "portrait", "tech", "Tech & startup", "Plan Équipe", { sur: "PLAN ÉQUIPE", gros: "29 €", sous: "par mois, jusqu'à dix utilisateurs", items: ["Utilisateurs illimités en lecture", "Historique conservé deux ans", "Export CSV et API incluse", "Assistance sous quatre heures", "Aucun frais de mise en service"], cta: "Essayer 14 jours" }],
  ["comparatif", "portrait", "tech", "Tech & startup", "Gratuit ou payant", { titre: "Ce que change\nle plan payant", sur: "GRATUIT", cta: "PAYANT", items: ["1 utilisateur|Jusqu'à 10", "30 jours d'historique|2 ans", "Export manuel|API complète", "Support communautaire|Réponse sous 4 h", "0 €|29 €/mois"], meta: "Aucune fonctionnalité retirée du plan gratuit depuis 2021" }],
  ["stats", "large", "tech", "Tech & startup", "Chiffres de fiabilité", { sur: "Douze derniers mois", titre: "Ce que vaut\nnotre disponibilité", items: ["99,97 %|de disponibilité", "11 min|d'indisponibilité totale", "4 h|délai de réponse moyen"], meta: "Historique public sur status.exemple.fr" }],
  ["etapes", "large", "froid", "Tech & startup", "Prise en main", { titre: "En route\nen quinze minutes", sous: "Aucune installation, aucun consultant.", items: ["Créer un compte|Une adresse e-mail suffit.", "Importer|CSV, ou connexion directe à votre outil.", "Inviter|L'équipe reçoit un lien, pas un mot de passe.", "Utiliser|Les premiers rapports arrivent le soir même."] }],
  ["chrono", "large", "tech", "Tech & startup", "Feuille de route", { titre: "Ce qui arrive\nen 2026", sous: "Publiée, datée, et tenue jusqu'ici.", items: ["T1|Export planifié.", "T2|Application mobile.", "T3|Permissions fines.", "T4|Connecteurs comptables."], meta: "Feuille de route détaillée et votes utilisateurs sur exemple.fr/roadmap" }],
  ["chiffre", "large", "tech", "Tech & startup", "Métrique clé", { sur: "Depuis le lancement", gros: "2 M", titre: "de documents traités", sous: "Sans une seule perte de données, et sans avoir augmenté nos tarifs.", cta: "Voir le rapport technique" }],
  ["progression", "large", "tech", "Tech & startup", "Migration en cours", { sur: "Migration", titre: "Bascule\nvers la v3", gros: "72", sous: "Les comptes restants basculent d'ici le 30 juin, sans interruption.", meta: "AUCUNE ACTION DE VOTRE PART" }],
  ["faq", "a4", "clair", "Tech & startup", "Questions de sécurité", { sur: "Sécurité", titre: "Ce que vous\navez le droit\nde nous demander", items: ["Où sont hébergées les données ?|En France, chez un hébergeur certifié HDS.", "Sont-elles chiffrées ?|Au repos et en transit, sans option à activer.", "Qui y accède en interne ?|Trois personnes, avec journalisation complète.", "Que se passe-t-il si je pars ?|Export complet, puis suppression sous 30 jours."], meta: "Documentation de conformité disponible sous NDA" }],
  ["avantages", "large", "tech", "Tech & startup", "Trois différences", { titre: "Trois choses\nqu'on fait\nautrement", sous: "Et qu'on ne compte pas changer.", items: ["Prix public|Affiché, y compris pour les grands comptes.", "Pas de verrou|Export complet en un clic, à tout moment.", "Support humain|Pas de robot en première ligne."], meta: "Conditions générales lisibles en dix minutes" }],
  ["tableau", "a4", "clair", "Tech & startup", "Comparatif des plans", { titre: "Ce que\ncontient chaque plan", sous: "Tarifs mensuels hors taxes, engagement libre.", sur: "FONCTION|SOLO / ÉQUIPE", items: ["Utilisateurs|1 / 10", "Historique|30 j / 2 ans", "API|Non / Oui", "Exports planifiés|Non / Oui", "Support|48 h / 4 h", "Prix mensuel|9 € / 29 €"], meta: "Remise de deux mois en paiement annuel" }],
  ["neon", "large", "tech", "Tech & startup", "Annonce de version", { gros: "v3", titre: "La version 3 est en ligne", sous: "Deux ans de retours utilisateurs, une interface repensée." }],
  ["bandeau", "large", "tech", "Tech & startup", "Annonce de levée", { sur: "Étape", titre: "Nous levons\n2 millions d'euros", sous: "Pour doubler l'équipe technique et ouvrir un support en anglais.", cta: "Lire l'annonce complète" }],
  ["equipe", "large", "clair", "Tech & startup", "L'équipe fondatrice", { titre: "Les quatre\nqui ont commencé", sous: "Toujours là, toujours au même endroit.", items: ["Sofia|Produit", "Marc|Technique", "Aline|Clients", "Noé|Opérations"] }],
  ["recrute", "large", "froid", "Tech & startup", "Offre développeur", { sur: "NOUS RECRUTONS", titre: "Développeur ou\ndéveloppeuse\nback-end", sous: "CDI — Bordeaux ou télétravail complet", items: ["Salaire annoncé : 48 à 58 k€", "Quatre jours de semaine possibles", "Aucune astreinte, aucun week-end"], meta: "Processus en trois étapes, deux semaines maximum" }],
  ["citation", "large", "chic", "Tech & startup", "Citation d'équipe", { titre: "« Une fonction\nqu'on n'explique pas\nen une phrase\nne sortira pas. »", auteur: "Sofia Bernard, produit", sous: "Règle interne, depuis 2021" }],
  ["carrousel", "li", "tech", "Tech & startup", "Volet de démonstration", { meta: "3/7", sur: "Démonstration", titre: "Vos rapports,\nplanifiés\nà l'avance", sous: "Choisissez le jour, l'heure et les destinataires. Le reste se fait sans vous.", cta: "Suite →" }],
  ["notation", "large", "clair", "Tech & startup", "Avis utilisateur B2B", { gros: "4,7", sur: "sur 210 avis vérifiés", titre: "Migration faite un vendredi soir, opérationnelle le lundi, sans un ticket ouvert.", auteur: "Direction des systèmes d'information, groupe régional", meta: "Avis collecté par un tiers — mars 2026" }],
  ["sommaire", "a4", "clair", "Tech & startup", "Sommaire de documentation", { sur: "Documentation", titre: "Par où\ncommencer", items: ["Créer son compte|3", "Importer ses données|7", "Inviter son équipe|12", "Configurer les rapports|18", "Utiliser l'API|26", "Exporter et partir|41"], meta: "Documentation complète sur docs.exemple.fr" }],
  ["chapitre", "a4", "tech", "Tech & startup", "Ouverture de documentation", { gros: "04", sur: "Chapitre", titre: "Configurer\nles rapports", sous: "Choisir les indicateurs, la fréquence et les destinataires, sans écrire une ligne de code.", meta: "MISE À JOUR : AVRIL 2026" }],
  ["contour", "large", "tech", "Tech & startup", "Écran de conférence", { sur: "Conférence", gros: "API", titre: "Tout ce qui est visible est appelable", sous: "Trente minutes de démonstration, code affiché en direct.", meta: "SALLE B — 14 H 30" }],
  ["progression", "carre", "vif", "Tech & startup", "Objectif bêta", { sur: "Programme bêta", titre: "Places\npresque toutes\nprises", gros: "92", sous: "Il reste huit places sur cent pour la bêta fermée de mai.", meta: "CANDIDATURE EN DEUX MINUTES" }],

  /* ══════════ Finance & assurance ══════════ */

  ["tableau", "a4", "clair", "Finance & assurance", "Grille de garanties", { titre: "Ce que couvre\nchaque formule", sous: "Contrat multirisque habitation, conditions au 1er janvier 2026.", sur: "GARANTIE|ESSENTIELLE / COMPLÈTE", items: ["Incendie et dégât des eaux|Oui / Oui", "Vol et vandalisme|Non / Oui", "Bris de glace|Option / Oui", "Dommages électriques|Non / Oui", "Franchise|250 € / 120 €", "Cotisation mensuelle|18 € / 31 €"], meta: "Conditions générales remises avant toute signature" }],
  ["cartes", "large", "froid", "Finance & assurance", "Trois formules d'assurance", { titre: "Trois niveaux\nde couverture", sous: "Résiliables à tout moment après un an.", items: ["Essentielle|18 €/mois, l'obligatoire bien fait.", "Confort|24 €/mois, vol et bris de glace.", "Complète|31 €/mois, franchise réduite."] }],
  ["chiffre", "carre", "tech", "Finance & assurance", "Délai d'indemnisation", { sur: "Notre moyenne", gros: "9", titre: "jours entre la déclaration et le virement", sous: "Sur 1 840 sinistres traités en 2025, hors expertise judiciaire.", cta: "Voir le détail" }],
  ["etapes", "a4", "froid", "Finance & assurance", "Déclarer un sinistre", { titre: "Déclarer\nun sinistre", sous: "Quatre étapes, aucune paperasse inutile.", items: ["Déclarer|En ligne ou par téléphone, sous cinq jours.", "Documenter|Photos et facture d'origine si vous l'avez.", "Expertise|Sous 72 h, à domicile si nécessaire.", "Indemnisation|Virement sous neuf jours en moyenne."] }],
  ["faq", "a4", "clair", "Finance & assurance", "Questions d'assuré", { sur: "Vous demandez", titre: "Quatre réponses\nclaires", items: ["Puis-je résilier quand je veux ?|Oui, à tout moment après la première année.", "La franchise est-elle négociable ?|Elle baisse avec la formule, pas au cas par cas.", "Que faire en cas d'urgence ?|Le 05 56 00 00 00 répond 24 h sur 24.", "Mes garanties évoluent-elles seules ?|Non. Toute modification vous est notifiée deux mois avant."], meta: "Service client : 05 56 00 00 00, du lundi au samedi" }],
  ["avantages", "large", "froid", "Finance & assurance", "Trois engagements", { titre: "Trois promesses\nchiffrées", sous: "Mesurées chaque trimestre, publiées chaque année.", items: ["Réponse en 4 h|Sur toute demande écrite, jours ouvrés.", "Indemnisation en 9 jours|Moyenne constatée en 2025.", "Aucune hausse cachée|Toute évolution notifiée deux mois avant."], meta: "Rapport de qualité de service disponible sur demande" }],
  ["stats", "large", "tech", "Finance & assurance", "Chiffres du cabinet", { sur: "Bilan 2025", titre: "L'année\nen trois chiffres", items: ["1 840|sinistres traités", "9 j|délai moyen", "94 %|de clients fidèles"], meta: "Chiffres audités — rapport annuel disponible" }],
  ["progression", "carre", "froid", "Finance & assurance", "Avancement de dossier", { sur: "Votre dossier", titre: "Expertise\nvalidée", gros: "80", sous: "Il reste la validation comptable, puis le virement sous 48 h.", meta: "AUCUNE ACTION DE VOTRE PART" }],
  ["fiche", "a4", "clair", "Finance & assurance", "Fiche produit d'épargne", { titre: "Contrat d'épargne\nà versements libres", meta: "Frais d'entrée 0 % — frais de gestion 0,60 %/an", sur: "AVANTAGES", sous: "POINTS DE VIGILANCE", items: ["Versements libres dès 50 €", "Retraits possibles à tout moment", "Fiscalité avantageuse après 8 ans", "Le capital n'est pas garanti sur les unités de compte", "La performance passée ne préjuge de rien", "Les frais s'appliquent même en cas de baisse"] }],
  ["cadre", "a4", "clair", "Finance & assurance", "Mention réglementaire", { sur: "Information légale", titre: "Ce document\nn'est pas\nun conseil", sous: "Les éléments présentés sont fournis à titre informatif et ne constituent ni une recommandation personnalisée, ni une offre de souscription.", meta: "ORIAS N° 00000000 — DOCUMENT NON CONTRACTUEL" }],
  ["tarif", "a4", "froid", "Finance & assurance", "Honoraires de conseil", { sur: "ACCOMPAGNEMENT", gros: "450 €", sous: "bilan patrimonial complet, honoraires forfaitaires", items: ["Entretien de deux heures", "Analyse écrite de votre situation", "Trois scénarios chiffrés", "Une réunion de restitution", "Aucune rétrocession perçue"], cta: "Prendre rendez-vous" }],
  ["visite", "carte", "chic", "Finance & assurance", "Carte de conseiller", { gros: "MV", titre: "Marc Vidal", sur: "CONSEILLER EN GESTION DE PATRIMOINE", sous: "ORIAS 00000000 · 06 00 00 00 00 · marc@exemple.fr" }],
  ["contact", "carte", "clair", "Finance & assurance", "Carte de cabinet", { sur: "Cabinet", titre: "Un rendez-vous\nsans frais", sous: "Premier entretien d'une heure, sans engagement.", items: ["05 56 00 00 00", "contact@exemple.fr", "8 quai Vauban, Bordeaux", "Du lundi au vendredi, 9 h – 18 h"], meta: "Cabinet indépendant — ORIAS n° 00000000" }],
  ["notation", "large", "clair", "Finance & assurance", "Avis client cabinet", { gros: "4,9", sur: "sur 128 avis", titre: "On nous a expliqué ce qu'on ne comprenait pas depuis dix ans, sans nous vendre quoi que ce soit ce jour-là.", auteur: "Famille Roux", meta: "Avis vérifié — janvier 2026" }],
  ["chrono", "large", "chic", "Finance & assurance", "Étapes d'un projet", { titre: "Un projet\nimmobilier,\nquatre jalons", sous: "Comptez quatre à six mois du premier rendez-vous à l'acte.", items: ["Mois 1|Bilan et capacité d'emprunt.", "Mois 2|Recherche et offre.", "Mois 3|Montage du prêt.", "Mois 5|Acte et déblocage."], meta: "Délais constatés sur nos dossiers 2025" }],
  ["checklist", "a4", "clair", "Finance & assurance", "Pièces pour un dossier de prêt", { sur: "Dossier de prêt", titre: "Les pièces\nà réunir", items: ["Trois derniers bulletins de salaire", "Deux derniers avis d'imposition", "Trois derniers relevés de compte", "Justificatif de domicile récent", "Pièce d'identité en cours de validité", "Compromis de vente signé", "Tableau d'amortissement des crédits en cours"], meta: "Dossier complet = deux semaines gagnées" }],

  /* ══════════ Juridique & conseil ══════════ */

  ["entete", "a4", "chic", "Juridique & conseil", "Papier à en-tête cabinet", { titre: "Cabinet Berthier", sur: "Avocats au barreau de Bordeaux", sous: "8 quai Vauban\n33000 Bordeaux\n05 56 00 00 00", meta: "OBJET : ____________________", items: ["Madame, Monsieur,", "", "", "", "Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées."], cta: "Toque 000 — SIRET 000 000 000 00000 — TVA FR00000000000" }],
  ["tableau", "a4", "clair", "Juridique & conseil", "Grille d'honoraires", { titre: "Nos honoraires", sous: "Convention d'honoraires signée avant toute intervention.", sur: "PRESTATION|MONTANT HT", items: ["Consultation (1 h)|150 €", "Rédaction de contrat|dès 600 €", "Assistance prud'homale|2 400 €", "Procédure civile|dès 3 000 €", "Abonnement conseil|400 €/mois", "Déplacement hors ressort|Sur devis"], meta: "TVA 20 % — aide juridictionnelle acceptée sous conditions" }],
  ["cartes", "large", "chic", "Juridique & conseil", "Trois domaines", { titre: "Nos trois\ndomaines", sous: "Nous n'intervenons pas au-delà.", items: ["Droit du travail|Contentieux et conseil aux employeurs.", "Droit commercial|Contrats, litiges, recouvrement.", "Droit des sociétés|Constitution, cession, gouvernance."] }],
  ["etapes", "a4", "froid", "Juridique & conseil", "Déroulé d'un dossier", { titre: "Comment\nse déroule\nun dossier", sous: "Vous savez à chaque étape où va l'argent.", items: ["Premier rendez-vous|Une heure, facturée, sans engagement.", "Convention|Honoraires écrits avant toute action.", "Instruction|Compte rendu à chaque acte de procédure.", "Décision|Analyse écrite et suites possibles."] }],
  ["faq", "a4", "clair", "Juridique & conseil", "Questions juridiques", { sur: "Avant de nous consulter", titre: "Quatre réponses\nsans jargon", items: ["Combien coûte un premier rendez-vous ?|150 € HT, déduits si le dossier se poursuit.", "Combien de temps dure une procédure ?|Douze à trente mois en moyenne aux prud'hommes.", "Puis-je changer d'avocat ?|Oui, à tout moment, le dossier vous appartient.", "L'aide juridictionnelle est-elle possible ?|Oui, sous conditions de ressources, nous la traitons."], meta: "05 56 00 00 00 — secrétariat de 9 h à 17 h" }],
  ["cadre", "a4", "chic", "Juridique & conseil", "Mention de confidentialité", { sur: "Confidentiel", titre: "Document\ncouvert par\nle secret", sous: "Le contenu de ce document est couvert par le secret professionnel. Toute diffusion, même partielle, est interdite sans accord écrit.", meta: "CABINET BERTHIER — BARREAU DE BORDEAUX" }],
  ["visite", "carte", "chic", "Juridique & conseil", "Carte de visite avocat", { gros: "SB", titre: "Sofia Bernard", sur: "AVOCATE AU BARREAU DE BORDEAUX", sous: "8 quai Vauban · 05 56 00 00 00 · s.bernard@cabinet.fr" }],
  ["contact", "carte", "clair", "Juridique & conseil", "Carte du cabinet", { sur: "Cabinet Berthier", titre: "Prendre\nrendez-vous", sous: "Secrétariat du lundi au vendredi, 9 h à 17 h.", items: ["05 56 00 00 00", "contact@cabinet-berthier.fr", "8 quai Vauban, Bordeaux", "Parking Vauban à 100 m"], meta: "Premier rendez-vous : 150 € HT" }],
  ["sommaire", "a4", "clair", "Juridique & conseil", "Sommaire de note", { sur: "Note juridique", titre: "Sommaire", items: ["Rappel des faits|2", "Cadre légal applicable|4", "Analyse|7", "Risques identifiés|12", "Recommandations|15", "Annexes|18"], meta: "Note établie le 12 avril 2026 — 21 pages" }],
  ["chapitre", "a4", "chic", "Juridique & conseil", "Ouverture de note", { gros: "III", sur: "Partie", titre: "Analyse\njuridique", sous: "Application des textes aux faits établis en partie I, et jurisprudence pertinente depuis 2021.", meta: "PAGES 7 À 11" }],
  ["colonnes", "a4", "clair", "Juridique & conseil", "Note de synthèse", { sur: "Synthèse", titre: "Ce qu'il faut\nretenir\nen deux minutes", sous: "Le détail complet figure aux pages 7 à 15.", items: ["Le risque principal tient à l'absence de formalisation écrite des heures supplémentaires. En l'état, la charge de la preuve pèsera sur l'employeur, ce qui affaiblit sensiblement la position en cas de contentieux.", "Deux mesures suffisent à rétablir la situation : mettre en place un décompte hebdomadaire signé, et régulariser les six derniers mois. Le coût de la régularisation reste très inférieur à celui d'une condamnation."], meta: "CABINET BERTHIER — 12 AVRIL 2026" }],
  ["avantages", "large", "chic", "Juridique & conseil", "Nos principes", { titre: "Trois principes\nde travail", sous: "Ils figurent dans chaque convention d'honoraires.", items: ["Honoraires écrits|Avant toute action, sans exception.", "Compte rendu systématique|À chaque acte, même défavorable.", "Refus assumé|Nous disons quand un dossier n'est pas tenable."], meta: "Cabinet inscrit au barreau de Bordeaux depuis 2009" }],
  ["notation", "large", "clair", "Juridique & conseil", "Avis client cabinet", { gros: "4,9", sur: "sur 76 avis", titre: "On nous a dit dès le premier rendez-vous que la procédure serait longue et incertaine. C'était vrai, et on a gagné.", auteur: "Entreprise cliente, secteur bâtiment", meta: "Avis vérifié — 2026" }],
  ["typo", "large", "sombre", "Juridique & conseil", "Slogan sobre", { titre: "ON NE PROMET\nPAS DE GAGNER.\nON PROMET\nDE TOUT DIRE.", sous: "Cabinet Berthier, barreau de Bordeaux.", meta: "05 56 00 00 00" }],

  /* ══════════ Emploi & recrutement ══════════ */

  ["recrute", "a4", "froid", "Emploi & recrutement", "Offre d'emploi complète", { sur: "NOUS RECRUTONS", titre: "Chargé·e\nde clientèle", sous: "CDI 35 h — Bordeaux — deux jours de télétravail", items: ["Salaire annoncé : 30 à 34 k€ brut", "Formation interne de six semaines", "Trois entretiens maximum, en deux semaines"], meta: "Candidatures : emploi@exemple.fr — réponse à toutes" }],
  ["recrute", "story", "vif", "Emploi & recrutement", "Offre en story", { sur: "ON RECRUTE", titre: "Serveur ou\nserveuse", sous: "CDI 39 h — Bordeaux — dès mai", items: ["Deux jours de repos consécutifs", "Pourboires partagés équitablement", "Pas de coupure le dimanche"], meta: "Passez déposer un CV, on répond toujours" }],
  ["recrute", "li", "clair", "Emploi & recrutement", "Offre cadre", { sur: "POSTE À POURVOIR", titre: "Responsable\ndes opérations", sous: "CDI — Bordeaux — statut cadre", items: ["Salaire annoncé : 55 à 65 k€", "Équipe de huit personnes à encadrer", "Poste créé, pas un remplacement"], meta: "Processus détaillé communiqué dès la première réponse" }],
  ["tableau", "a4", "clair", "Emploi & recrutement", "Étapes du recrutement", { titre: "Notre processus\nde recrutement", sous: "Deux semaines entre la candidature et la réponse finale.", sur: "ÉTAPE|DÉLAI", items: ["Accusé de réception|24 h", "Réponse sur le CV|5 jours", "Entretien visio|Semaine 1", "Cas pratique rémunéré|Semaine 2", "Entretien final|Semaine 2", "Réponse définitive|48 h après"], meta: "Chaque candidature reçoit une réponse, même négative" }],
  ["avantages", "large", "froid", "Emploi & recrutement", "Ce que nous offrons", { titre: "Trois choses\nqu'on annonce\navant l'entretien", sous: "Parce que les découvrir après fait perdre du temps à tout le monde.", items: ["Le salaire|Affiché dans l'offre, fourchette réelle.", "Le rythme|35 h, aucune astreinte, aucun week-end.", "Le télétravail|Deux jours par semaine dès le premier mois."], meta: "Grille de salaires interne consultable en entretien" }],
  ["faq", "a4", "clair", "Emploi & recrutement", "Questions de candidats", { sur: "Candidats", titre: "Quatre réponses\navant de postuler", items: ["Faut-il une lettre de motivation ?|Non, nous ne les lisons plus.", "Combien d'entretiens ?|Trois maximum, dont un cas pratique payé.", "Y a-t-il une période d'essai ?|Quatre mois, renouvelable une fois.", "Répondez-vous à tout le monde ?|Oui, sous cinq jours ouvrés."], meta: "emploi@exemple.fr" }],
  ["equipe", "a4", "clair", "Emploi & recrutement", "Vos futurs collègues", { titre: "Avec qui\nvous travaillerez", sous: "Une équipe de quatre, sans hiérarchie intermédiaire.", items: ["Sofia|Direction", "Marc|Technique", "Aline|Clients", "Noé|Logistique"] }],
  ["temoignage", "carre", "pastel", "Emploi & recrutement", "Témoignage de recrue", { emoji: "🙋", titre: "« On m'avait annoncé 34 k€, j'ai signé à 34 k€. Ça paraît normal, ça ne l'est pas toujours. »", auteur: "Noé T.", sous: "Chargé de clientèle, arrivé en 2025" }],
  ["chiffre", "carre", "tech", "Emploi & recrutement", "Délai de réponse", { sur: "Notre engagement", gros: "5", titre: "jours pour répondre à toute candidature", sous: "Y compris quand la réponse est non. Surtout quand elle est non.", cta: "Voir nos offres" }],
  ["cv", "cv", "clair", "Emploi & recrutement", "CV sobre", { gros: "SB", titre: "Sofia\nBernard", sur: "RESPONSABLE DES OPÉRATIONS", sous: "06 00 00 00 00\nsofia@exemple.fr\nBordeaux\nPermis B", meta: "PARCOURS", items: ["Responsable des opérations — Aubépine|2022 à aujourd'hui. Encadrement de huit personnes, refonte du service client, délais divisés par trois.", "Chargée de projet — Studio Verrier|2019-2022. Pilotage de vingt-cinq projets clients, budget annuel de 400 k€.", "Assistante d'exploitation — Groupe Roux|2017-2019. Planification et suivi de la logistique régionale.", "Master management des organisations|Université de Bordeaux, 2017."] }],
  ["cv", "cv", "chic", "Emploi & recrutement", "CV élégant", { gros: "MV", titre: "Marc\nVidal", sur: "CHEF DE CUISINE", sous: "06 00 00 00 00\nmarc@exemple.fr\nBordeaux\nDisponible en septembre", meta: "EXPÉRIENCE", items: ["Chef de cuisine — Le Comptoir du Port|2021 à aujourd'hui. Brigade de quatre, carte renouvelée chaque semaine, 90 couverts par service.", "Second de cuisine — La Table de Sofia|2018-2021. Poste chaud, gestion des commandes et des stocks.", "Chef de partie — Hôtel des Quinconces|2015-2018. Poste poisson, service de 120 couverts.", "CAP et BP cuisine|CFA de Bordeaux, 2015."] }],
  ["cv", "cv", "tech", "Emploi & recrutement", "CV technique", { gros: "AR", titre: "Aline\nRoux", sur: "DÉVELOPPEUSE BACK-END", sous: "06 00 00 00 00\naline@exemple.fr\nTélétravail complet\ngithub.com/aline", meta: "EXPÉRIENCE", items: ["Développeuse senior — Aubépine|2023 à aujourd'hui. Refonte de l'API, temps de réponse divisé par quatre.", "Développeuse — Studio Verrier|2020-2023. Back-end de la plateforme de réservation, 40 000 utilisateurs.", "Développeuse junior — Groupe Roux|2018-2020. Maintenance et migration d'un ERP interne.", "Licence informatique|Université de Bordeaux, 2018."] }],
  ["entete", "a4", "clair", "Emploi & recrutement", "Lettre de motivation", { titre: "Sofia Bernard", sur: "Responsable des opérations", sous: "06 00 00 00 00\nsofia@exemple.fr\nBordeaux", meta: "OBJET : CANDIDATURE AU POSTE DE RESPONSABLE DES OPÉRATIONS", items: ["Madame, Monsieur,", "Votre annonce mentionne un poste créé plutôt qu'un remplacement, et une équipe de huit personnes à structurer. C'est exactement le travail que j'ai mené ces trois dernières années chez Aubépine.", "J'y ai repris un service client de six personnes sans procédure écrite. En dix-huit mois, le délai de traitement est passé de douze heures à deux, sans recrutement supplémentaire.", "Je serais heureuse de vous en détailler la méthode, et d'entendre où vous en êtes.", "Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées."], cta: "Bordeaux, le 12 avril 2026" }],
  ["checklist", "a4", "clair", "Emploi & recrutement", "Préparer son entretien", { sur: "Candidats", titre: "Six choses\nà préparer", items: ["Relire l'offre, ligne par ligne", "Préparer trois exemples chiffrés", "Vérifier le nom des interlocuteurs", "Préparer deux questions sur le poste", "Connaître sa prétention, au chiffre près", "Arriver dix minutes avant, pas trente"], meta: "Un entretien préparé se voit en trois minutes" }],
  ["progression", "carre", "vif", "Emploi & recrutement", "Avancement de candidature", { sur: "Votre candidature", titre: "Entretien\nfinal passé", gros: "85", sous: "Il reste la décision collégiale, réponse sous 48 heures.", meta: "NOUS VOUS APPELONS DANS TOUS LES CAS" }],

  /* ══════════ Web & e-mail ══════════ */

  ["banniere", "bandeau", "tech", "Web & e-mail", "Bandeau d'accueil", { gros: "→", titre: "Tout ce que vous cherchez, au même endroit", sous: "Fichiers, design et partage, sans passer d'un outil à l'autre.", cta: "Essayer gratuitement" }],
  ["banniere", "bandeau", "chaud", "Web & e-mail", "Bandeau promotion site", { gros: "-20%", titre: "Vingt pour cent sur tout le catalogue", sous: "Jusqu'à dimanche minuit, remise appliquée au panier.", cta: "En profiter" }],
  ["bandeau", "large", "froid", "Web & e-mail", "En-tête de newsletter", { sur: "Lettre n° 42", titre: "Ce mois-ci :\ntrois nouveautés", sous: "Une fonction attendue, un changement de tarif, et une histoire de client.", cta: "Lire la lettre" }],
  ["bandeau", "large", "nature", "Web & e-mail", "En-tête de lettre saisonnière", { sur: "Lettre du printemps", titre: "Ce qui pousse\nen ce moment", sous: "Les arrivages de la semaine, et deux recettes pour en faire quelque chose.", cta: "Voir les arrivages" }],
  ["entete", "signa", "clair", "Web & e-mail", "Signature e-mail sobre", { titre: "Sofia Bernard", sur: "Responsable des opérations", sous: "06 00 00 00 00\nsofia@exemple.fr", meta: "Aubépine — 12 rue du Marché, Bordeaux" }],
  ["entete", "signa", "tech", "Web & e-mail", "Signature e-mail technique", { titre: "Aline Roux", sur: "Développeuse back-end", sous: "aline@exemple.fr\ngithub.com/aline", meta: "Aubépine — télétravail, fuseau Europe/Paris" }],
  ["visite", "signa", "chic", "Web & e-mail", "Signature carte — Chef de cuisine", { gros: "MV", titre: "Marc Vidal", sur: "CHEF DE CUISINE", sous: "Le Comptoir du Port · 05 56 00 00 00" }],
  ["chiffre", "large", "vif", "Web & e-mail", "Bloc e-mail promotion", { sur: "Offre du mois", gros: "-25%", titre: "sur votre première commande", sous: "Code appliqué automatiquement au panier, jusqu'au 30 avril.", cta: "J'en profite" }],
  ["cartes", "large", "clair", "Web & e-mail", "Bloc trois offres e-mail", { titre: "Trois façons\nde commencer", sous: "Aucun engagement, aucune carte bancaire.", items: ["Découvrir|Un tour du produit en 4 minutes.", "Essayer|14 jours, toutes les fonctions.", "En parler|30 minutes avec quelqu'un de l'équipe."] }],
  ["avantages", "large", "froid", "Web & e-mail", "Bloc réassurance", { titre: "Trois raisons\nde nous faire\nconfiance", sous: "Affichées sur chaque page de commande.", items: ["Paiement sécurisé|Certificat vérifiable, aucune donnée stockée.", "Retour gratuit|Trente jours, étiquette incluse.", "Assistance humaine|Du lundi au samedi, 9 h à 18 h."], meta: "Mentions légales et CGV accessibles en bas de page" }],
  ["faq", "a4", "clair", "Web & e-mail", "FAQ de site", { sur: "Aide", titre: "Les questions\nles plus posées", items: ["Comment suivre ma commande ?|Un lien de suivi part par SMS dès l'expédition.", "Comment modifier mon adresse ?|Depuis votre compte, tant que le colis n'est pas parti.", "Comment vous joindre ?|05 56 00 00 00 ou bonjour@exemple.fr.", "Puis-je payer en plusieurs fois ?|Oui, en trois fois sans frais dès 100 €."], meta: "Centre d'aide complet : exemple.fr/aide" }],
  ["sommaire", "a4", "clair", "Web & e-mail", "Plan de site", { sur: "Plan du site", titre: "Tout\nle contenu", items: ["Accueil|/", "Boutique|/boutique", "Notre atelier|/atelier", "Journal|/journal", "Aide et livraison|/aide", "Mentions légales|/mentions"], meta: "Dernière mise à jour : avril 2026" }],
  ["cadre", "a4", "clair", "Web & e-mail", "Page de mentions légales", { sur: "Mentions légales", titre: "Éditeur\ndu site", sous: "Aubépine SAS, capital de 10 000 €, RCS Bordeaux 000 000 000, siège social 12 rue du Marché, 33000 Bordeaux. Directeur de la publication : Sofia Bernard.", meta: "HÉBERGEUR : NOM, ADRESSE, TÉLÉPHONE" }],
  ["mosaique", "large", "pastel", "Web & e-mail", "Page de remerciement", { titre: "Merci,\nc'est validé", sous: "Un e-mail de confirmation vient de partir. Vérifiez vos indésirables si rien n'arrive." }],
  ["question", "large", "clair", "Web & e-mail", "Page introuvable", { sur: "Erreur 404", titre: "Cette page\nn'existe pas\nou plus", sous: "Le lien est peut-être ancien. La boutique et le journal, eux, sont toujours là." }],
  ["progression", "large", "tech", "Web & e-mail", "Page de maintenance", { sur: "Maintenance", titre: "On remet\nle site\nd'aplomb", gros: "65", sous: "Retour prévu à 14 h. Les commandes en cours ne sont pas affectées.", meta: "SUIVI EN DIRECT SUR STATUS.EXEMPLE.FR" }],
  ["typo", "large", "sombre", "Web & e-mail", "Page à venir", { titre: "BIENTÔT\nEN LIGNE", sous: "Laissez votre adresse, vous serez prévenu en premier.", meta: "exemple.fr" }],

];
