// Modèles — impression, présentation, papeterie, marque.
//
// Ce qui se pose sur une table, s'accroche à un mur ou se projette sur un
// écran. Les formats sont ceux de l'imprimeur (A4, A3, A5, cartes) et de la
// salle de réunion (16/9, 4/3). Les contenus sont écrits pour être lus de
// loin ou en diagonale : peu de mots, mais les bons.

import type { Row } from "./design-templates";

export const ROWS_PRINT: Row[] = [

  /* ══════════ Impression & affiche ══════════ */

  ["bloc", "affiche", "vif", "Impression & affiche", "Affiche brutaliste", { titre: "TROIS\nJOURS\nSEULEMENT", sous: "Portes ouvertes de l'atelier : démonstrations, ventes directes, café offert.", meta: "DU 12 AU 14 JUIN — 4 RUE DES FORGES" }],
  ["bloc", "a3", "sombre", "Impression & affiche", "Affiche de conférence", { titre: "PENSER\nPLUS\nLENTEMENT", sous: "Conférence publique de Sofia Bernard, suivie d'une discussion avec la salle.", meta: "JEUDI 15 OCTOBRE — 19 H — SALLE DES FÊTES" }],
  ["ombredure", "affiche", "vif", "Impression & affiche", "Affiche typographique", { sur: "Association du quartier", titre: "ON SE\nBOUGE", sous: "Assemblée générale ouverte à tous les habitants, avec vote du budget.", meta: "MARDI 3 JUIN — 18 H 30 — MAIRIE ANNEXE" }],
  ["contour", "affiche", "sombre", "Impression & affiche", "Affiche lettres creuses", { sur: "Exposition", gros: "TRACES", titre: "Photographies argentiques, 1994-2026", sous: "Trente ans de reportages en noir et blanc, tirages d'époque.", meta: "GALERIE DU PORT — DU 3 AVRIL AU 30 MAI" }],
  ["rayures", "a3", "vif", "Impression & affiche", "Affiche de kermesse", { sur: "École Jean Moulin", titre: "GRANDE\nKERMESSE", sous: "Jeux, stands, tombola et barbecue. Bénéfices intégralement reversés à la coopérative.", meta: "SAMEDI 21 JUIN — 11 H À 18 H" }],
  ["damier", "a3", "sombre", "Impression & affiche", "Affiche de tournoi", { sur: "Club d'échecs", titre: "TOURNOI\nOUVERT", sous: "Cadence 15 minutes plus 5 secondes, sept rondes, inscription sur place.", meta: "DIMANCHE 8 NOVEMBRE — DÈS 9 H" }],
  ["soleil", "affiche", "chaud", "Impression & affiche", "Affiche de fête d'été", { sur: "Comité des fêtes", titre: "Fête\nde l'été", sous: "Bal, buvette, feu d'artifice à 23 h. Entrée libre, repli en salle si pluie.", meta: "SAMEDI 27 JUIN — PLACE DU MARCHÉ" }],
  ["montagne", "affiche", "nature", "Impression & affiche", "Affiche de randonnée", { sur: "Randonnée annuelle", titre: "La marche\ndes crêtes", sous: "Trois parcours : 8, 15 et 24 kilomètres. Ravitaillement compris, départ échelonné.", meta: "DIMANCHE 17 MAI — DÉPART DÈS 7 H 30" }],
  ["vagues", "affiche", "froid", "Impression & affiche", "Affiche de fête nautique", { sur: "Port de plaisance", titre: "Fête\ndu port", sous: "Régates, baptêmes de voile, marché de producteurs et concert le soir.", meta: "SAMEDI 4 JUILLET — DE 10 H À MINUIT" }],
  ["pois", "a3", "pastel", "Impression & affiche", "Affiche d'atelier enfants", { sur: "Bibliothèque municipale", titre: "L'heure\ndu conte", sous: "Tous les mercredis à 15 h, pour les 3 à 7 ans, accompagnés d'un adulte.", meta: "ENTRÉE LIBRE — SANS INSCRIPTION" }],
  ["arche", "affiche", "chic", "Impression & affiche", "Affiche de concert classique", { sur: "Saison musicale", titre: "Quatuor\nà cordes", sous: "Haydn, Ravel et Chostakovitch. Concert d'une heure quinze, sans entracte.", meta: "VENDREDI 12 JUIN — 20 H 30 — ÉGLISE SAINT-LOUIS" }],
  ["disque", "a3", "vif", "Impression & affiche", "Affiche d'ouverture", { sur: "Ouverture", titre: "La médiathèque rouvre", sous: "Après dix-huit mois de travaux, avec deux fois plus de places assises.", meta: "SAMEDI 5 SEPTEMBRE — 10 H" }],
  ["sablier", "a3", "sombre", "Impression & affiche", "Affiche de dernière séance", { sur: "DERNIÈRE SEMAINE", titre: "L'exposition\nferme dimanche", sous: "Dernières visites guidées à 11 h et 15 h, sans réservation.", meta: "GALERIE DU PORT — ENTRÉE LIBRE" }],
  ["cadre", "a3", "chic", "Impression & affiche", "Affiche sobre encadrée", { sur: "Vernissage", titre: "Traces", sous: "En présence de l'auteur, verre offert à partir de 18 h 30.", meta: "VENDREDI 3 AVRIL — GALERIE DU PORT" }],
  ["journal", "a3", "clair", "Impression & affiche", "Affiche façon journal", { sur: "LE JOURNAL DU QUARTIER", meta: "NUMÉRO 12 — JUIN 2026 — GRATUIT", titre: "La rue des Halles\nrouvre à pied", sous: "Après deux ans de discussions et six mois de travaux, la voie devient piétonne du lundi au samedi.", items: ["Les commerçants attendaient cette décision depuis 2019. Les premiers relevés montrent une fréquentation en hausse de vingt-trois pour cent sur les samedis d'essai, sans report notable sur les rues voisines.", "Le stationnement reste possible sur le parking Vauban, à cent mètres, dont les deux premières heures deviennent gratuites. Une navette électrique dessert la place toutes les vingt minutes.", "Reste la question des livraisons, tranchée provisoirement : elles sont autorisées avant dix heures. Un bilan est prévu en décembre, avec une réunion publique ouverte à tous les riverains."], cta: "PROCHAIN NUMÉRO EN SEPTEMBRE — CONTRIBUTIONS BIENVENUES" }],
  ["magazine", "a3", "chic", "Impression & affiche", "Couverture de programme", { sur: "SAISON", meta: "2026-2027 — THÉÂTRE MUNICIPAL", titre: "Vingt-\nquatre\nsoirs", sous: "Une saison de théâtre, de danse et de musique, construite avec le public.", items: ["Douze spectacles, six créations", "Abonnement dès 60 €", "Tarif unique pour les moins de 26 ans"] }],
  ["grille", "a3", "clair", "Impression & affiche", "Affiche programme", { titre: "Le programme\nde la saison", sous: "Six rendez-vous, d'octobre à mars", items: ["Octobre", "Novembre", "Décembre", "Janvier", "Février", "Mars"], meta: "Abonnement six spectacles : 60 € — à l'unité : 14 €" }],
  ["sommaire", "a4", "clair", "Impression & affiche", "Programme détaillé", { sur: "Saison 2026-2027", titre: "Le programme", items: ["Ouverture — Quatuor à cordes|10 oct.", "Théâtre — Les Justes|14 nov.", "Danse — Corps communs|12 déc.", "Musique — Trio Aubépine|16 janv.", "Théâtre — Création|13 févr.", "Clôture — Bal|20 mars"], meta: "Billetterie ouverte le 1er septembre — 05 56 00 00 00" }],
  ["horaires", "a4", "terre", "Impression & affiche", "Affichette d'ouverture", { sur: "Ouvert au public", titre: "Horaires", items: ["Lundi|Fermé", "Mardi – vendredi|10 h – 18 h", "Samedi|10 h – 19 h", "Dimanche|14 h – 18 h", "Jours fériés|Fermé"], meta: "DERNIÈRE ENTRÉE TRENTE MINUTES AVANT LA FERMETURE" }],
  ["contact", "a4", "clair", "Impression & affiche", "Affichette de contact", { sur: "Nous joindre", titre: "En cas\nde besoin", sous: "Une permanence physique tous les mardis matin.", items: ["05 56 00 00 00", "accueil@exemple.fr", "12 rue du Marché, Bordeaux", "Permanence : mardi 9 h – 12 h"], meta: "Accueil accessible aux personnes à mobilité réduite" }],
  ["checklist", "a4", "clair", "Impression & affiche", "Consignes affichées", { sur: "Consignes", titre: "Avant de\nquitter les lieux", items: ["Éteindre les lumières de la salle", "Fermer les fenêtres, y compris en hauteur", "Ranger les chaises contre le mur", "Vider les poubelles dans le local", "Couper l'eau du point d'eau", "Fermer à clé et déposer le trousseau", "Signaler tout problème sur le cahier"], meta: "Merci de laisser la salle comme vous aimeriez la trouver" }],
  ["cadre", "a4", "clair", "Impression & affiche", "Affichette réglementaire", { sur: "Information", titre: "Établissement\nnon-fumeur", sous: "Il est interdit de fumer et de vapoter dans l'ensemble des locaux, y compris les parties communes.", meta: "ARTICLE R.3512-2 DU CODE DE LA SANTÉ PUBLIQUE" }],
  ["ruban", "a4", "chaud", "Impression & affiche", "Affichette de fermeture", { sur: "Information", titre: "FERMÉ", sous: "Fermeture exceptionnelle le lundi 5 mai. Réouverture le mardi 6 à 10 h.", meta: "MERCI DE VOTRE COMPRÉHENSION" }],
  ["typo", "a3", "sombre", "Impression & affiche", "Affiche manifeste", { titre: "RIEN\nNE SE FAIT\nTOUT SEUL", sous: "L'association a besoin de six bénévoles pour tenir la saison.", meta: "RENSEIGNEMENTS À L'ACCUEIL" }],
  ["souligne", "a3", "clair", "Impression & affiche", "Affiche trois mots", { sur: "Semaine de la propreté", titre: "Trier.\nRéparer.\nDonner.", sous: "Trois ateliers gratuits, du lundi au samedi, à la maison de quartier.", meta: "DU 8 AU 13 JUIN — PROGRAMME À L'ACCUEIL" }],
  ["coins", "a3", "chic", "Impression & affiche", "Affiche photo", { sur: "Concours photo", titre: "La ville\nà hauteur\nd'enfant", sous: "Ouvert à tous, deux photos par participant, tirage argentique offert aux lauréats.", meta: "DÉPÔT JUSQU'AU 30 SEPTEMBRE" }],
  ["etiquette", "etiq", "terre", "Impression & affiche", "Étiquette de bocal", { sur: "CONFITURE MAISON", gros: "250 g", titre: "Abricots de la Combe,\nrécolte 2026", sous: "Fruits, sucre de canne, jus de citron. Rien d'autre.", meta: "À CONSERVER AU FRAIS APRÈS OUVERTURE" }],
  ["etiquette", "etiq", "nature", "Impression & affiche", "Étiquette de plant", { sur: "PLANT DE SAISON", gros: "3,50 €", titre: "Tomate Coeur de Boeuf,\nplant greffé", sous: "Repiquer après les Saints de glace, arroser au pied.", meta: "PRODUIT À LA FERME DE LA COMBE" }],
  ["billet", "billet", "vif", "Impression & affiche", "Ticket de tombola", { sur: "TOMBOLA", titre: "KERMESSE 2026", gros: "2€", meta: "N° 000 000", sous: "Tirage à 17 h — présence non obligatoire — un lot par ticket gagnant" }],
  ["billet", "billet", "sombre", "Impression & affiche", "Ticket de vestiaire", { sur: "VESTIAIRE", titre: "SALLE DES FÊTES", gros: "042", meta: "SOIRÉE DU 12 JUIN", sous: "Objet remis contre présentation du ticket — aucun duplicata" }],

  /* ══════════ Présentation ══════════ */

  ["couverture", "slide", "sombre", "Présentation", "Diapositive d'ouverture", { sur: "Comité de direction", titre: "Bilan\ndu premier\nsemestre", sous: "Résultats, écarts au budget, et trois décisions à prendre aujourd'hui.", auteur: "Sofia Bernard — 12 juillet 2026" }],
  ["couverture", "diapo43", "chic", "Présentation", "Ouverture sobre", { sur: "Assemblée générale", titre: "Rapport\nannuel 2026", sous: "Activité, comptes et perspectives, présentés en quarante minutes.", auteur: "Association du quartier — 20 juin 2026" }],
  ["sommaire", "slide", "clair", "Présentation", "Sommaire de présentation", { sur: "Au programme", titre: "Ce qu'on\nva voir", items: ["Où nous en sommes|3", "Ce qui a changé|8", "Les trois écarts|14", "Ce que ça coûte|19", "Décisions à prendre|24", "Questions|30"], meta: "Quarante minutes, questions comprises" }],
  ["chapitre", "slide", "tech", "Présentation", "Séparateur de partie", { gros: "02", sur: "Partie", titre: "Ce qui\na changé", sous: "Trois évolutions majeures depuis janvier, et leurs effets mesurés.", meta: "PAGES 8 À 13" }],
  ["stats", "slide", "tech", "Présentation", "Diapositive chiffres", { sur: "Premier semestre", titre: "Trois chiffres\nà retenir", items: ["+18 %|de chiffre d'affaires", "-32 %|de délai moyen", "0|départ subi"], meta: "Comparaison à périmètre constant, hors cession de l'activité Nord" }],
  ["duo", "slide", "vif", "Présentation", "Deux chiffres opposés", { gros: "2026", items: ["+18 %|de chiffre d'affaires", "-4 pts|de marge brute"] }],
  ["tableau", "slide", "clair", "Présentation", "Tableau de résultats", { titre: "Résultats\npar activité", sous: "En milliers d'euros, premier semestre 2026.", sur: "ACTIVITÉ|CHIFFRE D'AFFAIRES", items: ["Atelier|1 240", "Boutique|860", "En ligne|1 910", "Grands comptes|640", "Formation|180", "Total|4 830"], meta: "Chiffres non audités — arrêté au 30 juin 2026" }],
  ["comparatif", "slide", "froid", "Présentation", "Deux scénarios", { titre: "Deux scénarios\npour 2027", sur: "PRUDENT", cta: "OFFENSIF", items: ["Croissance 6 %|Croissance 18 %", "Aucun recrutement|Quatre recrutements", "Marge maintenue|Marge -3 pts", "Trésorerie stable|Besoin de 400 k€", "Risque faible|Risque modéré"], meta: "Décision demandée aujourd'hui" }],
  ["chrono", "slide", "tech", "Présentation", "Jalons du plan", { titre: "Les jalons\nde 2027", sous: "Quatre décisions, quatre dates.", items: ["T1|Validation du budget.", "T2|Recrutements.", "T3|Ouverture Lyon.", "T4|Bilan et arbitrage."], meta: "Chaque jalon fait l'objet d'un point en comité" }],
  ["etapes", "slide", "froid", "Présentation", "Méthode en quatre temps", { titre: "Comment\non s'y prend", sous: "Une méthode déjà appliquée sur deux chantiers.", items: ["Constater|Chiffres partagés avec les équipes.", "Décider|Une seule réunion, décision écrite.", "Faire|Un responsable nommé, une date.", "Vérifier|Point à trente jours, sans exception."] }],
  ["frise", "slide", "chic", "Présentation", "Historique du projet", { titre: "D'où\non part", sous: "Le projet a trois ans, il est utile de le rappeler.", items: ["2023|Première étude, abandonnée.", "2024|Reprise avec un périmètre réduit.", "2025|Pilote sur deux sites.", "2026|Généralisation en cours.", "2027|Bilan et arbitrage."], meta: "Documents des étapes précédentes disponibles sur demande" }],
  ["liste", "slide", "clair", "Présentation", "Points clés", { sur: "À retenir", titre: "Cinq points\nde vigilance", items: ["Le délai fournisseur reste le facteur limitant", "Deux sites sur cinq n'ont pas encore basculé", "Le budget formation est consommé à 90 %", "Le turnover a baissé, mais reste au-dessus du secteur", "Aucun indicateur ne se dégrade"], meta: "Détail chiffré en annexe, pages 31 à 38" }],
  ["avantages", "slide", "froid", "Présentation", "Trois recommandations", { titre: "Nos trois\nrecommandations", sous: "Classées par effet attendu, pas par facilité.", items: ["Recruter deux personnes|Effet immédiat sur le délai, coût 78 k€ par an.", "Fermer l'activité Nord|Marge négative depuis 2024, sortie propre en six mois.", "Décaler le projet Lyon|Six mois, le temps de stabiliser l'existant."], meta: "Chiffrage détaillé en annexe" }],
  ["question", "slide", "sombre", "Présentation", "Diapositive question", { sur: "La vraie question", titre: "Sommes-nous\nprêts à ralentir\npour tenir ?", sous: "La réponse conditionne les trois arbitrages qui suivent." }],
  ["citation", "slide", "chic", "Présentation", "Diapositive citation", { titre: "« Un plan qui\nn'a pas de date\nn'est pas\nun plan. »", auteur: "Règle interne, depuis 2022", sous: "Affichée en salle de réunion" }],
  ["progression", "slide", "vif", "Présentation", "Avancement de projet", { sur: "Projet Lyon", titre: "Où\nnous en sommes", gros: "45", sous: "Local signé, équipe non recrutée, ouverture décalée à septembre.", meta: "PROCHAIN POINT : 15 MAI" }],
  ["equipe", "slide", "clair", "Présentation", "L'équipe projet", { titre: "Qui fait\nquoi", sous: "Un responsable par chantier, nommément.", items: ["Sofia|Pilotage", "Marc|Technique", "Aline|Clients", "Noé|Budget"] }],
  ["mosaique", "slide", "pastel", "Présentation", "Diapositive de clôture", { titre: "Merci", sous: "Questions, remarques, objections : c'est le moment." }],
  ["typo", "slide", "sombre", "Présentation", "Diapositive à message unique", { titre: "ON ARRÊTE\nL'ACTIVITÉ\nNORD", sous: "Décision proposée au vote, effet au 31 décembre.", meta: "Détail pages 19 à 23" }],
  ["cartes", "slide", "froid", "Présentation", "Trois options", { titre: "Trois options,\nune décision", sous: "Chacune est chiffrée, aucune n'est neutre.", items: ["Statu quo|Aucun coût, aucun gain, risque croissant.", "Réduction|-140 k€ de charges, six postes concernés.", "Investissement|+400 k€, retour attendu en 2028."] }],
  ["chiffre", "slide", "tech", "Présentation", "Chiffre unique", { sur: "Le chiffre du semestre", gros: "4,8 M€", titre: "de chiffre d'affaires consolidé", sous: "En progression de 18 % à périmètre constant.", cta: "Détail par activité en page 11" }],
  ["diapo", "slide", "clair", "Présentation", "Diapositive à puces", { sur: "Constats", titre: "Ce que disent\nles chiffres", items: ["Le délai moyen a baissé de douze à huit jours", "Deux sites concentrent 80 % des retards", "La satisfaction client gagne quatre points", "Le coût par dossier reste stable"], sous: "Aucune de ces évolutions n'est due à un effet de périmètre.", meta: "Source : tableau de bord mensuel, juin 2026" }],
  ["colonnes", "slide", "clair", "Présentation", "Diapositive de synthèse", { sur: "Synthèse", titre: "En deux\nparagraphes", sous: "Pour ceux qui n'auront pas le temps de tout lire.", items: ["Le semestre est bon, mais la croissance vient d'une seule activité. En ligne représente désormais quarante pour cent du chiffre d'affaires, contre vingt-huit l'an dernier. Cette concentration est une force à court terme et une fragilité à moyen terme.", "Deux décisions sont demandées aujourd'hui : le sort de l'activité Nord, déficitaire depuis deux ans, et le calendrier de Lyon. Les deux sont indépendantes, mais la seconde suppose la première."], meta: "COMITÉ DE DIRECTION — 12 JUILLET 2026" }],
  ["faq", "slide", "clair", "Présentation", "Diapositive questions anticipées", { sur: "Questions attendues", titre: "Nos réponses,\navant que\nvous demandiez", items: ["Pourquoi ne pas avoir agi plus tôt ?|Le pilote n'était pas concluant avant octobre.", "Quel effet sur l'emploi ?|Six postes concernés, cinq reclassements possibles.", "Et si on ne fait rien ?|Perte estimée à 180 k€ sur 2027.", "Qui pilote ?|Sofia Bernard, avec un point mensuel en comité."], meta: "Autres questions : maintenant" }],

  /* ══════════ Carte & papeterie ══════════ */

  ["visite", "carte", "chic", "Carte & papeterie", "Carte de visite classique", { gros: "SB", titre: "Sofia Bernard", sur: "DIRECTRICE DES OPÉRATIONS", sous: "Aubépine · 12 rue du Marché, Bordeaux · 06 00 00 00 00" }],
  ["visite", "carte", "sombre", "Carte & papeterie", "Carte de visite sombre", { gros: "MV", titre: "Marc Vidal", sur: "PHOTOGRAPHE", sous: "marcvidal.fr · 06 00 00 00 00 · Bordeaux et alentours" }],
  ["visite", "carte", "nature", "Carte & papeterie", "Carte de visite nature", { gros: "AR", titre: "Aline Roux", sur: "PAYSAGISTE — CONCEPTRICE", sous: "06 00 00 00 00 · aline@jardins-roux.fr · Gironde" }],
  ["monogramme", "carte", "chic", "Carte & papeterie", "Carte monogramme", { gros: "AB", titre: "Atelier Berthier", sous: "MENUISERIE — BORDEAUX" }],
  ["embleme", "carte", "terre", "Carte & papeterie", "Carte à emblème", { meta: "seal", gros: "FC", titre: "Ferme de la Combe", sous: "VENTE DIRECTE DEPUIS 1998" }],
  ["contact", "carte", "clair", "Carte & papeterie", "Carte de coordonnées", { sur: "Nous joindre", titre: "Toujours\njoignables", sous: "Du lundi au samedi, de 9 h à 18 h.", items: ["05 56 00 00 00", "bonjour@exemple.fr", "12 rue du Marché, Bordeaux", "exemple.fr"], meta: "Réponse sous 24 h ouvrées" }],
  ["etiquette", "carteV", "chic", "Carte & papeterie", "Carte verticale", { sur: "ATELIER", gros: "AB", titre: "Atelier Berthier,\nmenuiserie", sous: "Sur rendez-vous, 4 rue des Forges.", meta: "06 00 00 00 00" }],
  ["cadre", "a5", "chic", "Carte & papeterie", "Carte de remerciement", { sur: "Merci", titre: "Pour votre\nprésence", sous: "Votre venue a rendu cette journée plus douce. Nous ne l'oublierons pas.", meta: "SOFIA ET MARC — JUIN 2026" }],
  ["cadre", "a5", "pastel", "Carte & papeterie", "Carte de vœux", { sur: "2027", titre: "Bonne\nannée", sous: "Que celle-ci vous apporte un peu plus de temps, et un peu moins d'urgence.", meta: "TOUTE L'ÉQUIPE D'AUBÉPINE" }],
  ["arche", "a5", "chic", "Carte & papeterie", "Faire-part élégant", { sur: "Nous nous marions", titre: "Sofia\n& Marc", sous: "Le 12 septembre 2026, à partir de 16 h, au domaine de la Combe.", meta: "RÉPONSE SOUHAITÉE AVANT LE 1ER AOÛT" }],
  ["cadre", "a5", "pastel", "Carte & papeterie", "Faire-part de naissance", { sur: "Elle est là", titre: "Camille", sous: "Née le 3 avril 2026, 3,2 kg, et déjà une opinion sur tout.", meta: "SOFIA ET MARC BERTHIER" }],
  ["entete", "a4", "clair", "Carte & papeterie", "Papier à lettres", { titre: "Aubépine", sur: "Atelier et boutique", sous: "12 rue du Marché\n33000 Bordeaux\n05 56 00 00 00", meta: "OBJET : ____________________", items: ["Madame, Monsieur,", "", "", "", "", "Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées."], cta: "SAS au capital de 10 000 € — RCS Bordeaux 000 000 000 — TVA FR00000000000" }],
  ["entete", "a4", "chic", "Carte & papeterie", "Papier à en-tête sobre", { titre: "Sofia Bernard", sur: "Conseil en organisation", sous: "06 00 00 00 00\nsofia@exemple.fr\nBordeaux", meta: "NOTE — ____________________", items: ["", "", "", "", "", ""], cta: "SIRET 000 000 000 00000 — dispensée d'immatriculation" }],
  ["tableau", "a4", "clair", "Carte & papeterie", "Facture", { titre: "Facture\nn° 2026-0184", sous: "Émise le 12 avril 2026 — échéance le 12 mai 2026.", sur: "DÉSIGNATION|MONTANT HT", items: ["Conception graphique|1 200,00 €", "Déclinaisons (4 formats)|380,00 €", "Retouches (2 tours)|Incluses", "Total HT|1 580,00 €", "TVA 20 %|316,00 €", "Total TTC|1 896,00 €"], meta: "Paiement à 30 jours — pénalités de retard : 3 fois le taux légal — indemnité forfaitaire 40 €" }],
  ["tableau", "a4", "froid", "Carte & papeterie", "Devis", { titre: "Devis\nn° D-2026-0092", sous: "Établi le 3 avril 2026 — valable trois mois.", sur: "PRESTATION|MONTANT HT", items: ["Relevé de cotes et étude|Offert", "Fabrication escalier chêne|2 800,00 €", "Traitement et finition|420,00 €", "Pose sur site (2 jours)|760,00 €", "Total HT|3 980,00 €", "Total TTC (TVA 10 %)|4 378,00 €"], meta: "Bon pour accord, date et signature — acompte de 30 % à la commande" }],
  ["billet", "billet", "chic", "Carte & papeterie", "Marque-place", { sur: "TABLE 4", titre: "SOFIA BERNARD", gros: "04", meta: "MARIAGE — 12 SEPTEMBRE 2026", sous: "Menu adapté signalé au service" }],
  ["etiquette", "etiq", "pastel", "Carte & papeterie", "Étiquette de cadeau", { sur: "POUR", gros: "🎁", titre: "Camille,\navec toute notre affection", sous: "À ouvrir le 25, pas avant.", meta: "SOFIA ET MARC" }],
  ["sceau", "carre", "chic", "Carte & papeterie", "Cachet de cire", { sur: "ATELIER", gros: "AB", meta: "DEPUIS 2019", titre: "Atelier Berthier", sous: "Chaque envoi est cacheté à la main." }],

  /* ══════════ Marque & logo ══════════ */

  ["embleme", "logo", "chic", "Marque & logo", "Emblème anneau", { meta: "ring", gros: "AB", titre: "Atelier Berthier", sous: "MENUISERIE D'ART" }],
  ["embleme", "logo", "sombre", "Marque & logo", "Emblème bouclier", { meta: "shield", gros: "GD", titre: "Garage Dupont", sous: "MÉCANIQUE GÉNÉRALE" }],
  ["embleme", "logo", "nature", "Marque & logo", "Emblème hexagone", { meta: "hexagon", gros: "FC", titre: "Ferme de la Combe", sous: "VENTE DIRECTE" }],
  ["embleme", "logo", "vif", "Marque & logo", "Emblème sceau", { meta: "seal", gros: "FH", titre: "Festival des Halles", sous: "TROIS JOURS, QUATRE SCÈNES" }],
  ["embleme", "logo", "froid", "Marque & logo", "Emblème losange", { meta: "diamond", gros: "SV", titre: "Studio Verrier", sous: "PHOTOGRAPHIE" }],
  ["monogramme", "logo", "chic", "Marque & logo", "Monogramme serif", { gros: "MB", titre: "Maison Berthier", sous: "PARFUMEUR DEPUIS 1974" }],
  ["monogramme", "logo", "terre", "Marque & logo", "Monogramme terre", { gros: "LC", titre: "La Combe", sous: "MIELS ET CONFITURES" }],
  ["monogramme", "logo", "sombre", "Marque & logo", "Monogramme sombre", { gros: "AR", titre: "Aline Roux", sous: "ARCHITECTE D'INTÉRIEUR" }],
  ["ecusson", "logo", "sombre", "Marque & logo", "Écusson de club", { gros: "ASR", meta: "EST. 1962", titre: "AS Rivière", sous: "Ne rien lâcher" }],
  ["ecusson", "logo", "terre", "Marque & logo", "Écusson artisan", { gros: "MB", meta: "DEPUIS 2006", titre: "Menuiserie Berthier", sous: "Le bois, correctement" }],
  ["sceau", "logo", "chic", "Marque & logo", "Sceau de qualité", { sur: "FAIT MAIN", gros: "100%", meta: "BORDEAUX", titre: "Atelier Berthier", sous: "Aucune sous-traitance, jamais." }],
  ["typo", "logo", "vif", "Marque & logo", "Logotype typographique", { titre: "AUBÉ\nPINE", sous: "Fichiers, design, partage.", meta: "aubepine.fr" }],
  ["contour", "logo", "sombre", "Marque & logo", "Logotype creux", { sur: "Studio", gros: "SV", titre: "Studio Verrier", sous: "Photographie culinaire et d'atelier.", meta: "BORDEAUX" }],
  ["disque", "logo", "vif", "Marque & logo", "Pastille de marque", { sur: "Depuis 2019", titre: "Aubépine", sous: "Tout au même endroit.", meta: "AUBEPINE.FR" }],
  ["arche", "logo", "chic", "Marque & logo", "Logotype sous arche", { sur: "Maison", titre: "Berthier", sous: "Parfumeur à Grasse depuis 1974.", meta: "PARIS — GRASSE" }],
  ["visite", "logo", "froid", "Marque & logo", "Bloc-marque", { gros: "AB", titre: "Atelier Berthier", sur: "MENUISERIE — AGENCEMENT", sous: "4 rue des Forges, Bordeaux · 06 00 00 00 00" }],
  ["souligne", "carreL", "clair", "Marque & logo", "Baseline en trois mots", { sur: "Notre promesse", titre: "Simple.\nSolide.\nRéparable.", sous: "Trois mots qui décident de ce qu'on fabrique, et surtout de ce qu'on ne fabrique pas.", meta: "atelierberthier.fr" }],
  ["cartes", "slide", "clair", "Marque & logo", "Charte : usages du logo", { titre: "Trois usages\ndu logo", sous: "Toute autre déclinaison doit être validée.", items: ["Principal|Sur fond clair, taille minimale 24 mm.", "Monochrome|Sur photo ou fond coloré, sans ombre.", "Réduit|Sous 24 mm, le monogramme seul."] }],
  ["tableau", "slide", "clair", "Marque & logo", "Charte : couleurs", { titre: "Nos couleurs", sous: "Références à respecter sur tous les supports.", sur: "COULEUR|RÉFÉRENCE", items: ["Encre|#1C1B18", "Accent|#7A6A3E", "Fond papier|#F7F3EA", "Gris texte|#5C574C", "Rouge alerte|#B91C1C", "Blanc|#FFFFFF"], meta: "Équivalents Pantone et CMJN disponibles dans la charte complète" }],
  ["tableau", "slide", "clair", "Marque & logo", "Charte : typographies", { titre: "Nos\ntypographies", sous: "Deux familles, pas une de plus.", sur: "USAGE|POLICE", items: ["Titres|Serif, graisse 700", "Sous-titres|Serif, graisse 400 italique", "Texte courant|Sans, graisse 400", "Chiffres clés|Sans, graisse 900", "Mentions légales|Sans, graisse 400, 8 pt", "Interdit|Toute autre police"], meta: "Substituts système indiqués dans la charte complète" }],

  /* ══════════ CV & document ══════════ */

  ["cv", "cv", "clair", "CV & document", "CV commercial", { gros: "NT", titre: "Noé\nTissot", sur: "RESPONSABLE COMMERCIAL", sous: "06 00 00 00 00\nnoe@exemple.fr\nBordeaux\nPermis B, véhicule", meta: "PARCOURS", items: ["Responsable commercial — Aubépine|2021 à aujourd'hui. Portefeuille de 140 clients, croissance annuelle de 22 % sur trois ans.", "Chargé d'affaires — Groupe Roux|2018-2021. Ouverture du secteur Sud-Ouest, 40 nouveaux comptes.", "Commercial sédentaire — Studio Verrier|2016-2018. Prise de commandes et suivi de la relation client.", "BTS négociation|Lycée Montaigne, Bordeaux, 2016."] }],
  ["cv", "cv", "nature", "CV & document", "CV reconversion", { gros: "CD", titre: "Camille\nDurand", sur: "EN RECONVERSION — MARAÎCHAGE", sous: "06 00 00 00 00\ncamille@exemple.fr\nGironde\nDisponible immédiatement", meta: "PARCOURS", items: ["Certificat de spécialisation maraîchage|CFPPA de Blanquefort, 2026. Six mois, dont trois en exploitation.", "Saisonnière — Ferme de la Combe|Été 2025. Récolte, conditionnement, vente directe sur marché.", "Chargée de projet — Groupe Roux|2017-2025. Huit ans de pilotage de projets, budgets jusqu'à 600 k€.", "Master gestion|Université de Bordeaux, 2017."] }],
  ["cv", "cv", "chic", "CV & document", "CV créatif", { gros: "SV", titre: "Sophie\nVerrier", sur: "DIRECTRICE ARTISTIQUE", sous: "06 00 00 00 00\nsophie@exemple.fr\nBordeaux\nPortfolio : sverrier.fr", meta: "EXPÉRIENCE", items: ["Directrice artistique — Studio Verrier|2020 à aujourd'hui. Identité visuelle de 40 marques, dont 6 nationales.", "Designer graphique — Agence Aubépine|2016-2020. Édition, packaging et signalétique.", "Graphiste junior — Imprimerie du Port|2014-2016. Préparation de fichiers et suivi de fabrication.", "DNSEP design graphique|EBABX, Bordeaux, 2014."] }],
  ["colonnes", "a4", "clair", "CV & document", "Lettre de recommandation", { sur: "Recommandation", titre: "Au sujet\nde Sofia\nBernard", sous: "Rédigée à sa demande, sans réserve.", items: ["Sofia a rejoint l'équipe en 2022 pour reprendre un service client de six personnes qui fonctionnait sans procédure écrite. En dix-huit mois, elle a divisé le délai de traitement par six, sans recruter et sans dégrader les conditions de travail — le turnover a même baissé.", "Elle sait dire non, argumente ses refus, et documente ses décisions. C'est rare. Je la recommande sans réserve à toute organisation qui cherche quelqu'un capable de structurer sans casser."], meta: "MARC VIDAL, DIRECTEUR GÉNÉRAL — 12 AVRIL 2026" }],
  ["sommaire", "a4", "clair", "CV & document", "Sommaire de rapport", { sur: "Rapport annuel", titre: "Sommaire", items: ["Le mot de la présidente|3", "Activité de l'année|5", "Comptes et budget|14", "Projets 2027|22", "Vie associative|28", "Annexes|34"], meta: "Rapport approuvé en assemblée générale du 20 juin 2026" }],
  ["chapitre", "a4", "chic", "CV & document", "Ouverture de rapport", { gros: "02", sur: "Chapitre", titre: "Activité\nde l'année", sous: "Ce qui a été fait, ce qui ne l'a pas été, et pourquoi.", meta: "PAGES 5 À 13" }],
  ["certificat", "paysage", "chic", "CV & document", "Attestation de formation", { sur: "ATTESTATION DE FORMATION", titre: "Aline Roux", auteur: "Sofia Bernard, responsable pédagogique", sous: "a suivi la formation « Sécurité au travail » d'une durée de quatorze heures, réparties sur deux journées.", meta: "BORDEAUX, LE 12 AVRIL 2026" }],
  ["certificat", "paysage", "sombre", "CV & document", "Diplôme d'honneur", { sur: "DIPLÔME D'HONNEUR", titre: "Marc Vidal", auteur: "Le conseil d'administration", sous: "pour vingt années de bénévolat au service de l'association et de ses adhérents.", meta: "ASSEMBLÉE GÉNÉRALE DU 20 JUIN 2026" }],
  ["fiche", "a4", "clair", "CV & document", "Fiche de poste", { titre: "Fiche de poste :\nchargé·e de clientèle", meta: "CDI 35 h — Bordeaux — rattachement : direction des opérations", sur: "MISSIONS", sous: "COMPÉTENCES ATTENDUES", items: ["Traiter les demandes entrantes sous 4 h", "Suivre un portefeuille de 200 clients", "Alimenter le tableau de bord hebdomadaire", "Aisance rédactionnelle en français", "Maîtrise d'un outil de ticketing", "Capacité à dire non avec tact"] }],
  ["checklist", "a4", "clair", "CV & document", "Check-list d'intégration", { sur: "Premier jour", titre: "Ce qui doit\nêtre prêt", items: ["Poste de travail et écran installés", "Comptes créés et testés la veille", "Badge d'accès remis", "Déjeuner d'équipe réservé", "Tuteur identifié et prévenu", "Planning des deux premières semaines", "Point de fin de journée à 17 h"], meta: "Une intégration ratée coûte trois mois de productivité" }],
  ["tableau", "a4", "clair", "CV & document", "Compte rendu de réunion", { titre: "Compte rendu\ndu 12 avril", sous: "Présents : S. Bernard, M. Vidal, A. Roux, N. Tissot.", sur: "DÉCISION|RESPONSABLE ET DATE", items: ["Arrêt de l'activité Nord|S. Bernard — 31/12", "Recrutement de deux postes|A. Roux — 30/06", "Report de l'ouverture Lyon|M. Vidal — sept.", "Révision de la grille tarifaire|N. Tissot — 15/05", "Point d'avancement mensuel|Tous — chaque 1er", "Diffusion du compte rendu|S. Bernard — 13/04"], meta: "Prochaine réunion : mardi 12 mai, 9 h 30, salle du fond" }],
  ["entete", "a4", "clair", "CV & document", "Attestation sur l'honneur", { titre: "Sofia Bernard", sur: "Attestation sur l'honneur", sous: "12 rue du Marché\n33000 Bordeaux\n06 00 00 00 00", meta: "OBJET : ATTESTATION SUR L'HONNEUR", items: ["Je soussignée Sofia Bernard, née le ____ / ____ / ______ à ____________________,", "demeurant 12 rue du Marché, 33000 Bordeaux,", "atteste sur l'honneur que ____________________________________________.", "Fait pour servir et valoir ce que de droit."], cta: "Fait à Bordeaux, le ____ / ____ / ______ — Signature" }],

];
