// Modèles — troisième série sectorielle.
//
// Les activités qui manquaient encore : crèche, aide aux devoirs, musique,
// couture, brasserie, caviste, primeur, poissonnerie, boucherie, épicerie,
// ressourcerie, tiers-lieu, coworking, salle de spectacle, école de danse.
// Même principe : des chiffres plausibles, des mentions réelles, rien à
// inventer au moment de publier.

import type { Row } from "./design-templates";

export const ROWS_SECTEURS3: Row[] = [

  /* ══════════ Enfance & jeunesse — accueil du jeune enfant ══════════ */

  ["tableau", "a4", "pastel", "Enfance & jeunesse", "Tarifs de crèche", { titre: "Participation\nfamiliale", sous: "Calculée selon le barème national, quotient familial appliqué.", sur: "REVENU MENSUEL|TARIF HORAIRE", items: ["Moins de 1 200 €|0,42 €", "1 200 à 1 800 €|0,58 €", "1 800 à 2 500 €|0,76 €", "2 500 à 3 500 €|0,98 €", "Plus de 3 500 €|1,24 €", "Repas et couches|Inclus"], meta: "Attestation fiscale délivrée chaque janvier — aucun supplément facturé" }],
  ["horaires", "a4", "pastel", "Enfance & jeunesse", "Horaires de crèche", { sur: "Multi-accueil", titre: "Horaires", items: ["Lundi – vendredi|7 h 30 – 18 h 30", "Accueil du matin|Jusqu'à 9 h 15", "Repas|11 h 30", "Sieste|12 h 30 – 15 h", "Départs|À partir de 15 h 45"], meta: "FERMETURE TROIS SEMAINES EN AOÛT ET UNE À NOËL" }],
  ["checklist", "a5", "clair", "Enfance & jeunesse", "Trousseau de crèche", { sur: "Chaque jour", titre: "Dans le sac", items: ["Deux tenues de rechange complètes", "Le doudou et la tétine, si besoin", "Une paire de chaussons marqués", "Un chapeau ou un bonnet selon la saison", "Le carnet de santé, une fois par an", "Le traitement avec l'ordonnance"], meta: "Tout doit être marqué au nom de l'enfant, chaussons compris" }],
  ["etapes", "a4", "pastel", "Enfance & jeunesse", "Adaptation en crèche", { titre: "L'adaptation,\nen quatre temps", sous: "Deux semaines, au rythme de l'enfant.", items: ["Jour 1|Une heure, avec le parent présent.", "Jours 2-3|Deux heures, séparation courte.", "Jours 4-6|Une demi-journée, repas compris.", "Semaine 2|Journée complète, sieste comprise."] }],
  ["faq", "a4", "clair", "Enfance & jeunesse", "Questions des familles", { sur: "Vous demandez", titre: "Quatre réponses\naux parents", items: ["Que faire en cas de fièvre ?|Au-delà de 38,5 °C, nous appelons ; l'enfant reste jusqu'à votre arrivée.", "Les repas sont-ils fournis ?|Oui, préparés sur place, allergies prises en compte.", "Peut-on venir en cours de journée ?|Oui, sauf pendant la sieste.", "Comment inscrire ?|Dossier en mairie, commission trois fois par an."], meta: "Direction : 05 56 00 00 00, de 8 h à 17 h" }],
  ["calendrier", "a5", "vif", "Enfance & jeunesse", "Réunion de parents", { sur: "JEUDI 18 SEPTEMBRE", gros: "18", titre: "Réunion\nde parents", items: ["18 h 30, salle de motricité", "Présentation de l'équipe", "Projet pédagogique de l'année", "Garde des enfants assurée sur place"] }],

  /* ══════════ Éducation & association — cours et pratique ══════════ */

  ["tableau", "a4", "clair", "Éducation & association", "Tarifs de soutien scolaire", { titre: "Nos tarifs", sous: "Prix TTC, crédit d'impôt de 50 % applicable.", sur: "FORMULE|TARIF HORAIRE", items: ["Collège|30 €", "Lycée|34 €", "Supérieur|40 €", "Forfait 10 h collège|280 €", "En petit groupe (3 élèves)|18 €", "Après crédit d'impôt|dès 9 €"], meta: "Organisme agréé services à la personne — attestation fiscale annuelle" }],
  ["tableau", "a4", "chic", "Éducation & association", "Tarifs d'école de musique", { titre: "Tarifs\nannuels", sous: "Cotisation annuelle, paiement en trois fois possible.", sur: "FORMULE|TARIF ANNUEL", items: ["Éveil musical (4-6 ans)|240 €", "Instrument, 30 min/semaine|540 €", "Instrument, 45 min/semaine|780 €", "Formation musicale seule|180 €", "Pratique collective|Incluse", "Location d'instrument|120 € / an"], meta: "Quotient familial appliqué — dossier à retirer au secrétariat" }],
  ["horaires", "a4", "chic", "Éducation & association", "Planning de l'école de musique", { sur: "Cours collectifs", titre: "Planning", items: ["Lundi|Formation musicale, 17 h", "Mardi|Orchestre junior, 18 h", "Mercredi|Éveil musical, 10 h", "Jeudi|Chorale adultes, 20 h", "Vendredi|Atelier jazz, 19 h", "Samedi|Ensemble à cordes, 14 h"], meta: "COURS INDIVIDUELS : CRÉNEAUX ATTRIBUÉS EN SEPTEMBRE" }],
  ["evenement", "a3", "chic", "Éducation & association", "Audition de fin d'année", { sur: "Audition", titre: "Les élèves\njouent", meta: "SAMEDI 20 JUIN — 17 H", sous: "Salle des fêtes, place du Marché", cta: "Entrée libre — durée 1 h 30 — buvette au profit de l'école" }],
  ["tableau", "a4", "vif", "Éducation & association", "Tarifs d'école de danse", { titre: "Tarifs\nannuels", sous: "Cotisation annuelle, tenue non comprise.", sur: "COURS|TARIF ANNUEL", items: ["Éveil (4-6 ans), 45 min|280 €", "Initiation (7-9 ans), 1 h|340 €", "Classique ado, 1 h 30|420 €", "Contemporain adulte, 1 h 30|420 €", "Deuxième cours|-30 %", "Adhésion association|20 €"], meta: "Spectacle de fin d'année inclus — costumes prêtés" }],
  ["progression", "carre", "vif", "Éducation & association", "Places restantes en cours", { sur: "Inscriptions", titre: "Il reste\nquatre places", gros: "80", sous: "Sur vingt, pour le cours de contemporain adulte du mardi soir.", meta: "INSCRIPTION AU SECRÉTARIAT" }],

  /* ══════════ Commerce & promotion — métiers de bouche ══════════ */

  ["menu", "menuc", "sombre", "Commerce & promotion", "Carte de caviste", { sur: "Sélection", titre: "Nos vins du moment", items: ["Bordeaux blanc sec, 2023|9,50", "Graves rouge, 2021|14,00", "Saint-Émilion grand cru, 2019|28,00", "Crémant brut, méthode traditionnelle|12,50", "Cahors, vieilles vignes 2020|11,00", "Jurançon moelleux, 2022|16,00"], meta: "Dégustation gratuite tous les samedis de 11 h à 13 h — conseil sans jargon" }],
  ["fiche", "a4", "sombre", "Commerce & promotion", "Fiche de vin", { titre: "Saint-Émilion\ngrand cru 2019", meta: "Merlot 80 %, cabernet franc 20 % — 14,5 % vol — 28 €", sur: "CE QU'IL FAUT SAVOIR", sous: "AVEC QUOI", items: ["Élevé quatorze mois en fût", "À boire de 2026 à 2034", "Carafer une heure avant", "Viandes rouges grillées", "Fromages affinés", "Champignons et gibier"] }],
  ["menu", "menuc", "nature", "Commerce & promotion", "Étal de primeur", { sur: "Aujourd'hui", titre: "Nos fruits et légumes", items: ["Tomates anciennes, le kilo|4,80", "Courgettes, le kilo|2,90", "Fraises de Dordogne, la barquette|4,50", "Pommes de terre nouvelles, le kilo|2,40", "Salade, la pièce|1,20", "Abricots du Roussillon, le kilo|5,20"], meta: "Origine affichée sur chaque cageot — arrivage du mardi et du vendredi" }],
  ["menu", "menuc", "froid", "Commerce & promotion", "Étal de poissonnerie", { sur: "Arrivage du jour", titre: "La criée", items: ["Bar de ligne, le kilo|28,00", "Maquereau, la pièce|3,50", "Moules de bouchot, le kilo|5,90", "Huîtres n° 3, la douzaine|9,50", "Filet de cabillaud, le kilo|24,00", "Sardines, le kilo|9,00"], meta: "Pêche française — zone et date de pêche affichées — préparation offerte" }],
  ["menu", "menuc", "chaud", "Commerce & promotion", "Étal de boucherie", { sur: "Nos viandes", titre: "À la découpe", items: ["Entrecôte de bœuf, le kilo|32,00", "Rôti de veau, le kilo|24,00", "Épaule d'agneau, le kilo|19,50", "Poulet fermier, la pièce|14,00", "Saucisses maison, le kilo|13,50", "Pot-au-feu, le kilo|12,00"], meta: "Viandes françaises — élevages à moins de 120 km — commandes la veille" }],
  ["avantages", "large", "nature", "Commerce & promotion", "Engagements d'épicerie", { titre: "Trois règles\nde l'épicerie", sous: "Affichées à l'entrée depuis l'ouverture.", items: ["Origine affichée|Sur chaque produit, sans exception.", "Vrac en priorité|Deux tiers du rayon, contenants acceptés.", "Prix au kilo|Toujours indiqué, y compris sur le vrac."], meta: "Liste complète des producteurs disponible en caisse" }],
  ["etiquette", "etiq", "nature", "Commerce & promotion", "Étiquette de vrac", { sur: "VRAC", gros: "4,80 €", titre: "Lentilles vertes\ndu Puy, le kilo", sous: "Récolte 2025, Haute-Loire, agriculture biologique.", meta: "APPORTEZ VOS CONTENANTS, ILS SONT PESÉS À VIDE" }],
  ["horaires", "a5", "nature", "Commerce & promotion", "Horaires de marché", { sur: "Nos marchés", titre: "Où nous\ntrouver", items: ["Mardi|Marché des Capucins, 7 h – 13 h", "Jeudi|Place du Marché, 8 h – 13 h", "Samedi|Marché du Port, 7 h – 14 h", "Dimanche|Marché de Talence, 8 h – 13 h", "Boutique|Mercredi et vendredi, 15 h – 19 h"], meta: "COMMANDES POSSIBLES LA VEILLE AU 06 00 00 00 00" }],

  /* ══════════ Commerce & promotion — réemploi et artisanat ══════════ */

  ["tableau", "a4", "terre", "Commerce & promotion", "Tarifs de ressourcerie", { titre: "Nos tarifs", sous: "Prix libres au-delà, tout est réemployé sur place.", sur: "CATÉGORIE|PRIX INDICATIF", items: ["Livre de poche|1 €", "Vaisselle, la pièce|0,50 €", "Vêtement adulte|3 €", "Petit électroménager testé|dès 10 €", "Meuble|dès 20 €", "Vélo révisé|dès 60 €"], meta: "Dépôts acceptés du mardi au samedi, 10 h à 17 h — rien n'est jeté sans essai de réparation" }],
  ["etapes", "a4", "nature", "Commerce & promotion", "Déposer un objet", { titre: "Déposer\nun objet", sous: "Quatre étapes, aucune contrainte.", items: ["Vérifier|Propre, complet, et en état de marche si possible.", "Apporter|Du mardi au samedi, 10 h à 17 h.", "Trier|Nous évaluons ce qui peut être réemployé.", "Réparer|L'atelier remet en état ce qui peut l'être."] }],
  ["tableau", "a4", "clair", "Commerce & promotion", "Tarifs de retouche couture", { titre: "Retouches", sous: "Prix TTC, délai de trois à cinq jours.", sur: "PRESTATION|TARIF", items: ["Ourlet simple, pantalon|12 €", "Ourlet à revers|18 €", "Fermeture éclair, pantalon|22 €", "Fermeture éclair, blouson|38 €", "Reprise de taille|25 €", "Doublure complète|Sur devis"], meta: "Essayage sur place conseillé — express 24 h : + 50 %" }],
  ["evenement", "a3", "pastel", "Commerce & promotion", "Atelier couture", { sur: "Atelier", titre: "Réparer\nplutôt que\njeter", meta: "TOUS LES SAMEDIS — 14 H À 17 H", sous: "Maison de quartier, salle du fond", cta: "Machines et fil fournis — participation libre — sans inscription" }],

  /* ══════════ Tech & startup — lieux partagés ══════════ */

  ["tableau", "a4", "tech", "Tech & startup", "Tarifs de coworking", { titre: "Nos formules", sous: "Prix HT, sans engagement, résiliation à quinze jours.", sur: "FORMULE|TARIF MENSUEL", items: ["Journée à l'unité|22 €", "Cinq jours par mois|95 €", "Illimité, poste partagé|180 €", "Poste attribué|260 €", "Bureau fermé, 2 postes|540 €", "Salle de réunion, l'heure|18 €"], meta: "Café, wifi fibre et impression compris — accès 7 h à 21 h en semaine" }],
  ["horaires", "a5", "tech", "Tech & startup", "Horaires de l'espace", { sur: "Espace de travail", titre: "Accès", items: ["Lundi – vendredi|7 h – 21 h", "Samedi|9 h – 18 h", "Dimanche|Fermé", "Badge 24 h/24|Formules illimitées", "Salles de réunion|Réservation en ligne"], meta: "FERMETURE ANNUELLE : UNE SEMAINE À NOËL" }],
  ["avantages", "large", "tech", "Tech & startup", "Ce que comprend l'abonnement", { titre: "Trois choses\ncomprises", sous: "Sans supplément, quelle que soit la formule.", items: ["Le café|Illimité, et il est correct.", "Le réseau|Fibre dédiée, 1 Gb/s symétrique.", "Les salles|Deux heures par mois incluses."], meta: "Visite libre du mardi au jeudi, sans rendez-vous" }],
  ["evenement", "carre", "tech", "Tech & startup", "Rencontre professionnelle", { sur: "Rencontre", titre: "Petit-déjeuner\ndes indépendants", meta: "PREMIER JEUDI DU MOIS — 8 H 30", sous: "Espace du Port, 8 quai Vauban", cta: "Gratuit, ouvert à tous, café et viennoiseries offerts" }],
  ["equipe", "a4", "clair", "Tech & startup", "Les résidents", { titre: "Ceux qui\ntravaillent ici", sous: "Douze indépendants, six métiers.", items: ["Sofia|Comptabilité", "Marc|Développement", "Aline|Traduction", "Noé|Design"] }],

  /* ══════════ Culture & spectacle — lieux ══════════ */

  ["tableau", "a4", "sombre", "Culture & spectacle", "Tarifs de location de salle", { titre: "Location\nde la salle", sous: "Prix TTC, caution de 500 € demandée.", sur: "FORMULE|TARIF", items: ["Demi-journée, associations|80 €", "Journée, associations|140 €", "Demi-journée, particuliers|180 €", "Journée, particuliers|320 €", "Week-end complet|560 €", "Sonorisation|+ 90 €"], meta: "État des lieux à l'entrée et à la sortie — ménage à la charge du locataire" }],
  ["cadre", "a4", "clair", "Culture & spectacle", "Règlement de la salle", { sur: "Règlement", titre: "Quatre règles\nde la salle", sous: "Capacité de 120 personnes assises. Musique coupée à 1 h. Aucune modification de l'installation électrique. Salle rendue balayée, chaises rangées, poubelles sorties.", meta: "TOUT MANQUEMENT EST RETENU SUR LA CAUTION" }],
  ["checklist", "a4", "clair", "Culture & spectacle", "État des lieux de sortie", { sur: "Avant de rendre les clés", titre: "Les sept\nvérifications", items: ["Sol balayé et lavé", "Chaises et tables rangées", "Poubelles sorties dans le local", "Réfrigérateur vidé et éteint", "Fenêtres et volets fermés", "Chauffage remis sur position hors gel", "Lumières éteintes, alarme armée"], meta: "L'état des lieux se fait avec le gardien, sur rendez-vous" }],
  ["horaires", "a4", "sombre", "Culture & spectacle", "Horaires de billetterie", { sur: "Billetterie", titre: "Horaires", items: ["Mardi – vendredi|13 h – 18 h", "Samedi|10 h – 13 h", "Soirs de spectacle|Dès 19 h", "En ligne|24 h/24", "Téléphone|05 56 00 00 00"], meta: "PLACEMENT LIBRE — OUVERTURE DES PORTES 30 MIN AVANT" }],

  /* ══════════ Restauration & café — brasserie artisanale ══════════ */

  ["menu", "menuc", "chaud", "Restauration & café", "Carte de brasserie artisanale", { sur: "Nos bières", titre: "Brassées ici", items: ["Blonde de soif, 4,5 %|Pinte 6,50", "IPA houblonnée, 6,2 %|Pinte 7,50", "Ambrée de saison, 5,8 %|Pinte 7,00", "Stout café, 6,8 %|Pinte 7,50", "Blanche à la coriandre, 4,8 %|Pinte 6,50", "Planche de dégustation, 5 × 15 cl|12,00"], meta: "Brassées sur place — visite de la brasserie le samedi à 15 h" }],
  ["fiche", "a4", "chaud", "Restauration & café", "Fiche de bière", { titre: "IPA houblonnée,\n6,2 %", meta: "Amertume 55 IBU — malts pale ale et cara — houblons Citra et Mosaic", sur: "CE QU'ON Y TROUVE", sous: "AVEC QUOI", items: ["Nez d'agrumes et de fruits tropicaux", "Amertume franche, finale sèche", "Robe dorée trouble, mousse tenue", "Fromages relevés", "Plats épicés", "Burgers et grillades"] }],
  ["evenement", "a3", "chaud", "Restauration & café", "Visite de brasserie", { sur: "Visite", titre: "Comment\non brasse", meta: "TOUS LES SAMEDIS — 15 H", sous: "Brasserie du Port, 4 rue des Forges", cta: "1 h 30, dégustation comprise — 12 € — réservation conseillée" }],
  ["etapes", "a4", "chaud", "Restauration & café", "Étapes du brassage", { titre: "Du grain\nà la pinte", sous: "Quatre étapes, trois semaines minimum.", items: ["Le brassage|Concassage, empâtage, filtration.", "L'ébullition|Une heure, houblonnage en trois fois.", "La fermentation|Sept jours à 20 °C.", "La garde|Deux semaines à froid, minimum."] }],

];
