// Modèles — dernière série : présentations sectorielles et supports mixtes.
//
// Un jeu de diapositives par métier, quelques documents qui manquaient, et les
// compositions restées sous-employées ailleurs. L'objectif de cette série est
// autant de combler des trous du catalogue que d'ajouter du volume : chaque
// ligne comble une case vide du tableau mise en page × format × secteur.

import type { Row } from "./design-templates";

export const ROWS_FINAL: Row[] = [

  /* ══════════ Présentations sectorielles ══════════ */

  ["couverture", "slide", "terre", "Présentation", "Ouverture — artisanat", { sur: "Présentation d'entreprise", titre: "Menuiserie\nBerthier", sous: "Vingt ans de chantiers, quatre personnes, un atelier à Bordeaux.", auteur: "Dossier de présentation — 2026" }],
  ["cartes", "slide", "terre", "Présentation", "Nos métiers — artisanat", { titre: "Ce que\nnous faisons", sous: "Trois activités, un seul atelier.", items: ["Menuiserie|Escaliers, portes, fenêtres bois.", "Agencement|Cuisines, dressings, bibliothèques.", "Restauration|Bâti ancien, à l'identique."] }],
  ["stats", "slide", "terre", "Présentation", "Chiffres — artisanat", { sur: "Bilan 2025", titre: "Une année\nd'atelier", items: ["68|chantiers livrés", "97 %|dans les délais", "0|litige"], meta: "Références et coordonnées de clients communiquées sur demande" }],
  ["grille", "slide", "terre", "Présentation", "Réalisations — artisanat", { titre: "Six chantiers\nrécents", sous: "Photos haute définition disponibles sur demande", items: ["Escalier chêne", "Cuisine sur mesure", "Bibliothèque", "Parquet massif", "Volets bois", "Verrière atelier"], meta: "Chaque chantier est photographié avant, pendant et après" }],
  ["couverture", "slide", "nature", "Présentation", "Ouverture — agriculture", { sur: "Présentation", titre: "Ferme\nde la Combe", sous: "Apiculture, maraîchage et vente directe depuis 1998.", auteur: "Saint-Émilion — dossier 2026" }],
  ["etapes", "slide", "nature", "Présentation", "Circuit court — agriculture", { titre: "Du champ\nà l'assiette", sous: "Quatre étapes, aucun intermédiaire.", items: ["Culture|Sans traitement de synthèse, depuis 2011.", "Récolte|À la main, le matin même.", "Conditionnement|Sur place, en contenants consignés.", "Vente|À la ferme et sur quatre marchés."] }],
  ["couverture", "slide", "pastel", "Présentation", "Ouverture — association", { sur: "Assemblée générale", titre: "Rapport\nmoral 2026", sous: "Activité, adhérents, comptes et projets pour l'année à venir.", auteur: "Association du quartier — 20 juin 2026" }],
  ["stats", "slide", "pastel", "Présentation", "Chiffres — association", { sur: "Année 2025-2026", titre: "L'année\nen trois chiffres", items: ["186|adhérents", "12|ateliers", "38|bénévoles"], meta: "Rapport complet remis à chaque adhérent" }],
  ["tableau", "slide", "pastel", "Présentation", "Comptes — association", { titre: "Comptes\nde l'exercice", sous: "Du 1er septembre 2025 au 31 août 2026.", sur: "POSTE|MONTANT", items: ["Cotisations|4 650 €", "Subventions|3 200 €", "Buvette et événements|2 140 €", "Charges de fonctionnement|-5 380 €", "Investissements|-2 900 €", "Résultat|+ 1 710 €"], meta: "Comptes vérifiés par le vérificateur aux comptes — quitus demandé au vote" }],
  ["couverture", "slide", "froid", "Présentation", "Ouverture — santé", { sur: "Maison de santé", titre: "Projet\nde santé\n2027", sous: "Organisation, patientèle, et deux recrutements à décider.", auteur: "Réunion de coordination — 12 mai 2026" }],
  ["cartes", "slide", "froid", "Présentation", "Trois axes — santé", { titre: "Trois axes\npour 2027", sous: "Décidés collectivement en janvier.", items: ["Accès aux soins|Deux créneaux d'urgence par jour.", "Prévention|Un atelier collectif par mois.", "Coordination|Un dossier partagé, une réunion mensuelle."] }],
  ["couverture", "slide", "chic", "Présentation", "Ouverture — culture", { sur: "Saison 2026-2027", titre: "Présentation\nde saison", sous: "Douze spectacles, six créations, un budget en équilibre.", auteur: "Théâtre municipal — 3 juin 2026" }],
  ["sommaire", "slide", "chic", "Présentation", "Programme — culture", { sur: "Saison", titre: "Les douze\nrendez-vous", items: ["Quatuor à cordes|10 oct.", "Les Justes|14 nov.", "Corps communs|12 déc.", "Trio Aubépine|16 janv.", "Création jeune public|13 févr.", "Bal de clôture|20 mars"], meta: "Six autres dates communiquées en septembre" }],
  ["couverture", "slide", "vif", "Présentation", "Ouverture — club sportif", { sur: "Assemblée générale", titre: "Saison\n2025-2026", sous: "Résultats sportifs, effectifs, comptes et projets.", auteur: "AS Rivière — 20 juin 2026" }],
  ["stats", "slide", "vif", "Présentation", "Chiffres — club sportif", { sur: "Saison écoulée", titre: "La saison\nen trois chiffres", items: ["186|licenciés", "24|victoires", "3|montées"], meta: "Détail par catégorie en annexe" }],
  ["couverture", "slide", "clair", "Présentation", "Ouverture — commerce", { sur: "Bilan annuel", titre: "L'année\nde la boutique", sous: "Chiffre d'affaires, paniers, saisonnalité et deux décisions.", auteur: "Aubépine — 15 janvier 2027" }],
  ["chrono", "slide", "clair", "Présentation", "Saisonnalité — commerce", { titre: "L'année\nen quatre temps", sous: "La saisonnalité explique presque tout.", items: ["T1|Soldes, trésorerie tendue.", "T2|Reprise, collection été.", "T3|Creux d'août, puis rentrée.", "T4|Novembre-décembre, 38 % de l'année."], meta: "Cette concentration justifie le stock de novembre" }],
  ["comparatif", "slide", "clair", "Présentation", "Boutique ou en ligne", { titre: "Boutique\nou en ligne", sur: "BOUTIQUE", cta: "EN LIGNE", items: ["1 940 k€|2 890 k€", "Panier moyen 62 €|Panier moyen 48 €", "Marge 44 %|Marge 36 %", "Charges fixes lourdes|Charges variables", "Fidélité forte|Fidélité faible"], meta: "Les deux canaux sont complémentaires, pas concurrents" }],

  /* ══════════ Documents complémentaires ══════════ */

  ["tableau", "a4", "clair", "CV & document", "Feuille d'émargement", { titre: "Feuille\nd'émargement", sous: "Formation « Sécurité au travail » — 12 et 13 octobre 2026.", sur: "PARTICIPANT|SIGNATURE", items: ["Sofia Bernard|", "Marc Vidal|", "Aline Roux|", "Noé Tissot|", "Camille Durand|", "Formateur|"], meta: "Une signature par demi-journée — document conservé cinq ans" }],
  ["tableau", "a4", "clair", "CV & document", "Registre de sortie", { titre: "Registre\ndes sorties", sous: "À remplir à chaque sortie de matériel.", sur: "MATÉRIEL|SORTI PAR / LE", items: ["Perceuse|", "Échafaudage|", "Niveau laser|", "Remorque|", "Groupe électrogène|", "Aspirateur de chantier|"], meta: "Tout matériel non rendu sous 48 h est signalé au responsable" }],
  ["tableau", "a4", "clair", "CV & document", "Grille d'entretien annuel", { titre: "Entretien\nprofessionnel", sous: "À remplir conjointement, une copie pour chaque partie.", sur: "THÈME|APPRÉCIATION", items: ["Missions de l'année|", "Ce qui a bien fonctionné|", "Ce qui a manqué|", "Besoins de formation|", "Souhaits d'évolution|", "Objectifs de l'année|"], meta: "Entretien obligatoire tous les deux ans — article L.6315-1 du code du travail" }],
  ["cadre", "a4", "clair", "CV & document", "Convocation à un entretien", { sur: "Convocation", titre: "Entretien\nprofessionnel", sous: "Vous êtes convié·e à votre entretien professionnel le ____ / ____ / ______ à ______ h, en salle de réunion. Vous pouvez vous faire assister par une personne de l'entreprise.", meta: "REMISE EN MAIN PROPRE CONTRE DÉCHARGE" }],
  ["colonnes", "a4", "chic", "CV & document", "Lettre de mission", { sur: "Lettre de mission", titre: "Diagnostic\norganisationnel", sous: "Objet, périmètre, livrables et conditions.", items: ["La mission porte sur l'organisation du service client, de la réception d'une demande à sa clôture. Elle comprend six entretiens individuels, une observation de deux journées et l'analyse des douze derniers mois de tickets.", "Le livrable est un rapport écrit d'une trentaine de pages, remis six semaines après le démarrage, suivi d'une réunion de restitution d'une heure trente. Les honoraires sont forfaitaires et ne varient pas selon la durée réelle."], meta: "HONORAIRES : 6 400 € HT — ACOMPTE DE 30 % À LA SIGNATURE" }],
  ["colonnes", "a4", "clair", "CV & document", "Procédure écrite", { sur: "Procédure", titre: "Traiter\nune réclamation", sous: "Applicable à toute réclamation écrite ou orale.", items: ["Toute réclamation est enregistrée le jour de sa réception, quel que soit le canal. Un accusé part sous quatre heures ouvrées, même si aucune réponse de fond n'est encore possible. Le client sait ainsi que sa demande existe.", "La réponse de fond intervient sous cinq jours ouvrés. Si elle n'est pas possible, un point d'étape est envoyé à J+5, puis tous les cinq jours. Aucune réclamation ne reste sans nouvelle plus d'une semaine, jamais."], meta: "PROCÉDURE N° 04 — VERSION DU 12 AVRIL 2026" }],
  ["checklist", "a4", "clair", "CV & document", "Check-list de clôture mensuelle", { sur: "Fin de mois", titre: "Les sept\nvérifications", items: ["Rapprochement bancaire terminé", "Factures fournisseurs saisies", "Factures clients émises", "Notes de frais validées", "Stocks comptés et ajustés", "Tableau de bord mis à jour", "Point de trésorerie envoyé"], meta: "À boucler avant le 5 du mois suivant, sans exception" }],
  ["frise", "a4", "chic", "CV & document", "Historique de dossier", { titre: "Historique\ndu dossier", sous: "Dossier n° 2026-0184.", items: ["12 janv.|Ouverture du dossier.", "3 févr.|Pièces complémentaires reçues.", "18 mars|Première réponse adverse.", "12 avril|Mémoire en réplique.", "En attente|Audience non fixée."], meta: "Historique mis à jour à chaque acte de procédure" }],

  /* ══════════ Réseaux — formats large et LinkedIn ══════════ */

  ["souligne", "large", "clair", "LinkedIn", "Trois mots professionnels", { sur: "Ma façon de travailler", titre: "Écrit.\nDaté.\nTenu.", sous: "Trois règles qui évitent la moitié des malentendus en mission.", meta: "aubepine.fr" }],
  ["empilement", "large", "froid", "LinkedIn", "Cinq enseignements", { titre: "Cinq choses\napprises\nen cinq ans", sous: "Aucune n'était évidente au départ.", items: ["Recruter lentement coûte moins cher", "Un process écrit bat un talent isolé", "Le premier départ dit ce qui ne va pas", "Payer correctement évite dix problèmes", "Dire non protège mieux qu'un discours"], meta: "Détail de chaque point en commentaire" }],
  ["bulle", "large", "pastel", "LinkedIn", "Retour d'une recrue", { sur: "Reçu ce matin", titre: "« On m'avait annoncé 34 k€. J'ai signé à 34 k€. Ça paraît normal, ça ne l'est pas. »", auteur: "Noé Tissot", sous: "Chargé de clientèle, arrivé en 2025" }],
  ["chapitre", "large", "tech", "LinkedIn", "Ouverture d'analyse", { gros: "01", sur: "Analyse", titre: "Le coût\nréel d'un\nrecrutement raté", sous: "Recrutement, intégration, perte de compétence et effet sur l'équipe : nous avons tout chiffré.", meta: "ÉTUDE INTERNE — AVRIL 2026" }],
  ["frise", "large", "chic", "LinkedIn", "Parcours d'entreprise", { titre: "De deux\nà quarante", sous: "Cinq ans, sans levée de fonds.", items: ["2021|Deux associés, un client.", "2022|Premier salarié.", "2023|Cap de rentabilité.", "2025|Ouverture à Lyon.", "2026|Quarante personnes."], meta: "Modèle économique détaillé en commentaire" }],
  ["avantages", "large", "clair", "LinkedIn", "Trois pratiques internes", { titre: "Trois choses\nqu'on fait\nautrement", sous: "Et qu'on ne compte pas changer.", items: ["Salaires publics|Grille complète, révisée chaque janvier.", "Pas d'entretien annuel|Un point de trente minutes tous les deux mois.", "Réunions à trente minutes|Au-delà, c'est qu'elle n'a pas tranché."], meta: "Aucune de ces pratiques n'a coûté un euro" }],
  ["notation", "large", "clair", "LinkedIn", "Retour de mission", { gros: "9,4", sur: "sur 10 — 28 missions évaluées", titre: "Cadrage clair dès la première réunion, budget respecté au centime, et une vraie passation à la fin.", auteur: "Direction générale, groupe régional", meta: "Enquête de satisfaction 2026" }],
  ["carrousel", "large", "tech", "LinkedIn", "Volet de guide", { meta: "1/8", sur: "Guide pratique", titre: "Réduire\nses délais\nsans presser\npersonne", sous: "Huit leviers testés sur des équipes de cinq à cinquante personnes, avec les chiffres avant et après.", cta: "Faites défiler →" }],
  ["duo", "large", "vif", "LinkedIn", "Deux chiffres de bilan", { gros: "2026", items: ["+18 %|de chiffre d'affaires", "0|départ subi"] }],
  ["question", "large", "sombre", "LinkedIn", "Question ouverte au réseau", { sur: "Question ouverte", titre: "Publiez-vous\nvos salaires\ndans vos offres ?", sous: "Nous le faisons depuis un an. Les candidatures ont doublé, la qualité n'a pas bougé." }],
  ["tableau", "large", "clair", "LinkedIn", "Grille de salaires publiée", { titre: "Nos salaires\nsont publics", sous: "Même grille pour tout le monde, révisée chaque janvier.", sur: "NIVEAU|BRUT ANNUEL", items: ["Junior|32 000 €", "Confirmé|41 000 €", "Senior|52 000 €", "Lead|63 000 €", "Direction|78 000 €", "Écart max|2,4"], meta: "Aucune négociation individuelle, aucune prime discrétionnaire" }],
  ["colonnes", "large", "clair", "LinkedIn", "Prise de position", { sur: "Prise de position", titre: "Pourquoi\nnous ne\nferons pas\nde soldes", sous: "Décision prise en 2021, jamais remise en cause depuis.", items: ["Solder suppose d'avoir vendu trop cher pendant onze mois, ou d'avoir mal prévu ses volumes. Dans les deux cas, c'est le client qui paie l'erreur — d'abord au prix fort, puis en achetant un invendu.", "Nous préférons un prix juste toute l'année, quitte à vendre moins en janvier. Cinq ans plus tard, notre taux de retour client est passé de 38 % à 61 %, et nous n'avons jamais eu de stock à liquider."], meta: "AUBÉPINE — 12 JANVIER 2026" }],
  ["magazine", "large", "chic", "LinkedIn", "Couverture d'étude", { sur: "ÉTUDE", meta: "AVRIL 2026 — 42 PAGES", titre: "Le coût\ndu turnover", sous: "Ce que coûte réellement un départ, poste par poste, sur trois ans.", items: ["La méthode de calcul", "Les postes les plus coûteux", "Ce qui réduit vraiment le turnover"] }],

  /* ══════════ Compléments visuels ══════════ */

  ["retro", "carre", "terre", "Instagram", "Archive d'atelier", { sur: "1984", titre: "Le même\nétabli", sous: "Il a changé trois fois d'atelier, jamais de propriétaire." }],
  ["retro", "large", "chaud", "Facebook", "Archive de commerce", { sur: "Il y a trente ans", titre: "La même\nvitrine", sous: "Trois générations, et la peinture d'origine sous la nouvelle." }],
  ["neon", "carre", "vif", "Commerce & promotion", "Annonce nocturne", { gros: "24H", titre: "Commandez à toute heure", sous: "La boutique en ligne ne ferme jamais. L'atelier, si." }],
  ["organique", "carre", "pastel", "Santé & cabinet", "Invitation au repos", { sur: "Rappel", titre: "Dormir\nn'est pas\nune perte\nde temps", sous: "Sept heures par nuit font plus pour votre santé que la plupart des compléments vendus.", cta: "Parlons-en en consultation" }],
  ["mosaique", "large", "pastel", "Web & e-mail", "Page de confirmation", { titre: "C'est\nnoté", sous: "Un e-mail de confirmation vient de partir. Vérifiez vos indésirables si rien n'arrive." }],
  ["mosaique", "carre", "chaud", "Commerce & promotion", "Merci de fin d'année", { titre: "Merci\npour 2026", sous: "Quatre mille commandes, et pas une seule perdue en route." }],
  ["centre", "large", "chic", "Web & e-mail", "Message d'absence", { sur: "Absence", titre: "Nous sommes\nfermés\njusqu'au 2 janvier", sous: "Les messages seront lus au retour. Bonnes fêtes à tous." }],
  ["centre", "a5", "sombre", "Impression & affiche", "Affichette de deuil", { sur: "En mémoire", titre: "Jean Berthier\n1948 — 2026", sous: "L'atelier reste fermé trois jours. Merci de votre compréhension." }],
  ["panneau", "large", "chic", "Marque & logo", "Présentation de marque", { gros: "01", sur: "Notre histoire", titre: "Un atelier,\ndeux personnes,\nzéro emprunt", sous: "Nous avons ouvert petit et attendu d'avoir des clients avant d'avoir un local. Ça a coûté deux ans de lenteur, et ça nous a sauvés.", meta: "Atelier Berthier — Bordeaux, depuis 2019" }],
  ["panneau", "li", "tech", "LinkedIn", "Présentation d'activité", { gros: "→", sur: "Ce que je fais", titre: "Remettre\ndes opérations\nd'aplomb", sous: "Diagnostic, chantier, passation. Trois mois en moyenne, un prix ferme, une seule interlocutrice.", meta: "Sofia Bernard — Bordeaux et Paris" }],
  ["diapo", "large", "clair", "Web & e-mail", "Bloc e-mail à puces", { sur: "Ce mois-ci", titre: "Trois choses\nà savoir", items: ["Les délais passent à 48 h, volontairement", "Les frais de port sont offerts dès 60 €", "L'atelier est visitable le premier samedi du mois"], sous: "Aucun prix n'augmente à cette occasion.", meta: "Se désabonner en un clic, en bas de cet e-mail" }],
  ["annonce", "large", "vif", "Web & e-mail", "Bloc e-mail nouveauté", { emoji: "🧴", gros: "NEW", titre: "Le savon\nsolide\narrive", sous: "Sans emballage plastique, saponifié à froid, fabriqué à quarante kilomètres.", items: ["Zéro plastique", "Fait ici", "3 mois d'usage"] }],
  ["bloc", "large", "sombre", "Web & e-mail", "Bloc e-mail manifeste", { titre: "ACHETEZ\nMOINS.\nGARDEZ\nPLUS.", sous: "Nous préférons vendre une pièce qui dure dix ans que dix qui durent un an.", meta: "ATELIER BERTHIER — BORDEAUX" }],
  ["coins", "large", "chic", "Photo & création", "Bloc portfolio", { sur: "Portfolio", titre: "Lumière\nnaturelle,\nsans retouche", sous: "Douze images tournées en une matinée, au 50 mm, sans flash.", meta: "PRISES DE VUE SUR DEVIS — STUDIOVERRIER.FR" }],
  ["damier", "large", "vif", "Commerce & promotion", "Bloc promotionnel graphique", { sur: "Trois jours", titre: "-40%\nPARTOUT", sous: "Sur tout le site, sans code à saisir, jusqu'à dimanche minuit.", meta: "AUCUNE PROLONGATION" }],
  ["rayures", "large", "chaud", "Événement", "Bloc événement", { sur: "Ce week-end", titre: "GRANDE\nBRADERIE", sous: "Cent vingt exposants, buvette, restauration sur place, entrée libre.", meta: "SAMEDI ET DIMANCHE — 8 H À 18 H" }],
  ["vagues", "large", "froid", "Voyage & saison", "Bloc saisonnier", { sur: "Enfin", titre: "La saison\nrouvre samedi", sous: "Base nautique ouverte tous les jours jusqu'au 30 septembre.", meta: "LOCATION DE PADDLE ET DE KAYAK SUR PLACE" }],
  ["montagne", "large", "nature", "Voyage & saison", "Bloc montagne", { sur: "Itinéraire", titre: "Le tour\ndes lacs\nen trois jours", sous: "38 kilomètres, 1 900 m de dénivelé, deux refuges gardés.", meta: "TRACE GPX EN DESCRIPTION" }],
  ["soleil", "large", "chaud", "Commerce & promotion", "Bloc estival", { sur: "Ventes d'été", titre: "Jusqu'à\n-40 %", sous: "Sur la collection printemps-été, jusqu'à épuisement des stocks.", meta: "DU 26 JUIN AU 23 JUILLET" }],
  ["pois", "large", "pastel", "Événement", "Bloc festif", { sur: "Trois ans", titre: "On fête\nça samedi", sous: "Portes ouvertes, café offert, tirage au sort d'un panier garni.", meta: "SAMEDI 14 JUIN — 10 H À 19 H" }],
  ["arche", "large", "chic", "Marque & logo", "Bloc identité", { sur: "Maison", titre: "Berthier", sous: "Parfums composés à Grasse, embouteillés à la main depuis 1974.", meta: "PARIS — GRASSE" }],
  ["ecusson", "large", "sombre", "Sport & bien-être", "Bloc club", { gros: "ASR", meta: "EST. 1962", titre: "AS Rivière", sous: "Ne rien lâcher" }],
  ["sceau", "large", "terre", "Agriculture & terroir", "Bloc label", { sur: "VENTE DIRECTE", gros: "1998", meta: "SAINT-ÉMILION", titre: "Ferme de la Combe", sous: "Aucun intermédiaire, depuis le premier jour." }],
  ["monogramme", "large", "chic", "Marque & logo", "Bloc monogramme", { gros: "AB", titre: "Atelier Berthier", sous: "MENUISERIE D'ART — BORDEAUX" }],
  ["contour", "large", "vif", "Commerce & promotion", "Bloc titre creux", { sur: "Nouvelle collection", gros: "ÉTÉ", titre: "Dix pièces, deux couleurs, aucune rupture prévue", sous: "En ligne le 1er mai, en boutique le lendemain.", meta: "SÉRIE LIMITÉE À 200 PIÈCES" }],
  ["ombredure", "large", "vif", "Commerce & promotion", "Bloc slogan", { sur: "Rappel", titre: "DERNIER\nJOUR", sous: "Les précommandes ferment ce soir à minuit.", meta: "APRÈS, C'EST TROP TARD" }],
  ["typo", "large", "sombre", "Marque & logo", "Bloc typographique", { titre: "ON N'A PAS\nDE PLAN B", sous: "Alors le plan A, on le soigne.", meta: "Atelier Berthier" }],
  ["bandeau", "large", "froid", "Web & e-mail", "En-tête de lettre mensuelle", { sur: "Lettre n° 43", titre: "Ce mois-ci :\ntrois nouveautés", sous: "Une fonction attendue, un changement d'horaires, et une histoire de client.", cta: "Lire la lettre" }],
  ["banniere", "large", "vif", "Web & e-mail", "Bandeau d'appel à l'action", { gros: "→", titre: "Un projet ? Parlons-en trente minutes", sous: "Premier échange gratuit, sans engagement, en visio ou sur place.", cta: "Prendre rendez-vous" }],

];
