// Modèles — bâtiment second œuvre, extérieurs, professions du chiffre.
//
// Suite des métiers : électricien, plombier, peintre, serrurier, paysagiste,
// pisciniste, imprimeur, comptable, notaire, architecte, traducteur. Le point
// commun, c'est le devis : ces professions vivent d'un document écrit, et
// leurs supports doivent d'abord dire un prix, un délai et une garantie.

import type { Row } from "./design-templates";

export const ROWS_METIERS2: Row[] = [

  /* ══════════ Artisanat & bâtiment — second œuvre ══════════ */

  ["tableau", "a4", "clair", "Artisanat & bâtiment", "Tarifs d'électricien", { titre: "Tarifs\nindicatifs", sous: "Prix TTC, TVA 10 % en rénovation de plus de deux ans.", sur: "PRESTATION|À PARTIR DE", items: ["Déplacement et devis|Gratuit", "Remplacement de prise|65 €", "Point lumineux supplémentaire|140 €", "Tableau électrique complet|1 400 €", "Mise aux normes T3|3 200 €", "Borne de recharge 7 kW|1 250 €"], meta: "Attestation Consuel fournie — assurance décennale à jour" }],
  ["tableau", "a4", "froid", "Artisanat & bâtiment", "Tarifs de plomberie", { titre: "Tarifs\nde plomberie", sous: "Prix TTC, hors fournitures sanitaires.", sur: "PRESTATION|À PARTIR DE", items: ["Déplacement et diagnostic|Gratuit", "Recherche de fuite|120 €", "Remplacement de mitigeur|110 €", "Chauffe-eau 200 L posé|890 €", "Salle de bain complète|4 800 €", "Urgence nuit et week-end|+ 80 %"], meta: "Devis obligatoire au-delà de 150 € — pièces conservées sur demande" }],
  ["tableau", "a4", "chaud", "Artisanat & bâtiment", "Tarifs de peinture", { titre: "Tarifs\nde peinture", sous: "Prix TTC, fourniture et pose, deux couches.", sur: "PRESTATION|TARIF", items: ["Murs et plafond, pièce 12 m²|480 €", "Plafond seul, le m²|18 €", "Murs seuls, le m²|14 €", "Boiserie, le mètre linéaire|22 €", "Préparation lourde|+ 30 %", "Protection et nettoyage|Inclus"], meta: "Peinture professionnelle sans solvant — devis ferme après visite" }],
  ["contact", "carte", "sombre", "Artisanat & bâtiment", "Carte de serrurier", { sur: "Urgence 7j/7", titre: "Ouverture\nde porte", sous: "Intervention sous une heure dans la métropole.", items: ["06 00 00 00 00", "Ouverture sans dégât dans 9 cas sur 10", "Devis annoncé avant intervention", "Facture détaillée systématique"], meta: "Tarifs affichés — arrêté du 24 janvier 2017" }],
  ["cadre", "a5", "clair", "Artisanat & bâtiment", "Affichage de tarifs de serrurerie", { sur: "Affichage obligatoire", titre: "Tarifs\nd'intervention", sous: "Déplacement 45 € · ouverture simple 90 € · ouverture avec dégât dès 160 € · majoration nuit et jours fériés 100 % · devis obligatoire au-delà de 150 €.", meta: "TARIFS TTC — ARRÊTÉ DU 24 JANVIER 2017" }],
  ["etapes", "a4", "froid", "Artisanat & bâtiment", "Déroulé d'un chantier de rénovation", { titre: "Une rénovation,\nquatre phases", sous: "Comptez huit à douze semaines pour un T3 complet.", items: ["Visite et relevé|Gratuit, deux heures sur place.", "Devis détaillé|Poste par poste, sous huit jours.", "Chantier|Planning affiché, un référent unique.", "Réception|Levée des réserves sous quinze jours."] }],
  ["checklist", "a4", "clair", "Artisanat & bâtiment", "Vérifications avant réception", { sur: "Réception de chantier", titre: "Les sept\npoints à\nvérifier", items: ["Toutes les prises alimentées et testées", "Aucune trace sur les plinthes", "Portes et fenêtres qui ferment sans forcer", "Joints propres et continus", "Évacuations testées à l'eau", "Reprises de peinture faites", "Chantier nettoyé, gravats évacués"], meta: "Les réserves notées le jour de la réception sont les seules opposables" }],
  ["avantages", "large", "terre", "Artisanat & bâtiment", "Engagements de rénovation", { titre: "Trois engagements\nde chantier", sous: "Écrits dans chaque devis.", items: ["Un planning affiché|Sur place, mis à jour chaque lundi.", "Un chantier propre|Nettoyé chaque soir, gravats évacués.", "Un prix ferme|Aucun avenant sans votre signature."], meta: "Assurance décennale et RC professionnelle fournies avant signature" }],
  ["faq", "a4", "clair", "Artisanat & bâtiment", "Questions de rénovation", { sur: "Avant de signer", titre: "Quatre réponses\nqui évitent\ndes litiges", items: ["Quelle TVA s'applique ?|10 % en rénovation de plus de deux ans, 5,5 % en énergie.", "Quel acompte ?|30 % maximum à la commande, jamais plus.", "Que couvre la décennale ?|Ce qui compromet la solidité ou l'usage, dix ans.", "Et si le chantier prend du retard ?|Pénalités prévues au devis, appliquées."], meta: "Devis type consultable avant tout engagement" }],

  /* ══════════ Immobilier & services — extérieurs ══════════ */

  ["tableau", "a4", "nature", "Immobilier & services", "Tarifs de paysagiste", { titre: "Entretien\net création", sous: "Prix TTC, crédit d'impôt de 50 % sur l'entretien.", sur: "PRESTATION|TARIF", items: ["Tonte, le passage (500 m²)|55 €", "Taille de haie, le mètre|8 €", "Contrat annuel, 12 passages|590 €", "Création de massif, le m²|dès 45 €", "Abattage d'arbre|Sur devis", "Évacuation des déchets verts|Incluse"], meta: "Entreprise agréée services à la personne — n° SAP 000000000" }],
  ["etapes", "a4", "nature", "Immobilier & services", "Créer un jardin", { titre: "Créer\nun jardin", sous: "Comptez six mois entre la première visite et la plantation.", items: ["La visite|Sol, exposition, usages, contraintes.", "Le plan|Dessiné, chiffré, discuté.", "Les travaux|Terrassement, réseaux, plantations.", "La reprise|Suivi de la première saison, inclus."] }],
  ["grille", "a4", "nature", "Immobilier & services", "Six aménagements", { titre: "Six façons\nd'occuper\nun jardin", sous: "Selon la surface et l'exposition", items: ["Potager", "Massif d'ombre", "Terrasse bois", "Haie libre", "Verger", "Prairie fleurie"], meta: "Étude et plan chiffré : 480 €, déduits en cas de travaux" }],
  ["liste", "a4", "nature", "Immobilier & services", "Calendrier du jardin", { sur: "Au fil de l'année", titre: "Cinq gestes\nqui comptent\nvraiment", items: ["Tailler les haies avant mars ou après août", "Ne pas tondre trop court en été", "Pailler les massifs à l'automne", "Arroser abondamment mais rarement", "Laisser une zone en friche, toujours"], meta: "La taille entre mars et août est interdite pour protéger la nidification" }],
  ["tableau", "a4", "froid", "Immobilier & services", "Tarifs d'entretien de piscine", { titre: "Entretien\nde piscine", sous: "Prix TTC, produits inclus sauf mention contraire.", sur: "PRESTATION|TARIF", items: ["Ouverture de saison|180 €", "Passage hebdomadaire|48 €", "Contrat annuel, 30 passages|1 290 €", "Hivernage|160 €", "Changement de filtre à sable|Sur devis", "Analyse et correction de l'eau|Incluse"], meta: "Interventions du lundi au vendredi — urgence sous 48 h" }],
  ["checklist", "a4", "clair", "Immobilier & services", "Ouverture de piscine", { sur: "Remise en service", titre: "Les sept\nétapes", items: ["Retirer et nettoyer la bâche d'hivernage", "Remonter le niveau d'eau à mi-écumeur", "Remettre les bouchons et le panier", "Nettoyer le filtre à contre-courant", "Lancer la filtration en continu 48 h", "Faire analyser l'eau avant de corriger", "Ajuster le pH avant tout traitement"], meta: "Corriger le pH avant le chlore : sinon le chlore ne sert à rien" }],

  /* ══════════ Animaux — services animaliers ══════════ */

  ["tableau", "a4", "clair", "Animaux", "Tarifs de toilettage", { titre: "Tarifs\nde toilettage", sous: "Prix TTC, selon la taille et l'état du poil.", sur: "PRESTATION|TARIF", items: ["Petit chien, bain et coupe|45 €", "Chien moyen|60 €", "Grand chien|85 €", "Chat, bain et démêlage|55 €", "Coupe de griffes seule|12 €", "Supplément poil très emmêlé|+ 20 €"], meta: "Sur rendez-vous — prévoir 2 h — carnet de vaccination demandé" }],
  ["tableau", "a4", "nature", "Animaux", "Tarifs de pension", { titre: "Pension\nanimalière", sous: "Par jour et par animal, alimentation comprise.", sur: "ANIMAL|TARIF JOURNALIER", items: ["Chien, moins de 15 kg|18 €", "Chien, plus de 15 kg|24 €", "Deux chiens du même foyer|38 €", "Chat|14 €", "Séjour de plus de 15 jours|-10 %", "Prise de médicaments|Sans supplément"], meta: "Vaccins à jour obligatoires — visite de la pension bienvenue avant réservation" }],
  ["checklist", "a5", "clair", "Animaux", "À apporter en pension", { sur: "Avant le séjour", titre: "À apporter", items: ["Carnet de vaccination à jour", "L'alimentation habituelle, en quantité", "Le panier ou la couverture familière", "Les médicaments avec l'ordonnance", "Un jouet, un seul", "Vos coordonnées et celles du vétérinaire"], meta: "Ne changez pas l'alimentation à l'occasion du séjour : c'est la première cause de troubles" }],
  ["horaires", "a5", "nature", "Animaux", "Horaires de la pension", { sur: "Pension", titre: "Horaires\nd'accueil", items: ["Lundi – vendredi|9 h – 12 h · 16 h – 18 h", "Samedi|9 h – 12 h", "Dimanche|Sur rendez-vous", "Départs|Avant 11 h", "Arrivées|À partir de 16 h"], meta: "VISITE DES INSTALLATIONS POSSIBLE SANS RENDEZ-VOUS" }],

  /* ══════════ Finance & assurance — professions du chiffre ══════════ */

  ["tableau", "a4", "clair", "Finance & assurance", "Honoraires d'expert-comptable", { titre: "Nos honoraires", sous: "Forfaits annuels HT, révisés chaque janvier.", sur: "STRUCTURE|FORFAIT ANNUEL", items: ["Micro-entreprise|590 €", "EI au réel|1 400 €", "SASU sans salarié|1 900 €", "SARL, 1 à 3 salariés|2 800 €", "Bulletin de paie|18 € / mois", "Création de société|790 €"], meta: "Lettre de mission signée avant toute prestation — sans engagement de durée" }],
  ["etapes", "a4", "froid", "Finance & assurance", "Créer son entreprise", { titre: "Créer\nson entreprise", sous: "Comptez trois semaines du premier rendez-vous à l'immatriculation.", items: ["Le choix du statut|Une heure, gratuite, chiffres à l'appui.", "Les statuts|Rédigés et relus avec vous.", "Les formalités|Guichet unique, dépôt de capital.", "Le démarrage|Comptabilité et obligations expliquées."] }],
  ["comparatif", "a4", "clair", "Finance & assurance", "Micro ou société", { titre: "Micro-entreprise\nou société", sur: "MICRO", cta: "SOCIÉTÉ", items: ["Comptabilité simplifiée|Comptabilité complète", "Pas de charges déductibles|Charges déductibles", "Plafond de chiffre d'affaires|Aucun plafond", "Pas de TVA sous seuil|TVA dès le début", "Coût annuel : ~600 €|Coût annuel : ~2 000 €"], meta: "Le bon choix dépend surtout de vos charges réelles, pas de votre chiffre d'affaires" }],
  ["checklist", "a4", "clair", "Finance & assurance", "Pièces pour le bilan", { sur: "Clôture d'exercice", titre: "Ce qu'il faut\nnous transmettre", items: ["Relevés bancaires de l'exercice complet", "Factures d'achat et de vente", "Justificatifs de frais professionnels", "État des stocks au dernier jour", "Contrats de prêt et échéanciers", "Bulletins de paie et déclarations sociales", "Inventaire des immobilisations"], meta: "Dossier complet remis avant le 31 mars : bilan livré avant le 30 avril" }],
  ["cadre", "a4", "clair", "Finance & assurance", "Rappel d'échéance fiscale", { sur: "Échéance", titre: "Déclaration\navant le\n15 mai", sous: "La liasse fiscale doit être télétransmise avant le 15 mai. Passé cette date, une majoration de 10 % s'applique automatiquement.", meta: "TRANSMETTEZ VOS PIÈCES AVANT LE 15 AVRIL" }],
  ["frise", "a4", "chic", "Finance & assurance", "Calendrier fiscal", { titre: "Les échéances\nde l'année", sous: "Pour un exercice clos au 31 décembre.", items: ["31 janv.|DSN de décembre.", "15 mars|Solde d'impôt sur les sociétés.", "15 mai|Liasse fiscale.", "15 juin|Deuxième acompte.", "31 déc.|Clôture de l'exercice."], meta: "Rappels envoyés par e-mail quinze jours avant chaque échéance" }],
  ["visite", "carte", "chic", "Finance & assurance", "Carte d'expert-comptable", { gros: "SB", titre: "Sofia Bernard", sur: "EXPERTE-COMPTABLE", sous: "8 quai Vauban, Bordeaux · 05 56 00 00 00 · Ordre des experts-comptables" }],

  /* ══════════ Juridique & conseil — office notarial ══════════ */

  ["tableau", "a4", "clair", "Juridique & conseil", "Frais d'acte notarié", { titre: "Frais\nd'acquisition", sous: "Estimation pour un bien ancien de 250 000 €.", sur: "POSTE|MONTANT", items: ["Droits de mutation|14 500 €", "Émoluments du notaire|2 650 €", "Frais et débours|1 200 €", "TVA sur émoluments|530 €", "Total estimé|18 880 €", "Soit environ|7,5 % du prix"], meta: "Estimation indicative — le décompte définitif est remis avant la signature" }],
  ["etapes", "a4", "froid", "Juridique & conseil", "Étapes d'une acquisition", { titre: "De l'offre\nà la remise\ndes clés", sous: "Comptez trois mois entre le compromis et l'acte.", items: ["Le compromis|Signé chez le notaire, dix jours de rétractation.", "Les diagnostics|Fournis par le vendeur, annexés à l'acte.", "Le prêt|Quarante-cinq jours pour l'obtenir.", "L'acte|Signature, virement, remise des clés."] }],
  ["checklist", "a4", "clair", "Juridique & conseil", "Pièces pour un acte", { sur: "Avant la signature", titre: "Les pièces\nà fournir", items: ["Pièce d'identité en cours de validité", "Livret de famille ou contrat de mariage", "Offre de prêt acceptée", "Justificatif de l'apport personnel", "Relevé d'identité bancaire", "Coordonnées de l'assurance habitation", "Dernier avis de taxe foncière"], meta: "Dossier complet quinze jours avant : signature à la date prévue" }],
  ["faq", "a4", "clair", "Juridique & conseil", "Questions au notaire", { sur: "Vous demandez", titre: "Quatre réponses\nsimples", items: ["Puis-je choisir mon notaire ?|Oui, toujours, et sans frais supplémentaires.", "Deux notaires coûtent-ils plus cher ?|Non, ils se partagent les mêmes émoluments.", "Que sont les frais de notaire ?|80 % d'impôts, 10 % d'émoluments, 10 % de débours.", "Le délai de rétractation ?|Dix jours après le compromis, sans justification."], meta: "Office notarial du Port — 05 56 00 00 00" }],
  ["entete", "a4", "chic", "Juridique & conseil", "Papier à en-tête d'office", { titre: "Office notarial du Port", sur: "Notaires associés", sous: "8 quai Vauban\n33000 Bordeaux\n05 56 00 00 00", meta: "DOSSIER N° 2026-0184", items: ["Madame, Monsieur,", "", "", "", "Je vous prie d'agréer, Madame, Monsieur, l'expression de mes sentiments dévoués."], cta: "Office notarial — SIRET 000 000 000 00000" }],

  /* ══════════ Tech & startup — métiers de la création ══════════ */

  ["tableau", "a4", "clair", "Tech & startup", "Tarifs d'imprimeur", { titre: "Tarifs\nd'impression", sous: "Prix HT, papier 300 g pelliculé mat.", sur: "PRODUIT|QUANTITÉ ET PRIX", items: ["Cartes de visite|500 — 48 €", "Flyers A5|1 000 — 89 €", "Affiches A3|50 — 120 €", "Dépliants 3 volets|500 — 240 €", "Bâche 2 × 1 m|1 — 95 €", "Livraison Bordeaux|Offerte dès 150 €"], meta: "Fichiers PDF avec 3 mm de fond perdu — BAT envoyé sous 24 h" }],
  ["checklist", "a4", "clair", "Tech & startup", "Préparer un fichier d'impression", { sur: "Avant d'envoyer", titre: "Les sept\nvérifications", items: ["Fond perdu de 3 mm sur chaque bord", "Textes à 5 mm minimum des coupes", "Mode colorimétrique CMJN, pas RVB", "Images à 300 dpi à la taille finale", "Polices vectorisées ou incorporées", "Un seul PDF, pages dans l'ordre", "Noir de texte en 100 % noir seul"], meta: "Un fichier conforme part en production le jour même" }],
  ["tableau", "a4", "clair", "Tech & startup", "Tarifs de traduction", { titre: "Tarifs\nde traduction", sous: "Prix HT au mot source, relecture comprise.", sur: "PRESTATION|TARIF", items: ["Français vers anglais|0,14 € / mot", "Anglais vers français|0,12 € / mot", "Relecture seule|0,05 € / mot", "Traduction assermentée|Sur devis", "Urgence (moins de 48 h)|+ 40 %", "Minimum de facturation|45 €"], meta: "Délai standard : 2 000 mots par jour ouvré" }],
  ["cartes", "large", "tech", "Tech & startup", "Trois offres de création de site", { titre: "Trois formats\nde site", sous: "Hébergement et nom de domaine non compris.", items: ["Vitrine|1 400 €, cinq pages, livré en 3 semaines.", "Catalogue|3 200 €, jusqu'à 100 produits.", "Boutique|Sur devis, paiement et stocks."] }],
  ["etapes", "a4", "froid", "Tech & startup", "Créer un site", { titre: "Un site,\nquatre étapes", sous: "Comptez six à huit semaines pour un site vitrine.", items: ["Le cadrage|Contenu, pages, objectifs, écrits.", "La maquette|Deux propositions, une retenue.", "L'intégration|Développement et contenus réels.", "La mise en ligne|Formation incluse, deux heures."] }],
  ["faq", "a4", "clair", "Tech & startup", "Questions sur un site", { sur: "Avant de commander", titre: "Quatre réponses\nfranches", items: ["À qui appartient le site ?|À vous, code et contenus, dès le paiement.", "Puis-je le modifier seul ?|Oui, formation de deux heures incluse.", "Combien coûte l'hébergement ?|Entre 5 et 20 € par mois, payés directement.", "Et si je veux changer de prestataire ?|Tout est exportable, aucun verrou."], meta: "Devis détaillé et planning remis avant tout engagement" }],
  ["visite", "carte", "tech", "Tech & startup", "Carte de graphiste", { gros: "SV", titre: "Sophie Verrier", sur: "DIRECTRICE ARTISTIQUE INDÉPENDANTE", sous: "06 00 00 00 00 · sophie@sverrier.fr · SIRET 000 000 000 00000" }],
  ["tableau", "a4", "clair", "Tech & startup", "Tarifs de graphisme", { titre: "Tarifs\nde création", sous: "Prix HT, cession de droits comprise pour le web.", sur: "PRESTATION|TARIF", items: ["Identité visuelle complète|2 400 €", "Logotype seul|900 €", "Charte graphique|1 200 €", "Mise en page, la page|65 €", "Déclinaison réseaux, le format|45 €", "Journée de création|540 €"], meta: "Deux tours de modification inclus — au-delà, 90 € de l'heure" }],

];
