// Modèles — complément d'équilibrage.
//
// Dernière série, écrite après avoir compté : elle sert les compositions
// restées les moins employées — journal, diapositive à puces, citation,
// emblème, rétro, recette, carte cadeau, tableau de score — pour qu'aucune
// mise en page du catalogue ne soit représentée par une seule variante.

import type { Row } from "./design-templates";

export const ROWS_COMPLEMENT: Row[] = [

  /* ══════════ Mise en page « journal » ══════════ */

  ["journal", "a3", "chic", "Impression & affiche", "Gazette d'association", { sur: "LA GAZETTE DU QUARTIER", meta: "NUMÉRO 21 — SEPTEMBRE 2026 — GRATUIT", titre: "L'école rouvre\navec deux classes\nde plus", sous: "Après trois ans de démarches, la mairie a obtenu les ouvertures. Ce que ça change concrètement dès la rentrée.", items: ["Les effectifs par classe passent de vingt-huit à vingt-deux élèves en moyenne. C'est la première baisse depuis 2018, et elle concerne les six niveaux, du CP au CM2, sans exception.", "Deux enseignants ont été nommés en juin, ce qui a permis de préparer la rentrée sereinement pour une fois. La salle de motricité est reconvertie en salle de classe, et une nouvelle salle est prévue pour 2028.", "Reste la cantine, dimensionnée pour deux cents couverts et qui en sert deux cent quarante. Un second service est mis en place dès septembre, ce qui décale la pause méridienne de vingt minutes pour les grands."], cta: "PROCHAIN NUMÉRO EN DÉCEMBRE — CONTRIBUTIONS BIENVENUES À GAZETTE@QUARTIER.FR" }],
  ["journal", "a4", "clair", "Éducation & association", "Bulletin municipal", { sur: "LE BULLETIN", meta: "MAIRIE — AVRIL 2026", titre: "Le budget 2026\nvoté à l'unanimité", sous: "Quatre millions d'euros, dont un tiers d'investissement. Les trois postes qui augmentent, et celui qui baisse.", items: ["L'investissement représente 1,3 million d'euros, principalement consacrés à la rénovation énergétique de l'école et du gymnase. Les travaux commencent en juillet et s'étalent sur deux étés.", "Les dépenses de fonctionnement progressent de 2,8 %, essentiellement sous l'effet de la revalorisation du point d'indice et du coût de l'énergie. Aucun service n'est réduit.", "Les taux d'imposition communaux restent inchangés pour la sixième année consécutive. Le recours à l'emprunt est limité à 400 000 euros, sur quinze ans."], cta: "BUDGET COMPLET CONSULTABLE EN MAIRIE ET SUR LE SITE DE LA COMMUNE" }],
  ["journal", "a4", "terre", "Agriculture & terroir", "Lettre de la ferme", { sur: "LA LETTRE DE LA FERME", meta: "PRINTEMPS 2026 — FERME DE LA COMBE", titre: "Une année sèche,\net ce qu'on en fait", sous: "Deux cents millimètres de pluie en moins qu'en 2025. Comment nous adaptons les cultures.", items: ["Les semis de printemps ont été avancés de trois semaines pour profiter de l'humidité résiduelle du sol. C'est un pari : une gelée tardive aurait tout compromis. Elle n'est pas venue.", "Nous abandonnons les courges pour cette saison, trop gourmandes en eau, au profit des légumineuses et des céréales anciennes, qui se contentent de ce que le ciel donne.", "Les paniers seront donc différents cet été : moins de courgettes, plus de pois chiches et de lentilles. Nous joindrons des fiches recettes, parce que tout le monde ne sait pas quoi en faire."], cta: "VENTE À LA FERME DU MARDI AU SAMEDI — 05 57 00 00 00" }],
  ["journal", "a4", "sombre", "Culture & spectacle", "Feuille de salle", { sur: "FEUILLE DE SALLE", meta: "LES JUSTES — NOVEMBRE 2026", titre: "Ce que vous allez\nvoir ce soir", sous: "Une heure quarante-cinq, sans entracte. Quelques repères avant de commencer.", items: ["La pièce se déroule à Moscou en 1905, autour d'un groupe de révolutionnaires qui prépare un attentat. Elle pose une seule question, et n'y répond pas : jusqu'où peut-on aller pour une cause juste ?", "Notre mise en scène a choisi le dépouillement. Pas de décor, cinq chaises, et un plateau nu. Tout se joue dans la parole et dans les silences, qui sont nombreux et volontaires.", "L'équipe reste en salle après la représentation pour échanger avec le public, une vingtaine de minutes. Restez si vous voulez, partez si vous préférez : les deux sont parfaitement bienvenus."], cta: "PROCHAIN SPECTACLE : CORPS COMMUNS, LE 12 DÉCEMBRE" }],

  /* ══════════ Diapositives à puces ══════════ */

  ["diapo", "slide", "tech", "Présentation", "Constats chiffrés", { sur: "Constats", titre: "Ce que disent\nles données", items: ["Le délai moyen a baissé de douze à huit jours", "Deux sites concentrent 80 % des retards", "La satisfaction gagne quatre points", "Le coût par dossier reste stable"], sous: "Aucune de ces évolutions n'est due à un effet de périmètre.", meta: "Source : tableau de bord mensuel, juin 2026" }],
  ["diapo", "slide", "froid", "Présentation", "Hypothèses de travail", { sur: "Hypothèses", titre: "Sur quoi\nrepose ce plan", items: ["Croissance du marché de 4 % par an", "Aucune hausse des matières au-delà de 3 %", "Deux recrutements effectifs avant septembre", "Aucun départ non anticipé"], sous: "Si l'une de ces hypothèses tombe, le plan doit être revu.", meta: "Sensibilité détaillée en annexe, pages 31 à 34" }],
  ["diapo", "diapo43", "clair", "Présentation", "Décisions attendues", { sur: "Décisions", titre: "Ce qu'on\nvous demande\naujourd'hui", items: ["Valider l'arrêt de l'activité Nord", "Autoriser deux recrutements", "Décaler l'ouverture de Lyon à mars", "Reconduire le budget formation"], sous: "Chaque décision est indépendante des trois autres.", meta: "Vote à main levée, décisions consignées au compte rendu" }],
  ["diapo", "a4", "clair", "CV & document", "Note à puces", { sur: "Note interne", titre: "Ce qui change\nau 1er septembre", items: ["L'atelier ferme à 16 h le vendredi", "Les heures sont reportées du lundi au jeudi", "Les pauses restent inchangées", "Aucune modification de rémunération"], sous: "Cette organisation est mise en place à titre d'essai jusqu'au 31 décembre.", meta: "Note diffusée le 12 juin 2026" }],
  ["diapo", "large", "vif", "Web & e-mail", "Bloc e-mail récapitulatif", { sur: "Cette semaine", titre: "Quatre choses\nà retenir", items: ["Les nouveautés sortent jeudi à 10 h", "La boutique ferme lundi pour inventaire", "L'atelier est visitable samedi matin", "Le service client répond jusqu'à 19 h"], sous: "Tout est aussi rappelé sur la page d'accueil du site.", meta: "Se désabonner en un clic, en bas de cet e-mail" }],
  ["diapo", "story", "sombre", "Story & Reel", "Story à puces", { sur: "À savoir", titre: "Trois infos\navant samedi", items: ["Ouverture à 8 h, pas à 10 h", "Paiement carte accepté dès 1 €", "Parking gratuit tout le week-end"], sous: "Rendez-vous place du Marché, quel que soit le temps.", meta: "Tout est rappelé en bio" }],

  /* ══════════ Citations ══════════ */

  ["citation", "carre", "terre", "Instagram", "Citation d'artisan", { titre: "« Un beau\ntravail,\nça se voit\nau dos. »", auteur: "Jean Berthier, menuisier", sous: "Quarante-deux ans de métier" }],
  ["citation", "portrait", "nature", "Instagram", "Citation de paysan", { titre: "« On ne\ncommande pas\nà la pluie. »", auteur: "Marc Vidal, maraîcher", sous: "Ferme de la Combe, Saint-Émilion" }],
  ["citation", "pin", "chic", "Pinterest", "Citation inspirante", { titre: "« Ce qui\nse fait vite\nse refait\ndeux fois. »", auteur: "Proverbe d'atelier", sous: "Affiché au-dessus de l'établi" }],
  ["citation", "story", "sombre", "Story & Reel", "Citation en story", { titre: "« La patience\nest un\nsavoir-faire. »", auteur: "Jean Berthier, tourneur", sous: "Quarante-deux ans de métier" }],
  ["citation", "a4", "chic", "Impression & affiche", "Citation affichée", { titre: "« On ne\nrattrape pas\nau montage\nce qu'on a raté\nau tournage. »", auteur: "Marc Vidal, chef opérateur", sous: "Affiche de l'école de cinéma" }],
  ["citation", "large", "froid", "LinkedIn", "Citation professionnelle", { titre: "« Un délai\nqu'on annonce\nest un délai\nqu'on tient. »", auteur: "Règle interne, depuis 2021", sous: "Affichée dans l'atelier de préparation" }],

  /* ══════════ Emblèmes et identités ══════════ */

  ["embleme", "logo", "terre", "Marque & logo", "Emblème pentagone", { meta: "pentagon", gros: "LC", titre: "La Combe", sous: "MIELS ET CONFITURES" }],
  ["embleme", "logo", "vif", "Marque & logo", "Emblème étoile", { meta: "star", gros: "AS", titre: "Atelier Stella", sous: "BIJOUX FAITS MAIN" }],
  ["embleme", "logo", "pastel", "Marque & logo", "Emblème cœur", { meta: "heart", gros: "MB", titre: "Maison Beauté", sous: "SOINS ET COIFFURE" }],
  ["embleme", "logo", "clair", "Marque & logo", "Emblème octogone", { meta: "octagon", gros: "GD", titre: "Garage Dupont", sous: "MÉCANIQUE — CARROSSERIE" }],
  ["embleme", "carte", "sombre", "Carte & papeterie", "Carte à emblème bouclier", { meta: "shield", gros: "ASR", titre: "AS Rivière", sous: "CLUB OMNISPORTS DEPUIS 1962" }],
  ["embleme", "carreL", "froid", "Marque & logo", "Grand emblème", { meta: "ring", gros: "SV", titre: "Studio Verrier", sous: "PHOTOGRAPHIE — BORDEAUX" }],
  ["ecusson", "carte", "chic", "Carte & papeterie", "Carte à écusson", { gros: "MB", meta: "DEPUIS 1974", titre: "Maison Berthier", sous: "Parfumeur à Grasse" }],
  ["ecusson", "a5", "vif", "Éducation & association", "Écusson d'association", { gros: "AQ", meta: "EST. 1998", titre: "Association du quartier", sous: "Faire ensemble, depuis vingt-huit ans" }],
  ["monogramme", "a5", "pastel", "Carte & papeterie", "Monogramme de faire-part", { gros: "C", titre: "Camille", sous: "NÉE LE 3 AVRIL 2026" }],
  ["monogramme", "story", "chic", "Story & Reel", "Story monogramme", { gros: "S&M", titre: "Sofia & Marc", sous: "12 SEPTEMBRE 2026" }],

  /* ══════════ Rétro et archives ══════════ */

  ["retro", "a3", "chaud", "Impression & affiche", "Affiche rétro", { sur: "Depuis 1971", titre: "Le goût\nd'avant", sous: "Même four, même farine, même patron." }],
  ["retro", "pin", "terre", "Pinterest", "Épingle rétro", { sur: "Archives", titre: "La cuisine\nde nos\ngrands-mères", sous: "Vingt recettes recopiées telles quelles, sans allègement." }],
  ["retro", "carre", "chic", "Marque & logo", "Post rétro de marque", { sur: "1974", titre: "Le premier\nflacon", sous: "Le dessin n'a pas changé depuis. La formule non plus." }],
  ["retro", "large", "sombre", "Facebook", "Couverture rétro", { sur: "Il y a cinquante ans", titre: "La même\nplace", sous: "Les platanes ont grandi, le kiosque est toujours là." }],
  ["retro", "story", "pastel", "Story & Reel", "Story archive", { sur: "2014", titre: "La première\nboutique", sous: "Quinze mètres carrés, et déjà trop petite." }],

  /* ══════════ Recettes et méthodes ══════════ */

  ["recette", "a4", "chaud", "Restauration & café", "Fiche technique de cuisine", { titre: "Pâte à pizza,\n48 h de pousse", meta: "48 H — 6 PÂTONS DE 250 G — MOYEN", sur: "IL FAUT", cta: "ON PROCÈDE", items: ["1 kg de farine T65", "650 g d'eau froide", "20 g de sel, 2 g de levure", "20 g d'huile d'olive", "Mélangez, laissez reposer 30 min.", "Pétrissez 8 min, boulez, filmez.", "24 h au frais, puis façonnez en pâtons.", "24 h de plus au frais, sortez 2 h avant."], sous: "La pousse longue au froid fait tout : c'est elle qui donne le goût, pas la levure." }],
  ["recette", "a4", "nature", "Agriculture & terroir", "Fiche de conservation", { titre: "Stériliser\nses bocaux", meta: "1 H 30 — CONSERVATION 12 MOIS", sur: "IL FAUT", cta: "ON PROCÈDE", items: ["Des bocaux à joint neuf", "Une grande marmite", "Un torchon pour caler", "De l'eau à hauteur", "Remplissez à 2 cm du bord, essuyez le col.", "Fermez, calez dans la marmite avec le torchon.", "Portez à ébullition, comptez 1 h à partir de là.", "Laissez refroidir dans l'eau, sans ouvrir."], sous: "Un joint réutilisé est la première cause de bocal raté. Ils coûtent trente centimes." }],
  ["recette", "pin", "pastel", "Pinterest", "Épingle méthode maison", { titre: "Lessive maison,\ndeux ingrédients", meta: "20 MIN — 3 LITRES — TRÈS FACILE", sur: "IL VOUS FAUT", cta: "ON Y VA", items: ["100 g de savon de Marseille râpé", "3 litres d'eau chaude", "2 cuillères de bicarbonate", "Un bidon de 3 litres", "Faites fondre le savon dans un litre d'eau chaude.", "Ajoutez le bicarbonate, mélangez.", "Complétez avec le reste d'eau.", "Laissez reposer 24 h, secouez avant chaque usage."], sous: "Elle épaissit en refroidissant. C'est normal, secouez, ça suffit." }],
  ["recette", "a4", "clair", "Éducation & association", "Méthode de réunion", { titre: "Une réunion\nqui sert\nà quelque chose", meta: "30 MINUTES — 6 PERSONNES MAXIMUM", sur: "IL FAUT", cta: "ON PROCÈDE", items: ["Un ordre du jour envoyé la veille", "Une personne qui tranche", "Un relevé de décisions écrit", "Un minuteur, vraiment", "Cinq minutes de chiffres, pas plus.", "Quinze minutes d'arbitrages.", "Cinq minutes de risques à venir.", "Cinq minutes de relecture des décisions."], sous: "Si elle dépasse trente minutes, c'est qu'elle n'a pas tranché." }],
  ["recette", "story", "chaud", "Story & Reel", "Story méthode express", { titre: "Omelette\nbaveuse", meta: "6 MIN — 2 PARTS — TRÈS FACILE", sur: "IL FAUT", cta: "ON FAIT", items: ["4 œufs", "Une noix de beurre", "Sel, poivre", "Poêle antiadhésive", "Battez à peine, pas jusqu'à mousser.", "Beurre mousseux, feu moyen, pas fort.", "Remuez sans arrêt les 30 premières secondes.", "Arrêtez quand ça paraît encore trop coulant."], sous: "Elle finit de cuire dans l'assiette. Toujours." }],

  /* ══════════ Cartes cadeaux et bons ══════════ */

  ["cartecadeau", "carte", "vif", "Commerce & promotion", "Carte cadeau colorée", { sur: "Carte cadeau", gros: "25 €", titre: "Pour un petit quelque chose", meta: "N° 0000 0000 0000", sous: "Valable deux ans, utilisable en plusieurs fois." }],
  ["cartecadeau", "carte", "nature", "Restauration & café", "Bon cadeau restaurant", { sur: "Bon cadeau", gros: "60 €", titre: "Un dîner pour deux, entrées et desserts compris", meta: "VALABLE UN AN", sous: "Hors boissons — sur réservation au 05 56 00 00 00." }],
  ["cartecadeau", "carte", "pastel", "Beauté & coiffure", "Bon cadeau institut", { sur: "Bon cadeau", gros: "95 €", titre: "Soin anti-âge, 75 minutes", meta: "N° 000 000", sous: "Valable un an, sur rendez-vous, non remboursable." }],
  ["cartecadeau", "a5", "terre", "Agriculture & terroir", "Bon cadeau ferme", { sur: "Bon cadeau", gros: "40 €", titre: "Panier de saison, à retirer à la ferme", meta: "VALABLE SIX MOIS", sous: "Composition selon la saison — prévenir la veille." }],
  ["cartecadeau", "story", "chic", "Story & Reel", "Story bon cadeau", { sur: "Idée cadeau", gros: "100 €", titre: "Quand on ne sait vraiment pas quoi offrir", meta: "DISPONIBLE EN BOUTIQUE", sous: "Valable deux ans, sans minimum d'achat." }],
  ["coupon", "carre", "nature", "Agriculture & terroir", "Coupon de fidélité ferme", { gros: "10E", sur: "CARTE DE FIDÉLITÉ", titre: "Le dixième panier est offert", sous: "Un tampon par panier retiré. Carte valable un an à compter du premier tampon.", meta: "CARTE N° 0000", cta: "Non nominative, transmissible" }],
  ["coupon", "a5", "pastel", "Beauté & coiffure", "Coupon parrainage institut", { gros: "-20 €", sur: "PARRAINAGE", titre: "Pour vous et pour la personne parrainée", sous: "Vingt euros pour elle sur son premier soin, vingt euros pour vous sur le suivant.", meta: "CODE : PARRAIN-0000", cta: "Sans limite de filleuls" }],

  /* ══════════ Scores, duos et pastilles ══════════ */

  ["score", "large", "vif", "Sport & bien-être", "Résultat de coupe", { sur: "COUPE RÉGIONALE — QUART", items: ["AS Rivière", "FC Aubépine"], gros: "1-0", titre: "Qualification arrachée à la 89e minute", meta: "DIMANCHE 15 H — STADE MUNICIPAL" }],
  ["score", "story", "sombre", "Story & Reel", "Story score", { sur: "MI-TEMPS", items: ["Rivière", "Combe"], gros: "2-1", titre: "Tout reste à jouer en seconde période", meta: "SUIVEZ LA FIN EN DIRECT" }],
  ["score", "a4", "clair", "Présentation", "Objectif contre réalisé", { sur: "EXERCICE 2026", items: ["Objectif", "Réalisé"], gros: "100-118", titre: "Objectif dépassé de dix-huit points", meta: "À PÉRIMÈTRE CONSTANT, HORS CESSION" }],
  ["score", "carre", "tech", "Jeux & e-sport", "Score de finale", { sur: "FINALE", items: ["Aubépine", "Rivière"], gros: "3-2", titre: "Victoire au cinquième round, après prolongation", meta: "DIMANCHE 20 H — DIFFUSÉ EN DIRECT" }],
  ["duo", "carre", "nature", "Agriculture & terroir", "Deux chiffres de récolte", { gros: "2026", items: ["840 kg|de miel récolté", "0|traitement chimique"] }],
  ["duo", "large", "chic", "Culture & spectacle", "Deux chiffres de saison", { gros: "SAISON", items: ["12|spectacles", "6|créations"] }],
  ["duo", "story", "vif", "Story & Reel", "Story deux chiffres", { gros: "MAI", items: ["368|commandes", "7 j|délai moyen"] }],
  ["pastille", "story", "chaud", "Story & Reel", "Story pastille de remise", { gros: "-25%", sur: "CE WEEK-END", titre: "Sur toute la boutique", meta: "SAMEDI ET DIMANCHE" }],
  ["pastille", "a5", "vif", "Impression & affiche", "Affichette de remise", { gros: "-40%", sur: "SUR CE PORTANT", titre: "Fins de série et tailles isolées", meta: "PRIX BARRÉ AFFICHÉ SUR CHAQUE ÉTIQUETTE" }],
  ["pastille", "etiq", "nature", "Commerce & promotion", "Étiquette pastille", { gros: "NEW", sur: "NOUVEAUTÉ", titre: "Arrivé cette semaine", meta: "QUANTITÉ LIMITÉE" }],

  /* ══════════ Tarifs, playlists, damiers, rayures ══════════ */

  ["tarif", "a4", "chic", "Beauté & coiffure", "Forfait beauté", { sur: "FORFAIT RITUEL", gros: "145 €", sous: "deux heures, en cabine individuelle", items: ["Diagnostic de peau complet", "Double nettoyage et gommage", "Massage du visage, 20 minutes", "Masque adapté au diagnostic", "Conseils et routine écrite"], cta: "Réserver un créneau" }],
  ["tarif", "a4", "nature", "Immobilier & services", "Forfait entretien de jardin", { sur: "CONTRAT ANNUEL", gros: "590 €", sous: "douze passages, crédit d'impôt déduit : 295 €", items: ["Tonte tous les quinze jours en saison", "Deux tailles de haie par an", "Ramassage des feuilles à l'automne", "Évacuation des déchets verts", "Aucun matériel à fournir"], cta: "Demander un devis" }],
  ["tarif", "a4", "vif", "Éducation & association", "Forfait d'atelier", { sur: "FORFAIT ANNUEL", gros: "340 €", sous: "un cours par semaine, 30 séances", items: ["Matériel fourni et cuisson comprise", "Accès libre à l'atelier le samedi", "Exposition de fin d'année", "Adhésion à l'association incluse", "Quotient familial appliqué"], cta: "S'inscrire en permanence" }],
  ["playlist", "large", "chic", "Culture & spectacle", "Programme de concert", { emoji: "🎻", titre: "Le programme\nde ce soir", sous: "Une heure quinze, sans entracte", items: ["Haydn — Quatuor op. 76|18:00", "Ravel — Quatuor en fa|29:00", "Entracte|—", "Chostakovitch — Quatuor n° 8|21:00", "Bis éventuel|—", "Rencontre avec les musiciens|20:00"], meta: "Merci d'éteindre les téléphones, y compris en mode silencieux" }],
  ["playlist", "pin", "pastel", "Pinterest", "Épingle sélection", { emoji: "📚", titre: "Six livres\npour l'été", sous: "Tous lus, aucun abandonné", items: ["Un roman d'atelier|1", "Un essai court|2", "Une bande dessinée|3", "Un récit de voyage|4", "Un policier lent|5", "Un livre de cuisine|6"], meta: "Références complètes dans l'article" }],
  ["damier", "a3", "vif", "Impression & affiche", "Affiche damier", { sur: "Trois jours", titre: "PORTES\nOUVERTES", sous: "Démonstrations toutes les heures, ventes directes, café offert.", meta: "DU 12 AU 14 JUIN — 4 RUE DES FORGES" }],
  ["damier", "carre", "tech", "Jeux & e-sport", "Post damier", { sur: "Tournoi d'hiver", titre: "LES\nINSCRIPTIONS\nSONT OUVERTES", sous: "Trente-deux équipes, double élimination, 1 500 € de dotation.", meta: "JUSQU'AU 30 MAI — 10 € PAR ÉQUIPE" }],
  ["rayures", "carre", "chaud", "Commerce & promotion", "Post rayures", { sur: "Ce week-end", titre: "MARCHÉ\nDE NOËL", sous: "Quarante artisans, vin chaud, manège pour les enfants.", meta: "SAMEDI ET DIMANCHE — 10 H À 20 H" }],
  ["rayures", "story", "vif", "Story & Reel", "Story rayures", { sur: "Aujourd'hui", titre: "BRADERIE", sous: "Tout à moins de trente euros, jusqu'à 19 h.", meta: "12 RUE DU MARCHÉ" }],
  ["bandeau", "carre", "froid", "Instagram", "Post bandeau", { sur: "Nouveauté", titre: "La réparation\nà vie", sous: "Toute pièce vendue depuis 2019 est réparée gratuitement, sans limite de temps.", cta: "En savoir plus" }],
  ["bandeau", "a4", "chaud", "Impression & affiche", "Affichette bandeau", { sur: "Information", titre: "Nouveaux\nhoraires", sous: "À partir du 1er septembre, la boutique ouvre à 9 h au lieu de 10 h, du mardi au samedi.", cta: "Merci de votre compréhension" }],
  ["centre", "a5", "chic", "Carte & papeterie", "Carte sobre", { sur: "Avec nos remerciements", titre: "Merci", sous: "Votre commande a été préparée à la main, dans notre atelier de Bordeaux." }],
  ["centre", "pin", "nature", "Pinterest", "Épingle sobre", { sur: "Rappel", titre: "Faites\nune chose\nà la fois", sous: "C'est le conseil le plus rebattu, et le seul qui ait jamais marché." }],
  ["coins", "a5", "chic", "Carte & papeterie", "Carte à équerres", { sur: "Invitation", titre: "Vernissage", sous: "En présence de l'auteur, verre offert à partir de 18 h 30.", meta: "VENDREDI 3 AVRIL — GALERIE DU PORT" }],
  ["coins", "pin", "sombre", "Photo & création", "Épingle cadrage", { sur: "Série", titre: "Lumière\nrasante,\nfin de journée", sous: "Six images prises en vingt minutes, avant que ça tombe.", meta: "STUDIO VERRIER — SEPTEMBRE 2026" }],
  ["demi", "large", "sombre", "Facebook", "Annonce en deux temps", { sur: "Information", gros: "ON\nDÉMÉNAGE", titre: "Nouvelle adresse au 4 rue des Forges", sous: "Deux fois plus grand, à cinq minutes à pied de l'ancienne boutique.", meta: "FERMETURE DU 3 AU 10 JUIN" }],
  ["demi", "a4", "vif", "Impression & affiche", "Affiche en deux temps", { sur: "Recrutement", gros: "ON\nRECRUTE", titre: "Trois postes ouverts, salaires affichés", sous: "Vente, atelier et livraison. CDI, Bordeaux, réponse sous cinq jours.", meta: "CANDIDATURES : EMPLOI@EXEMPLE.FR" }],
  ["panneau", "a4", "froid", "Santé & cabinet", "Plaquette de cabinet", { gros: "04", sur: "Maison de santé", titre: "Quatre\nprofessionnels,\nun seul lieu", sous: "Médecine générale, kinésithérapie, infirmerie et diététique, coordonnés autour du même dossier partagé.", meta: "12 rue du Marché — 05 56 00 00 00" }],
  ["panneau", "a4", "chic", "Juridique & conseil", "Plaquette de cabinet juridique", { gros: "03", sur: "Cabinet Berthier", titre: "Trois\ndomaines,\naucun autre", sous: "Droit du travail, droit commercial, droit des sociétés. Nous refusons ce que nous ne maîtrisons pas.", meta: "8 quai Vauban, Bordeaux — 05 56 00 00 00" }],
  ["ombredure", "a3", "vif", "Impression & affiche", "Affiche ombre dure", { sur: "Association du quartier", titre: "ASSEMBLÉE\nGÉNÉRALE", sous: "Ouverte à tous les habitants, avec vote du budget et renouvellement du bureau.", meta: "SAMEDI 20 JUIN — 10 H — MAISON DE QUARTIER" }],
  ["ombredure", "carre", "sombre", "Instagram", "Post ombre dure", { sur: "Rappel", titre: "DERNIÈRE\nSEMAINE", sous: "L'exposition ferme dimanche. Dernières visites guidées à 11 h et 15 h.", meta: "GALERIE DU PORT — ENTRÉE LIBRE" }],
  ["cv", "cv", "vif", "CV & document", "CV créatif coloré", { gros: "CD", titre: "Camille\nDurand", sur: "CHARGÉE DE COMMUNICATION", sous: "06 00 00 00 00\ncamille@exemple.fr\nBordeaux\nPermis B", meta: "PARCOURS", items: ["Chargée de communication — Aubépine|2022 à aujourd'hui. Refonte complète des supports, audience multipliée par quatre en deux ans.", "Assistante communication — Groupe Roux|2019-2022. Rédaction, réseaux sociaux, relations presse régionales.", "Alternante — Studio Verrier|2017-2019. Production de contenus et suivi de fabrication.", "Master communication|Université Bordeaux Montaigne, 2019."] }],
  ["cv", "cv", "nature", "CV & document", "CV secteur associatif", { gros: "NT", titre: "Noé\nTissot", sur: "COORDINATEUR DE PROJETS", sous: "06 00 00 00 00\nnoe@exemple.fr\nBordeaux\nBAFD", meta: "PARCOURS", items: ["Coordinateur — Association du quartier|2021 à aujourd'hui. Douze ateliers, trente-huit bénévoles, budget de 90 k€.", "Animateur — Centre de la Combe|2018-2021. Séjours d'été, groupes de vingt-quatre enfants.", "Service civique — Maison des jeunes|2017-2018. Accompagnement scolaire et sorties.", "Licence sciences de l'éducation|Université de Bordeaux, 2017."] }],
  ["magazine", "portrait", "sombre", "Instagram", "Une de série", { sur: "SÉRIE", meta: "ÉPISODE 4 — AVRIL 2026", titre: "Le dernier\ntanneur", sous: "Quarante ans de cuves, deux apprentis, et une décision à prendre avant l'hiver.", items: ["Comment on tanne au végétal", "Pourquoi ça a presque disparu", "Ce qu'il transmet, et à qui"] }],
  ["magazine", "a4", "clair", "Impression & affiche", "Couverture de rapport", { sur: "RAPPORT", meta: "EXERCICE 2026 — 42 PAGES", titre: "L'année\nen clair", sous: "Activité, comptes, effectifs et perspectives, sans arrondi favorable.", items: ["Ce qui a marché", "Ce qui n'a pas marché", "Ce qu'on décide pour 2027"] }],
  ["bulle", "large", "froid", "Facebook", "Message reçu", { sur: "Reçu ce matin", titre: "« Trois générations passent chez vous. Ça veut tout dire. »", auteur: "Famille Roux", sous: "Clients depuis 1994" }],
  ["bulle", "a5", "pastel", "Carte & papeterie", "Carte à message", { sur: "Un mot", titre: "« Merci d'être passés. Ça compte plus que vous ne le croyez. »", auteur: "Sofia et Marc", sous: "Atelier Aubépine, Bordeaux" }],

];
