// Modèles — immobilier, santé, artisanat, automobile.
//
// Des métiers où la communication sert surtout à rassurer : un prix affiché,
// un horaire tenu, une garantie écrite. Les contenus sont donc précis et
// vérifiables plutôt que vendeurs — c'est ce qui fait la différence sur le
// terrain, et c'est ce qu'un modèle doit permettre de dire vite.

import type { Row } from "./design-templates";

export const ROWS_METIERS: Row[] = [

  /* ══════════ Immobilier & services ══════════ */

  ["fiche", "a4", "clair", "Immobilier & services", "Fiche de bien", { titre: "Maison de ville,\n4 pièces, 96 m²", meta: "Bordeaux Nansouty — DPE C — 389 000 €", sur: "LES ATOUTS", sous: "À PRÉVOIR", items: ["Jardin exposé sud de 60 m²", "Chauffage au gaz récent", "Cave et combles aménageables", "Rafraîchissement des peintures", "Salle de bain d'origine", "Pas de stationnement privatif"] }],
  ["fiche", "a4", "froid", "Immobilier & services", "Fiche appartement", { titre: "T3 lumineux,\n68 m², 3e étage", meta: "Bordeaux Chartrons — DPE B — 279 000 €", sur: "POINTS FORTS", sous: "À NOTER", items: ["Ascenseur et balcon plein sud", "Copropriété de 12 lots", "Charges de 92 € par mois", "Pas de place de parking", "Travaux de façade votés", "Étage sans vis-à-vis mais rue passante"] }],
  ["tableau", "a4", "clair", "Immobilier & services", "Caractéristiques du bien", { titre: "Le bien\nen détail", sous: "Informations vérifiées au 1er avril 2026.", sur: "CARACTÉRISTIQUE|VALEUR", items: ["Surface habitable|96 m²", "Terrain|60 m²", "Année de construction|1932", "Chauffage|Gaz individuel", "DPE|C (168 kWh/m²/an)", "Taxe foncière|1 240 € / an", "Honoraires|4 % TTC charge vendeur"], meta: "Mandat n° 2026-0184 — diagnostic complet sur demande" }],
  ["ruban", "carre", "chaud", "Immobilier & services", "Bien vendu", { sur: "Encore un", titre: "VENDU", sous: "Maison de ville, quatre pièces, vendue au prix demandé en dix-neuf jours.", meta: "MERCI POUR VOTRE CONFIANCE" }],
  ["pastille", "carre", "vif", "Immobilier & services", "Baisse de prix", { gros: "-15 000 €", sur: "NOUVEAU PRIX", titre: "T3 Chartrons, 68 m²", meta: "DÈS AUJOURD'HUI — 264 000 €" }],
  ["chiffre", "carre", "tech", "Immobilier & services", "Délai de vente", { sur: "Notre moyenne", gros: "38", titre: "jours entre le mandat et le compromis", sous: "Sur les 42 biens vendus en 2025, tous types confondus.", cta: "Estimation gratuite" }],
  ["question", "large", "clair", "Immobilier & services", "Question propriétaire", { sur: "Propriétaires", titre: "Savez-vous\nce que vaut\nvraiment votre bien ?", sous: "Estimation écrite, gratuite, sous 48 heures, sans obligation de mandat." }],
  ["etapes", "a4", "froid", "Immobilier & services", "Étapes de la vente", { titre: "Vendre\nen quatre étapes", sous: "Comptez trois à quatre mois du mandat à l'acte.", items: ["Estimation|Visite du bien et étude comparative écrite.", "Mise en vente|Photos, annonce, diffusion sur huit portails.", "Compromis|Négociation, puis signature chez le notaire.", "Acte définitif|Trois mois plus tard, remise des clés."] }],
  ["frise", "a4", "chic", "Immobilier & services", "Calendrier d'une vente", { titre: "Le calendrier\nréel d'une vente", sous: "Ce qui prend du temps, et pourquoi.", items: ["Semaine 1|Estimation et mandat.", "Semaine 2|Photos et mise en ligne.", "Semaine 3-6|Visites, en moyenne onze.", "Semaine 7|Offre acceptée, compromis.", "Mois 4|Acte authentique, clés remises."], meta: "Délais constatés sur nos ventes 2025" }],
  ["avantages", "large", "froid", "Immobilier & services", "Nos engagements agence", { titre: "Trois engagements\népais", sous: "Écrits dans le mandat, pas dans une brochure.", items: ["Estimation argumentée|Trois biens comparables, chiffres à l'appui.", "Un seul interlocuteur|La personne qui estime est celle qui visite.", "Compte rendu hebdomadaire|Chaque vendredi, même s'il n'y a rien à dire."], meta: "Honoraires affichés en vitrine et sur le site" }],
  ["tarif", "a4", "froid", "Immobilier & services", "Honoraires agence", { sur: "HONORAIRES DE VENTE", gros: "4 %", sous: "TTC du prix de vente, charge vendeur", items: ["Estimation écrite offerte", "Photos professionnelles incluses", "Diffusion sur huit portails", "Visites accompagnées systématiques", "Accompagnement jusqu'à l'acte"], cta: "Demander une estimation" }],
  ["contact", "carte", "clair", "Immobilier & services", "Carte agence", { sur: "Agence du Port", titre: "On habite\nle quartier", sous: "Ouvert du mardi au samedi, sans rendez-vous.", items: ["8 quai Vauban, Bordeaux", "05 56 00 00 00", "contact@agenceduport.fr", "agenceduport.fr"], meta: "Estimation gratuite et sans engagement" }],
  ["visite", "carte", "chic", "Immobilier & services", "Carte de visite agent", { gros: "SB", titre: "Sofia Bernard", sur: "CONSEILLÈRE EN IMMOBILIER", sous: "Agence du Port · 06 00 00 00 00 · sofia@agenceduport.fr" }],
  ["notation", "large", "clair", "Immobilier & services", "Avis vendeur", { gros: "5/5", sur: "sur 68 avis clients", titre: "Estimation honnête, même quand elle ne nous arrangeait pas. Vendu en trois semaines au prix annoncé.", auteur: "Famille Roux, Talence", meta: "Avis Google — février 2026" }],
  ["temoignage", "carre", "pastel", "Immobilier & services", "Témoignage acquéreur", { emoji: "🔑", titre: "« On a visité onze maisons avec eux. Aucune pression, jamais. »", auteur: "Camille et Noé", sous: "Acquéreurs, mars 2026" }],
  ["recrute", "a4", "froid", "Immobilier & services", "Recrutement conseiller", { sur: "NOUS RECRUTONS", titre: "Conseiller ou\nconseillère\nen immobilier", sous: "Statut salarié — Bordeaux — débutant accepté", items: ["Formation interne de deux mois", "Fixe 2 100 € brut plus commissions", "Secteur attribué, pas de concurrence interne"], meta: "Candidatures : emploi@agenceduport.fr" }],
  ["horaires", "a5", "clair", "Immobilier & services", "Horaires d'agence", { sur: "Agence", titre: "Nos horaires", items: ["Lundi|Sur rendez-vous", "Mardi – vendredi|9 h 30 – 12 h 30 · 14 h – 19 h", "Samedi|9 h 30 – 17 h", "Dimanche|Fermé"], meta: "VISITES POSSIBLES EN SOIRÉE SUR DEMANDE" }],
  ["banniere", "large", "froid", "Immobilier & services", "Bannière estimation", { gros: "48H", titre: "Une estimation écrite en deux jours", sous: "Gratuite, argumentée, sans obligation de nous confier le bien.", cta: "Demander mon estimation" }],
  ["typo", "large", "clair", "Immobilier & services", "Slogan agence", { titre: "ON NE VEND PAS\nDU RÊVE.\nON VEND\nDES MAISONS.", sous: "Estimation honnête, même quand elle déçoit.", meta: "Agence du Port — 05 56 00 00 00" }],
  ["grille", "a4", "clair", "Immobilier & services", "Nos biens du moment", { titre: "Six biens\ndisponibles", sous: "Mise à jour du 1er avril 2026", items: ["T2 Victoire", "T3 Chartrons", "Maison Nansouty", "Loft Bacalan", "T4 Caudéran", "Terrain Pessac"], meta: "Détail de chaque bien en agence ou sur le site" }],
  ["checklist", "a4", "clair", "Immobilier & services", "Avant la visite", { sur: "Vendeurs", titre: "Préparer\nsa maison\npour une visite", items: ["Ouvrir tous les volets, même par temps gris", "Ranger les surfaces, pas les placards", "Aérer une heure avant", "Retirer les photos personnelles", "Régler la température à 20 degrés", "Sortir les animaux si possible", "Laisser l'agent faire visiter seul"], meta: "Une visite préparée dure dix minutes de plus, et convertit deux fois mieux" }],
  ["faq", "a4", "clair", "Immobilier & services", "Questions de vendeurs", { sur: "Vous nous demandez", titre: "Quatre réponses\nfranches", items: ["Le mandat exclusif est-il obligatoire ?|Non. Il vend plus vite, mais vous restez libre.", "Puis-je fixer mon prix ?|Oui. Nous dirons simplement s'il est tenable.", "Qui paie les honoraires ?|Le vendeur, sauf accord contraire écrit.", "Combien de temps pour vendre ?|38 jours en moyenne chez nous, en 2025."], meta: "05 56 00 00 00 — nous répondons toujours" }],
  ["progression", "carre", "vif", "Immobilier & services", "Avancement de dossier", { sur: "Votre dossier", titre: "Compromis\nsigné", gros: "75", sous: "Il reste le délai de rétractation, le prêt, puis l'acte définitif.", meta: "PROCHAINE ÉTAPE : OFFRE DE PRÊT" }],
  ["stats", "large", "tech", "Immobilier & services", "Bilan de l'agence", { sur: "Année 2025", titre: "Ce que ça\ndonne en chiffres", items: ["42|biens vendus", "38 j|délai moyen", "97 %|du prix affiché"], meta: "Chiffres vérifiables sur demande" }],

  /* ══════════ Santé & cabinet ══════════ */

  ["horaires", "a4", "froid", "Santé & cabinet", "Horaires de cabinet", { sur: "Cabinet médical", titre: "Horaires\nde consultation", items: ["Lundi|8 h 30 – 12 h · 14 h – 18 h", "Mardi|8 h 30 – 12 h", "Mercredi|8 h 30 – 12 h · 14 h – 19 h", "Jeudi|8 h 30 – 12 h · 14 h – 18 h", "Vendredi|8 h 30 – 12 h · 14 h – 17 h", "Samedi|Urgences uniquement"], meta: "PRISE DE RENDEZ-VOUS EN LIGNE OU AU 05 56 00 00 00" }],
  ["contact", "a5", "clair", "Santé & cabinet", "Coordonnées du cabinet", { sur: "Cabinet", titre: "Nous\ncontacter", sous: "Secrétariat ouvert de 8 h 30 à 17 h.", items: ["05 56 00 00 00", "Prise de rendez-vous en ligne", "12 rue du Marché, Bordeaux", "Accès de plain-pied, PMR"], meta: "En cas d'urgence vitale, appelez le 15" }],
  ["avantages", "a4", "froid", "Santé & cabinet", "Informations patients", { titre: "Trois choses\nà savoir", sous: "Elles évitent les rendez-vous perdus.", items: ["Annulation|Prévenez 24 h avant, le créneau profite à quelqu'un d'autre.", "Documents|Apportez carte Vitale, mutuelle et ordonnances en cours.", "Retard|Au-delà de 15 minutes, la consultation peut être reportée."], meta: "Merci de votre compréhension" }],
  ["checklist", "a5", "clair", "Santé & cabinet", "Avant votre consultation", { sur: "Préparer sa venue", titre: "À apporter", items: ["Carte Vitale à jour", "Carte de mutuelle", "Ordonnances en cours", "Résultats d'analyses récents", "Carnet de vaccination", "Liste des questions à poser"], meta: "Cela fait gagner cinq minutes, autant de temps pour vous écouter" }],
  ["etapes", "a4", "froid", "Santé & cabinet", "Parcours de soin", { titre: "Comment se\ndéroule le suivi", sous: "Quatre rendez-vous sur six mois.", items: ["Bilan initial|Une heure, examen complet et antécédents.", "Mise en place|Traitement expliqué, effets attendus détaillés.", "Contrôle à 6 semaines|Ajustement si nécessaire.", "Suivi à 6 mois|Bilan, puis rythme annuel."] }],
  ["faq", "a4", "clair", "Santé & cabinet", "Questions fréquentes patients", { sur: "Vous demandez souvent", titre: "Quatre réponses\nutiles", items: ["Le cabinet est-il conventionné ?|Secteur 1, tarifs de la Sécurité sociale.", "Faut-il une ordonnance ?|Non pour une première consultation.", "Le tiers payant est-il pratiqué ?|Oui, sur la part obligatoire.", "Comment obtenir un certificat ?|Il se délivre en consultation, jamais par téléphone."], meta: "Autres questions au secrétariat" }],
  ["tableau", "a4", "clair", "Santé & cabinet", "Tarifs des consultations", { titre: "Tarifs\naffichés", sous: "Conformément à l'article R.1111-21 du code de la santé publique.", sur: "ACTE|TARIF", items: ["Consultation|26,50 €", "Visite à domicile|36,50 €", "Consultation complexe|46,00 €", "Certificat sportif|26,50 €", "Vaccination|26,50 €", "Majoration nuit|+ 42,00 €"], meta: "Cabinet conventionné secteur 1 — carte Vitale acceptée" }],
  ["cadre", "a4", "clair", "Santé & cabinet", "Affichage réglementaire", { sur: "Information", titre: "Cabinet\nconventionné\nsecteur 1", sous: "Les honoraires sont ceux fixés par l'Assurance maladie. Aucun dépassement n'est pratiqué.", meta: "MISE À JOUR : JANVIER 2026" }],
  ["ruban", "a5", "chaud", "Santé & cabinet", "Fermeture du cabinet", { sur: "Information", titre: "FERMÉ", sous: "Le cabinet est fermé du 3 au 17 août. Continuité assurée par le Dr Roux, 05 56 00 00 01.", meta: "URGENCES : COMPOSEZ LE 15" }],
  ["equipe", "a4", "clair", "Santé & cabinet", "L'équipe du cabinet", { titre: "L'équipe\ndu cabinet", sous: "Une maison de santé pluriprofessionnelle.", items: ["Dr Bernard|Médecin généraliste", "Dr Vidal|Médecin généraliste", "Aline|Infirmière", "Noé|Secrétariat"] }],
  ["organique", "a4", "nature", "Santé & cabinet", "Prévention", { sur: "Prévention", titre: "Bouger\nvingt minutes\npar jour", sous: "Marcher compte. Monter les escaliers compte. Le vélo pour aller travailler compte.", cta: "Parlons-en en consultation" }],
  ["liste", "a4", "froid", "Santé & cabinet", "Conseils de prévention", { sur: "Prévention", titre: "Cinq gestes\nqui changent\nvraiment quelque chose", items: ["Dormir sept heures, à heures régulières", "Marcher trente minutes par jour", "Limiter l'alcool à dix verres par semaine", "Faire contrôler sa tension une fois par an", "Consulter dès qu'un symptôme dure trois semaines"], meta: "Aucune de ces recommandations ne coûte d'argent" }],
  ["chiffre", "carre", "froid", "Santé & cabinet", "Rappel de dépistage", { sur: "Dépistage", gros: "50", titre: "ans : le dépistage devient systématique", sous: "Un courrier vous parvient tous les deux ans. Ne le laissez pas de côté.", cta: "Parlons-en au cabinet" }],
  ["calendrier", "a5", "froid", "Santé & cabinet", "Campagne de vaccination", { sur: "OCTOBRE 2026", gros: "01", titre: "Vaccination\ngrippe", items: ["Sans rendez-vous les mercredis", "De 14 h à 18 h, jusqu'au 30 novembre", "Apportez votre bon de prise en charge", "Gratuite pour les plus de 65 ans"] }],
  ["contact", "carte", "clair", "Santé & cabinet", "Carte de rendez-vous", { sur: "Prochain rendez-vous", titre: "Cabinet\nmédical\ndu Marché", sous: "Prévenez 24 h à l'avance en cas d'empêchement.", items: ["Date : ____ / ____ / ______", "Heure : ______ h ______", "Praticien : ______________", "05 56 00 00 00"], meta: "12 rue du Marché, 33000 Bordeaux" }],
  ["visite", "carte", "froid", "Santé & cabinet", "Carte praticien", { gros: "SB", titre: "Dr Sofia Bernard", sur: "MÉDECIN GÉNÉRALISTE", sous: "12 rue du Marché, Bordeaux · 05 56 00 00 00 · RPPS 10000000000" }],
  ["recrute", "a4", "froid", "Santé & cabinet", "Recherche de remplaçant", { sur: "RECHERCHE", titre: "Médecin\nremplaçant", sous: "Du 3 au 17 août 2026 — maison de santé, Bordeaux", items: ["Patientèle stable, logiciel Weda", "Secrétariat sur place", "Rétrocession 80 %"], meta: "Contact : cabinet@exemple.fr" }],

  /* ══════════ Artisanat & bâtiment ══════════ */

  ["panneau", "a4", "chaud", "Artisanat & bâtiment", "Plaquette artisan", { gros: "20", sur: "Depuis 2006", titre: "Menuiserie\nBerthier", sous: "Escaliers, parquets, agencement sur mesure. Vingt ans de chantiers dans la région, et pas un abandonné.", meta: "Devis gratuit — 06 00 00 00 00" }],
  ["cartes", "a4", "terre", "Artisanat & bâtiment", "Trois métiers", { titre: "Ce que\nnous faisons", sous: "Trois activités, un seul atelier.", items: ["Menuiserie|Escaliers, portes, fenêtres bois.", "Agencement|Cuisines, dressings, bibliothèques.", "Restauration|Bâti ancien, à l'identique."] }],
  ["tableau", "a4", "clair", "Artisanat & bâtiment", "Tarifs indicatifs", { titre: "Tarifs\nindicatifs", sous: "Fourniture et pose, TVA 10 % pour la rénovation.", sur: "PRESTATION|À PARTIR DE", items: ["Déplacement et devis|Gratuit", "Pose de parquet|48 € / m²", "Escalier droit sur mesure|3 200 €", "Placard sur mesure|750 € / ml", "Porte intérieure posée|420 €", "Volet battant bois|380 € / unité"], meta: "Devis ferme après visite — validité 3 mois" }],
  ["etapes", "a4", "froid", "Artisanat & bâtiment", "Déroulé de chantier", { titre: "Un chantier,\nquatre temps", sous: "Vous savez toujours où vous en êtes.", items: ["Visite|Relevé de cotes, sur place, gratuit.", "Devis|Écrit et détaillé sous huit jours.", "Fabrication|En atelier, deux à six semaines.", "Pose|Date fixée d'avance, tenue."] }],
  ["avantages", "a4", "terre", "Artisanat & bâtiment", "Nos garanties", { titre: "Trois garanties\nsérieuses", sous: "Attestations disponibles avant signature.", items: ["Décennale|Assurance à jour, attestation fournie.", "Devis ferme|Aucun supplément sans avenant signé.", "Atelier local|Fabrication à Bordeaux, pas d'import."], meta: "SIRET et assurances communiqués sur simple demande" }],
  ["avantapres", "a4", "froid", "Artisanat & bâtiment", "Chantier avant/après", { titre: "Une cuisine,\ntrois semaines", sur: "AVANT", cta: "APRÈS", items: ["Meubles d'origine 1985, plan stratifié gonflé, aucun rangement en hauteur.", "Façades chêne massif, plan en granit, tout rangé jusqu'au plafond."], sous: "Budget : 14 200 € TTC, pose comprise, sans dépassement.", meta: "Chantier réalisé en mars 2026 à Talence" }],
  ["grille", "a4", "terre", "Artisanat & bâtiment", "Réalisations", { titre: "Six chantiers\nrécents", sous: "Photos disponibles sur demande", items: ["Escalier chêne", "Cuisine sur mesure", "Bibliothèque", "Parquet massif", "Volets bois", "Verrière atelier"], meta: "Références et coordonnées de clients communiquées volontiers" }],
  ["visite", "carte", "terre", "Artisanat & bâtiment", "Carte de visite artisan", { gros: "MB", titre: "Menuiserie Berthier", sur: "MENUISIER — AGENCEUR", sous: "06 00 00 00 00 · contact@menuiserie-berthier.fr · Bordeaux" }],
  ["contact", "carte", "clair", "Artisanat & bâtiment", "Carte contact chantier", { sur: "Un projet ?", titre: "Devis\ngratuit", sous: "Déplacement offert dans un rayon de 40 km.", items: ["06 00 00 00 00", "contact@exemple.fr", "Atelier : 4 rue des Forges", "SIRET 000 000 000 00000"], meta: "Assurance décennale AXA n° 0000000" }],
  ["entete", "a4", "clair", "Artisanat & bâtiment", "Papier à en-tête devis", { titre: "Menuiserie Berthier", sur: "Menuisier — agenceur", sous: "4 rue des Forges\n33000 Bordeaux\n06 00 00 00 00", meta: "DEVIS N° 2026-0184", items: ["Client : ____________________", "Adresse du chantier : ____________________", "Date de visite : ____ / ____ / ______", "Validité de l'offre : 3 mois", "", "Détail des prestations :"], cta: "SIRET 000 000 000 00000 — TVA FR00000000000 — décennale AXA n° 0000000" }],
  ["notation", "large", "clair", "Artisanat & bâtiment", "Avis client artisan", { gros: "4,9", sur: "sur 94 avis", titre: "Devis respecté au centime, chantier fini avec deux jours d'avance, et le chantier nettoyé chaque soir.", auteur: "Marc T., Talence", meta: "Avis Google — avril 2026" }],
  ["recrute", "a4", "froid", "Artisanat & bâtiment", "Recherche apprenti menuisier", { sur: "NOUS RECRUTONS", titre: "Un apprenti\nmenuisier", sous: "Rentrée septembre 2026 — CAP ou BP — Bordeaux", items: ["Atelier équipé, machines récentes", "Un tuteur dédié, pas un tuteur sur le papier", "Embauche envisagée à la fin du contrat"], meta: "CV à contact@menuiserie-berthier.fr" }],
  ["horaires", "a5", "terre", "Artisanat & bâtiment", "Horaires d'atelier", { sur: "Atelier", titre: "Horaires", items: ["Lundi – jeudi|7 h 30 – 12 h · 13 h – 17 h 30", "Vendredi|7 h 30 – 12 h · 13 h – 16 h", "Samedi|Sur rendez-vous", "Dimanche|Fermé"], meta: "VISITES D'ATELIER BIENVENUES, PRÉVENEZ AVANT" }],
  ["checklist", "a4", "clair", "Artisanat & bâtiment", "Avant les travaux", { sur: "Préparer son chantier", titre: "Ce qu'il faut\nprévoir", items: ["Vider la pièce, meubles compris", "Prévoir un accès pour le véhicule", "Couper l'eau ou l'électricité si demandé", "Prévenir les voisins de la durée", "Prévoir une prise et un point d'eau", "Garder les animaux à l'écart", "Être joignable pendant le chantier"], meta: "Un chantier préparé, c'est deux jours gagnés" }],
  ["faq", "a4", "clair", "Artisanat & bâtiment", "Questions travaux", { sur: "Avant de signer", titre: "Quatre questions\nà nous poser", items: ["Le devis peut-il évoluer ?|Seulement par avenant écrit et signé par vous.", "Quels délais ?|Deux à six semaines de fabrication, pose datée à la signature.", "Quelle TVA ?|10 % en rénovation de plus de deux ans, 20 % sinon.", "Et après la pose ?|Décennale dix ans, et on revient si ça bouge."], meta: "Posez-les à tous vos artisans, pas seulement à nous" }],
  ["stats", "large", "tech", "Artisanat & bâtiment", "Chiffres de l'atelier", { sur: "Bilan 2025", titre: "Une année\nd'atelier", items: ["68|chantiers livrés", "97 %|dans les délais", "0|litige"], meta: "Références consultables sur demande" }],
  ["ecusson", "logo", "terre", "Artisanat & bâtiment", "Emblème d'atelier", { gros: "MB", meta: "DEPUIS 2006", titre: "Menuiserie Berthier", sous: "Le bois, correctement" }],
  ["typo", "bandeau", "sombre", "Artisanat & bâtiment", "Bâche de chantier", { titre: "ICI TRAVAILLE\nLA MENUISERIE\nBERTHIER", sous: "Escaliers, agencement, restauration du bâti ancien.", meta: "06 00 00 00 00 — menuiserie-berthier.fr" }],
  ["banniere", "bandeau", "chaud", "Artisanat & bâtiment", "Panneau de chantier", { gros: "🔨", titre: "Chantier en cours, merci de votre patience", sous: "Fin des travaux prévue le 30 juin. Accès piéton maintenu.", cta: "Menuiserie Berthier — 06 00 00 00 00" }],

  /* ══════════ Auto & mobilité ══════════ */

  ["tableau", "a4", "clair", "Auto & mobilité", "Tarifs de garage", { titre: "Nos tarifs\nd'atelier", sous: "Prix TTC, pièces d'origine ou équivalentes.", sur: "PRESTATION|TARIF", items: ["Diagnostic électronique|45 €", "Vidange et filtres|89 €", "Plaquettes avant, pose comprise|140 €", "Distribution complète|dès 590 €", "Climatisation, recharge|75 €", "Passage au contrôle technique|Offert si révision"], meta: "Devis obligatoire au-delà de 150 € — pièces conservées à votre demande" }],
  ["etapes", "a4", "froid", "Auto & mobilité", "Déroulé d'une révision", { titre: "Une révision,\nquatre temps", sous: "Vous repartez en connaissant l'état réel du véhicule.", items: ["Accueil|Dix minutes, on note ce que vous constatez.", "Diagnostic|Contrôle en 42 points, écrit.", "Validation|On vous appelle avant toute intervention.", "Restitution|Facture détaillée, pièces montrées."] }],
  ["horaires", "a5", "sombre", "Auto & mobilité", "Horaires du garage", { sur: "Garage", titre: "Horaires", items: ["Lundi – vendredi|8 h – 12 h · 14 h – 18 h 30", "Samedi|8 h – 12 h", "Dimanche|Fermé", "Dépôt de véhicule|Dès 7 h 30"], meta: "VÉHICULE DE PRÊT SUR RÉSERVATION" }],
  ["promo", "carre", "vif", "Auto & mobilité", "Offre révision", { sur: "Offre de printemps", titre: "Révision\ncomplète", gros: "129 €", items: ["189 €"], sous: "Vidange, filtres, contrôle 42 points, jusqu'au 30 avril.", meta: "SUR RENDEZ-VOUS UNIQUEMENT" }],
  ["fiche", "a4", "clair", "Auto & mobilité", "Fiche véhicule d'occasion", { titre: "Berline 2019,\n86 000 km", meta: "Diesel — boîte manuelle — 14 900 €", sur: "POINTS FORTS", sous: "À SAVOIR", items: ["Carnet d'entretien complet", "Distribution faite à 80 000 km", "Deux jeux de pneus fournis", "Rayure sur l'aile arrière droite", "Pneus avant à changer sous 10 000 km", "Contrôle technique de moins d'un mois"] }],
  ["checklist", "a5", "clair", "Auto & mobilité", "Avant le contrôle technique", { sur: "Contrôle technique", titre: "Vérifiez\nces six points", items: ["Toutes les ampoules, y compris la plaque", "Niveau de liquide lave-glace", "Usure et pression des pneus", "Essuie-glaces en bon état", "Aucun voyant allumé au tableau de bord", "Carte grise dans le véhicule"], meta: "Six minutes de vérification évitent une contre-visite" }],
  ["faq", "a4", "clair", "Auto & mobilité", "Questions de garage", { sur: "Vous demandez", titre: "Quatre réponses\nsans détour", items: ["Puis-je fournir mes pièces ?|Oui, mais la garantie ne couvre alors que la main-d'œuvre.", "Un véhicule de prêt ?|Gratuit dès deux heures d'immobilisation, sur réservation.", "Combien de temps pour un devis ?|Le jour même, après diagnostic.", "Gardez-vous les pièces changées ?|Oui, si vous le demandez à l'accueil."], meta: "05 56 00 00 00" }],
  ["avantages", "large", "froid", "Auto & mobilité", "Trois engagements garage", { titre: "Trois choses\nqu'on tient", sous: "Depuis l'ouverture, sans exception.", items: ["Aucun travail non validé|On appelle avant, toujours.", "Devis écrit|Au-delà de 150 €, systématiquement.", "Pièces conservées|Sur simple demande, dans un carton à votre nom."], meta: "Garage indépendant, agréé toutes marques" }],
  ["notation", "carre", "clair", "Auto & mobilité", "Avis garage", { gros: "4,8", sur: "sur 340 avis", titre: "Devis annoncé à 480 €, facture à 462 €. Ils m'ont montré les pièces changées sans que je demande.", auteur: "Aline R.", meta: "Avis Google — mars 2026" }],
  ["visite", "carte", "sombre", "Auto & mobilité", "Carte de visite garage", { gros: "GD", titre: "Garage Dupont", sur: "MÉCANIQUE — CARROSSERIE", sous: "4 avenue de la Gare, Bordeaux · 05 56 00 00 00" }],
  ["contact", "carte", "clair", "Auto & mobilité", "Carte de rendez-vous atelier", { sur: "Prochain entretien", titre: "Garage\nDupont", sous: "Prévenez 48 h avant en cas d'empêchement.", items: ["Date : ____ / ____ / ______", "Kilométrage prévu : ____________", "Véhicule : ____________________", "05 56 00 00 00"], meta: "Véhicule de prêt sur réservation" }],
  ["chrono", "large", "tech", "Auto & mobilité", "Entretien par kilométrage", { titre: "Quand\nfaire quoi", sous: "Repères valables pour la plupart des motorisations.", items: ["15 000|Vidange et filtre à huile.", "40 000|Filtres air et habitacle.", "80 000|Distribution et pompe à eau.", "120 000|Embrayage, selon usage."], meta: "Se référer au carnet constructeur en cas de doute" }],
  ["progression", "carre", "froid", "Auto & mobilité", "Suivi de réparation", { sur: "Votre véhicule", titre: "Réparation\nen cours", gros: "60", sous: "Pièces reçues, montage en cours, restitution prévue demain 16 h.", meta: "NOUS VOUS APPELONS AVANT" }],
  ["recrute", "a4", "froid", "Auto & mobilité", "Recherche mécanicien", { sur: "NOUS RECRUTONS", titre: "Mécanicien\nautomobile", sous: "CDI 39 h — Bordeaux — expérience 2 ans minimum", items: ["Atelier six ponts, outillage récent", "Formation constructeur prise en charge", "Samedi travaillé une fois sur trois"], meta: "CV à emploi@garagedupont.fr" }],
  ["banniere", "bandeau", "vif", "Auto & mobilité", "Bandeau de garage", { gros: "42", titre: "Un contrôle en 42 points, offert à chaque passage", sous: "Écrit, remis en main propre, sans obligation de faire les travaux.", cta: "Garage Dupont — 05 56 00 00 00" }],
  ["etiquette", "etiq", "sombre", "Auto & mobilité", "Étiquette prix véhicule", { sur: "OCCASION GARANTIE", gros: "14 900 €", titre: "Berline 2019,\n86 000 km, diesel", sous: "Garantie 12 mois pièces et main-d'œuvre.", meta: "CT DE MOINS D'UN MOIS" }],

];
