// Modèles — commerces de proximité et services aux particuliers.
//
// Fleuriste, opticien, auto-école, pressing, aide à domicile, hôtellerie…
// Ces métiers ont peu de temps pour communiquer et beaucoup de choses à
// afficher : des prix, des horaires, des règles. Les compositions retenues
// sont donc celles qui portent de l'information, pas seulement une image.

import type { Row } from "./design-templates";

export const ROWS_SERVICES2: Row[] = [

  /* ══════════ Restauration & café — commerces de bouche ══════════ */

  ["menu", "menuc", "chaud", "Restauration & café", "Carte de boulangerie", { sur: "Boulangerie", titre: "Nos pains", items: ["Tradition, 250 g|1,20", "Pain de campagne, 500 g|3,40", "Pain complet au levain, 500 g|3,80", "Seigle et noix, 400 g|4,20", "Petit épeautre, 500 g|4,50", "Baguette viennoise|1,60", "Pain de mie maison, tranché|4,00"], meta: "Cuisson toutes les deux heures — dernière fournée à 17 h" }],
  ["menu", "menuc", "pastel", "Restauration & café", "Carte de pâtisserie", { sur: "Pâtisserie", titre: "Nos gâteaux", items: ["Tarte au citron meringuée|4,50", "Paris-Brest|5,20", "Éclair au chocolat|3,80", "Saint-honoré, la part|5,50", "Flan vanille bourbon|3,50", "Entremets 6 personnes, sur commande|28,00"], meta: "Commandes 48 h à l'avance pour les entremets — 05 56 00 00 00" }],
  ["menu", "a4", "sombre", "Restauration & café", "Carte de food truck", { sur: "Ce midi", titre: "À la carte", items: ["Burger maison, frites fraîches|12", "Végétarien, galette de pois chiches|11", "Croque au comté, salade|9", "Frites seules|4", "Cookie maison|2,50", "Limonade artisanale|3"], meta: "Place du Marché le mardi et le jeudi, 11 h 30 à 14 h" }],
  ["horaires", "a5", "chaud", "Restauration & café", "Tournée du food truck", { sur: "Notre tournée", titre: "Où nous\ntrouver", items: ["Lundi|Zone des Forges, 11 h 30", "Mardi|Place du Marché, 11 h 30", "Mercredi|Repos", "Jeudi|Place du Marché, 11 h 30", "Vendredi|Parc d'activités, 11 h 30", "Samedi|Marché du Port, 9 h"], meta: "SUIVEZ NOS DÉPLACEMENTS SUR LA PAGE DU CAMION" }],
  ["tableau", "a4", "clair", "Restauration & café", "Tarifs traiteur", { titre: "Tarifs\ntraiteur", sous: "Par personne, à partir de vingt convives.", sur: "FORMULE|PRIX PAR PERSONNE", items: ["Cocktail, 8 pièces|14 €", "Cocktail dînatoire, 14 pièces|24 €", "Buffet froid|28 €", "Repas servi à table|42 €", "Service (2 personnes, 5 h)|380 €", "Location vaisselle|3 € / couvert"], meta: "Devis ferme après échange — acompte de 30 % à la réservation" }],
  ["etapes", "a4", "froid", "Restauration & café", "Commander un traiteur", { titre: "Commander\nen quatre étapes", sous: "Comptez trois semaines avant l'événement.", items: ["Nous appeler|Vingt minutes pour cadrer le format.", "Le devis|Écrit sous 48 h, menus proposés.", "La dégustation|Offerte à partir de cinquante convives.", "Le jour J|Livraison, installation, reprise du matériel."] }],
  ["etiquette", "etiq", "chaud", "Restauration & café", "Étiquette de pain", { sur: "CUIT CE MATIN", gros: "3,40 €", titre: "Pain de campagne,\n500 g", sous: "Farine T80 du moulin de Cadillac, levain naturel.", meta: "SE CONSERVE 4 JOURS DANS UN LINGE" }],
  ["avantages", "large", "terre", "Restauration & café", "Trois engagements boulangerie", { titre: "Trois choses\nqu'on ne fait\npas", sous: "Depuis 1998, sans exception.", items: ["Aucun surgelé|Tout est pétri et cuit ici, chaque matin.", "Aucun améliorant|Farine, eau, sel, levain. C'est tout.", "Aucune vente de la veille|Les invendus partent à l'association."], meta: "Visite du fournil possible le samedi matin" }],

  /* ══════════ Commerce & promotion — commerces spécialisés ══════════ */

  ["menu", "a4", "pastel", "Commerce & promotion", "Tarifs de fleuriste", { sur: "Compositions", titre: "Nos bouquets", items: ["Petit bouquet du marché|15", "Bouquet rond, fleurs de saison|25", "Grand bouquet, sur mesure|40", "Composition en coupe|35", "Deuil, coussin ou raquette|dès 60", "Abonnement mensuel, 4 bouquets|80"], meta: "Livraison offerte à Bordeaux dès 30 € — commandes au 05 56 00 00 00" }],
  ["arche", "carre", "pastel", "Commerce & promotion", "Annonce de fleuriste", { sur: "Arrivage", titre: "Les pivoines\nsont là", sous: "Trois semaines, pas plus. Après, il faudra attendre un an.", meta: "EN BOUTIQUE DU MARDI AU DIMANCHE" }],
  ["tableau", "a4", "clair", "Commerce & promotion", "Tarifs d'opticien", { titre: "Nos tarifs", sous: "Prix TTC, verres et monture, avant remboursement.", sur: "PRESTATION|TARIF", items: ["Examen de vue|Offert", "Monture, entrée de gamme|dès 49 €", "Verres unifocaux, la paire|dès 90 €", "Verres progressifs, la paire|dès 290 €", "Traitement antireflet|Inclus", "Adaptation lentilles|45 €"], meta: "Tiers payant pratiqué — devis normalisé remis systématiquement" }],
  ["faq", "a4", "clair", "Commerce & promotion", "Questions d'opticien", { sur: "Vous demandez", titre: "Quatre réponses\nutiles", items: ["L'ordonnance est-elle obligatoire ?|Oui pour un premier équipement, sinon valable 5 ans.", "Le tiers payant ?|Pratiqué avec la plupart des mutuelles.", "Combien de temps d'attente ?|Cinq à huit jours ouvrés selon les verres.", "Et si je ne m'adapte pas ?|Adaptation reprise gratuitement sous 30 jours."], meta: "05 56 00 00 00 — sans rendez-vous du mardi au samedi" }],
  ["tableau", "a4", "clair", "Commerce & promotion", "Tarifs de pressing", { titre: "Nos tarifs", sous: "Prix TTC, délai standard de 48 heures.", sur: "ARTICLE|TARIF", items: ["Chemise|3,50 €", "Pantalon|7,00 €", "Veste|9,50 €", "Costume 2 pièces|16,00 €", "Robe|dès 12,00 €", "Couette 2 personnes|24,00 €", "Express (24 h)|+ 50 %"], meta: "Retouches assurées sur place — devis avant toute intervention" }],
  ["horaires", "a5", "clair", "Commerce & promotion", "Horaires de pressing", { sur: "Pressing", titre: "Horaires", items: ["Lundi|Fermé", "Mardi – vendredi|8 h – 19 h", "Samedi|8 h – 13 h", "Dimanche|Fermé", "Dépôt|Jusqu'à 30 min avant fermeture"], meta: "ARTICLES NON RETIRÉS SOUS 3 MOIS : NOUS CONTACTER" }],
  ["tableau", "a4", "terre", "Commerce & promotion", "Tarifs de cordonnerie", { titre: "Cordonnerie\net clés", sous: "Prix TTC, travail réalisé sur place.", sur: "PRESTATION|TARIF", items: ["Ressemelage cuir|dès 45 €", "Talons, la paire|18 €", "Fermeture éclair de botte|32 €", "Reproduction de clé plate|6 €", "Clé de sécurité|dès 25 €", "Gravure de médaille|8 €"], meta: "Réparation en 24 à 72 h selon la prestation" }],
  ["menu", "menuc", "chic", "Commerce & promotion", "Carte de librairie", { sur: "Nos coups de cœur", titre: "Ce mois-ci", items: ["Le roman de la rentrée, 320 p.|21", "Un premier roman remarquable|18", "L'essai qu'on n'attendait pas|22", "La bande dessinée du mois|24", "Le jeunesse dès 8 ans|12", "Le poche à emporter|8"], meta: "Commandes en 24 h pour tout ouvrage disponible — 05 56 00 00 00" }],
  ["evenement", "a3", "chic", "Commerce & promotion", "Rencontre en librairie", { sur: "Rencontre", titre: "Lecture\net dédicace", meta: "SAMEDI 14 MARS — 18 H", sous: "Librairie du Port, 8 quai Vauban", cta: "Entrée libre — réservation conseillée au 05 56 00 00 00" }],
  ["etiquette", "carteV", "chic", "Commerce & promotion", "Étiquette de bijouterie", { sur: "PIÈCE UNIQUE", gros: "340 €", titre: "Bague argent massif,\npierre de lune", sous: "Réalisée à l'atelier, gravure offerte.", meta: "GARANTIE À VIE SUR LE SERTISSAGE" }],
  ["avantages", "large", "chic", "Commerce & promotion", "Garanties bijouterie", { titre: "Trois garanties\nà vie", sous: "Sur toute pièce achetée chez nous.", items: ["Sertissage|Repris gratuitement, sans limite de temps.", "Polissage|Une fois par an, offert.", "Mise à taille|Deux tailles en plus ou en moins, offertes."], meta: "Atelier sur place — réparations également acceptées hors achat" }],

  /* ══════════ Immobilier & services — services à domicile ══════════ */

  ["tableau", "a4", "clair", "Immobilier & services", "Tarifs d'aide à domicile", { titre: "Nos tarifs", sous: "Prix TTC avant crédit d'impôt de 50 %.", sur: "PRESTATION|TARIF HORAIRE", items: ["Ménage et repassage|26 €", "Aide aux courses|26 €", "Garde d'enfants +3 ans|24 €", "Accompagnement véhiculé|28 €", "Dimanche et fériés|+ 25 %", "Après crédit d'impôt|dès 12 €"], meta: "Organisme agréé — attestation fiscale délivrée chaque janvier" }],
  ["etapes", "a4", "froid", "Immobilier & services", "Mettre en place une aide", { titre: "Mettre en place\nune intervention", sous: "Comptez une semaine du premier appel à la première visite.", items: ["Le premier appel|Vingt minutes pour comprendre le besoin.", "La visite|À domicile, gratuite, sans engagement.", "Le devis|Écrit, avec le crédit d'impôt calculé.", "La mise en place|Toujours la même personne, présentée avant."] }],
  ["avantages", "large", "froid", "Immobilier & services", "Engagements du service à domicile", { titre: "Trois engagements", sous: "Écrits dans chaque contrat.", items: ["La même personne|Un intervenant référent, un remplaçant connu.", "Aucun engagement|Résiliation avec un préavis de deux semaines.", "Salariés déclarés|Aucun statut précaire, aucune sous-traitance."], meta: "Organisme agréé par la préfecture — n° SAP 000000000" }],
  ["tableau", "a4", "clair", "Immobilier & services", "Tarifs de déménagement", { titre: "Tarifs\nindicatifs", sous: "Devis ferme après visite ou visio.", sur: "PRESTATION|À PARTIR DE", items: ["Studio, même ville|390 €", "T2, même ville|590 €", "T3, même ville|850 €", "Longue distance|Sur devis", "Emballage complet|+ 40 %", "Garde-meuble, le m³/mois|18 €"], meta: "Assurance dommages incluse jusqu'à 30 000 € — options au-delà" }],
  ["checklist", "a4", "clair", "Immobilier & services", "Check-list de déménagement", { sur: "J-30", titre: "Ce qu'il faut\navoir fait", items: ["Donner le préavis au propriétaire", "Réserver le camion et l'ascenseur", "Résilier internet, gaz, électricité", "Faire suivre le courrier", "Prévenir l'école et les assurances", "Trier une pièce par week-end", "Préparer un carton « première nuit »"], meta: "Ce qui n'est pas fait à J-30 se fera dans la panique à J-3" }],
  ["tableau", "a4", "clair", "Immobilier & services", "Tarifs de nettoyage", { titre: "Nettoyage\nprofessionnel", sous: "Prix HT, matériel et produits fournis.", sur: "PRESTATION|TARIF", items: ["Bureaux, le m²/mois|1,80 €", "Vitrerie, le m²|2,40 €", "Remise en état après travaux|dès 6 €/m²", "Fin de bail, T3|280 €", "Copropriété, forfait mensuel|Sur devis", "Intervention ponctuelle|38 €/heure"], meta: "Personnel salarié, formé et assuré — devis gratuit sous 48 h" }],
  ["contact", "carte", "clair", "Immobilier & services", "Carte de dépannage", { sur: "Urgence 7j/7", titre: "Dépannage\nà toute heure", sous: "Intervention sous deux heures dans la métropole.", items: ["06 00 00 00 00", "Serrurerie, plomberie, électricité", "Devis avant intervention", "Facture détaillée systématique"], meta: "Aucun déplacement facturé sans devis accepté" }],
  ["cadre", "a5", "clair", "Immobilier & services", "Affichage de tarifs de dépannage", { sur: "Affichage obligatoire", titre: "Tarifs\nde dépannage", sous: "Déplacement 45 € · main-d'œuvre 55 €/h en journée, 90 €/h la nuit et les jours fériés · devis obligatoire au-delà de 150 €.", meta: "ARRÊTÉ DU 24 JANVIER 2017 — TARIFS TTC" }],

  /* ══════════ Santé & cabinet — paramédical ══════════ */

  ["tableau", "a4", "clair", "Santé & cabinet", "Tarifs de kinésithérapie", { titre: "Tarifs\nconventionnés", sous: "Cabinet conventionné secteur 1, tiers payant pratiqué.", sur: "ACTE|TARIF", items: ["Séance de rééducation|16,13 €", "Bilan initial|Inclus", "Séance à domicile|+ 4,00 €", "Rééducation respiratoire|Sur prescription", "Séance non décommandée|16,13 €", "Dépassement|Aucun"], meta: "Annulation gratuite jusqu'à 24 h avant la séance" }],
  ["horaires", "a5", "froid", "Santé & cabinet", "Horaires de cabinet paramédical", { sur: "Cabinet", titre: "Horaires", items: ["Lundi – jeudi|7 h 30 – 19 h 30", "Vendredi|7 h 30 – 18 h", "Samedi|8 h – 12 h", "Dimanche|Fermé", "Domicile|Après 17 h sur demande"], meta: "PRISE DE RENDEZ-VOUS EN LIGNE OU AU 05 56 00 00 00" }],
  ["cadre", "a5", "clair", "Santé & cabinet", "Règle d'annulation", { sur: "Information", titre: "Annulation\nsous 24 heures", sous: "Toute séance non décommandée au moins vingt-quatre heures à l'avance est due. Le créneau libéré profite à un autre patient.", meta: "MERCI DE VOTRE COMPRÉHENSION" }],
  ["liste", "a4", "froid", "Santé & cabinet", "Conseils après séance", { sur: "Après la séance", titre: "Cinq consignes\nà respecter", items: ["Boire un grand verre d'eau en sortant", "Éviter tout effort intense pendant six heures", "Appliquer du froid si une douleur apparaît", "Refaire les exercices deux fois par jour", "Signaler toute douleur inhabituelle"], meta: "En cas de doute, appelez plutôt que d'attendre la prochaine séance" }],
  ["etapes", "a4", "nature", "Santé & cabinet", "Parcours diététique", { titre: "Un suivi\nen quatre temps", sous: "Trois mois, quatre rendez-vous, aucun régime.", items: ["Bilan|Une heure : habitudes, antécédents, objectifs.", "Plan|Adapté à vos horaires, pas à un modèle.", "Ajustement|À trois semaines, sur vos retours.", "Suivi|À trois mois, puis à la demande."] }],
  ["tableau", "a4", "clair", "Santé & cabinet", "Tarifs de pharmacie et services", { titre: "Nos services", sous: "Services proposés sans rendez-vous.", sur: "SERVICE|CONDITIONS", items: ["Vaccination grippe|Sans RDV, dès 65 ans", "Test antigénique|Sur RDV, 15 min", "Entretien pharmaceutique|Gratuit, sur RDV", "Location de matériel médical|Sur ordonnance", "Préparation de piluliers|Gratuit", "Livraison à domicile|Sur demande, gratuit"], meta: "Pharmacie de garde : composez le 3237" }],
  ["horaires", "a5", "nature", "Santé & cabinet", "Horaires de pharmacie", { sur: "Pharmacie", titre: "Horaires", items: ["Lundi – vendredi|8 h 30 – 19 h 30", "Samedi|9 h – 19 h", "Dimanche|Fermé", "Jours fériés|Fermé", "Garde|Composez le 3237"], meta: "LIVRAISON À DOMICILE GRATUITE SUR SIMPLE DEMANDE" }],

  /* ══════════ Éducation & association — formation ══════════ */

  ["tableau", "a4", "clair", "Éducation & association", "Tarifs d'auto-école", { titre: "Nos forfaits", sous: "Prix TTC, financement CPF possible.", sur: "FORFAIT|TARIF", items: ["Code en ligne, 6 mois|290 €", "Forfait 20 h de conduite|1 190 €", "Heure supplémentaire|48 €", "Conduite accompagnée|1 390 €", "Présentation à l'examen|Incluse", "Boîte automatique, 13 h|890 €"], meta: "Taux de réussite affiché en agence — aucun frais de dossier caché" }],
  ["etapes", "a4", "froid", "Éducation & association", "Étapes du permis", { titre: "Le permis\nen quatre étapes", sous: "Comptez six à neuf mois selon votre rythme.", items: ["Inscription|Dossier ANTS monté par nos soins.", "Le code|En salle ou en ligne, à votre rythme.", "La conduite|Vingt heures minimum, évaluées.", "L'examen|Présentation dès que le niveau y est."] }],
  ["progression", "carre", "vif", "Éducation & association", "Avancement de formation", { sur: "Votre formation", titre: "Quinze heures\nsur vingt", gros: "75", sous: "Encore cinq heures avant l'évaluation de présentation.", meta: "PROCHAIN CRÉNEAU : MARDI 14 H" }],
  ["tableau", "a4", "clair", "Éducation & association", "Programme de formation professionnelle", { titre: "Programme\nde la formation", sous: "Quatorze heures réparties sur deux journées.", sur: "SÉQUENCE|DURÉE", items: ["Cadre réglementaire|2 h", "Analyse des risques|3 h", "Mise en pratique|4 h", "Étude de cas|3 h", "Évaluation|1 h", "Bilan et questions|1 h"], meta: "Organisme certifié Qualiopi — formation finançable" }],
  ["certificat", "paysage", "chic", "Éducation & association", "Attestation de stage", { sur: "ATTESTATION DE STAGE", titre: "Camille Durand", auteur: "Sofia Bernard, tutrice", sous: "a effectué un stage de huit semaines au sein de notre atelier, du 6 janvier au 28 février 2026.", meta: "BORDEAUX, LE 28 FÉVRIER 2026" }],
  ["faq", "a4", "clair", "Éducation & association", "Questions sur la formation", { sur: "Avant de vous inscrire", titre: "Quatre réponses\npratiques", items: ["Est-ce finançable ?|CPF, OPCO et France Travail, nous montons le dossier.", "Quel niveau requis ?|Aucun prérequis pour cette formation.", "Y a-t-il un examen ?|Une évaluation, pas un examen : rien n'est éliminatoire.", "Et si je dois annuler ?|Report gratuit jusqu'à sept jours avant."], meta: "formation@exemple.fr — 05 56 00 00 00" }],
  ["chiffre", "carre", "tech", "Éducation & association", "Taux de réussite", { sur: "Session 2025", gros: "92 %", titre: "de réussite à l'examen", sous: "Sur 148 candidats présentés, en première présentation.", cta: "Chiffres affichés en agence" }],

  /* ══════════ Voyage & saison — hébergement ══════════ */

  ["tableau", "a4", "clair", "Voyage & saison", "Tarifs de chambres d'hôtes", { titre: "Nos tarifs", sous: "Par nuit, petit-déjeuner compris, pour deux personnes.", sur: "PÉRIODE|CHAMBRE / SUITE", items: ["Novembre – mars|85 € / 120 €", "Avril – juin|105 € / 145 €", "Juillet – août|125 € / 175 €", "Septembre – octobre|105 € / 145 €", "Personne supplémentaire|25 €", "Table d'hôtes, par personne|32 €"], meta: "Taxe de séjour 1,10 € par nuit et par adulte — arrivée dès 16 h" }],
  ["arche", "a5", "chic", "Voyage & saison", "Présentation de maison d'hôtes", { sur: "Chambres d'hôtes", titre: "La maison\nde la Combe", sous: "Quatre chambres dans une maison de 1830, au milieu des vignes.", meta: "SAINT-ÉMILION — 05 57 00 00 00" }],
  ["horaires", "a5", "terre", "Voyage & saison", "Informations de séjour", { sur: "Votre séjour", titre: "Repères\npratiques", items: ["Arrivée|À partir de 16 h", "Départ|Avant 11 h", "Petit-déjeuner|8 h – 10 h", "Table d'hôtes|20 h, sur réservation", "Départ tardif|Sur demande, selon planning"], meta: "WIFI GRATUIT — CODE AFFICHÉ DANS CHAQUE CHAMBRE" }],
  ["faq", "a4", "clair", "Voyage & saison", "Questions des hôtes", { sur: "Avant de réserver", titre: "Quatre réponses\nutiles", items: ["Les animaux sont-ils acceptés ?|Oui, dans deux chambres, 12 € par nuit.", "Y a-t-il un parking ?|Fermé, gratuit, dans la cour.", "Peut-on dîner sur place ?|Table d'hôtes le soir, sur réservation la veille.", "Quelle politique d'annulation ?|Gratuite jusqu'à sept jours avant."], meta: "05 57 00 00 00 — contact@lacombe.fr" }],
  ["checklist", "a5", "clair", "Voyage & saison", "Livret d'accueil", { sur: "Bienvenue", titre: "Quelques\nrepères", items: ["Le code wifi est affiché près de la fenêtre", "Le petit-déjeuner est servi de 8 h à 10 h", "Les vélos sont à disposition dans la grange", "Le village est à douze minutes à pied", "La boulangerie ouvre à 7 h, sauf le lundi", "Merci de laisser les clés sur la commode", "En cas de besoin : 06 00 00 00 00"], meta: "Bon séjour — Sofia et Marc" }],
  ["grille", "pin", "nature", "Voyage & saison", "À faire autour", { titre: "Six choses\nà faire\nautour", sous: "Toutes à moins de trente minutes", items: ["Village médiéval", "Marché du dimanche", "Balade des vignes", "Grotte préhistorique", "Base nautique", "Marché nocturne"], meta: "Itinéraires et horaires détaillés dans le livret d'accueil" }],
  ["etiquette", "etiq", "chic", "Voyage & saison", "Étiquette de chambre", { sur: "CHAMBRE", gros: "3", titre: "La chambre\ndes vignes", sous: "Deux personnes, salle d'eau privative, vue sur le coteau.", meta: "MERCI DE NE PAS FUMER" }],

  /* ══════════ Auto & mobilité — transport ══════════ */

  ["tableau", "a4", "clair", "Auto & mobilité", "Tarifs de taxi", { titre: "Tarifs\nréglementés", sous: "Tarifs préfectoraux, affichage obligatoire.", sur: "POSTE|TARIF", items: ["Prise en charge|2,80 €", "Kilomètre, tarif A (jour)|1,10 €", "Kilomètre, tarif B (nuit)|1,65 €", "Attente, l'heure|28,00 €", "Course minimum|8,00 €", "Bagage supplémentaire|2,00 €"], meta: "Compteur obligatoire — reçu remis systématiquement" }],
  ["contact", "carte", "sombre", "Auto & mobilité", "Carte de chauffeur", { sur: "Taxi — VTC", titre: "Disponible\n7 jours sur 7", sous: "Réservation possible à l'avance, transferts aéroport et gare.", items: ["06 00 00 00 00", "Paiement carte accepté", "Transport de personnes assises", "Conventionné CPAM"], meta: "Licence n° 000 — Bordeaux Métropole" }],
  ["tableau", "a4", "clair", "Auto & mobilité", "Tarifs de location de matériel", { titre: "Location\nde matériel", sous: "Prix TTC, caution demandée à la prise.", sur: "MATÉRIEL|LA JOURNÉE", items: ["Ponceuse à parquet|58 €", "Nettoyeur haute pression|32 €", "Remorque bagagère|28 €", "Échafaudage roulant|45 €", "Bétonnière|38 €", "Marteau-piqueur|52 €"], meta: "Week-end (sam. 9 h – lun. 9 h) : deux journées facturées" }],
  ["checklist", "a5", "clair", "Auto & mobilité", "Avant la location", { sur: "Prise de matériel", titre: "À apporter", items: ["Pièce d'identité en cours de validité", "Justificatif de domicile de moins de 3 mois", "Moyen de paiement pour la caution", "Un véhicule adapté au gabarit", "Des sangles pour l'arrimage", "Le permis pour les remorques"], meta: "Matériel vérifié devant vous au départ et au retour" }],

  /* ══════════ Sport & bien-être — suite ══════════ */

  ["tableau", "a4", "clair", "Sport & bien-être", "Tarifs de coaching", { titre: "Tarifs\nde coaching", sous: "Prix TTC, à domicile ou en extérieur.", sur: "FORMULE|TARIF", items: ["Séance découverte|Offerte", "Séance à l'unité|55 €", "Forfait 10 séances|490 €", "Forfait 20 séances|920 €", "Duo, par personne|35 €", "Plan nutrition|+ 90 €"], meta: "Déplacement offert dans un rayon de 15 km" }],
  ["fiche", "a4", "froid", "Sport & bien-être", "Fiche d'exercice", { titre: "Le gainage,\ncorrectement", meta: "3 séries de 30 secondes — repos 45 secondes", sur: "À FAIRE", sous: "À ÉVITER", items: ["Coudes à l'aplomb des épaules", "Bassin dans l'alignement du dos", "Respiration continue, jamais bloquée", "Creuser le bas du dos", "Lever les fesses vers le plafond", "Tenir plus longtemps que la forme"] }],
  ["progression", "portrait", "vif", "Sport & bien-être", "Suivi d'objectif", { sur: "Objectif semi-marathon", titre: "Huit semaines\nsur douze", gros: "67", sous: "La sortie longue est passée à 16 km. Le plus dur est fait.", meta: "COURSE LE 12 SEPTEMBRE" }],
  ["checklist", "a5", "clair", "Sport & bien-être", "Sac de sport", { sur: "Avant la séance", titre: "Dans le sac", items: ["Une gourde d'un litre, remplie", "Une serviette, obligatoire en salle", "Des chaussures propres, à changer sur place", "Un cadenas pour le vestiaire", "Une tenue de rechange", "De quoi manger dans l'heure qui suit"], meta: "Ce qui est oublié une fois est oublié tout le temps : préparez le sac la veille" }],
  ["horaires", "a4", "vif", "Sport & bien-être", "Horaires de la salle", { sur: "Salle", titre: "Horaires\nd'ouverture", items: ["Lundi – vendredi|6 h – 23 h", "Samedi|8 h – 20 h", "Dimanche|9 h – 18 h", "Jours fériés|9 h – 13 h", "Accès badge|24 h/24 pour les annuels"], meta: "COURS COLLECTIFS : PLANNING AFFICHÉ À L'ACCUEIL" }],
  ["cadre", "a5", "clair", "Sport & bien-être", "Règlement intérieur", { sur: "Règlement", titre: "Trois règles\nqui suffisent", sous: "Une serviette sur chaque appareil. Les charges se rangent après usage. Le matériel abîmé se signale, il ne se cache pas.", meta: "MERCI DE RESPECTER LES AUTRES ADHÉRENTS" }],

  /* ══════════ Tech & startup — prestataires ══════════ */

  ["tableau", "a4", "clair", "Tech & startup", "Tarifs de dépannage informatique", { titre: "Nos tarifs", sous: "Prix TTC, crédit d'impôt de 50 % pour les particuliers.", sur: "PRESTATION|TARIF", items: ["Diagnostic|Offert", "Intervention à domicile, 1 h|60 €", "Installation et configuration|60 €", "Récupération de données|dès 120 €", "Nettoyage complet|90 €", "Assistance à distance, 30 min|35 €"], meta: "Aucune intervention facturée sans accord préalable" }],
  ["cartes", "large", "tech", "Tech & startup", "Trois offres de prestataire", { titre: "Trois façons\nde travailler\nensemble", sous: "Selon ce dont vous avez besoin, pas selon ce qu'on préfère vendre.", items: ["À la demande|60 € de l'heure, sans engagement.", "Forfait mensuel|290 €, cinq heures, report possible.", "Projet|Sur devis, prix ferme, délai écrit."] }],
  ["etapes", "a4", "froid", "Tech & startup", "Déroulé d'une mission", { titre: "Comment\nse passe\nune mission", sous: "Quatre étapes, un devis, aucune surprise.", items: ["Le cadrage|Une heure, gratuite, en visio ou sur place.", "Le devis|Prix ferme, périmètre écrit, délai daté.", "La réalisation|Point d'avancement chaque vendredi.", "La livraison|Formation incluse, documentation remise."] }],
  ["faq", "a4", "clair", "Tech & startup", "Questions de prestataire", { sur: "Avant de nous confier un projet", titre: "Quatre réponses\nfranches", items: ["Le prix peut-il changer ?|Seulement par avenant signé par vous.", "À qui appartient le code ?|À vous, intégralement, dès le paiement.", "Et après la livraison ?|Trois mois de corrections incluses.", "Travaillez-vous seul ?|Oui. Au-delà, je le dis et je passe la main."], meta: "contact@exemple.fr — réponse sous un jour ouvré" }],
  ["visite", "carte", "tech", "Tech & startup", "Carte de prestataire", { gros: "AR", titre: "Aline Roux", sur: "DÉVELOPPEUSE INDÉPENDANTE", sous: "06 00 00 00 00 · aline@exemple.fr · SIRET 000 000 000 00000" }],

];
