// Modèles — saisons, fêtes, terroir, nature, jeux, photographie.
//
// Les temps forts de l'année reviennent tous les ans et se préparent toujours
// dans l'urgence : Noël, la rentrée, les soldes, la fête des mères. Avoir la
// composition déjà écrite fait gagner la seule chose qui manque à ce
// moment-là — du temps. Les dates sont datées, à changer d'une frappe.

import type { Row } from "./design-templates";

export const ROWS_SAISON: Row[] = [

  /* ══════════ Voyage & saison — fêtes de fin d'année ══════════ */

  ["arche", "carre", "chic", "Voyage & saison", "Vœux élégants", { sur: "2027", titre: "Bonne\nannée", sous: "Que celle-ci vous laisse un peu plus de temps, et un peu moins d'urgence.", meta: "TOUTE L'ÉQUIPE D'AUBÉPINE" }],
  ["cadre", "a5", "chic", "Voyage & saison", "Carte de vœux imprimée", { sur: "Meilleurs vœux", titre: "2027", sous: "Merci pour cette année passée ensemble. La suivante se prépare déjà.", meta: "AUBÉPINE — 12 RUE DU MARCHÉ, BORDEAUX" }],
  ["sablier", "carre", "sombre", "Voyage & saison", "Compte à rebours du réveillon", { sur: "PLUS QUE 3 JOURS", titre: "Les commandes\nde Noël\nferment jeudi", sous: "Après, nous ne garantissons plus la livraison avant le 24.", meta: "COMMANDES EN LIGNE ET EN BOUTIQUE" }],
  ["pastille", "carre", "vif", "Voyage & saison", "Remise de Noël", { gros: "-25%", sur: "JUSQU'AU 24 DÉCEMBRE", titre: "Sur toutes les idées cadeaux", meta: "EN BOUTIQUE ET EN LIGNE" }],
  ["cartecadeau", "carte", "chic", "Voyage & saison", "Carte cadeau de Noël", { sur: "Joyeux Noël", gros: "60 €", titre: "Pour ceux à qui on ne sait jamais quoi offrir", meta: "N° 0000 0000 0000", sous: "Valable deux ans, en boutique et en ligne." }],
  ["grille", "portrait", "chaud", "Voyage & saison", "Six idées cadeaux", { titre: "Six idées\npour Noël", sous: "Toutes à moins de cinquante euros", items: ["Carnet relié", "Savon d'atelier", "Écharpe laine", "Bougie cire", "Confiture", "Carte cadeau"], meta: "Emballage cadeau offert — commandes jusqu'au 20 décembre" }],
  ["horaires", "a4", "terre", "Voyage & saison", "Horaires des fêtes", { sur: "Décembre", titre: "Horaires\nde fin d'année", items: ["Du 1er au 23|10 h – 20 h, tous les jours", "24 décembre|9 h – 16 h", "25 décembre|Fermé", "Du 26 au 30|10 h – 19 h", "31 décembre|9 h – 16 h", "1er janvier|Fermé"], meta: "RÉOUVERTURE NORMALE LE 2 JANVIER À 10 H" }],
  ["menu", "a4", "chic", "Voyage & saison", "Menu du réveillon", { sur: "31 décembre", titre: "Menu du réveillon", items: ["Velouté de châtaigne, huile de truffe|Entrée", "Saint-jacques poêlées, purée de panais|Poisson", "Chapon fermier, jus corsé, légumes anciens|Viande", "Fromages affinés de la région|Fromage", "Bûche maison, praliné et vanille|Dessert"], meta: "89 € par personne, hors boissons — réservation avant le 20 décembre" }],
  ["damier", "carre", "sombre", "Voyage & saison", "Nouvel An", { sur: "31 décembre", titre: "SOIRÉE\nDE FIN\nD'ANNÉE", sous: "Dîner à 20 h, bal à 23 h, soupe à l'oignon à 3 h.", meta: "89 € PAR PERSONNE — RÉSERVATION OBLIGATOIRE" }],
  ["ruban", "carre", "chaud", "Voyage & saison", "Congés de fin d'année", { sur: "Information", titre: "CONGÉS", sous: "L'atelier est fermé du 24 décembre au 2 janvier. Les commandes reprennent le 3.", meta: "BONNES FÊTES À TOUS" }],

  /* ══════════ Voyage & saison — rentrée, printemps, été, automne ══════════ */

  ["calendrier", "a4", "vif", "Voyage & saison", "Date de rentrée", { sur: "LUNDI 1ER SEPTEMBRE", gros: "01", titre: "C'est\nla rentrée", items: ["Ouverture des inscriptions dès 9 h", "Permanences les samedis de septembre", "Tarifs inchangés depuis 2024", "Une séance d'essai offerte"] }],
  ["promo", "carre", "chaud", "Voyage & saison", "Offre de rentrée", { sur: "Rentrée", titre: "L'abonnement\nannuel", gros: "290 €", items: ["390 €"], sous: "Pour toute inscription avant le 30 septembre, paiement en trois fois possible.", meta: "CODE : RENTREE26" }],
  ["checklist", "a4", "clair", "Voyage & saison", "Check-list de rentrée", { sur: "Septembre", titre: "Ce qu'il faut\navoir fait", items: ["Inscrire les enfants à la cantine", "Renouveler l'assurance scolaire", "Prendre les rendez-vous médicaux", "Réinscrire aux activités", "Vérifier les vaccins obligatoires", "Faire les papiers de garderie", "Poser les dates de vacances de Toussaint"], meta: "Tout ce qui n'est pas fait en septembre se paiera en novembre" }],
  ["soleil", "carre", "chaud", "Voyage & saison", "Premier jour de l'été", { sur: "21 juin", titre: "L'été\ncommence", sous: "Horaires d'été, terrasse ouverte, service continu jusqu'à 23 h.", meta: "TOUS LES JOURS JUSQU'AU 15 SEPTEMBRE" }],
  ["vagues", "carre", "froid", "Voyage & saison", "Horaires d'été", { sur: "Du 1er juillet au 31 août", titre: "Horaires\nd'été", sous: "Ouvert tous les jours de 9 h à 20 h, sans interruption.", meta: "FERMETURE ANNUELLE DU 15 AU 25 AOÛT" }],
  ["montagne", "carre", "nature", "Voyage & saison", "Automne", { sur: "Automne", titre: "La saison\ndes bois\net des soupes", sous: "Nouvelle carte à partir du 1er octobre, avec ce que la saison donne.", meta: "OUVERT DU MARDI AU SAMEDI" }],
  ["pois", "carre", "pastel", "Voyage & saison", "Printemps", { sur: "Printemps", titre: "Tout\nrecommence", sous: "Nouvelle collection, nouveaux horaires, et la terrasse qui rouvre.", meta: "À PARTIR DU 21 MARS" }],
  ["sceau", "carre", "sombre", "Voyage & saison", "Hiver", { sur: "SAISON D'HIVER", gros: "2026", meta: "DU 15 DÉC. AU 15 MARS", titre: "Horaires d'hiver", sous: "Fermeture à 18 h, sauf le vendredi." }],
  ["disque", "carre", "vif", "Voyage & saison", "Changement d'heure", { sur: "Ce week-end", titre: "On recule\nd'une heure", sous: "Nos horaires ne changent pas, mais la nuit tombe plus tôt : pensez à l'éclairage.", meta: "NUIT DU SAMEDI AU DIMANCHE" }],

  /* ══════════ Commerce & promotion — temps forts de l'année ══════════ */

  ["bloc", "carre", "vif", "Commerce & promotion", "Black Friday brutal", { titre: "BLACK\nFRIDAY", sous: "-40 % sur tout le site, un seul jour, sans code à saisir.", meta: "VENDREDI 27 NOVEMBRE — 0 H À 23 H 59" }],
  ["sablier", "story", "sombre", "Commerce & promotion", "Cyber Monday", { sur: "DERNIÈRES HEURES", titre: "Ça se termine\nà minuit", sous: "Après, les prix reviennent à la normale. Aucune prolongation, jamais.", meta: "LUNDI 30 NOVEMBRE" }],
  ["pastille", "carre", "chaud", "Commerce & promotion", "Soldes d'hiver", { gros: "-50%", sur: "SOLDES D'HIVER", titre: "Sur la collection automne-hiver", meta: "DU 7 JANVIER AU 3 FÉVRIER" }],
  ["rayures", "a3", "vif", "Commerce & promotion", "Affiche premier jour de soldes", { sur: "Premier jour", titre: "SOLDES", sous: "Jusqu'à -50 % dès l'ouverture, sur plus de trois cents références.", meta: "MERCREDI 7 JANVIER — 8 H — 12 RUE DU MARCHÉ" }],
  ["coupon", "large", "pastel", "Commerce & promotion", "Bon fête des mères", { gros: "-15%", sur: "FÊTE DES MÈRES", titre: "Sur toute la gamme soin et parfum", sous: "Du 20 au 31 mai, en boutique et en ligne, non cumulable avec les remises en cours.", meta: "MAMAN15", cta: "Emballage cadeau offert" }],
  ["arche", "carre", "pastel", "Commerce & promotion", "Fête des mères", { sur: "31 mai", titre: "Pour elle", sous: "Une sélection de dix idées, toutes fabriquées à l'atelier.", meta: "EMBALLAGE CADEAU OFFERT" }],
  ["etiquette", "etiq", "sombre", "Commerce & promotion", "Fête des pères", { sur: "FÊTE DES PÈRES", gros: "45 €", titre: "Coffret rasage,\nblaireau et savon", sous: "Fabriqué à l'atelier, gravure du prénom offerte.", meta: "COMMANDES JUSQU'AU 15 JUIN" }],
  ["cadre", "carre", "chic", "Commerce & promotion", "Saint-Valentin", { sur: "14 février", titre: "À deux,\nc'est mieux", sous: "Menu en deux services, un verre de crémant offert.", meta: "58 € POUR DEUX — RÉSERVATION CONSEILLÉE" }],
  ["pois", "carre", "pastel", "Commerce & promotion", "Pâques", { sur: "Pâques", titre: "La chasse\naux œufs", sous: "Dimanche 5 avril, de 10 h à 12 h, dans le jardin de la boutique.", meta: "GRATUIT — POUR LES MOINS DE 10 ANS" }],
  ["damier", "carre", "sombre", "Commerce & promotion", "Halloween", { sur: "31 octobre", titre: "SOIRÉE\nHALLOWEEN", sous: "Déguisement conseillé, boisson offerte aux plus convaincants.", meta: "VENDREDI 31 — À PARTIR DE 20 H" }],
  ["ruban", "carre", "vif", "Commerce & promotion", "Anniversaire de la boutique", { sur: "Trois ans", titre: "MERCI", sous: "Trois ans jour pour jour. Toute la semaine, -15 % sur l'ensemble de la boutique.", meta: "DU 12 AU 18 MAI" }],
  ["soleil", "carre", "chaud", "Commerce & promotion", "Ventes d'été", { sur: "Ventes d'été", titre: "Jusqu'à\n-40 %", sous: "Sur la collection printemps-été, jusqu'à épuisement des stocks.", meta: "DU 26 JUIN AU 23 JUILLET" }],
  ["montagne", "carre", "nature", "Commerce & promotion", "Vente d'automne", { sur: "Automne", titre: "Nouvelle\ncollection", sous: "Laines, velours et couleurs de sous-bois. En boutique dès le 1er octobre.", meta: "SÉRIE LIMITÉE À 200 PIÈCES" }],

  /* ══════════ Agriculture & terroir ══════════ */

  ["etiquette", "etiq", "nature", "Agriculture & terroir", "Étiquette de miel", { sur: "RÉCOLTE 2026", gros: "6,50 €", titre: "Miel de châtaignier,\npot de 500 g", sous: "Ruchers de la Combe, récolté en juillet.", meta: "À CONSOMMER DE PRÉFÉRENCE AVANT 2029" }],
  ["etiquette", "etiq", "terre", "Agriculture & terroir", "Étiquette de confiture", { sur: "FAIT MAISON", gros: "250 g", titre: "Confiture d'abricots,\nrécolte 2026", sous: "Fruits, sucre de canne, jus de citron. Rien d'autre.", meta: "À CONSERVER AU FRAIS APRÈS OUVERTURE" }],
  ["etiquette", "carteV", "chaud", "Agriculture & terroir", "Étiquette de vin", { sur: "SAINT-ÉMILION", gros: "2021", titre: "Château\nde la Combe", sous: "Merlot 80 %, cabernet franc 20 %. Élevé 14 mois en fût.", meta: "MIS EN BOUTEILLE À LA PROPRIÉTÉ" }],
  ["menu", "a4", "nature", "Agriculture & terroir", "Liste de produits", { sur: "Vente directe", titre: "Nos produits", items: ["Miel de châtaignier, 500 g|6,50", "Miel d'acacia, 500 g|7,50", "Confiture d'abricots, 250 g|4,50", "Jus de pomme, 1 L|3,20", "Œufs plein air, la douzaine|4,00", "Panier de légumes de saison|18,00"], meta: "Vente à la ferme du mardi au samedi, 9 h à 12 h et 15 h à 19 h" }],
  ["horaires", "a4", "terre", "Agriculture & terroir", "Horaires de vente à la ferme", { sur: "Vente directe", titre: "À la ferme", items: ["Lundi|Fermé", "Mardi – vendredi|9 h – 12 h · 15 h – 19 h", "Samedi|9 h – 13 h", "Dimanche|Fermé", "Marché de Bordeaux|Jeudi et dimanche matin"], meta: "PAIEMENT PAR CARTE ACCEPTÉ DÈS 5 €" }],
  ["calendrier", "a4", "nature", "Agriculture & terroir", "Date de récolte", { sur: "SAMEDI 12 SEPTEMBRE", gros: "12", titre: "Vendanges\nouvertes", items: ["Dès 8 h, rendez-vous au chai", "Repas de midi offert aux vendangeurs", "Prévoir sécateur et bottes", "Inscription au 05 57 00 00 00"] }],
  ["grille", "a4", "nature", "Agriculture & terroir", "Le calendrier des légumes", { titre: "Ce qui\npousse\nen ce moment", sous: "Disponible cette semaine à la ferme", items: ["Poireaux", "Carottes", "Choux", "Panais", "Betteraves", "Courges"], meta: "Le panier de saison change chaque semaine — 18 € pour 5 kg environ" }],
  ["fiche", "a4", "nature", "Agriculture & terroir", "Fiche de production", { titre: "Nos poulets\nde plein air", meta: "Élevés 110 jours — 12 m² par animal — abattus sur place", sur: "CE QU'ON FAIT", sous: "CE QU'ON NE FAIT PAS", items: ["Alimentation à base de céréales de la ferme", "Parcours herbeux ouvert toute la journée", "Abattage à la ferme, sans transport", "Aucun antibiotique préventif", "Aucun aliment importé", "Aucune vente en grande surface"] }],
  ["avantages", "large", "nature", "Agriculture & terroir", "Nos engagements de ferme", { titre: "Trois choses\nsur lesquelles\non ne cède pas", sous: "Elles coûtent plus cher, et c'est assumé.", items: ["Vente directe|Aucun intermédiaire, prix fixé par nous.", "Saison|Rien hors saison, jamais, même sur demande.", "Traçabilité|Chaque produit porte son lot et sa date."], meta: "Visite de l'exploitation possible sur rendez-vous" }],
  ["evenement", "a3", "nature", "Agriculture & terroir", "Marché de producteurs", { sur: "Marché de producteurs", titre: "À la ferme", meta: "DIMANCHE 17 MAI — 9 H À 18 H", sous: "Ferme de la Combe, route de Saint-Émilion", cta: "Douze producteurs — restauration sur place — entrée libre" }],
  ["visite", "carte", "terre", "Agriculture & terroir", "Carte de producteur", { gros: "FC", titre: "Ferme de la Combe", sur: "APICULTURE — MARAÎCHAGE", sous: "Route de Saint-Émilion · 05 57 00 00 00 · fermedelacombe.fr" }],
  ["progression", "carre", "nature", "Agriculture & terroir", "Avancement de la récolte", { sur: "Récolte 2026", titre: "Les trois\nquarts sont\nrentrés", gros: "76", sous: "Il reste la parcelle du haut, à finir avant les pluies annoncées.", meta: "SUIVEZ LA SUITE SUR LA PAGE DE LA FERME" }],
  ["recette", "a4", "terre", "Agriculture & terroir", "Recette du panier", { titre: "Que faire\ndes panais ?", meta: "40 MIN — 4 PARTS — TRÈS FACILE", sur: "IL VOUS FAUT", cta: "ON Y VA", items: ["800 g de panais du panier", "2 gousses d'ail", "3 cuillères d'huile d'olive", "Thym, sel, poivre", "Épluchez et coupez en bâtonnets.", "Mélangez avec l'huile, l'ail et le thym.", "Étalez sur une plaque, sans les superposer.", "35 min à 200 °C, en remuant à mi-cuisson."], sous: "Se mange aussi bien froid le lendemain, en salade." }],

  /* ══════════ Nature & écologie ══════════ */

  ["montagne", "a3", "nature", "Nature & écologie", "Affiche de chantier nature", { sur: "Chantier participatif", titre: "Replanter\nla haie", sous: "Trois cents mètres de haie champêtre à replanter. Outils fournis, gants conseillés.", meta: "SAMEDI 22 NOVEMBRE — 9 H À 16 H" }],
  ["liste", "a4", "nature", "Nature & écologie", "Gestes du quotidien", { sur: "Au quotidien", titre: "Cinq gestes\nqui pèsent\nvraiment", items: ["Baisser le chauffage d'un degré", "Décaler les lessives en heures creuses", "Réparer plutôt que remplacer", "Acheter d'occasion en premier réflexe", "Composter les déchets de cuisine"], meta: "Les cinq réunis représentent l'équivalent d'un aller-retour Paris-Nice en voiture" }],
  ["stats", "large", "nature", "Nature & écologie", "Bilan environnemental", { sur: "Bilan 2026", titre: "Ce qu'on\na réduit", items: ["-42 %|d'emballages", "0|plastique à usage unique", "100 %|d'électricité renouvelable"], meta: "Bilan carbone complet publié sur notre site" }],
  ["progression", "carre", "nature", "Nature & écologie", "Objectif zéro plastique", { sur: "Engagement 2026", titre: "Vers le\nzéro plastique", gros: "84", sous: "Il reste les films de palettisation, pour lesquels aucune solution n'existe encore.", meta: "RAPPORT COMPLET SUR NOTRE SITE" }],
  ["cartes", "large", "nature", "Nature & écologie", "Trois façons de composter", { titre: "Trois façons\nde composter", sous: "Selon la place dont vous disposez.", items: ["Lombricomposteur|Sous l'évier, sans odeur, 4 personnes max.", "Composteur de jardin|Un mètre carré, tout y passe.", "Bokashi|En appartement, fermentation, très rapide."] }],
  ["etapes", "a4", "nature", "Nature & écologie", "Démarrer un compost", { titre: "Démarrer\nun compost", sous: "Quatre étapes, aucun matériel spécifique.", items: ["Choisir l'endroit|À l'ombre, en contact avec la terre.", "Alterner|Une part d'humide pour une part de sec.", "Aérer|Retourner une fois par mois, pas plus.", "Récolter|Six à neuf mois, quand ça sent la forêt."] }],
  ["faq", "a4", "clair", "Nature & écologie", "Questions sur le tri", { sur: "Tri sélectif", titre: "Quatre réponses\nqui évitent\ndes erreurs", items: ["Faut-il laver les emballages ?|Non, il suffit de les vider correctement.", "Les pots de yaourt se recyclent ?|Oui depuis 2023, dans le bac jaune.", "Et le papier gras ?|Poubelle classique, il contamine le tri.", "Les bouchons ?|Séparés du flacon, tous les deux dans le jaune."], meta: "En cas de doute, la règle est simple : tous les emballages vont dans le bac jaune" }],
  ["checklist", "a4", "clair", "Nature & écologie", "Économies d'énergie", { sur: "Avant l'hiver", titre: "Sept vérifications\nqui font baisser\nla facture", items: ["Purger les radiateurs", "Vérifier les joints de fenêtre", "Isoler le bas des portes", "Baisser le chauffe-eau à 55 °C", "Fermer volets et rideaux la nuit", "Dépoussiérer l'arrière du frigo", "Programmer le chauffage la nuit"], meta: "Ces sept gestes coûtent moins de trente euros et se rentabilisent en un hiver" }],
  ["chiffre", "carre", "nature", "Nature & écologie", "Chiffre marquant", { sur: "Le saviez-vous", gros: "80 %", titre: "de l'impact d'un vêtement se joue avant l'achat", sous: "Culture, filature, teinture, transport : tout est déjà fait quand vous l'essayez.", cta: "Acheter moins, choisir mieux" }],
  ["evenement", "a3", "nature", "Nature & écologie", "Journée de ramassage", { sur: "Journée citoyenne", titre: "Nettoyons\nles berges", meta: "SAMEDI 14 MARS — 9 H À 13 H", sous: "Rendez-vous au ponton, quai Vauban", cta: "Sacs et gants fournis — casse-croûte offert à midi" }],
  ["souligne", "carre", "nature", "Nature & écologie", "Trois mots écologie", { sur: "Notre règle", titre: "Réparer.\nRéutiliser.\nRefuser.", sous: "Dans cet ordre. Recycler ne vient qu'après, et c'est déjà un échec partiel.", meta: "association-berges.fr" }],

  /* ══════════ Jeux & e-sport ══════════ */

  ["neon", "carre", "tech", "Jeux & e-sport", "Annonce de tournoi", { gros: "5v5", titre: "Le tournoi ouvre les inscriptions", sous: "Trente-deux équipes, format double élimination, 1 500 € de dotation." }],
  ["score", "carre", "vif", "Jeux & e-sport", "Résultat de match", { sur: "DEMI-FINALE", items: ["Aubépine", "Rivière"], gros: "2-1", titre: "Qualification arrachée au troisième round", meta: "SAMEDI 20 H — DIFFUSÉ EN DIRECT" }],
  ["ecusson", "logo", "sombre", "Jeux & e-sport", "Logo d'équipe", { gros: "AUB", meta: "EST. 2023", titre: "Aubépine Esport", sous: "Jouer propre, gagner quand même" }],
  ["tableau", "a4", "sombre", "Jeux & e-sport", "Classement", { titre: "Classement\nde la saison", sous: "Après quatorze journées.", sur: "ÉQUIPE|POINTS", items: ["Aubépine|38", "Rivière|35", "Combe|31", "Port|27", "Halles|22", "Forges|18"], meta: "Deux premiers qualifiés pour les phases finales" }],
  ["chrono", "large", "tech", "Jeux & e-sport", "Programme du tournoi", { titre: "Le week-end\nen quatre temps", sous: "Diffusion intégrale sur la chaîne du club.", items: ["SAM 10 h|Phase de poules.", "SAM 18 h|Quarts de finale.", "DIM 14 h|Demi-finales.", "DIM 20 h|Finale."], meta: "Salle municipale — entrée libre dans la limite des places" }],
  ["recrute", "carre", "sombre", "Jeux & e-sport", "Recherche de joueur", { sur: "ON RECRUTE", titre: "Un cinquième\njoueur", sous: "Entraînements mardi et jeudi soir — niveau intermédiaire suffisant", items: ["Aucun frais d'adhésion", "Coaching hebdomadaire assuré", "Bonne ambiance exigée, pas le classement"], meta: "Candidatures sur le serveur du club" }],
  ["progression", "carre", "vif", "Jeux & e-sport", "Cagnotte du tournoi", { sur: "Dotation", titre: "La cagnotte\nmonte", gros: "68", sous: "1 020 € réunis sur les 1 500 € annoncés. Chaque inscription fait monter le total.", meta: "INSCRIPTIONS OUVERTES JUSQU'AU 30 MAI" }],
  ["faq", "a4", "clair", "Jeux & e-sport", "Règlement du tournoi", { sur: "Règlement", titre: "Quatre points\nà connaître", items: ["Quel format ?|Double élimination, BO3, finale en BO5.", "Faut-il payer ?|Dix euros par équipe, reversés à la dotation.", "Les remplaçants ?|Un par équipe, déclaré avant le premier match.", "En cas de litige ?|L'arbitre tranche, sa décision est définitive."], meta: "Règlement complet disponible sur le serveur du club" }],
  ["playlist", "carre", "sombre", "Jeux & e-sport", "Programme de diffusion", { emoji: "🎮", titre: "Le programme\ndu week-end", sous: "Six diffusions, commentées en direct", items: ["Poules, groupe A|10:00", "Poules, groupe B|13:00", "Quarts de finale|18:00", "Demi-finale 1|14:00", "Demi-finale 2|16:30", "Finale|20:00"], meta: "Sur la chaîne du club — rediffusions le lundi" }],
  ["contour", "carre", "tech", "Jeux & e-sport", "Écran de stream", { sur: "En direct", gros: "LIVE", titre: "Tournoi d'hiver, phase de poules", sous: "Commentaires assurés par l'équipe du club.", meta: "CHAT MODÉRÉ — RESPECT EXIGÉ" }],

  /* ══════════ Photo & création ══════════ */

  ["coins", "carre", "chic", "Photo & création", "Annonce de série photo", { sur: "Nouvelle série", titre: "Lumière\nnaturelle,\nsans retouche", sous: "Douze images, tournées en une matinée, au 50 mm.", meta: "PRISES DE VUE SUR DEVIS — STUDIOVERRIER.FR" }],
  ["polaroid", "carre", "terre", "Photo & création", "Instantané de tournage", { sur: "Coulisses", titre: "Trois heures\npour une image", emoji: "📷", meta: "Studio Verrier, mardi" }],
  ["tarif", "a4", "chic", "Photo & création", "Forfait de prise de vue", { sur: "FORFAIT PRODUIT", gros: "480 €", sous: "la demi-journée, jusqu'à 15 références", items: ["Prise de vue en studio", "Retouche légère incluse", "Fichiers haute définition livrés", "Cession de droits web illimitée", "Livraison sous cinq jours ouvrés"], cta: "Demander un devis" }],
  ["tableau", "a4", "clair", "Photo & création", "Grille tarifaire photo", { titre: "Nos tarifs", sous: "Prix HT, cession de droits web comprise.", sur: "PRESTATION|TARIF", items: ["Portrait, 1 h|180 €", "Produit, demi-journée|480 €", "Reportage, journée|890 €", "Événement, soirée|650 €", "Retouche approfondie|45 € / image", "Cession print|Sur devis"], meta: "Déplacement offert dans un rayon de 30 km" }],
  ["grille", "pin", "chic", "Photo & création", "Portfolio en six images", { titre: "Six séries\nrécentes", sous: "Studio, produit, reportage", items: ["Atelier bois", "Table de fête", "Portraits", "Chantier", "Nature morte", "Boutique"], meta: "Portfolio complet sur studioverrier.fr" }],
  ["etapes", "a4", "froid", "Photo & création", "Déroulé d'une prise de vue", { titre: "Comment\nse déroule\nune séance", sous: "Rien n'est improvisé, tout est validé avant.", items: ["Cadrage|Un échange d'une heure, gratuit.", "Devis|Écrit, avec les droits précisés.", "Séance|Vous validez les images sur place.", "Livraison|Fichiers sous cinq jours ouvrés."] }],
  ["faq", "a4", "clair", "Photo & création", "Questions clients photo", { sur: "Avant la séance", titre: "Quatre réponses\nsur les droits", items: ["Puis-je tout publier ?|Sur le web oui, l'affichage se négocie à part.", "Combien de temps de cession ?|Illimitée pour le web, cinq ans en print.", "Les fichiers bruts ?|Non livrés, c'est un choix assumé.", "Et si je ne suis pas satisfait ?|Une nouvelle séance offerte, une seule fois."], meta: "Conditions complètes remises avec le devis" }],
  ["contact", "carte", "sombre", "Photo & création", "Carte de photographe", { sur: "Studio Verrier", titre: "Photographie\nculinaire\net d'atelier", sous: "Bordeaux et Sud-Ouest, déplacements possibles.", items: ["06 00 00 00 00", "contact@studioverrier.fr", "studioverrier.fr", "8 quai Vauban, Bordeaux"], meta: "SIRET 000 000 000 00000" }],
  ["certificat", "paysage", "chic", "Photo & création", "Certificat de tirage", { sur: "CERTIFICAT D'AUTHENTICITÉ", titre: "Traces, n° 4/30", auteur: "Marc Vidal, photographe", sous: "tirage argentique sur papier baryté, réalisé par l'auteur, signé et numéroté au dos.", meta: "BORDEAUX, LE 3 AVRIL 2026" }],
  ["magazine", "pin", "chic", "Photo & création", "Couverture de portfolio", { sur: "PORTFOLIO", meta: "STUDIO VERRIER — 2026", titre: "Ce qui\nreste", sous: "Trois ans de commandes, vingt images retenues.", items: ["Culinaire et produit", "Portraits d'artisans", "Reportage d'atelier"] }],
  ["souligne", "carre", "clair", "Photo & création", "Méthode en trois mots", { sur: "Ma façon de travailler", titre: "Lumière.\nCadre.\nPatience.", sous: "Dans cet ordre. Le reste se règle au montage, et le montage ne rattrape rien.", meta: "studioverrier.fr" }],

];
