// Modèles — équilibrage des catégories les moins fournies.
//
// Dernier apport, décidé après avoir compté par groupe : écologie, jeu vidéo,
// vidéo courte, photographie, mariage, mode et enfance étaient les catégories
// les plus maigres du catalogue. Elles reçoivent ici de quoi tenir la
// comparaison avec les autres, sans allonger celles qui débordaient déjà.

import type { Row } from "./design-templates";

export const ROWS_EQUILIBRE: Row[] = [

  /* ══════════ Nature & écologie ══════════ */

  ["etapes", "a4", "nature", "Nature & écologie", "Réduire ses déchets", { titre: "Réduire\nses déchets\nen quatre gestes", sous: "Classés du plus efficace au moins efficace.", items: ["Refuser|Ce qui n'entre pas ne sera jamais à jeter.", "Réduire|Acheter en vrac, cuisiner brut.", "Réutiliser|Réparer, donner, détourner.", "Recycler|En dernier recours, jamais en premier."] }],
  ["tableau", "a4", "nature", "Nature & écologie", "Ce qui va dans quel bac", { titre: "Que met-on\noù ?", sous: "Consignes valables sur la métropole depuis 2023.", sur: "DÉCHET|BAC", items: ["Tous les emballages|Jaune", "Papier et carton|Jaune", "Verre|Colonne à verre", "Épluchures|Compost", "Papier gras|Ordures ménagères", "Piles et ampoules|Point de collecte"], meta: "En cas de doute : tous les emballages vont dans le bac jaune, sans exception" }],
  ["chiffre", "carre", "nature", "Nature & écologie", "Chiffre de consommation", { sur: "Le saviez-vous", gros: "148 L", titre: "d'eau par personne et par jour", sous: "Dont la moitié pour la douche et les toilettes. Le reste se joue à la marge.", cta: "Cinq gestes qui comptent vraiment" }],
  ["comparatif", "a4", "nature", "Nature & écologie", "Neuf ou d'occasion", { titre: "Neuf\nou d'occasion", sur: "NEUF", cta: "D'OCCASION", items: ["Impact carbone plein|Impact déjà amorti", "Garantie 2 ans|Garantie 6 mois", "Prix fort|-40 % en moyenne", "Choix illimité|Choix limité", "Zéro recherche|Un peu de patience"], meta: "Pour l'électroménager, l'occasion reconditionnée reste le meilleur compromis" }],
  ["montagne", "a3", "nature", "Nature & écologie", "Affiche de sensibilisation", { sur: "Protégeons ce qu'on traverse", titre: "Ne laissez\nque vos\ntraces de pas", sous: "Les déchets abandonnés en montagne mettent de quinze ans à quatre siècles à disparaître.", meta: "PARC NATUREL — ASSOCIATION DES SENTIERS" }],
  ["progression", "carre", "nature", "Nature & écologie", "Objectif de collecte", { sur: "Collecte de textile", titre: "Deux tonnes\nsur trois", gros: "67", sous: "Il reste une tonne à collecter avant la fin du mois pour atteindre l'objectif.", meta: "POINTS DE DÉPÔT EN MAIRIE ET À LA MÉDIATHÈQUE" }],
  ["evenement", "a3", "nature", "Nature & écologie", "Journée de nettoyage", { sur: "Journée citoyenne", titre: "Nettoyons\nles berges", meta: "SAMEDI 14 MARS — 9 H À 13 H", sous: "Rendez-vous au ponton, quai Vauban", cta: "Sacs et gants fournis — casse-croûte offert à midi" }],
  ["liste", "pin", "nature", "Nature & écologie", "Épingle gestes du quotidien", { sur: "Au quotidien", titre: "Cinq gestes\nqui pèsent\nvraiment", items: ["Baisser le chauffage d'un degré", "Réparer plutôt que remplacer", "Acheter d'occasion en premier réflexe", "Composter les déchets de cuisine", "Décaler les lessives en heures creuses"], meta: "Les cinq réunis valent bien plus que tous les écogestes symboliques" }],
  ["souligne", "carre", "nature", "Nature & écologie", "Post trois mots", { sur: "Notre règle", titre: "Réparer.\nRéutiliser.\nRefuser.", sous: "Dans cet ordre. Recycler ne vient qu'après, et c'est déjà un demi-échec.", meta: "association-berges.fr" }],
  ["stats", "large", "nature", "Nature & écologie", "Bilan de collecte", { sur: "Bilan 2026", titre: "Ce que la\ncollecte a\névité", items: ["4,2 t|de textile collecté", "68 %|réemployés", "0|incinéré"], meta: "Rapport complet disponible auprès de l'association" }],

  /* ══════════ Jeux & e-sport ══════════ */

  ["evenement", "a3", "sombre", "Jeux & e-sport", "Affiche de tournoi", { sur: "3e édition", titre: "Tournoi\nd'hiver", meta: "SAMEDI 12 ET DIMANCHE 13 DÉCEMBRE", sous: "Salle municipale, place du Marché — entrée libre", cta: "Trente-deux équipes — 1 500 € de dotation — diffusion en direct" }],
  ["etapes", "a4", "tech", "Jeux & e-sport", "Comment s'inscrire", { titre: "S'inscrire\nau tournoi", sous: "Cinq minutes, avant le 30 mai.", items: ["Constituer l'équipe|Cinq joueurs, un remplaçant déclaré.", "S'inscrire|Formulaire en ligne, dix euros par équipe.", "Confirmer|Un message de validation sous 48 h.", "Se présenter|Le samedi à 9 h, pièce d'identité."] }],
  ["cadre", "a4", "sombre", "Jeux & e-sport", "Règlement affiché", { sur: "Règlement", titre: "Quatre règles\nnon négociables", sous: "Aucune insulte, sous aucun prétexte. Pas de logiciel tiers. Un forfait à l'heure d'appel est définitif. La décision de l'arbitre ne se discute pas.", meta: "TOUT MANQUEMENT ENTRAÎNE LA DISQUALIFICATION DE L'ÉQUIPE" }],
  ["playlist", "carre", "tech", "Jeux & e-sport", "Programme de diffusion", { emoji: "📺", titre: "Le programme\ndu week-end", sous: "Six diffusions, commentées en direct", items: ["Poules, groupe A|10:00", "Poules, groupe B|13:00", "Quarts de finale|18:00", "Demi-finale 1|14:00", "Demi-finale 2|16:30", "Finale|20:00"], meta: "Sur la chaîne du club — rediffusions dès le lundi" }],
  ["recrute", "carre", "vif", "Jeux & e-sport", "Recherche de joueurs", { sur: "ON RECRUTE", titre: "Deux joueurs\npour la\nsaison", sous: "Entraînements mardi et jeudi soir — niveau intermédiaire suffisant", items: ["Aucun frais d'adhésion", "Coaching hebdomadaire", "Bonne ambiance exigée, pas le classement"], meta: "Candidatures sur le serveur du club" }],
  ["stats", "carre", "sombre", "Jeux & e-sport", "Bilan de saison", { sur: "Saison 2026", titre: "La saison\nen trois chiffres", items: ["38|matchs joués", "24|victoires", "2|finales"], meta: "Statistiques détaillées sur le site du club" }],
  ["temoignage", "carre", "tech", "Jeux & e-sport", "Témoignage de joueur", { emoji: "🎮", titre: "« Je suis venu pour jouer. Je suis resté pour l'équipe. »", auteur: "Noé T.", sous: "Membre depuis 2024" }],
  ["contour", "story", "tech", "Jeux & e-sport", "Story écran de stream", { sur: "En direct", gros: "LIVE", titre: "Tournoi d'hiver, phase de poules", sous: "Commentaires assurés par l'équipe du club.", meta: "CHAT MODÉRÉ — RESPECT EXIGÉ" }],
  ["horaires", "a4", "sombre", "Jeux & e-sport", "Créneaux du local", { sur: "Local associatif", titre: "Créneaux\nd'accès", items: ["Lundi|Fermé", "Mardi|18 h – 23 h", "Mercredi|14 h – 23 h", "Jeudi|18 h – 23 h", "Vendredi|18 h – 1 h", "Samedi|10 h – 1 h"], meta: "ACCÈS RÉSERVÉ AUX ADHÉRENTS — ADHÉSION 30 € L'ANNÉE" }],
  ["tarif", "a4", "tech", "Jeux & e-sport", "Adhésion au club", { sur: "ADHÉSION ANNUELLE", gros: "30 €", sous: "de septembre à août, tarif unique", items: ["Accès libre au local", "Matériel mis à disposition", "Coaching hebdomadaire", "Inscription aux tournois offerte", "Tarif réduit 15 € pour les étudiants"], cta: "Adhérer au local" }],

  /* ══════════ TikTok & vidéo courte ══════════ */

  ["contour", "story", "vif", "TikTok & vidéo courte", "Accroche typographique", { sur: "Ne partez pas", gros: "STOP", titre: "Ce que vous faites tous les jours est peut-être faux", sous: "Trente secondes pour vérifier.", meta: "RESTEZ JUSQU'AU BOUT" }],
  ["empilement", "story", "chaud", "TikTok & vidéo courte", "Liste en cinq points", { titre: "Cinq erreurs\nde débutant", sous: "Faites-en une, le résultat est raté.", items: ["Poêle pas assez chaude", "Trop de choses à la fois", "Retourner sans arrêt", "Saler seulement à la fin", "Couper juste après cuisson"], meta: "Laquelle faites-vous ?" }],
  ["duo", "story", "tech", "TikTok & vidéo courte", "Deux chiffres", { gros: "TEST", items: ["3 €|le coût réel du plat", "22 min|de préparation"] }],
  ["etapes", "story", "froid", "TikTok & vidéo courte", "Tutoriel en quatre étapes", { titre: "Réussir\nun œuf poché", sous: "Quatre gestes, aucun vinaigre.", items: ["Un œuf très frais|C'est le seul point non négociable.", "Eau frémissante|Jamais bouillante, sinon ça se disperse.", "Un tourbillon|On y dépose l'œuf sans le lâcher de haut.", "Trois minutes|Puis on égoutte sur du papier."] }],
  ["score", "story", "vif", "TikTok & vidéo courte", "Duel à l'aveugle", { sur: "TEST À L'AVEUGLE", items: ["Maison", "Industriel"], gros: "4-1", titre: "Le maison gagne, sauf sur le temps", meta: "CINQ GOÛTEURS, AUCUN PRÉVENU" }],
  ["bulle", "story", "pastel", "TikTok & vidéo courte", "Commentaire du jour", { sur: "Commentaire du jour", titre: "« Je l'ai fait hier soir, mes enfants ont redemandé. »", auteur: "@camille_d", sous: "Recette du 12 avril" }],
  ["disque", "story", "chaud", "TikTok & vidéo courte", "Écran de fin", { sur: "C'est fini", titre: "Abonnez-vous", sous: "Une nouvelle technique chaque mardi et chaque vendredi.", meta: "ENREGISTREZ POUR PLUS TARD" }],
  ["souligne", "story", "sombre", "TikTok & vidéo courte", "Trois mots", { sur: "Le principe", titre: "Chaud.\nSec.\nRapide.", sous: "Les trois conditions d'une bonne saisie. Il en manque une, c'est raté.", meta: "Détail en vidéo" }],
  ["question", "story", "clair", "TikTok & vidéo courte", "Question ouverte", { sur: "Dites-moi", titre: "Quelle recette\nvous rate\nà chaque fois ?", sous: "J'en fais une vidéo. La plus citée passe en premier." }],

  /* ══════════ Photo & création ══════════ */

  ["etapes", "a4", "chic", "Photo & création", "Préparer une séance", { titre: "Préparer\nune séance\nphoto", sous: "Une heure de préparation économise trois heures de tournage.", items: ["Le brief|Ce qu'on veut montrer, en trois phrases.", "La liste|Chaque plan noté, dans l'ordre.", "Le décor|Fonds et accessoires réunis la veille.", "La lumière|Réglée avant l'arrivée des produits."] }],
  ["fiche", "a4", "clair", "Photo & création", "Fiche technique de prise de vue", { titre: "Photographier\nun produit\nsans studio", meta: "Lumière naturelle — fond neutre — trépied indispensable", sur: "À FAIRE", sous: "À ÉVITER", items: ["Se placer près d'une fenêtre, pas devant", "Utiliser un réflecteur blanc en face", "Fermer à f/8 pour la netteté", "Le flash intégré, jamais", "Le plein soleil direct", "Les fonds à motifs"] }],
  ["notation", "carre", "clair", "Photo & création", "Avis client photo", { gros: "5/5", sur: "sur 46 avis", titre: "Séance calée en trois jours, images livrées en cinq, et exactement ce qu'on avait décrit au brief.", auteur: "Direction marketing, marque régionale", meta: "Avis vérifié — mars 2026" }],
  ["cartes", "large", "chic", "Photo & création", "Trois formules photo", { titre: "Trois formats\nde séance", sous: "Cession de droits web comprise dans les trois.", items: ["Portrait|180 €, une heure, cinq images retenues.", "Produit|480 €, demi-journée, quinze références.", "Reportage|890 €, journée complète."] }],
  ["evenement", "a3", "chic", "Photo & création", "Affiche de stage photo", { sur: "Stage", titre: "Photographier\nen lumière\nnaturelle", meta: "SAMEDI 16 MAI — 9 H À 17 H", sous: "Studio Verrier, 8 quai Vauban — huit places", cta: "180 € la journée, déjeuner compris — matériel non fourni" }],
  ["coins", "carreL", "sombre", "Photo & création", "Grand cadrage", { sur: "Série", titre: "Lumière\nrasante,\nfin de journée", sous: "Six images prises en vingt minutes, avant que ça tombe.", meta: "STUDIO VERRIER — SEPTEMBRE 2026" }],
  ["polaroid", "pin", "terre", "Photo & création", "Épingle instantané", { sur: "Coulisses", titre: "Trois heures\npour une image", emoji: "📷", meta: "Studio Verrier, mardi" }],

  /* ══════════ Mariage & famille ══════════ */

  ["horaires", "a5", "chic", "Mariage & famille", "Programme de la journée", { sur: "Samedi 12 septembre", titre: "Le programme", items: ["16 h|Cérémonie sous les chênes", "17 h 30|Vin d'honneur", "20 h|Dîner servi à table", "22 h 30|Ouverture du bal", "2 h|Soupe à l'oignon"], meta: "NAVETTE VERS LE CENTRE À 1 H ET À 3 H" }],
  ["checklist", "a5", "pastel", "Mariage & famille", "Ce qu'il faut apporter", { sur: "Pour les invités", titre: "Trois choses\nà prévoir", items: ["Des chaussures qui tiennent sur l'herbe", "Une veste, il fait frais après 22 h", "Votre réponse avant le 1er août", "Le nom de vos éventuelles allergies", "Un peu de patience pour les photos"], meta: "Le reste, on s'en occupe" }],
  ["faq", "a4", "chic", "Mariage & famille", "Questions des invités", { sur: "Vous nous demandez", titre: "Quatre réponses\navant le jour J", items: ["Y a-t-il un thème ?|Non. Venez comme vous voulez, en évitant le blanc.", "Peut-on venir avec les enfants ?|Oui, une table et une garde sont prévues.", "Où dormir ?|Trois adresses à moins de dix minutes, liste jointe.", "Liste de mariage ?|Une cagnotte, si vous y tenez. Rien n'est attendu."], meta: "Une question de plus : 06 00 00 00 00" }],
  ["tableau", "a4", "pastel", "Mariage & famille", "Budget de mariage", { titre: "Le budget,\nen clair", sous: "Pour cent vingt personnes, estimation au 1er avril.", sur: "POSTE|MONTANT", items: ["Lieu et location|4 200 €", "Traiteur, 120 couverts|8 400 €", "Boissons|1 900 €", "Musique|1 200 €", "Fleurs et décoration|900 €", "Photographe|1 400 €"], meta: "Total estimé : 18 000 € — marge de 10 % conseillée" }],
  ["frise", "a4", "chic", "Mariage & famille", "Rétroplanning de mariage", { titre: "Rétroplanning", sous: "Douze mois, cinq jalons.", items: ["J-12 mois|Lieu et date réservés.", "J-9 mois|Traiteur et photographe.", "J-6 mois|Faire-part envoyés.", "J-3 mois|Nombre définitif au traiteur.", "J-1 mois|Plan de table bouclé."], meta: "Tout ce qui glisse après J-1 mois se fera dans l'urgence" }],
  ["cadre", "a5", "chic", "Mariage & famille", "Carte de menu invité", { sur: "Menu", titre: "Dîner\ndu 12 septembre", sous: "Velouté de courge · Saint-jacques poêlées · Filet de bœuf, légumes anciens · Fromages affinés · Pièce montée", meta: "MENUS VÉGÉTARIEN ET SANS GLUTEN DISPONIBLES" }],

  /* ══════════ Mode & boutique ══════════ */

  ["tableau", "a4", "chic", "Mode & boutique", "Composition et entretien", { titre: "Composition\net entretien", sous: "Modèle Chanvre, référence CH-2026.", sur: "INFORMATION|DÉTAIL", items: ["Composition|100 % chanvre européen", "Tissage|Belgique", "Confection|Bordeaux", "Lavage|30 °C, cycle délicat", "Séchage|À plat, à l'ombre", "Repassage|Fer moyen, légèrement humide"], meta: "Traçabilité complète disponible sur la fiche produit en ligne" }],
  ["etapes", "a4", "terre", "Mode & boutique", "Fabrication d'une pièce", { titre: "D'où vient\nvotre chemise", sous: "Quatre étapes, toutes en Europe.", items: ["La culture|Chanvre cultivé sans irrigation, en France.", "Le tissage|En Belgique, chez un tisseur familial.", "La coupe|À Bordeaux, dans notre atelier.", "La confection|Sur place, par trois couturières salariées."] }],
  ["evenement", "a3", "chic", "Mode & boutique", "Affiche de vente d'atelier", { sur: "Vente d'atelier", titre: "Trois jours\nde vente\ndirecte", meta: "DU 12 AU 14 JUIN — 10 H À 19 H", sous: "Atelier Berthier, 4 rue des Forges", cta: "Prototypes, fins de série et pièces d'essai — jusqu'à -60 %" }],
  ["notation", "carre", "clair", "Mode & boutique", "Avis produit", { gros: "4,8", sur: "sur 640 avis produit", titre: "Taille juste, tissu épais sans être lourd, et la couleur n'a pas bougé après vingt lavages.", auteur: "Aline R.", meta: "Achat vérifié — modèle Chanvre" }],
  ["grille", "pin", "terre", "Mode & boutique", "Épingle vestiaire", { titre: "Six pièces,\nquinze tenues", sous: "Le vestiaire minimum, testé une saison", items: ["Chemise blanche", "Pantalon droit", "Maille fine", "Veste non doublée", "Jean brut", "Trench"], meta: "Guide complet et associations sur le blog" }],
  ["cartes", "large", "chic", "Mode & boutique", "Trois services boutique", { titre: "Trois services\ncompris", sous: "Sans supplément, sur toute pièce achetée chez nous.", items: ["Retouches|Ourlets et reprises, offerts à vie.", "Réparation|Coutures et boutons, gratuits.", "Reprise|-20 % sur la suivante si vous la rapportez."] }],

  /* ══════════ Enfance & jeunesse ══════════ */

  ["calendrier", "a4", "pastel", "Enfance & jeunesse", "Spectacle de fin d'année", { sur: "VENDREDI 26 JUIN", gros: "26", titre: "Spectacle\nde fin d'année", items: ["18 h, salle des fêtes", "Durée une heure quinze", "Entrée libre, arrivez tôt", "Buvette au profit de la coopérative"] }],
  ["grille", "a4", "vif", "Enfance & jeunesse", "Six ateliers d'été", { titre: "Six ateliers\ncet été", sous: "Du 7 juillet au 22 août, pour les 6-11 ans", items: ["Cirque", "Poterie", "Nature", "Cuisine", "Théâtre", "Sport"], meta: "Une semaine 120 €, repas compris — quotient familial appliqué" }],
  ["cadre", "a5", "clair", "Enfance & jeunesse", "Règles de la cour", { sur: "Règles de vie", titre: "Quatre règles\nde la cour", sous: "On se parle sans se moquer. On demande avant de prendre. On range ce qu'on sort. On prévient un adulte quand ça va mal.", meta: "AFFICHÉES ET RELUES CHAQUE TRIMESTRE" }],
  ["tableau", "a4", "clair", "Enfance & jeunesse", "Menu de la cantine", { titre: "Menus\nde la semaine", sous: "Semaine du 8 au 12 juin — 60 % de produits locaux.", sur: "JOUR|MENU", items: ["Lundi|Carottes râpées, poisson pané, purée", "Mardi|Salade verte, sauté de veau, pâtes", "Mercredi|Betteraves, omelette, riz", "Jeudi|Concombres, poulet rôti, haricots", "Vendredi|Melon, gratin de courgettes", "Chaque jour|Fruit ou laitage"], meta: "Menu végétarien proposé tous les jours sur inscription" }],
  ["etapes", "a4", "pastel", "Enfance & jeunesse", "Inscrire son enfant", { titre: "Inscrire\nson enfant", sous: "Comptez une semaine, dossier en main.", items: ["Le dossier|À retirer en mairie ou en ligne.", "Les pièces|Livret de famille, justificatif, vaccins.", "Le dépôt|En mairie, avant le 30 juin.", "La confirmation|Envoyée courant juillet."] }],
  ["progression", "carre", "vif", "Enfance & jeunesse", "Places restantes en stage", { sur: "Stage d'été", titre: "Il reste\nsix places", gros: "70", sous: "Sur vingt, pour la semaine du 20 au 24 juillet.", meta: "INSCRIPTION EN MAIRIE" }],

  /* ══════════ Agriculture & terroir ══════════ */

  ["chrono", "large", "nature", "Agriculture & terroir", "Calendrier des récoltes", { titre: "Ce qu'on\nrécolte, quand", sous: "Les paniers suivent, sans exception.", items: ["Printemps|Asperges, radis, fraises.", "Été|Tomates, courgettes, abricots.", "Automne|Courges, poireaux, pommes.", "Hiver|Choux, panais, betteraves."], meta: "Aucun produit hors saison, même sur demande" }],
  ["temoignage", "carre", "terre", "Agriculture & terroir", "Retour d'adhérent", { emoji: "🥕", titre: "« On ne choisit pas ce qu'il y a dans le panier. C'est justement ce qui nous a fait changer de cuisine. »", auteur: "Famille Roux", sous: "Adhérents depuis 2022" }],
  ["etapes", "a4", "nature", "Agriculture & terroir", "Rejoindre une AMAP", { titre: "Rejoindre\nun panier\nhebdomadaire", sous: "Un engagement de six mois, renouvelable.", items: ["Se renseigner|Une permanence chaque samedi à la ferme.", "S'engager|Six mois, réglés en une à trois fois.", "Récupérer|Le mardi soir, au point de dépôt.", "Participer|Deux permanences par semestre."] }],
  ["question", "carre", "nature", "Agriculture & terroir", "Sondage sur les paniers", { sur: "On vous écoute", titre: "Panier de 5 kg\nou de 8 kg\npour l'été ?", sous: "Le format qui l'emporte sera le seul proposé de juin à septembre." }],
  ["billet", "billet", "nature", "Agriculture & terroir", "Bon pour un panier", { sur: "BON POUR UN PANIER", titre: "FERME DE LA COMBE", gros: "18€", meta: "VALABLE SIX MOIS", sous: "Composition selon la saison — prévenir la veille au 05 57 00 00 00" }],
  ["polaroid", "carre", "terre", "Agriculture & terroir", "Instantané de récolte", { sur: "Ce matin", titre: "Première\nrécolte de fraises", emoji: "🍓", meta: "Parcelle du haut, 6 h 40" }],

  /* ══════════ Animaux ══════════ */

  ["chiffre", "carre", "nature", "Animaux", "Chiffre d'abandon", { sur: "Chaque été", gros: "60 000", titre: "animaux abandonnés en France", sous: "Un sur deux l'est en juillet et en août. Le refuge est plein dès la mi-juillet.", cta: "Adopter, c'est faire de la place" }],
  ["etapes", "a4", "nature", "Animaux", "Adopter au refuge", { titre: "Adopter,\nen quatre étapes", sous: "Comptez deux semaines entre la visite et le départ.", items: ["Venir|Sans rendez-vous, du mardi au samedi.", "Échanger|Une heure, pour parler de votre quotidien.", "Rencontrer|Plusieurs fois si nécessaire, sans pression.", "Repartir|Après un contrat et une visite prévue à un mois."] }],
  ["liste", "a4", "clair", "Animaux", "Conseils d'hiver", { sur: "Hiver", titre: "Cinq réflexes\nquand il gèle", items: ["Rentrer les gamelles d'eau la nuit", "Essuyer les pattes après le sel de déneigement", "Ne pas tondre, même les poils longs", "Surveiller les vieux animaux, plus fragiles", "Laisser un abri accessible aux chats du quartier"], meta: "Un abri de fortune sauve chaque hiver plusieurs chats errants" }],
  ["evenement", "a3", "chaud", "Animaux", "Affiche de collecte", { sur: "Collecte", titre: "Croquettes\net couvertures", meta: "SAMEDI 14 NOVEMBRE — 10 H À 18 H", sous: "Devant la jardinerie, route de Bassens", cta: "Croquettes, litière, couvertures propres — tout est utile" }],
  ["notation", "carre", "clair", "Animaux", "Avis vétérinaire", { gros: "4,9", sur: "sur 180 avis", titre: "On nous a expliqué chaque option et chaque prix avant de décider. Rare, et appréciable.", auteur: "Camille D.", meta: "Avis Google — avril 2026" }],
  ["cartecadeau", "carte", "nature", "Animaux", "Bon cadeau toilettage", { sur: "Bon cadeau", gros: "60 €", titre: "Toilettage complet, chien moyen", meta: "VALABLE UN AN", sous: "Sur rendez-vous — carnet de vaccination demandé." }],

  /* ══════════ Juridique & conseil ══════════ */

  ["etapes", "a4", "chic", "Juridique & conseil", "Créer une association", { titre: "Créer\nune association", sous: "Comptez trois semaines, gratuitement.", items: ["Rédiger|Des statuts courts valent mieux que longs.", "Réunir|Une assemblée constitutive, un procès-verbal.", "Déclarer|En ligne, en quinze minutes.", "Publier|Au Journal officiel, gratuit depuis 2020."] }],
  ["liste", "a4", "clair", "Juridique & conseil", "Cinq réflexes contractuels", { sur: "Avant de signer", titre: "Cinq clauses\nà lire deux fois", items: ["La durée et les conditions de résiliation", "Le prix et ce qu'il inclut vraiment", "Les pénalités de retard, dans les deux sens", "La clause de reconduction tacite", "Le tribunal compétent en cas de litige"], meta: "Ces cinq lignes règlent la quasi-totalité des litiges commerciaux" }],
  ["comparatif", "a4", "clair", "Juridique & conseil", "Salarié ou indépendant", { titre: "Salarié\nou indépendant", sur: "SALARIÉ", cta: "INDÉPENDANT", items: ["Lien de subordination|Autonomie réelle", "Congés payés|Aucun", "Chômage|Non, sauf exceptions", "Charges ~22 %|Charges ~45 %", "Rupture encadrée|Fin de mission libre"], meta: "Requalification possible si l'autonomie n'est qu'apparente" }],
  ["cadre", "a5", "chic", "Juridique & conseil", "Mention de convention d'honoraires", { sur: "Information", titre: "Convention\nd'honoraires\nobligatoire", sous: "Aucune intervention ne débute sans convention écrite précisant le montant ou le mode de calcul des honoraires, conformément à l'article 10 de la loi du 31 décembre 1971.", meta: "CABINET BERTHIER — BARREAU DE BORDEAUX" }],
  ["chiffre", "carre", "sombre", "Juridique & conseil", "Délai moyen de procédure", { sur: "Prud'hommes", gros: "18", titre: "mois en moyenne jusqu'au jugement", sous: "Sur nos dossiers 2023-2025, hors départage et hors appel.", cta: "Nous le disons dès le premier rendez-vous" }],
  ["contact", "carte", "chic", "Juridique & conseil", "Carte de rendez-vous cabinet", { sur: "Votre rendez-vous", titre: "Cabinet\nBerthier", sous: "Merci d'apporter l'ensemble des pièces demandées.", items: ["Date : ____ / ____ / ______", "Heure : ______ h ______", "Avocat : ______________", "05 56 00 00 00"], meta: "8 quai Vauban, 33000 Bordeaux" }],

  /* ══════════ Finance & assurance ══════════ */

  ["liste", "a4", "clair", "Finance & assurance", "Cinq réflexes d'assuré", { sur: "En cas de sinistre", titre: "Cinq réflexes\nà avoir", items: ["Photographier avant de toucher à quoi que ce soit", "Déclarer sous cinq jours ouvrés, deux en cas de vol", "Conserver les objets endommagés jusqu'à l'expertise", "Retrouver les factures d'origine", "Ne jamais jeter avant l'accord de l'assureur"], meta: "Jeter avant l'expertise fait perdre le droit à indemnisation" }],
  ["chrono", "large", "froid", "Finance & assurance", "Étapes d'une indemnisation", { titre: "Du sinistre\nau virement", sous: "Neuf jours en moyenne, hors expertise judiciaire.", items: ["J+0|Déclaration.", "J+2|Accusé et pièces demandées.", "J+4|Expertise si nécessaire.", "J+9|Virement."], meta: "Un point d'étape est envoyé tous les cinq jours si le délai s'allonge" }],
  ["question", "carre", "clair", "Finance & assurance", "Question d'assuré", { sur: "Idée reçue", titre: "Faut-il vraiment\nassurer\nson téléphone ?", sous: "Dans la plupart des cas, non. Voilà les trois situations où si." }],
  ["cadre", "a5", "clair", "Finance & assurance", "Mention de délai de rétractation", { sur: "Information", titre: "Quatorze jours\npour changer\nd'avis", sous: "Vous disposez d'un délai de rétractation de quatorze jours à compter de la signature, sans avoir à vous justifier ni à supporter de pénalité.", meta: "ARTICLE L.112-2-1 DU CODE DES ASSURANCES" }],
  ["tableau", "a4", "clair", "Finance & assurance", "Comparatif de franchises", { titre: "Franchises\npar garantie", sous: "Contrat multirisque habitation, formule Complète.", sur: "GARANTIE|FRANCHISE", items: ["Dégât des eaux|120 €", "Incendie|120 €", "Vol|250 €", "Bris de glace|Aucune", "Catastrophe naturelle|380 € (légale)", "Dommages électriques|120 €"], meta: "Franchise légale non modifiable pour les catastrophes naturelles" }],
  ["visite", "carte", "froid", "Finance & assurance", "Carte d'agent d'assurance", { gros: "AR", titre: "Aline Roux", sur: "AGENTE GÉNÉRALE", sous: "12 rue du Marché, Bordeaux · 05 56 00 00 00 · ORIAS 00000000" }],

  /* ══════════ Podcast, Culture, Beauté, Auto ══════════ */

  ["etapes", "a4", "sombre", "Podcast & musique", "Enregistrer un épisode", { titre: "Un épisode,\nquatre temps", sous: "Comptez huit heures pour cinquante minutes diffusées.", items: ["La préparation|Trois heures de lecture, dix questions écrites.", "L'entretien|Une heure trente, jamais coupé.", "Le montage|Trois heures, on retire les silences, pas les hésitations.", "La publication|Titre, description, chapitres."] }],
  ["question", "carre", "tech", "Podcast & musique", "Question aux auditeurs", { sur: "On vous écoute", titre: "Quel métier\nvoulez-vous\nentendre ?", sous: "Le plus cité devient l'épisode de septembre." }],
  ["cadre", "a5", "chic", "Culture & spectacle", "Consignes de salle", { sur: "Avant le lever de rideau", titre: "Trois\nconsignes", sous: "Téléphones éteints, y compris en mode silencieux. Aucune photo pendant la représentation. Les retardataires entrent au premier changement de scène.", meta: "MERCI POUR LES ARTISTES ET POUR VOS VOISINS" }],
  ["chiffre", "carre", "chic", "Culture & spectacle", "Fréquentation de saison", { sur: "Saison 2026", gros: "8 400", titre: "spectateurs sur douze soirs", sous: "Taux de remplissage de 87 %, le meilleur depuis l'ouverture.", cta: "Merci d'être venus" }],
  ["liste", "a4", "pastel", "Beauté & coiffure", "Cinq conseils d'entretien", { sur: "Entre deux rendez-vous", titre: "Cinq gestes\nqui font\ntenir la coupe", items: ["Laver à l'eau tiède, jamais chaude", "Deux shampoings par semaine au maximum", "Un masque tous les dix jours", "Protéger de la chaleur avant le séchage", "Couper les pointes tous les trois mois"], meta: "Une coupe tient trois mois si l'entretien suit, six semaines sinon" }],
  ["progression", "carre", "pastel", "Beauté & coiffure", "Avancement de forfait", { sur: "Votre forfait", titre: "Trois soins\nsur cinq", gros: "60", sous: "Il reste deux soins à utiliser avant le 31 décembre.", meta: "PRENDRE RENDEZ-VOUS AU 05 56 00 00 00" }],
  ["liste", "a4", "sombre", "Auto & mobilité", "Cinq gestes d'entretien", { sur: "Chaque mois", titre: "Cinq contrôles\nqui évitent\nla panne", items: ["Niveau d'huile, moteur froid", "Pression des pneus, à froid également", "Liquide de refroidissement", "Usure des balais d'essuie-glace", "Éclairage complet, avec quelqu'un dehors"], meta: "Cinq minutes par mois évitent la majorité des immobilisations" }],
  ["question", "carre", "sombre", "Auto & mobilité", "Question d'automobiliste", { sur: "Idée reçue", titre: "Faut-il faire\nchauffer\nson moteur ?", sous: "Plus depuis trente ans. Voilà ce qu'il faut faire à la place." }],

  /* ══════════ Papeterie, emploi, Facebook, Pinterest ══════════ */

  ["cadre", "a5", "pastel", "Carte & papeterie", "Carte de condoléances", { sur: "Avec toute notre sympathie", titre: "Nos pensées\nvous accompagnent", sous: "Nous partageons votre peine et restons à vos côtés, autant qu'il le faudra.", meta: "TOUTE L'ÉQUIPE D'AUBÉPINE" }],
  ["cadre", "a5", "vif", "Carte & papeterie", "Carte de félicitations", { sur: "Félicitations", titre: "Bravo\npour cette\nnouvelle étape", sous: "Nous savons ce que ça représente, et le travail qu'il y a derrière.", meta: "SOFIA, MARC, ALINE ET NOÉ" }],
  ["cadre", "a5", "chic", "Carte & papeterie", "Carte de départ", { sur: "Bon vent", titre: "Merci\npour ces\nhuit ans", sous: "L'atelier ne sera plus tout à fait le même. Reviens quand tu veux, la porte reste ouverte.", meta: "TOUTE L'ÉQUIPE" }],
  ["etiquette", "etiq", "chic", "Carte & papeterie", "Étiquette d'expédition", { sur: "EXPÉDIÉ PAR", gros: "AB", titre: "Atelier Berthier,\nBordeaux", sous: "Préparé à la main, sans plastique.", meta: "COMMANDE N° 0000 — MERCI !" }],
  ["checklist", "a4", "clair", "Emploi & recrutement", "Check-list de départ", { sur: "Dernier jour", titre: "Ce qu'il reste\nà faire", items: ["Restituer badge, clés et matériel", "Transmettre les dossiers en cours par écrit", "Vider les espaces personnels", "Récupérer solde de tout compte et certificat", "Demander l'attestation France Travail", "Faire le point sur la mutuelle", "Laisser une adresse personnelle"], meta: "Un départ préparé évite trois semaines d'allers-retours" }],
  ["comparatif", "a4", "clair", "Emploi & recrutement", "CDI ou CDD", { titre: "CDI\nou CDD", sur: "CDD", cta: "CDI", items: ["Durée fixée d'avance|Sans terme", "Prime de précarité 10 %|Aucune", "Rupture encadrée strictement|Démission ou licenciement", "Accès au crédit difficile|Accès facilité", "Renouvelable 2 fois|Sans limite"], meta: "Un CDD ne peut pourvoir durablement un emploi lié à l'activité normale" }],
  ["empilement", "large", "chaud", "Facebook", "Cinq informations locales", { titre: "Cinq infos\nde la semaine", sous: "Tout ce qu'il faut savoir avant samedi.", items: ["La boutique ferme lundi pour inventaire", "Le marché est déplacé place du Port", "Les inscriptions ouvrent mercredi", "La braderie se tient samedi", "Le parking reste gratuit tout le mois"], meta: "Détails à l'accueil ou au 05 56 00 00 00" }],
  ["calendrier", "large", "vif", "Facebook", "Date d'événement local", { sur: "SAMEDI 27 JUIN", gros: "27", titre: "Fête\ndu quartier", items: ["Vide-grenier dès 8 h", "Barbecue à midi, 8 € l'assiette", "Bal à 21 h, entrée libre", "Feu d'artifice à 23 h"] }],
  ["horaires", "large", "terre", "Facebook", "Horaires d'été", { sur: "Du 1er juillet au 31 août", titre: "Horaires\nd'été", items: ["Lundi|Fermé", "Mardi – vendredi|8 h – 13 h · 16 h – 20 h", "Samedi|8 h – 20 h", "Dimanche|8 h – 13 h"], meta: "FERMETURE ANNUELLE DU 15 AU 25 AOÛT" }],
  ["faq", "large", "clair", "Facebook", "Questions du quartier", { sur: "Vous nous demandez", titre: "Quatre réponses\nrapides", items: ["Faites-vous des commandes ?|Oui, la veille avant 18 h, par téléphone.", "Y a-t-il du sans gluten ?|Mercredi et samedi, en quantité limitée.", "Livrez-vous ?|Non, mais on garde vos commandes jusqu'à la fermeture.", "Acceptez-vous les tickets restaurant ?|Oui, jusqu'à 25 € par jour."], meta: "05 56 00 00 00" }],
  ["fiche", "pin", "clair", "Pinterest", "Épingle fiche pratique", { titre: "Choisir\nsa peinture\nd'intérieur", meta: "Mate, satinée ou brillante — ce que ça change vraiment", sur: "OÙ METTRE QUOI", sous: "ERREURS COURANTES", items: ["Mate au plafond, elle masque les défauts", "Satinée dans les pièces à vivre", "Brillante en cuisine et salle de bain", "Mate dans un couloir : impossible à nettoyer", "Brillante sur un mur irrégulier", "Une seule couche, jamais suffisante"] }],
  ["etapes", "pin", "terre", "Pinterest", "Épingle méthode bricolage", { titre: "Repeindre\nun meuble\nsans poncer", sous: "Quatre étapes, un week-end.", items: ["Nettoyer|Dégraissant, puis rinçage, puis séchage complet.", "Accrocher|Une sous-couche spéciale support lisse.", "Peindre|Deux couches fines valent mieux qu'une épaisse.", "Protéger|Un vernis mat, sinon ça marque en trois mois."] }],
  ["tableau", "pin", "nature", "Pinterest", "Épingle calendrier de semis", { titre: "Quand\nsemer quoi", sous: "Pour un climat tempéré, en pleine terre.", sur: "LÉGUME|PÉRIODE", items: ["Radis|Mars à septembre", "Carottes|Mars à juillet", "Haricots verts|Mai à juillet", "Épinards|Mars et août", "Salades|Mars à septembre", "Mâche|Août à octobre"], meta: "Décaler de deux semaines dans le Nord, avancer d'autant dans le Sud" }],
  ["chrono", "pin", "pastel", "Pinterest", "Épingle routine du soir", { titre: "Une heure\navant de\ndormir", sous: "Quatre gestes, dans cet ordre.", items: ["-60 min|Dernier écran.", "-45 min|Lumière baissée.", "-30 min|Rangement rapide.", "-15 min|Lecture, rien d'autre."], meta: "La régularité compte plus que la durée" }],

  /* ══════════ Derniers manques repérés au comptage ══════════ */

  ["magazine", "pin", "terre", "Pinterest", "Couverture de dossier maison", { sur: "DOSSIER", meta: "AUTOMNE 2026 — 24 PAGES", titre: "Passer\nl'hiver\nau chaud", sous: "Ce qui fait vraiment baisser la facture, et ce qui n'y change rien.", items: ["Les six vérifications d'octobre", "Isoler sans gros travaux", "Le mythe du degré en moins"] }],
  ["magazine", "pod", "vif", "Podcast & musique", "Pochette façon magazine", { sur: "SAISON 3", meta: "DOUZE ÉPISODES — DÈS SEPTEMBRE", titre: "Les gens\nqui font", sous: "Des métiers racontés par ceux qui les exercent, sans montage flatteur.", items: ["Le dernier tanneur", "La juge de proximité", "La routière de nuit"] }],
  ["journal", "large", "clair", "Facebook", "Lettre de commerçant", { sur: "LA LETTRE DU MARCHÉ", meta: "AVRIL 2026 — NUMÉRO 9", titre: "Ce qui change\nà la boulangerie", sous: "Trois informations, dont une qui va se voir dès mardi.", items: ["Nous ouvrons désormais à 6 h 30 au lieu de 7 h. La demande venait des personnes qui partent tôt travailler, et elle revenait depuis deux ans. La dernière fournée reste à 17 h.", "Le pain de seigle revient à la carte, le mercredi et le samedi uniquement. Il avait disparu faute de farine ; nous avons trouvé un moulin à quarante kilomètres.", "Enfin, nous fermerons du 10 au 31 août. C'est trois semaines, comme chaque année, et la boulangerie de la place du Port prend le relais."], cta: "12 RUE DU MARCHÉ — 05 56 00 00 00" }],
  ["colonnes", "carre", "chic", "Marque & logo", "Récit de marque", { sur: "Notre histoire", titre: "Pourquoi\nl'atelier\ns'appelle\nAubépine", sous: "La question revient assez souvent pour mériter une réponse.", items: ["L'aubépine pousse en haie, sur les terrains qu'on ne cultive pas. Elle met huit ans à donner ses premières fleurs et vit deux siècles. C'est à peu près l'inverse de ce qu'on nous conseillait de faire en ouvrant.", "Nous avons ouvert petit, sans emprunt, en attendant d'avoir des clients avant d'avoir un local. Ça a coûté deux ans de lenteur. Sept ans plus tard, l'atelier est toujours là, et il nous appartient encore."], meta: "SOFIA ET MARC — ATELIER AUBÉPINE" }],
  ["colonnes", "large", "terre", "Restauration & café", "Édito de carte", { sur: "Notre carte", titre: "Pourquoi\nelle est\naussi courte", sous: "Six plats, changés chaque semaine. C'est un choix, pas une contrainte.", items: ["Une carte de trente plats suppose des stocks, donc des produits qui attendent, donc des surgelés. Six plats permettent d'acheter le matin ce qui sera servi le midi, et de tout écouler le soir même.", "Cela veut dire que le plat que vous avez aimé ne sera peut-être plus là la semaine prochaine. C'est le seul inconvénient, et nous l'assumons depuis huit ans."], meta: "LE COMPTOIR DU PORT — 8 QUAI VAUBAN" }],
  ["cv", "cv", "froid", "CV & document", "CV secteur santé", { gros: "AR", titre: "Aline\nRoux", sur: "INFIRMIÈRE DIPLÔMÉE D'ÉTAT", sous: "06 00 00 00 00\naline@exemple.fr\nBordeaux\nN° ADELI 000000000", meta: "PARCOURS", items: ["Infirmière libérale — cabinet du Marché|2021 à aujourd'hui. Tournée de trente patients, coordination avec deux médecins traitants.", "Infirmière — CHU de Bordeaux|2016-2021. Service de chirurgie digestive, équipe de nuit pendant trois ans.", "Infirmière — clinique du Port|2014-2016. Bloc opératoire, aide instrumentiste.", "Diplôme d'État infirmier|IFSI de Bordeaux, 2014."] }],
  ["cv", "cv", "terre", "CV & document", "CV secteur bâtiment", { gros: "MB", titre: "Marc\nBerthier", sur: "MENUISIER — AGENCEUR", sous: "06 00 00 00 00\nmarc@exemple.fr\nBordeaux\nPermis B et E", meta: "PARCOURS", items: ["Chef d'atelier — Menuiserie Berthier|2015 à aujourd'hui. Quatre personnes, soixante-huit chantiers par an, zéro litige.", "Menuisier confirmé — Agencement du Sud|2009-2015. Cuisines et dressings sur mesure, pose comprise.", "Menuisier — Ateliers Roux|2005-2009. Fabrication d'escaliers et de fenêtres bois.", "CAP et BP menuiserie|CFA de Bordeaux, 2005."] }],
  ["certificat", "paysage", "terre", "Artisanat & bâtiment", "Certificat de garantie", { sur: "CERTIFICAT DE GARANTIE", titre: "Escalier chêne massif", auteur: "Marc Berthier, gérant", sous: "fabriqué et posé par nos soins, garanti dix ans contre tout défaut de fabrication ou de pose.", meta: "CHANTIER N° 2026-0184 — POSÉ LE 12 AVRIL 2026" }],
  ["certificat", "paysage", "nature", "Agriculture & terroir", "Certificat d'origine", { sur: "CERTIFICAT D'ORIGINE", titre: "Miel de châtaignier", auteur: "Sofia Bernard, apicultrice", sous: "récolté sur les ruchers de la Combe, en juillet 2026, non chauffé et non mélangé.", meta: "LOT 2026-07 — 340 POTS PRODUITS" }],
  ["tarif", "a4", "sombre", "Podcast & musique", "Tarif de studio", { sur: "STUDIO", gros: "45 €", sous: "de l'heure, ingénieur du son compris", items: ["Cabine traitée, quatre micros", "Enregistrement et mixage", "Fichiers livrés sous 48 h", "Forfait journée : 320 €", "Demi-tarif pour les associations"], cta: "Réserver un créneau" }],
  ["tarif", "a4", "chic", "Photo & création", "Forfait mariage photo", { sur: "FORFAIT MARIAGE", gros: "1 400 €", sous: "journée complète, de la préparation au bal", items: ["Dix heures de présence", "Trois cents images retouchées", "Galerie en ligne pendant un an", "Cession de droits privée illimitée", "Repérage du lieu offert"], cta: "Vérifier ma disponibilité" }],
  ["etiquette", "etiq", "vif", "Jeux & e-sport", "Étiquette de lot", { sur: "LOT DU TOURNOI", gros: "1er", titre: "Chèque de 800 €\net trophée gravé", sous: "Remis en fin de finale, sur scène.", meta: "TOURNOI D'HIVER 2026" }],
  ["etiquette", "carteV", "pastel", "Enfance & jeunesse", "Étiquette de vestiaire", { sur: "VESTIAIRE", gros: "12", titre: "Camille Durand,\ngroupe des Chênes", sous: "Merci de vérifier les affaires chaque soir.", meta: "CENTRE DE LA COMBE" }],
  ["contact", "carte", "nature", "Nature & écologie", "Carte d'association", { sur: "Association des berges", titre: "Agir\nprès de\nchez soi", sous: "Chantiers participatifs un samedi par mois.", items: ["contact@association-berges.fr", "06 00 00 00 00", "Maison de quartier, place du Port", "association-berges.fr"], meta: "Adhésion 15 € l'année — RNA W000000000" }],
  ["contact", "carte", "vif", "Jeux & e-sport", "Carte de club", { sur: "Aubépine Esport", titre: "Le local\nest ouvert", sous: "Adhésion 30 € l'année, matériel fourni.", items: ["Local : 4 rue des Forges", "contact@aubepine-esport.fr", "Mardi, mercredi, jeudi, vendredi, samedi", "aubepine-esport.fr"], meta: "Association loi 1901 — créée en 2023" }],
  ["visite", "carte", "pastel", "Beauté & coiffure", "Carte de coiffeuse", { gros: "AR", titre: "Aline Roux", sur: "COIFFEUSE — COLORISTE", sous: "Maison Beauté · 05 56 00 00 00 · 12 rue du Marché, Bordeaux" }],
  ["visite", "carte", "nature", "Animaux", "Carte de vétérinaire", { gros: "SB", titre: "Dr Sofia Bernard", sur: "VÉTÉRINAIRE", sous: "Cabinet du Port · 05 56 00 00 00 · Urgences 24 h/24 : 05 56 00 00 01" }],
  ["horaires", "a5", "chic", "Culture & spectacle", "Horaires de la médiathèque", { sur: "Médiathèque", titre: "Horaires", items: ["Lundi|Fermé", "Mardi|14 h – 18 h", "Mercredi|10 h – 18 h", "Jeudi|14 h – 18 h", "Vendredi|14 h – 19 h", "Samedi|10 h – 17 h"], meta: "GRATUIT POUR LES MOINS DE 18 ANS" }],
  ["horaires", "a5", "vif", "Mode & boutique", "Horaires de boutique", { sur: "Boutique", titre: "Nos horaires", items: ["Lundi|14 h – 19 h", "Mardi – vendredi|10 h 30 – 19 h", "Samedi|10 h – 19 h 30", "Dimanche|Fermé", "Essayages|Sur rendez-vous le lundi matin"], meta: "RETOUCHES OFFERTES SUR TOUTE PIÈCE ACHETÉE ICI" }],
  ["progression", "carre", "chic", "Culture & spectacle", "Avancement d'abonnements", { sur: "Abonnements", titre: "Quatre-vingts\npour cent\nvendus", gros: "80", sous: "Il reste soixante abonnements sur les trois cents ouverts à la vente.", meta: "BILLETTERIE : 05 56 00 00 00" }],
  ["etiquette", "etiq", "sombre", "Photo & création", "Étiquette de tirage", { sur: "TIRAGE ARGENTIQUE", gros: "4/30", titre: "Traces, série de trente\ntirages numérotés", sous: "Papier baryté, signé au dos par l'auteur.", meta: "STUDIO VERRIER — 2026" }],
  ["souligne", "carre", "vif", "Jeux & e-sport", "Devise d'équipe", { sur: "Notre devise", titre: "Jouer.\nApprendre.\nRecommencer.", sous: "Le classement vient après, et il vient tout seul.", meta: "AUBÉPINE ESPORT — DEPUIS 2023" }],
  ["chiffre", "carre", "pastel", "Mariage & famille", "Compte à rebours en chiffre", { sur: "Avant le grand jour", gros: "30", titre: "jours, et il reste le plan de table", sous: "Les alliances sont prêtes. Le reste suivra, comme toujours.", cta: "12 septembre 2026" }],
  ["liste", "a4", "terre", "Mode & boutique", "Cinq conseils d'entretien", { sur: "Faire durer", titre: "Cinq gestes\nqui doublent\nla durée de vie", items: ["Laver moins souvent, aérer davantage", "Toujours à 30 °C, cycle délicat", "Sécher à plat, jamais au sèche-linge", "Réparer dès le premier fil tiré", "Ranger plié, pas sur cintre, pour les mailles"], meta: "Retouches et réparations offertes à vie sur nos pièces" }],
  ["polaroid", "carre", "nature", "Nature & écologie", "Instantané de chantier nature", { sur: "Samedi", titre: "Trois cents mètres\nde haie replantés", emoji: "🌱", meta: "Berges du Port, novembre" }],

];
