// Banque de photos du studio Design — images RÉELLES sous licence CC0
// (domaine public : usage commercial libre, sans attribution, sans restriction
// de redistribution). Récupérées via Openverse, redimensionnées et servies
// depuis /public/stock — donc en même origine, compatible avec la CSP stricte.
//
// Ces photos ne sont PAS recolorables : on les insère telles quelles, comme une
// image importée (filtres, rognage, ombre et export passent par le calque image).

export type StockPhoto = {
  id: string;
  cat: string;
  label: string;
  w: number;
  h: number;
  kw: string; // mots-clés normalisés (sans accents) pour la recherche
};

export const PHOTO_CATEGORIES: { id: string; label: string }[] = [
  { id: "nature", label: "Nature" },
  { id: "food", label: "Nourriture" },
  { id: "animals", label: "Animaux" },
  { id: "sport", label: "Sport" },
  { id: "city", label: "Ville & voyage" },
  { id: "objects", label: "Objets" },
  { id: "tech", label: "Tech" },
  { id: "weather", label: "Météo & ciel" },
  { id: "texture", label: "Textures & fonds" },
  { id: "business", label: "Bureau & travail" },
  { id: "daily", label: "Objets du quotidien" },
];

export const PHOTOS: StockPhoto[] = [
  { id: "nature-000", cat: "nature", label: "Snow Covered Mountain Landscape", w: 900, h: 720, kw: "snow covered mountain landscape mountain landscape ice landscape mountains publicdomain snow nature" },
  { id: "nature-001", cat: "nature", label: "Mount Everest Mountain Landscape", w: 900, h: 601, kw: "mount everest mountain landscape mountain landscape amadablam bluesky clouds forest ice landscape nature" },
  { id: "nature-002", cat: "nature", label: "Snow Covered Mountain Landscape", w: 900, h: 600, kw: "snow covered mountain landscape mountain landscape bluesky ice landscape mountain outdoor publicdomain nature" },
  { id: "nature-003", cat: "nature", label: "Backpackers Viewing Mountain Landscape", w: 900, h: 600, kw: "backpackers viewing mountain landscape mountain landscape backpacker bluesky hiker landscape mountain outdoor nature" },
  { id: "nature-004", cat: "nature", label: "Cloudy Mountain Landscape", w: 900, h: 598, kw: "cloudy mountain landscape mountain landscape cloudy fog hazy hills landscape mountain nature" },
  { id: "nature-005", cat: "nature", label: "Hiker with Backpack on Mountain Landscape", w: 900, h: 655, kw: "hiker with backpack on mountain landscape mountain landscape backpack backpacker hiker hills human landscape nature" },
  { id: "nature-006", cat: "nature", label: "Road Between Mountainous Landscape", w: 900, h: 600, kw: "road between mountainous landscape mountain landscape bluesky clouds cumulus fence grass guardrail nature" },
  { id: "nature-007", cat: "nature", label: "forest trees and ferns, Vancouver", w: 900, h: 463, kw: "forest trees and ferns, vancouver forest trees portra nature" },
  { id: "nature-008", cat: "nature", label: "Forest Trees Reflected in a Pond", w: 900, h: 598, kw: "forest trees reflected in a pond forest trees forest lake outdoor pond publicdomain reflection nature" },
  { id: "nature-009", cat: "nature", label: "Felled Forest Trees", w: 900, h: 600, kw: "felled forest trees forest trees felledtrees forest logs publicdomain trees nature" },
  { id: "nature-010", cat: "nature", label: "Canopy of Forest Trees", w: 900, h: 675, kw: "canopy of forest trees forest trees background canopy environment environmentalscience forest nature nature" },
  { id: "nature-011", cat: "nature", label: "Forest Trees on Hillside", w: 900, h: 601, kw: "forest trees on hillside forest trees background forest grass hill hillside landscape nature" },
  { id: "nature-012", cat: "nature", label: "forest tree close up", w: 900, h: 531, kw: "forest tree close up forest trees portra nature" },
  { id: "nature-013", cat: "nature", label: "forest-trees-hiker-hiking", w: 900, h: 600, kw: "forest-trees-hiker-hiking forest trees nature" },
  { id: "nature-014", cat: "nature", label: "Rockaway Sunset Sky", w: 900, h: 522, kw: "rockaway sunset sky sunset sky beach ca circularpolarizer cloudy fall filter nature" },
  { id: "nature-015", cat: "nature", label: "Sunset Sky", w: 900, h: 600, kw: "sunset sky sunset sky clouds guy looking people rocks sky nature" },
  { id: "nature-016", cat: "nature", label: "Sunset Sky", w: 900, h: 601, kw: "sunset sky sunset sky aerial airplane flying ocean sea sky nature" },
  { id: "nature-017", cat: "nature", label: "Day 220 - “Clouds come floating into my life, no lon", w: 900, h: 600, kw: "day 220 - “clouds come floating into my life, no longer to c sunset sky 2012 366project a77 sunset nature" },
  { id: "nature-018", cat: "nature", label: "Sunset Sky", w: 900, h: 600, kw: "sunset sky sunset sky agriculture clouds countryside farm field grass nature" },
  { id: "nature-019", cat: "nature", label: "Sunset Sky", w: 900, h: 600, kw: "sunset sky sunset sky architecture city goldengatebridge mountains red sanfrancisco nature" },
  { id: "nature-020", cat: "nature", label: "Sunset Sky", w: 900, h: 581, kw: "sunset sky sunset sky clouds field hills landscape mountains nature nature" },
  { id: "nature-021", cat: "nature", label: "People on Beach with Ocean Waves", w: 900, h: 600, kw: "people on beach with ocean waves ocean waves beach cloudy coast ocean overcast people nature" },
  { id: "nature-022", cat: "nature", label: "Blue Ocean Waves", w: 900, h: 600, kw: "blue ocean waves ocean waves background bluesky bluewater horizon ocean outdoor nature" },
  { id: "nature-023", cat: "nature", label: "Ocean Waves on a Sandy Beach", w: 900, h: 675, kw: "ocean waves on a sandy beach ocean waves beach coast coastal landscape ocean outdoor nature" },
  { id: "nature-024", cat: "nature", label: "Ocean Waves Hitting an Outcrop", w: 900, h: 600, kw: "ocean waves hitting an outcrop ocean waves ocean outcrop outdoor publicdomain rock sea nature" },
  { id: "nature-025", cat: "nature", label: "Strong Ocean Waves on Beach", w: 900, h: 600, kw: "strong ocean waves on beach ocean waves beach blackandwhite clouds coast monochrome ocean nature" },
  { id: "nature-026", cat: "nature", label: "Rocky Beach with Ocean Waves", w: 900, h: 599, kw: "rocky beach with ocean waves ocean waves beach clouds ocean outdoor publicdomain puddles nature" },
  { id: "nature-027", cat: "nature", label: "Ocean Wave Splashing Against Rocks", w: 900, h: 506, kw: "ocean wave splashing against rocks ocean waves ocean outcrop outdoor publicdomain rock shore nature" },
  { id: "nature-028", cat: "nature", label: "background waterfalls magnificent", w: 900, h: 506, kw: "background waterfalls magnificent waterfall landscape water waterfall nature" },
  { id: "nature-029", cat: "nature", label: "Waterfall Trail on Fossil Creek", w: 900, h: 598, kw: "waterfall trail on fossil creek waterfall arizona campverde canyon coconinonationalforest desert forest nature" },
  { id: "nature-030", cat: "nature", label: "Waterfall Trail on Fossil Creek", w: 900, h: 598, kw: "waterfall trail on fossil creek waterfall arizona campverde canyon coconinonationalforest creek desert nature" },
  { id: "nature-031", cat: "nature", label: "Swift River Waterfall", w: 900, h: 675, kw: "swift river waterfall waterfall erosion geology landscape maine mothernature nature nature" },
  { id: "nature-032", cat: "nature", label: "Waterfall Trail on Fossil Creek", w: 900, h: 598, kw: "waterfall trail on fossil creek waterfall arizona campverde canyon coconinonationalforest desert forest nature" },
  { id: "nature-033", cat: "nature", label: "Waterfall Trail on Fossil Creek", w: 900, h: 598, kw: "waterfall trail on fossil creek waterfall arizona campverde canyon coconinonationalforest desert forest nature" },
  { id: "nature-034", cat: "nature", label: "Waterfall Trail on Fossil Creek", w: 900, h: 598, kw: "waterfall trail on fossil creek waterfall arizona campverde canyon coconinonationalforest desert forest nature" },
  { id: "nature-035", cat: "nature", label: "Green Leaves", w: 900, h: 600, kw: "green leaves green leaves big brilliant colorful garden green layers nature" },
  { id: "nature-036", cat: "nature", label: "Green Leaves", w: 900, h: 600, kw: "green leaves green leaves fujifilm garden green leaves park summer nature" },
  { id: "nature-037", cat: "nature", label: "Creative tropical green leaves layout. Tropical palm", w: 900, h: 600, kw: "creative tropical green leaves layout. tropical palm backgro green leaves abstract area art artificial asian background nature" },
  { id: "nature-038", cat: "nature", label: "Creative tropical green leaves layout. Tropical palm", w: 900, h: 600, kw: "creative tropical green leaves layout. tropical palm backgro green leaves abstract art artificial asian background botanical nature" },
  { id: "nature-039", cat: "nature", label: "Closeup of Green Leaves", w: 900, h: 675, kw: "closeup of green leaves green leaves closeup green leaves macro outdoor plant nature" },
  { id: "nature-040", cat: "nature", label: "Purple Flowers with Green Leaves", w: 900, h: 675, kw: "purple flowers with green leaves green leaves flowers leaves nature outdoor petals plant nature" },
  { id: "nature-041", cat: "nature", label: "Yellow Flowers with Green Leaves", w: 900, h: 675, kw: "yellow flowers with green leaves green leaves flowers green macro nature plant publicdomain nature" },
  { id: "nature-042", cat: "nature", label: "art-desert-dunes-bw", w: 900, h: 602, kw: "art-desert-dunes-bw desert dunes nature" },
  { id: "nature-043", cat: "nature", label: "Free desert dunes sand fabric", w: 900, h: 602, kw: "free desert dunes sand fabric desert dunes desert desert sand dunes fabric sand sand dunes nature" },
  { id: "nature-044", cat: "nature", label: "Rolling desert dunes covered fog", w: 900, h: 506, kw: "rolling desert dunes covered fog desert dunes desert desert cloud desert night desktop wallpaper nature sand dunes nature" },
  { id: "nature-045", cat: "nature", label: "Silhouette of a Camel in the desert dunes.", w: 900, h: 600, kw: "silhouette of a camel in the desert dunes. desert dunes afterglow camel desert dusk sky sunset nature" },
  { id: "nature-046", cat: "nature", label: "Mongolian Gobi desert dune 9", w: 900, h: 506, kw: "mongolian gobi desert dune 9 desert dunes nature" },
  { id: "nature-047", cat: "nature", label: "Mongolian Gobi desert dune 156", w: 900, h: 506, kw: "mongolian gobi desert dune 156 desert dunes nature" },
  { id: "nature-048", cat: "nature", label: "Mongolian Gobi desert dune (3)", w: 900, h: 421, kw: "mongolian gobi desert dune (3) desert dunes nature" },
  { id: "nature-049", cat: "nature", label: "Trout Lake reflection", w: 900, h: 675, kw: "trout lake reflection lake reflection cameraphone eastvan n70 reflection shozu troutlake nature" },
  { id: "nature-050", cat: "nature", label: "264 vilnius Balžis Lake Reflection", w: 900, h: 612, kw: "264 vilnius balzis lake reflection lake reflection abstract balu017eislake balzislake cloud lietuva lithuania nature" },
  { id: "nature-051", cat: "nature", label: "Lake Reflection", w: 900, h: 601, kw: "lake reflection lake reflection autumn calm clouds day fall forest nature" },
  { id: "nature-052", cat: "nature", label: "Whipple Dam Lake reflective", w: 900, h: 675, kw: "whipple dam lake reflective lake reflection nature" },
  { id: "nature-053", cat: "nature", label: "306 vilnius Balžis Lake Reflection", w: 900, h: 581, kw: "306 vilnius balzis lake reflection lake reflection balu017eislake balzislake lietuva lithuania reflection vilnius nature" },
  { id: "nature-054", cat: "nature", label: "Davidof Lake Reflection-Tongass-DJS-07", w: 900, h: 675, kw: "davidof lake reflection-tongass-djs-07 lake reflection scenic nature" },
  { id: "nature-055", cat: "nature", label: "Lake Reflection", w: 900, h: 600, kw: "lake reflection lake reflection day forest lake landscape mirror natural nature" },
  { id: "nature-056", cat: "nature", label: "field-flowers-yellow-agriculture", w: 900, h: 601, kw: "field-flowers-yellow-agriculture field flowers blue commercialphotography crop edgregory farm farming nature" },
  { id: "nature-057", cat: "nature", label: "Field Flowers", w: 900, h: 589, kw: "field flowers field flowers field flowers nature spring summer yellow nature" },
  { id: "food-058", cat: "food", label: "Variety of fresh fruits on organic food night market", w: 900, h: 600, kw: "variety of fresh fruits on organic food night market. bali i fresh fruit agriculture air asia asian assorted background nourriture" },
  { id: "food-059", cat: "food", label: "Fresh fruit 4 kids", w: 900, h: 675, kw: "fresh fruit 4 kids fresh fruit bananas cart corn free grocery oranges nourriture" },
  { id: "food-060", cat: "food", label: "Behold The Fresh Fruit", w: 900, h: 599, kw: "behold the fresh fruit fresh fruit garden veggies nourriture" },
  { id: "food-061", cat: "food", label: "Fresh Fruit", w: 900, h: 600, kw: "fresh fruit fresh fruit alcohol beverage bottle drink food fresh nourriture" },
  { id: "food-062", cat: "food", label: "Fresh Fruit", w: 900, h: 600, kw: "fresh fruit fresh fruit assortment background bag basket berries colorful nourriture" },
  { id: "food-063", cat: "food", label: "Free pile fresh fruits outdoors", w: 900, h: 600, kw: "free pile fresh fruits outdoors fresh fruit fresh produce fruit fruit market greengrocery nature nature photo nourriture" },
  { id: "food-064", cat: "food", label: "Vegetable Harvest", w: 900, h: 675, kw: "vegetable harvest vegetables vegetable nourriture" },
  { id: "food-065", cat: "food", label: "Accidental Unintended Vegetable Garden", w: 900, h: 675, kw: "accidental unintended vegetable garden vegetables garden strawberryaz vegetable agriculture environment farm nourriture" },
  { id: "food-066", cat: "food", label: "2011.05 - 'Photo of a single graffiti written tag on", w: 900, h: 600, kw: "2011.05 - 'photo of a single graffiti written tag on a stone vegetables 952011 amsterdam city culture forintyard graffiti nourriture" },
  { id: "food-067", cat: "food", label: "Arabic-Shells-Dips-Sauces-Dumplings-Appetizers-Veget", w: 900, h: 675, kw: "arabic-shells-dips-sauces-dumplings-appetizers-vegetables-16 vegetables nourriture" },
  { id: "food-068", cat: "food", label: "Ivy vegetation on the facade of an old residential h", w: 900, h: 675, kw: "ivy vegetation on the facade of an old residential house + t vegetables amsterdam city december ivy light nature nourriture" },
  { id: "food-069", cat: "food", label: "2013.06 - 'Green urban Nature', vegetation along the", w: 900, h: 675, kw: "2013.06 - 'green urban nature', vegetation along the housebo vegetables 2013 amsterdam city gate green photo nourriture" },
  { id: "food-070", cat: "food", label: "Coffee Cup with Coffee on Red Background", w: 900, h: 506, kw: "coffee cup with coffee on red background coffee cup brown coffee coffeecup cup drunk liquid nourriture" },
  { id: "food-071", cat: "food", label: "black-and-white-coffee-cup-apple", w: 900, h: 601, kw: "black-and-white-coffee-cup-apple coffee cup 35mm 50mm apple bw camera coffee nourriture" },
  { id: "food-072", cat: "food", label: "black-and-white-coffee-cup-mug", w: 900, h: 601, kw: "black-and-white-coffee-cup-mug coffee cup business bw coffee commercialphotography desk edgregory nourriture" },
  { id: "food-073", cat: "food", label: "Girl holding christmas coffee cup", w: 900, h: 600, kw: "girl holding christmas coffee cup coffee cup background cafe casual christmas city clothing nourriture" },
  { id: "food-074", cat: "food", label: "Coffee cup", w: 900, h: 600, kw: "coffee cup coffee cup nourriture" },
  { id: "food-075", cat: "food", label: "coffee-cup-mug-spoon", w: 900, h: 600, kw: "coffee-cup-mug-spoon coffee cup nourriture" },
  { id: "food-076", cat: "food", label: "Bread Bakery", w: 900, h: 675, kw: "bread bakery bread bakery bakery baking baskets bread food loafs nourriture" },
  { id: "food-077", cat: "food", label: "F & S Maranto Italian Bread Bakery, 244 Pearl Street", w: 900, h: 675, kw: "f & s maranto italian bread bakery, 244 pearl street, baltim bread bakery bakery baltimore baltimorecity industrialbuilding maryland pearlstreet nourr" },
  { id: "food-078", cat: "food", label: "Free big bread bakery shop", w: 900, h: 600, kw: "free big bread bakery shop bread bakery bakery bakery shop bread food free shop nourriture" },
  { id: "food-079", cat: "food", label: "Wrapping sliced bread. Bakery, San", w: 900, h: 691, kw: "wrapping sliced bread. bakery, san bread bakery art building factory great depression bread lines man person nourriture" },
  { id: "food-082", cat: "food", label: "Breakfast Table", w: 900, h: 600, kw: "breakfast table breakfast table basket breakfast coffee croissant food hotel nourriture" },
  { id: "food-083", cat: "food", label: "Free breakfast table food image", w: 900, h: 600, kw: "free breakfast table food image breakfast table breakfast food free nutrition table nourriture" },
  { id: "food-084", cat: "food", label: "Breakfast table", w: 900, h: 831, kw: "breakfast table breakfast table breakfast breakfast bowl breakfast table correct food bowl milk nourriture" },
  { id: "food-085", cat: "food", label: "Breakfast Table", w: 900, h: 639, kw: "breakfast table breakfast table apple bakery bakery table bread breakfast carbohydrate nourriture" },
  { id: "food-086", cat: "food", label: "overhead shot breakfast table pancakes", w: 900, h: 600, kw: "overhead shot breakfast table pancakes breakfast table breakfast cafe coffee dessert food hot chocolate nourriture" },
  { id: "food-087", cat: "food", label: "Breakfast Table Tomatoes", w: 900, h: 600, kw: "breakfast table tomatoes breakfast table brunch cafe food photo plant table nourriture" },
  { id: "food-088", cat: "food", label: "Autumn Berries Autumn Skies Autumn Trees", w: 900, h: 600, kw: "autumn berries autumn skies autumn trees berries autumn aylesford berries carmelite flickrexplore thefriarsaylesford nourriture" },
  { id: "food-089", cat: "food", label: "Rowan berries.", w: 900, h: 633, kw: "rowan berries. berries cco freephotos geotagged nature panasonicdmcfz200 redleaves nourriture" },
  { id: "food-090", cat: "food", label: "Red Berries", w: 900, h: 675, kw: "red berries berries nourriture" },
  { id: "food-091", cat: "food", label: "Berry Creek Fog", w: 900, h: 568, kw: "berry creek fog berries a7r2 berry creek fog hdr mist nourriture" },
  { id: "food-092", cat: "food", label: "Coffea canephora berries", w: 900, h: 675, kw: "coffea canephora berries berries nourriture" },
  { id: "food-093", cat: "food", label: "Goji berries", w: 900, h: 598, kw: "goji berries berries nourriture" },
  { id: "food-094", cat: "food", label: "Co-worker Monalisa holding a paper cup of coffee, sa", w: 900, h: 584, kw: "co-worker monalisa holding a paper cup of coffee, salad bowl salad bowl cafe chicago coffee cosibreadrestaurant coworkerholdingapapercupofcoffee cup n" },
  { id: "food-095", cat: "food", label: "<div class='fn'> Salad bowl (Saladier)</div>", w: 900, h: 640, kw: "<div class='fn'> salad bowl (saladier)</div> salad bowl nourriture" },
  { id: "food-096", cat: "food", label: "<div class='fn'> Salad bowl (Saladier) (one of six) ", w: 900, h: 541, kw: "<div class='fn'> salad bowl (saladier) (one of six) (part of salad bowl nourriture" },
  { id: "food-097", cat: "food", label: "Salad Bowl", w: 900, h: 600, kw: "salad bowl salad bowl bean bowl colorful corn dish food nourriture" },
  { id: "food-905", cat: "food", label: "Pasta Dish", w: 900, h: 600, kw: "pasta dish pasta dish dish food macaroni pasta photo plate nourriture" },
  { id: "food-906", cat: "food", label: "Colorful ingredients pasta dish", w: 900, h: 900, kw: "colorful ingredients pasta dish pasta dish cooking fresh food italian italian food pasta raw pasta nourriture" },
  { id: "animals-098", cat: "animals", label: "Office dog portraits", w: 900, h: 675, kw: "office dog portraits dog portrait animaux" },
  { id: "animals-099", cat: "animals", label: "Office dog portraits", w: 900, h: 675, kw: "office dog portraits dog portrait animaux" },
  { id: "animals-100", cat: "animals", label: "Office dog portraits", w: 900, h: 675, kw: "office dog portraits dog portrait animaux" },
  { id: "animals-101", cat: "animals", label: "Office dog portraits", w: 900, h: 675, kw: "office dog portraits dog portrait animaux" },
  { id: "animals-102", cat: "animals", label: "Office dog portraits", w: 900, h: 675, kw: "office dog portraits dog portrait animaux" },
  { id: "animals-103", cat: "animals", label: "Office dog portraits", w: 900, h: 675, kw: "office dog portraits dog portrait animaux" },
  { id: "animals-104", cat: "animals", label: "Free dog portrait monochrome photo", w: 900, h: 600, kw: "free dog portrait monochrome photo dog portrait dog dog adoption dog breed dog portrait portrait animaux" },
  { id: "animals-105", cat: "animals", label: "Outdoor tabby cat, animal image", w: 900, h: 600, kw: "outdoor tabby cat, animal image cat animal animal background cat cat photo tabby cat animaux" },
  { id: "animals-106", cat: "animals", label: "Cute striped cat, animal image", w: 900, h: 600, kw: "cute striped cat, animal image cat animal animal background cat cute tabby cat animaux" },
  { id: "animals-107", cat: "animals", label: "Colorful abstract cat, animal hand", w: 900, h: 900, kw: "colorful abstract cat, animal hand cat animal abstract abstract animal abstract vector animals cat cat abstract animaux" },
  { id: "animals-108", cat: "animals", label: "Cute ginger cat, animal image", w: 900, h: 719, kw: "cute ginger cat, animal image cat animal animal cat cute ginger cat orange orange cat animaux" },
  { id: "animals-109", cat: "animals", label: "Outdoor tabby cat, animal image", w: 900, h: 600, kw: "outdoor tabby cat, animal image cat animal animal background cat cat kittens cat outdoor cute animaux" },
  { id: "animals-110", cat: "animals", label: "Outdoor tabby cat, animal image", w: 900, h: 600, kw: "outdoor tabby cat, animal image cat animal animal background cat cute outdoor cats public animaux" },
  { id: "animals-111", cat: "animals", label: "Cute ginger cat, animal image", w: 900, h: 587, kw: "cute ginger cat, animal image cat animal animal cat cute ginger cat orange orange cat animaux" },
  { id: "animals-112", cat: "animals", label: "Bird Wildlife", w: 900, h: 600, kw: "bird wildlife bird wildlife animal bird bokeh branch feathers forest animaux" },
  { id: "animals-113", cat: "animals", label: "bird-wildlife-blue-sky", w: 900, h: 596, kw: "bird-wildlife-blue-sky bird wildlife animaux" },
  { id: "animals-114", cat: "animals", label: "Bird Wildlife", w: 900, h: 802, kw: "bird wildlife bird wildlife animal beak bird feathers grass habitat animaux" },
  { id: "animals-115", cat: "animals", label: "Bird Wildlife", w: 900, h: 600, kw: "bird wildlife bird wildlife animal beak bird blackbellied closeup eye animaux" },
  { id: "animals-116", cat: "animals", label: "Bird Wildlife", w: 900, h: 506, kw: "bird wildlife bird wildlife animal background bird blue coastal feather animaux" },
  { id: "animals-117", cat: "animals", label: "Bird Wildlife", w: 900, h: 623, kw: "bird wildlife bird wildlife animal beak beautiful bird blue coastal animaux" },
  { id: "animals-118", cat: "animals", label: "Bird Wildlife", w: 900, h: 600, kw: "bird wildlife bird wildlife animal beak bird birdwatching branch egret animaux" },
  { id: "animals-119", cat: "animals", label: "Horses Field", w: 900, h: 600, kw: "horses field horse field background bokeh eating equestrian equine farm animaux" },
  { id: "animals-120", cat: "animals", label: "Free horse field fog image", w: 900, h: 600, kw: "free horse field fog image horse field animal fog free horse horse field horses field mist animaux" },
  { id: "animals-121", cat: "animals", label: "Plow Horse Field (1870–1874) Stanislas", w: 900, h: 504, kw: "plow horse field (1870–1874) stanislas horse field field horse painting oil painting painting vintage animal animaux" },
  { id: "animals-122", cat: "animals", label: "Horses field Peter Hansen", w: 900, h: 652, kw: "horses field peter hansen horse field animal art horses person peter hansen watercolor field animaux" },
  { id: "animals-123", cat: "animals", label: "Free scenic view horses field", w: 900, h: 407, kw: "free scenic view horses field horse field farm farm animals grassy field green meadow horse horse stable animaux" },
  { id: "animals-124", cat: "animals", label: "Happy brown horse field", w: 900, h: 600, kw: "happy brown horse field horse field arabian horse free horse images happy horse horse horse head pferdeportrait animaux" },
  { id: "animals-125", cat: "animals", label: "Chestnut horse field", w: 900, h: 599, kw: "chestnut horse field horse field animal brown horse horse horse images horse riding horse running animaux" },
  { id: "animals-126", cat: "animals", label: "Butterfly Insect", w: 900, h: 600, kw: "butterfly insect butterfly insect black blossom bokeh bug butterfly closeup animaux" },
  { id: "animals-127", cat: "animals", label: "Butterfly Insect", w: 900, h: 676, kw: "butterfly insect butterfly insect butterfly flowers garden insect nature animaux" },
  { id: "animals-128", cat: "animals", label: "Butterfly Insect", w: 900, h: 596, kw: "butterfly insect butterfly insect butterfly flower insect animaux" },
  { id: "animals-129", cat: "animals", label: "Butterfly Insect", w: 900, h: 600, kw: "butterfly insect butterfly insect bee blossom bokeh bug butterfly closeup animaux" },
  { id: "sport-130", cat: "sport", label: "running track", w: 900, h: 662, kw: "running track running track harrow harrowonthehill northwickpark competition daylight fence sport" },
  { id: "sport-131", cat: "sport", label: "running track", w: 900, h: 675, kw: "running track running track harrow harrowonthehill northwickpark sport" },
  { id: "sport-132", cat: "sport", label: "Running Track", w: 900, h: 600, kw: "running track running track fast field lane outdoors race running sport" },
  { id: "sport-133", cat: "sport", label: "Empty running track field daytime", w: 900, h: 600, kw: "empty running track field daytime running track athletic tracks race track run marathon running running track sports running track sport" },
  { id: "sport-134", cat: "sport", label: "Empty running track field", w: 900, h: 602, kw: "empty running track field running track athletics track background marathon run track running running track sport" },
  { id: "sport-135", cat: "sport", label: "Free close texture running track", w: 900, h: 675, kw: "free close texture running track running track competition race track run race run track running ground running track sport" },
  { id: "sport-136", cat: "sport", label: "La famiglia *", w: 900, h: 701, kw: "la famiglia * bicycle sport デンマーク コペンハーゲン advocacy” bicycle bike bikeadvocacy sport" },
  { id: "sport-137", cat: "sport", label: "Phillips Academy students cycling, c. 1900", w: 900, h: 687, kw: "phillips academy students cycling, c. 1900 bicycle sport 1900s athletics bicycle phillipsacademy sports sport" },
  { id: "sport-138", cat: "sport", label: "Vintage Retro Bicycle on the beach.", w: 900, h: 600, kw: "vintage retro bicycle on the beach. bicycle sport ancient antique basket beach bicycle bike sport" },
  { id: "sport-139", cat: "sport", label: "Crown Victoria: Bellingham, WA Police", w: 900, h: 506, kw: "crown victoria: bellingham, wa police bicycle sport bellinghampolice bellinghampolicecrownvic bellinghamwa bellinghamwapolice bicycle bike sport" },
  { id: "sport-140", cat: "sport", label: "MotoX racing.", w: 900, h: 573, kw: "motox racing. bicycle sport cco dirtbikes freephotos motorbikeracing motorbikes motorcross sport" },
  { id: "sport-141", cat: "sport", label: "155017-J-Bike", w: 900, h: 675, kw: "155017-j-bike bicycle sport active activity adult adventure bicycle bike sport" },
  { id: "sport-142", cat: "sport", label: "Swimming pool in the Spree", w: 900, h: 603, kw: "swimming pool in the spree swimming pool 2d agua alemania allemagne azul berlin sport" },
  { id: "sport-143", cat: "sport", label: "swimming pool", w: 900, h: 675, kw: "swimming pool swimming pool blue light pool swim underwater water sport" },
  { id: "sport-144", cat: "sport", label: "Swimming pool", w: 900, h: 601, kw: "swimming pool swimming pool ecoresort hue hueresort hueriverside hueriversideresort perfumeriver sport" },
  { id: "sport-145", cat: "sport", label: "Crystal Clear Swimming Pool Water with Diving Board", w: 900, h: 600, kw: "crystal clear swimming pool water with diving board swimming pool blue bluebackground clear diving divingboard pool sport" },
  { id: "sport-146", cat: "sport", label: "Outdoor Swimming Pool at Villa", w: 900, h: 603, kw: "outdoor swimming pool at villa swimming pool dusk outdoor outdoorpool pool publicdomain reflection sport" },
  { id: "sport-147", cat: "sport", label: "swimming pool", w: 900, h: 675, kw: "swimming pool swimming pool pool reflection relax water sport" },
  { id: "sport-148", cat: "sport", label: "Yoga Fitness", w: 900, h: 600, kw: "yoga fitness yoga fitness blue exercise fitness girl health lake sport" },
  { id: "sport-149", cat: "sport", label: "Yoga Fitness", w: 900, h: 600, kw: "yoga fitness yoga fitness athlete clouds exercise fashion fitness girl sport" },
  { id: "sport-150", cat: "sport", label: "Yoga Fitness", w: 900, h: 600, kw: "yoga fitness yoga fitness beach exercise fitness girl health ocean sport" },
  { id: "sport-151", cat: "sport", label: "Yoga Fitness", w: 900, h: 600, kw: "yoga fitness yoga fitness beach blue exercise fitness girl health sport" },
  { id: "sport-152", cat: "sport", label: "A fit pregnant woman", w: 900, h: 600, kw: "a fit pregnant woman yoga fitness baby back belly birth care child sport" },
  { id: "sport-153", cat: "sport", label: "Landscape Mountains", w: 900, h: 600, kw: "landscape mountains yoga fitness adventure cliffs exercise fitness girl health sport" },
  { id: "sport-154", cat: "sport", label: "Crowded School Football Stadium", w: 900, h: 600, kw: "crowded school football stadium football stadium americanflag bluesky crowd football footballgame game sport" },
  { id: "sport-155", cat: "sport", label: "Aerial view of Westmoor High School and football sta", w: 900, h: 601, kw: "aerial view of westmoor high school and football stadium in football stadium sport" },
  { id: "city-156", cat: "city", label: "City skyline with Skytower", w: 900, h: 547, kw: "city skyline with skytower city skyline auckland aucklandskytower cco ferrybuildingauckland freephotos geotagged ville & voyage" },
  { id: "city-157", cat: "city", label: "City skyline with Auckland NZ", w: 900, h: 548, kw: "city skyline with auckland nz city skyline auckland cco ferrybuildingauckland freephotos geotagged harbourcruisesauckland ville & voyage" },
  { id: "city-158", cat: "city", label: "Toronto City Skyline", w: 900, h: 596, kw: "toronto city skyline city skyline cntower toronto torontocityskyline ville & voyage" },
  { id: "city-159", cat: "city", label: "Toronto City Skyline", w: 900, h: 596, kw: "toronto city skyline city skyline cntower toronto torontocityskyline ville & voyage" },
  { id: "city-160", cat: "city", label: "20160109 Taoyuan City Skyline", w: 900, h: 601, kw: "20160109 taoyuan city skyline city skyline ville & voyage" },
  { id: "city-161", cat: "city", label: "Cebu city skyline 2025", w: 900, h: 675, kw: "cebu city skyline 2025 city skyline ville & voyage" },
  { id: "city-162", cat: "city", label: "city-people-street-architecture", w: 900, h: 598, kw: "city-people-street-architecture street architecture ville & voyage" },
  { id: "city-163", cat: "city", label: "Street Architecture", w: 900, h: 900, kw: "street architecture street architecture alley architecture building city cobblestone house ville & voyage" },
  { id: "city-164", cat: "city", label: "Street Architecture Falkland Fife (10)", w: 900, h: 675, kw: "street architecture falkland fife (10) street architecture ville & voyage" },
  { id: "city-165", cat: "city", label: "Street Architecture Falkland Fife (3)", w: 900, h: 675, kw: "street architecture falkland fife (3) street architecture ville & voyage" },
  { id: "city-166", cat: "city", label: "Street Architecture Falkland Fife (1)", w: 900, h: 675, kw: "street architecture falkland fife (1) street architecture ville & voyage" },
  { id: "city-167", cat: "city", label: "Charming medieval European street architecture", w: 900, h: 675, kw: "charming medieval european street architecture street architecture buildings city houses leaf medieval path ville & voyage" },
  { id: "city-168", cat: "city", label: "Bridge City", w: 900, h: 596, kw: "bridge city bridge city architecture benches bridge cable city couple ville & voyage" },
  { id: "city-169", cat: "city", label: "Bridge City", w: 900, h: 596, kw: "bridge city bridge city architecture bridge cable cars city clouds ville & voyage" },
  { id: "city-170", cat: "city", label: "Roman bridge city gate, Banias", w: 900, h: 668, kw: "roman bridge city gate, banias bridge city art city landscape mountain nature travel ville & voyage" },
  { id: "city-171", cat: "city", label: "Free bridge city twilight image", w: 900, h: 675, kw: "free bridge city twilight image bridge city architecture building city free landscape sky ville & voyage" },
  { id: "city-172", cat: "city", label: "Northern views. Roman bridge city", w: 900, h: 657, kw: "northern views. roman bridge city bridge city arch art city landscape nature path ville & voyage" },
  { id: "city-173", cat: "city", label: "Chromolithograph Brooklyn Bridge City New", w: 900, h: 646, kw: "chromolithograph brooklyn bridge city new bridge city boat from above brooklyn brooklyn bridge currier and ives electric new york ville & voyage" },
  { id: "city-174", cat: "city", label: "Snowy night city lights calm and lovely, Space Needl", w: 900, h: 599, kw: "snowy night city lights calm and lovely, space needle, lake night city lights 2442 calm city cloud cloudy gasworkspark ville & voyage" },
  { id: "city-175", cat: "city", label: "The blue way it feels on a snowy night city lights c", w: 900, h: 599, kw: "the blue way it feels on a snowy night city lights calm and night city lights 2460 blue calm calmandlovely city clouds ville & voyage" },
  { id: "city-176", cat: "city", label: "File:Late Nights + City Lights (Unsplash).jpg", w: 900, h: 506, kw: "file:late nights + city lights (unsplash).jpg night city lights ville & voyage" },
  { id: "city-177", cat: "city", label: "Rainbokeh", w: 900, h: 600, kw: "rainbokeh night city lights city final japan kyoto light night ville & voyage" },
  { id: "city-178", cat: "city", label: "City Lights", w: 900, h: 603, kw: "city lights night city lights a330 alberta bright calgary canada cars ville & voyage" },
  { id: "city-179", cat: "city", label: "On record snow, night skier with pack and head light", w: 900, h: 698, kw: "on record snow, night skier with pack and head light, city r night city lights 2476 alone cityreflectedinlakeunion cloudy fromthetopofthehill gasworks" },
  { id: "city-180", cat: "city", label: "2010.02 - 'Photo of a decorated Dutch train - rail-c", w: 900, h: 506, kw: "2010.02 - 'photo of a decorated dutch train - rail-car at th train station 2010 amsterdam art central colored colors ville & voyage" },
  { id: "city-181", cat: "city", label: "2011.05 - 'Bus-entrance to drive up the new bus-stat", w: 900, h: 600, kw: "2011.05 - 'bus-entrance to drive up the new bus-station', be train station amsterdam arches architecture bus busstation central ville & voyage" },
  { id: "city-182", cat: "city", label: "William Shakespeare & James Russell Lowell Mashed To", w: 900, h: 540, kw: "william shakespeare & james russell lowell mashed together o train station 1840 1907 80004523 aia150 amtrak columbuscircle ville & voyage" },
  { id: "city-183", cat: "city", label: "2016.09 - Amsterdam photo of a 'Light-play' in train", w: 900, h: 675, kw: "2016.09 - amsterdam photo of a 'light-play' in train station train station 2016 amsterdam amsterdamcity ccophotography commons daylight ville & voyage" },
  { id: "city-184", cat: "city", label: "Lucerne Train Station", w: 900, h: 655, kw: "lucerne train station train station a7r2 blackandwhite bw hdr lucerne monochrome ville & voyage" },
  { id: "city-185", cat: "city", label: "Naujoji Vilnia train station 4", w: 900, h: 506, kw: "naujoji vilnia train station 4 train station ville & voyage" },
  { id: "objects-186", cat: "objects", label: "Vintage cameras", w: 900, h: 600, kw: "vintage cameras vintage camera antique camera film filmcamera filming old objets" },
  { id: "objects-187", cat: "objects", label: "Collection of Vintage Cameras", w: 900, h: 605, kw: "collection of vintage cameras vintage camera camera cameras publicdomain vintage vintagecameras objets" },
  { id: "objects-188", cat: "objects", label: "Kodak Brownie Flash B Vintage Camera", w: 900, h: 600, kw: "kodak brownie flash b vintage camera vintage camera brown brownie brownieflashb camera handheld kodak objets" },
  { id: "objects-189", cat: "objects", label: "Collection of Vintage Cameras", w: 900, h: 603, kw: "collection of vintage cameras vintage camera antiques cameraequipment cameras collection pattern photography objets" },
  { id: "objects-190", cat: "objects", label: "Woman with vintage camera", w: 900, h: 600, kw: "woman with vintage camera vintage camera adult attractive beautiful beauty camera caucasian objets" },
  { id: "objects-191", cat: "objects", label: "Kodak Vintage Camera", w: 900, h: 600, kw: "kodak vintage camera vintage camera brownieflashb camera focus kodak photography publicdomain objets" },
  { id: "objects-192", cat: "objects", label: "Book Stack", w: 900, h: 600, kw: "book stack books stack books brooks candy johngreen nicholassparks objets" },
  { id: "objects-194", cat: "objects", label: "Free old books stacked messy", w: 900, h: 600, kw: "free old books stacked messy books stack book books messy stacks bookshelf bookshelf messy free old books stacked objets" },
  { id: "objects-198", cat: "objects", label: "Work space, Microsoft Custom Development Solutions T", w: 900, h: 599, kw: "work space, microsoft custom development solutions technical desk workspace 20floorsup 4990 adobephotoshop bigalowchaitea california chai objets" },
  { id: "objects-199", cat: "objects", label: "Office Work", w: 900, h: 675, kw: "office work desk workspace autocad blueprints business computer corel design objets" },
  { id: "objects-200", cat: "objects", label: "Office Work", w: 900, h: 600, kw: "office work desk workspace brown business desk journal minimalist notebook objets" },
  { id: "objects-201", cat: "objects", label: "Office Work", w: 900, h: 601, kw: "office work desk workspace bokeh business coffee cup desk gadgets objets" },
  { id: "objects-202", cat: "objects", label: "Office Work", w: 900, h: 600, kw: "office work desk workspace brown business desk gadgets journal minimalist objets" },
  { id: "objects-203", cat: "objects", label: "Home Office", w: 900, h: 600, kw: "home office desk workspace apartment computer decor design desk equipment objets" },
  { id: "objects-204", cat: "objects", label: "David Wessell playing SLABS musical instrument proto", w: 900, h: 598, kw: "david wessell playing slabs musical instrument prototype at musical instrument california santacruz unitedstates objets" },
  { id: "objects-205", cat: "objects", label: "Ancient Egypt Musical Instruments", w: 900, h: 600, kw: "ancient egypt musical instruments musical instrument ancient egypt france louvre paris objets" },
  { id: "objects-206", cat: "objects", label: "David Wessell's SLABS musical instrument prototype a", w: 900, h: 598, kw: "david wessell's slabs musical instrument prototype at 2012 p musical instrument california santacruz unitedstates objets" },
  { id: "objects-207", cat: "objects", label: "David Wessell playing SLABS musical instrument proto", w: 900, h: 811, kw: "david wessell playing slabs musical instrument prototype at musical instrument california santacruz unitedstates objets" },
  { id: "objects-208", cat: "objects", label: "Aztec Musical Instrument", w: 900, h: 600, kw: "aztec musical instrument musical instrument ancient aztec inah mesoamerica mexica mexico objets" },
  { id: "objects-209", cat: "objects", label: "Aztec Bone Musical Instruments", w: 900, h: 600, kw: "aztec bone musical instruments musical instrument ancient aztec inah mesoamerica mexica mexico objets" },
  { id: "objects-210", cat: "objects", label: "Tools Workshop", w: 900, h: 600, kw: "tools workshop tools workshop garage hammers mallets pliers saws screwdrivers objets" },
  { id: "objects-211", cat: "objects", label: "THE SHOP", w: 900, h: 600, kw: "the shop tools workshop tools woodworking workbench workshop objets" },
  { id: "objects-212", cat: "objects", label: "20190505-2", w: 900, h: 600, kw: "20190505-2 tools workshop energy garage powercable tools wires workshop objets" },
  { id: "objects-215", cat: "objects", label: "Workshop Industrialdesign", w: 900, h: 506, kw: "workshop industrialdesign tools workshop guy industrialdesign man people shop tools objets" },
  { id: "objects-900", cat: "objects", label: "Antique furniture living room", w: 900, h: 600, kw: "antique furniture living room antique furniture antique furniture antique interior fireplace home libraries interior design library objets" },
  { id: "objects-901", cat: "objects", label: "HK 灣仔北 Wan Chai North 香港會展 HKCEC 佳士得 拍賣 Christie's A", w: 900, h: 675, kw: "hk 灣仔北 wan chai north 香港會展 hkcec 佳士得 拍賣 christie's auction 預 antique furniture objets" },
  { id: "objects-902", cat: "objects", label: "HK 灣仔北 Wan Chai North 香港會展 HKCEC 佳士得 拍賣 Christie's A", w: 900, h: 675, kw: "hk 灣仔北 wan chai north 香港會展 hkcec 佳士得 拍賣 christie's auction 預 antique furniture objets" },
  { id: "objects-903", cat: "objects", label: "HK 灣仔北 Wan Chai North 香港會展 HKCEC 佳士得 拍賣 Christie's A", w: 900, h: 675, kw: "hk 灣仔北 wan chai north 香港會展 hkcec 佳士得 拍賣 christie's auction 預 antique furniture objets" },
  { id: "objects-904", cat: "objects", label: "HK 灣仔北 Wan Chai North 香港會展 HKCEC 佳士得 拍賣 Christie's A", w: 900, h: 675, kw: "hk 灣仔北 wan chai north 香港會展 hkcec 佳士得 拍賣 christie's auction 預 antique furniture objets" },
  { id: "tech-216", cat: "tech", label: "Man Holding Laptop Computer Typing While Dog Watches", w: 900, h: 596, kw: "man holding laptop computer typing while dog watches laptop computer animal computer dog indoor laptop male tech" },
  { id: "tech-217", cat: "tech", label: "Apple Laptop Computer with Headphones, Camera, and O", w: 900, h: 600, kw: "apple laptop computer with headphones, camera, and open note laptop computer computer desktop diagrams earphones indoor ios tech" },
  { id: "tech-218", cat: "tech", label: "Desktop Still Life with Books and Laptop Computer", w: 900, h: 604, kw: "desktop still life with books and laptop computer laptop computer advertisement apple book books drawing eraser tech" },
  { id: "tech-219", cat: "tech", label: "Laptop Computer", w: 900, h: 600, kw: "laptop computer laptop computer blogging business cellphone computer desk laptop tech" },
  { id: "tech-220", cat: "tech", label: "Laptop Computer", w: 900, h: 598, kw: "laptop computer laptop computer business computer desk ipad laptop mobile tech" },
  { id: "tech-221", cat: "tech", label: "Macro shot of a circuit board", w: 900, h: 598, kw: "macro shot of a circuit board circuit board tech" },
  { id: "tech-222", cat: "tech", label: "Like A Giant Circuit Board", w: 900, h: 675, kw: "like a giant circuit board circuit board texas abstract color daylight desktop landscape tech" },
  { id: "tech-223", cat: "tech", label: "Fire damaged circuit board", w: 900, h: 600, kw: "fire damaged circuit board circuit board circuitboard damaged electronics fire soot tech" },
  { id: "tech-224", cat: "tech", label: "Macro of circuit board closeup", w: 900, h: 598, kw: "macro of circuit board closeup circuit board tech" },
  { id: "tech-225", cat: "tech", label: "컴퓨터 회로 기판 PC Circuit board", w: 900, h: 600, kw: "컴퓨터 회로 기판 pc circuit board circuit board free freeimage freephoto tech" },
  { id: "tech-226", cat: "tech", label: "K-178-Ae-04026-id-419970", w: 900, h: 628, kw: "k-178-ae-04026-id-419970 smartphone device active activity adventure backpack backpacker backpacking tech" },
  { id: "tech-227", cat: "tech", label: "Some accessories on a white desk", w: 900, h: 600, kw: "some accessories on a white desk smartphone device accessories business calendar cell clock communication tech" },
  { id: "tech-228", cat: "tech", label: "Keep Moving", w: 900, h: 600, kw: "keep moving smartphone device astronomy atmosphere blue cellphone clouds dark tech" },
  { id: "tech-229", cat: "tech", label: "iPhone 6s, iPhone 8 plus and iPhone X", w: 900, h: 600, kw: "iphone 6s, iphone 8 plus and iphone x smartphone device 6s 8plus accessories anniversary app apple tech" },
  { id: "tech-230", cat: "tech", label: "MacBook and iPhone", w: 900, h: 600, kw: "macbook and iphone smartphone device 6s accessories app apple cell coffee tech" },
  { id: "tech-231", cat: "tech", label: "Ethernet switch", w: 900, h: 600, kw: "ethernet switch server data cloudcomputing communication computer data ethernet internet tech" },
  { id: "tech-232", cat: "tech", label: "Lucifer Race", w: 900, h: 584, kw: "lucifer race server data 2021 art artistic bible bigpharma blot tech" },
  { id: "tech-233", cat: "tech", label: "cutting which wire disables the bomb? Red, blue or g", w: 900, h: 599, kw: "cutting which wire disables the bomb? red, blue or green, i server data 2957 blueorgreen bomb cutting disables iwonder tech" },
  { id: "tech-235", cat: "tech", label: "Control Data Cyber 860", w: 900, h: 600, kw: "control data cyber 860 server data 860 cdc cmm computermueseummuenchen craycyber backup tech" },
  { id: "tech-907", cat: "tech", label: "Robot Technology", w: 900, h: 600, kw: "robot technology robot technology humanoid modern robot technology white tech" },
  { id: "tech-908", cat: "tech", label: "NCS Starfury", w: 900, h: 600, kw: "ncs starfury robot technology classic ironbuilder lego microscale moc ncs tech" },
  { id: "weather-236", cat: "weather", label: "cloud, sky", w: 900, h: 598, kw: "cloud, sky clouds sky cloud skycloud meteo & ciel" },
  { id: "weather-237", cat: "weather", label: "Clouds Sky", w: 900, h: 506, kw: "clouds sky clouds sky battleships blue boats clouds ocean sea meteo & ciel" },
  { id: "weather-238", cat: "weather", label: "Clouds Sky", w: 900, h: 600, kw: "clouds sky clouds sky clouds dating guy holdinghands mountain nature meteo & ciel" },
  { id: "weather-239", cat: "weather", label: "Clouds Sky", w: 900, h: 600, kw: "clouds sky clouds sky clouds cloudy nature sky sunset meteo & ciel" },
  { id: "weather-240", cat: "weather", label: "Clouds Sky", w: 900, h: 608, kw: "clouds sky clouds sky clouds dark landscape mountain night sky meteo & ciel" },
  { id: "weather-241", cat: "weather", label: "Cloud Sky", w: 900, h: 593, kw: "cloud sky clouds sky cloud condo sky tower meteo & ciel" },
  { id: "weather-242", cat: "weather", label: "ETC Wallpaper - Flowers and Rain Drops", w: 900, h: 600, kw: "etc wallpaper - flowers and rain drops rain drops 0x aelf aeternity altcoins auroracoin background meteo & ciel" },
  { id: "weather-243", cat: "weather", label: "rain drops on a mirror", w: 900, h: 900, kw: "rain drops on a mirror rain drops mirror rain raindrop vancouver meteo & ciel" },
  { id: "weather-244", cat: "weather", label: "Rain Drops", w: 900, h: 600, kw: "rain drops rain drops drops rain raining wet window meteo & ciel" },
  { id: "weather-245", cat: "weather", label: "Rain Drops", w: 900, h: 600, kw: "rain drops rain drops child drops figure glass jacket kid meteo & ciel" },
  { id: "weather-246", cat: "weather", label: "rain drops keep falling on my head", w: 900, h: 600, kw: "rain drops keep falling on my head rain drops rain rainforest rainy subtropicalrainforest temperaterainforest vancouver meteo & ciel" },
  { id: "weather-247", cat: "weather", label: "Rain Drops", w: 900, h: 720, kw: "rain drops rain drops bubble clear dew drops green leaf meteo & ciel" },
  { id: "weather-248", cat: "weather", label: "Snow Winter", w: 900, h: 600, kw: "snow winter snow winter cliffs clouds hill landscape mountain rocks meteo & ciel" },
  { id: "weather-249", cat: "weather", label: "cold-snow-winter-mountain", w: 900, h: 506, kw: "cold-snow-winter-mountain snow winter meteo & ciel" },
  { id: "weather-250", cat: "weather", label: "Snow Winter", w: 900, h: 600, kw: "snow winter snow winter athabasca canyon forest glacier lake river meteo & ciel" },
  { id: "weather-251", cat: "weather", label: "Snow Winter", w: 900, h: 675, kw: "snow winter snow winter background branches christmas closeup cold evergreen meteo & ciel" },
  { id: "weather-252", cat: "weather", label: "Snow Winter", w: 900, h: 600, kw: "snow winter snow winter cold formation ice landscape mountain nature meteo & ciel" },
  { id: "weather-253", cat: "weather", label: "Snow Winter", w: 900, h: 600, kw: "snow winter snow winter bark bicycle bike cold homeless lampposts meteo & ciel" },
  { id: "weather-254", cat: "weather", label: "Thunder storm lightning city night", w: 900, h: 788, kw: "thunder storm lightning city night storm lightning city lightning lightning storm night city storm thunder meteo & ciel" },
  { id: "weather-255", cat: "weather", label: "Thunder storm lightning city night", w: 900, h: 600, kw: "thunder storm lightning city night storm lightning lightning nature photo storm thunder thunder night thunder storm meteo & ciel" },
  { id: "weather-256", cat: "weather", label: "Thunder storm lightning city night", w: 900, h: 600, kw: "thunder storm lightning city night storm lightning city city night lightning purple thunder thunder storm meteo & ciel" },
  { id: "weather-257", cat: "weather", label: "Lightning on 7-14-15", w: 900, h: 679, kw: "lightning on 7-14-15 storm lightning 2015 70d adairsville lightning storm meteo & ciel" },
  { id: "weather-258", cat: "weather", label: "Lightning", w: 900, h: 531, kw: "lightning storm lightning australia australianweather cloud clouds electricalstorm extremeweather meteo & ciel" },
  { id: "weather-259", cat: "weather", label: "Lightning", w: 900, h: 462, kw: "lightning storm lightning australia australianweather cloud clouds dark electricalstorm meteo & ciel" },
  { id: "weather-260", cat: "weather", label: "starry-night-sky", w: 900, h: 563, kw: "starry-night-sky starry night sky meteo & ciel" },
  { id: "weather-261", cat: "weather", label: "Starry night sky", w: 900, h: 675, kw: "starry night sky starry night sky night sky night stars outer space star night sky star sky starry night meteo & ciel" },
  { id: "texture-262", cat: "texture", label: "Wood Texture", w: 900, h: 675, kw: "wood texture wood texture wood textures & fonds" },
  { id: "texture-263", cat: "texture", label: "Wood Texture", w: 900, h: 675, kw: "wood texture wood texture textures & fonds" },
  { id: "texture-264", cat: "texture", label: "Two Holes in Wood Texture", w: 900, h: 600, kw: "two holes in wood texture wood texture blackandwhite closeup holes woodtexture textures & fonds" },
  { id: "texture-265", cat: "texture", label: "Wood texture at Bryght", w: 900, h: 675, kw: "wood texture at bryght wood texture bryght decay picoblogger rolandtanglao texture vancouver textures & fonds" },
  { id: "texture-266", cat: "texture", label: "wood texture 1 (bear profile)", w: 900, h: 600, kw: "wood texture 1 (bear profile) wood texture background bear cco free freephotos gray textures & fonds" },
  { id: "texture-267", cat: "texture", label: "Marble Texture", w: 900, h: 600, kw: "marble texture marble texture abstract abstract art abstract painting art paint abstract textures & fonds" },
  { id: "texture-268", cat: "texture", label: "A close-up of a white plate filled with thinly slice", w: 900, h: 600, kw: "a close-up of a white plate filled with thinly sliced iberic marble texture food meat textures & fonds" },
  { id: "texture-269", cat: "texture", label: "Winter Layers", w: 900, h: 596, kw: "winter layers marble texture 52project2016 darktable dune lakesidepark layers lightbox textures & fonds" },
  { id: "texture-270", cat: "texture", label: "Texture", w: 900, h: 600, kw: "texture marble texture free gratuit hd magicphil magicphilch magikphil textures & fonds" },
  { id: "texture-271", cat: "texture", label: "Texture Dump 12", w: 900, h: 600, kw: "texture dump 12 marble texture cliff cracks gray grey mountain rock textures & fonds" },
  { id: "texture-272", cat: "texture", label: "Aged Concrete Wall Texture", w: 900, h: 522, kw: "aged concrete wall texture concrete wall cement concrete material rough texture wall textures & fonds" },
  { id: "texture-273", cat: "texture", label: "Concrete Wall", w: 900, h: 676, kw: "concrete wall concrete wall abstract concrete surface wall textures & fonds" },
  { id: "texture-274", cat: "texture", label: "Decaying Concrete Wall", w: 900, h: 675, kw: "decaying concrete wall concrete wall cc creativecommons textures & fonds" },
  { id: "texture-275", cat: "texture", label: "Concrete Wall", w: 900, h: 600, kw: "concrete wall concrete wall camera cctv concrete pipe security wall textures & fonds" },
  { id: "texture-276", cat: "texture", label: "Dirty concrete wall", w: 900, h: 450, kw: "dirty concrete wall concrete wall aged concrete dirt dirty free grunge textures & fonds" },
  { id: "texture-277", cat: "texture", label: "Fabric Texture", w: 900, h: 600, kw: "fabric texture fabric texture fabric pattern texture textures & fonds" },
  { id: "texture-278", cat: "texture", label: "Fabric Texture", w: 900, h: 600, kw: "fabric texture fabric texture background closeup copyspace crafty diy fabric textures & fonds" },
  { id: "texture-279", cat: "texture", label: "Fabric Texture", w: 900, h: 600, kw: "fabric texture fabric texture closeup clothing copyspace fabric macro maroon textures & fonds" },
  { id: "texture-280", cat: "texture", label: "Fabric Texture", w: 900, h: 601, kw: "fabric texture fabric texture backdrop background canvas closeup cloth detail textures & fonds" },
  { id: "texture-281", cat: "texture", label: "Fabric Textures", w: 900, h: 601, kw: "fabric textures fabric texture background blue closeup cloth clothing crafts textures & fonds" },
  { id: "texture-282", cat: "texture", label: "Paper texture on a fading poster", w: 900, h: 675, kw: "paper texture on a fading poster paper texture 7610 cameraphone eastvan joyce paper shozu textures & fonds" },
  { id: "texture-283", cat: "texture", label: "multicolored paper texture", w: 900, h: 596, kw: "multicolored paper texture paper texture abstract background black cco design free textures & fonds" },
  { id: "texture-284", cat: "texture", label: "Beige paper texture, simple background", w: 900, h: 636, kw: "beige paper texture, simple background paper texture old paper texture paper paper texture paper texture background photo paper textured paper texture" },
  { id: "texture-285", cat: "texture", label: "Free old paper texture image", w: 900, h: 900, kw: "free old paper texture image paper texture cardboard texture grainy paper texture grainy texture old paper old paper texture paper textures & fonds" },
  { id: "texture-286", cat: "texture", label: "Paper texture, beige background, simple", w: 900, h: 600, kw: "paper texture, beige background, simple paper texture gray paper old paper old paper texture paper paper background paper texture textures & fonds" },
  { id: "texture-287", cat: "texture", label: "Water surface", w: 900, h: 600, kw: "water surface water surface a6400 aichi creativecommons freeculturalworks japan nagoya textures & fonds" },
  { id: "texture-288", cat: "texture", label: "Grimy Water Surface, Krumme Lanke", w: 900, h: 599, kw: "grimy water surface, krumme lanke water surface textures & fonds" },
  { id: "texture-289", cat: "texture", label: "Cherry blosson on the water surface", w: 900, h: 600, kw: "cherry blosson on the water surface water surface cherryblossum textures & fonds" },
  { id: "business-290", cat: "business", label: "Office Desk", w: 900, h: 600, kw: "office desk office desk business chair creative decor design desk bureau & travail" },
  { id: "business-291", cat: "business", label: "Office Desk", w: 900, h: 600, kw: "office desk office desk business coffee creative cup design desk bureau & travail" },
  { id: "business-292", cat: "business", label: "Person Sitting at Office Desk in Warehouse by Pillar", w: 900, h: 675, kw: "person sitting at office desk in warehouse by pillar office desk cement chair computer desk indoor office bureau & travail" },
  { id: "business-293", cat: "business", label: "Modern Styled Workstation Office Desk", w: 900, h: 600, kw: "modern styled workstation office desk office desk agency backup black box brightness buero bureau & travail" },
  { id: "business-294", cat: "business", label: "Writing Drawing", w: 900, h: 600, kw: "writing drawing meeting notebook business coffee creative desk drawing hand bureau & travail" },
  { id: "business-295", cat: "business", label: "Easy", w: 900, h: 675, kw: "easy meeting notebook 1s07 1y20 91115 91127 cafe cafu00e9 bureau & travail" },
  { id: "business-296", cat: "business", label: "Journal Notepad", w: 900, h: 600, kw: "journal notepad meeting notebook business coffee croissant cup desk food bureau & travail" },
  { id: "business-297", cat: "business", label: "Business Office", w: 900, h: 598, kw: "business office meeting notebook business charts computer desk finance graphs bureau & travail" },
  { id: "business-298", cat: "business", label: "HANDSHAKE 2016-07-18", w: 900, h: 600, kw: "handshake 2016-07-18 handshake business bratislava council ec eu eu2016sk europe bureau & travail" },
  { id: "business-299", cat: "business", label: "HANDSHAKE 2016-07-18", w: 900, h: 606, kw: "handshake 2016-07-18 handshake business bratislava council ec eu eu2016sk europe bureau & travail" },
  { id: "daily-monitor-0", cat: "daily", label: "Écran", w: 640, h: 900, kw: "ecran computer monitor screen ecran objets du quotidien" },
  { id: "daily-monitor-1", cat: "daily", label: "Écran", w: 900, h: 599, kw: "ecran computer monitor screen ecran objets du quotidien" },
  { id: "daily-tv-0", cat: "daily", label: "Télévision", w: 900, h: 600, kw: "television television set television objets du quotidien" },
  { id: "daily-tv-1", cat: "daily", label: "Télévision", w: 900, h: 676, kw: "television television set television objets du quotidien" },
  { id: "daily-laptop-0", cat: "daily", label: "Ordinateur portable", w: 900, h: 596, kw: "ordinateur portable laptop computer ordinateur portable objets du quotidien" },
  { id: "daily-laptop-1", cat: "daily", label: "Ordinateur portable", w: 900, h: 600, kw: "ordinateur portable laptop computer ordinateur portable objets du quotidien" },
  { id: "daily-tablet-0", cat: "daily", label: "Tablette", w: 900, h: 601, kw: "tablette tablet device tablette objets du quotidien" },
  { id: "daily-tablet-1", cat: "daily", label: "Tablette", w: 900, h: 600, kw: "tablette tablet device tablette objets du quotidien" },
  { id: "daily-phone-0", cat: "daily", label: "Smartphone", w: 900, h: 603, kw: "smartphone smartphone mobile phone smartphone objets du quotidien" },
  { id: "daily-phone-1", cat: "daily", label: "Smartphone", w: 900, h: 600, kw: "smartphone smartphone mobile phone smartphone objets du quotidien" },
  { id: "daily-keyboard-0", cat: "daily", label: "Clavier", w: 900, h: 600, kw: "clavier computer keyboard clavier objets du quotidien" },
  { id: "daily-keyboard-1", cat: "daily", label: "Clavier", w: 900, h: 600, kw: "clavier computer keyboard clavier objets du quotidien" },
  { id: "daily-mouse-0", cat: "daily", label: "Souris", w: 900, h: 900, kw: "souris computer mouse souris objets du quotidien" },
  { id: "daily-mouse-1", cat: "daily", label: "Souris", w: 900, h: 900, kw: "souris computer mouse souris objets du quotidien" },
  { id: "daily-printer-0", cat: "daily", label: "Imprimante", w: 900, h: 900, kw: "imprimante printer office imprimante objets du quotidien" },
  { id: "daily-printer-1", cat: "daily", label: "Imprimante", w: 900, h: 900, kw: "imprimante printer office imprimante objets du quotidien" },
  { id: "daily-router-0", cat: "daily", label: "Box internet", w: 900, h: 667, kw: "box internet wifi router modem box internet objets du quotidien" },
  { id: "daily-console-0", cat: "daily", label: "Console de jeu", w: 900, h: 761, kw: "console de jeu game controller console console de jeu objets du quotidien" },
  { id: "daily-console-1", cat: "daily", label: "Console de jeu", w: 900, h: 600, kw: "console de jeu game controller console console de jeu objets du quotidien" },
  { id: "daily-robot-0", cat: "daily", label: "Robot", w: 900, h: 675, kw: "robot robot machine robot objets du quotidien" },
  { id: "daily-robot-1", cat: "daily", label: "Robot", w: 675, h: 900, kw: "robot robot machine robot objets du quotidien" },
  { id: "daily-speaker-0", cat: "daily", label: "Enceinte", w: 596, h: 523, kw: "enceinte loudspeaker audio enceinte objets du quotidien" },
  { id: "daily-speaker-1", cat: "daily", label: "Enceinte", w: 900, h: 600, kw: "enceinte loudspeaker audio enceinte objets du quotidien" },
  { id: "daily-headset-0", cat: "daily", label: "Casque audio", w: 900, h: 600, kw: "casque audio headphones audio casque audio objets du quotidien" },
  { id: "daily-headset-1", cat: "daily", label: "Casque audio", w: 900, h: 479, kw: "casque audio headphones audio casque audio objets du quotidien" },
  { id: "daily-camera-0", cat: "daily", label: "Appareil photo", w: 900, h: 675, kw: "appareil photo photo camera appareil photo objets du quotidien" },
  { id: "daily-camera-1", cat: "daily", label: "Appareil photo", w: 900, h: 675, kw: "appareil photo photo camera appareil photo objets du quotidien" },
  { id: "daily-remote-0", cat: "daily", label: "Télécommande", w: 900, h: 600, kw: "telecommande tv remote control telecommande objets du quotidien" },
  { id: "daily-remote-1", cat: "daily", label: "Télécommande", w: 675, h: 900, kw: "telecommande tv remote control telecommande objets du quotidien" },
  { id: "daily-fridge-0", cat: "daily", label: "Réfrigérateur", w: 900, h: 600, kw: "refrigerateur refrigerator kitchen refrigerateur objets du quotidien" },
  { id: "daily-fridge-1", cat: "daily", label: "Réfrigérateur", w: 900, h: 599, kw: "refrigerateur refrigerator kitchen refrigerateur objets du quotidien" },
  { id: "daily-oven-0", cat: "daily", label: "Four", w: 900, h: 600, kw: "four kitchen oven four objets du quotidien" },
  { id: "daily-oven-1", cat: "daily", label: "Four", w: 900, h: 721, kw: "four kitchen oven four objets du quotidien" },
  { id: "daily-microwave-0", cat: "daily", label: "Micro-ondes", w: 600, h: 900, kw: "micro-ondes microwave oven micro-ondes objets du quotidien" },
  { id: "daily-microwave-1", cat: "daily", label: "Micro-ondes", w: 899, h: 900, kw: "micro-ondes microwave oven micro-ondes objets du quotidien" },
  { id: "daily-washer-0", cat: "daily", label: "Lave-linge", w: 600, h: 900, kw: "lave-linge washing machine lave-linge objets du quotidien" },
  { id: "daily-washer-1", cat: "daily", label: "Lave-linge", w: 600, h: 900, kw: "lave-linge washing machine lave-linge objets du quotidien" },
  { id: "daily-kettle-0", cat: "daily", label: "Bouilloire", w: 900, h: 600, kw: "bouilloire kettle teapot bouilloire objets du quotidien" },
  { id: "daily-kettle-1", cat: "daily", label: "Bouilloire", w: 900, h: 643, kw: "bouilloire kettle teapot bouilloire objets du quotidien" },
  { id: "daily-toaster-0", cat: "daily", label: "Grille-pain", w: 900, h: 675, kw: "grille-pain toaster bread grille-pain objets du quotidien" },
  { id: "daily-toaster-1", cat: "daily", label: "Grille-pain", w: 900, h: 600, kw: "grille-pain toaster bread grille-pain objets du quotidien" },
  { id: "daily-coffeemachine-0", cat: "daily", label: "Machine à café", w: 900, h: 600, kw: "machine a cafe espresso coffee machine machine a cafe objets du quotidien" },
  { id: "daily-coffeemachine-1", cat: "daily", label: "Machine à café", w: 900, h: 450, kw: "machine a cafe espresso coffee machine machine a cafe objets du quotidien" },
  { id: "daily-blender-0", cat: "daily", label: "Mixeur", w: 637, h: 900, kw: "mixeur kitchen blender mixeur objets du quotidien" },
  { id: "daily-blender-1", cat: "daily", label: "Mixeur", w: 864, h: 900, kw: "mixeur kitchen blender mixeur objets du quotidien" },
  { id: "daily-fan-0", cat: "daily", label: "Ventilateur", w: 643, h: 900, kw: "ventilateur electric fan ventilateur objets du quotidien" },
  { id: "daily-fan-1", cat: "daily", label: "Ventilateur", w: 900, h: 900, kw: "ventilateur electric fan ventilateur objets du quotidien" },
  { id: "daily-lamp-0", cat: "daily", label: "Lampe", w: 675, h: 900, kw: "lampe table lamp lampe objets du quotidien" },
  { id: "daily-lamp-1", cat: "daily", label: "Lampe", w: 641, h: 900, kw: "lampe table lamp lampe objets du quotidien" },
  { id: "daily-bulb-0", cat: "daily", label: "Ampoule", w: 590, h: 900, kw: "ampoule light bulb ampoule objets du quotidien" },
  { id: "daily-bulb-1", cat: "daily", label: "Ampoule", w: 600, h: 900, kw: "ampoule light bulb ampoule objets du quotidien" },
  { id: "daily-plug-0", cat: "daily", label: "Prise", w: 900, h: 599, kw: "prise electric plug socket prise objets du quotidien" },
  { id: "daily-plug-1", cat: "daily", label: "Prise", w: 900, h: 675, kw: "prise electric plug socket prise objets du quotidien" },
  { id: "daily-vacuum-0", cat: "daily", label: "Aspirateur", w: 900, h: 675, kw: "aspirateur vacuum cleaner aspirateur objets du quotidien" },
  { id: "daily-vacuum-1", cat: "daily", label: "Aspirateur", w: 626, h: 900, kw: "aspirateur vacuum cleaner aspirateur objets du quotidien" },
  { id: "daily-iron-0", cat: "daily", label: "Fer à repasser", w: 675, h: 900, kw: "fer a repasser clothes iron fer a repasser objets du quotidien" },
  { id: "daily-iron-1", cat: "daily", label: "Fer à repasser", w: 900, h: 900, kw: "fer a repasser clothes iron fer a repasser objets du quotidien" },
  { id: "daily-house-0", cat: "daily", label: "Maison", w: 900, h: 701, kw: "maison house home exterior maison objets du quotidien" },
  { id: "daily-house-1", cat: "daily", label: "Maison", w: 900, h: 599, kw: "maison house home exterior maison objets du quotidien" },
  { id: "daily-door-0", cat: "daily", label: "Porte", w: 900, h: 600, kw: "porte wooden door porte objets du quotidien" },
  { id: "daily-door-1", cat: "daily", label: "Porte", w: 900, h: 600, kw: "porte wooden door porte objets du quotidien" },
  { id: "daily-window-0", cat: "daily", label: "Fenêtre", w: 900, h: 863, kw: "fenetre window glass fenetre objets du quotidien" },
  { id: "daily-window-1", cat: "daily", label: "Fenêtre", w: 900, h: 675, kw: "fenetre window glass fenetre objets du quotidien" },
  { id: "daily-chair-0", cat: "daily", label: "Chaise", w: 900, h: 600, kw: "chaise wooden chair chaise objets du quotidien" },
  { id: "daily-chair-1", cat: "daily", label: "Chaise", w: 596, h: 900, kw: "chaise wooden chair chaise objets du quotidien" },
  { id: "daily-sofa-0", cat: "daily", label: "Canapé", w: 900, h: 597, kw: "canape sofa couch living room canape objets du quotidien" },
  { id: "daily-sofa-1", cat: "daily", label: "Canapé", w: 900, h: 506, kw: "canape sofa couch living room canape objets du quotidien" },
  { id: "daily-bed-0", cat: "daily", label: "Lit", w: 900, h: 600, kw: "lit bed bedroom lit objets du quotidien" },
  { id: "daily-bed-1", cat: "daily", label: "Lit", w: 900, h: 600, kw: "lit bed bedroom lit objets du quotidien" },
  { id: "daily-table-0", cat: "daily", label: "Table", w: 900, h: 675, kw: "table wooden table furniture table objets du quotidien" },
  { id: "daily-table-1", cat: "daily", label: "Table", w: 900, h: 506, kw: "table wooden table furniture table objets du quotidien" },
  { id: "daily-shelf-0", cat: "daily", label: "Étagère", w: 900, h: 596, kw: "etagere bookshelf shelf etagere objets du quotidien" },
  { id: "daily-shelf-1", cat: "daily", label: "Étagère", w: 900, h: 600, kw: "etagere bookshelf shelf etagere objets du quotidien" },
  { id: "daily-mirror-0", cat: "daily", label: "Miroir", w: 900, h: 675, kw: "miroir mirror interior miroir objets du quotidien" },
  { id: "daily-mirror-1", cat: "daily", label: "Miroir", w: 900, h: 675, kw: "miroir mirror interior miroir objets du quotidien" },
  { id: "daily-clock-0", cat: "daily", label: "Horloge", w: 651, h: 900, kw: "horloge wall clock horloge objets du quotidien" },
  { id: "daily-clock-1", cat: "daily", label: "Horloge", w: 900, h: 900, kw: "horloge wall clock horloge objets du quotidien" },
  { id: "daily-trash-0", cat: "daily", label: "Poubelle", w: 675, h: 900, kw: "poubelle trash bin waste poubelle objets du quotidien" },
  { id: "daily-trash-1", cat: "daily", label: "Poubelle", w: 900, h: 675, kw: "poubelle trash bin waste poubelle objets du quotidien" },
  { id: "daily-plant-0", cat: "daily", label: "Plante", w: 900, h: 675, kw: "plante potted plant indoor plante objets du quotidien" },
  { id: "daily-plant-1", cat: "daily", label: "Plante", w: 675, h: 900, kw: "plante potted plant indoor plante objets du quotidien" },
  { id: "daily-frame-0", cat: "daily", label: "Cadre photo", w: 900, h: 600, kw: "cadre photo picture frame wall cadre photo objets du quotidien" },
  { id: "daily-frame-1", cat: "daily", label: "Cadre photo", w: 600, h: 900, kw: "cadre photo picture frame wall cadre photo objets du quotidien" },
  { id: "daily-towel-0", cat: "daily", label: "Serviette", w: 900, h: 600, kw: "serviette towel bathroom serviette objets du quotidien" },
  { id: "daily-towel-1", cat: "daily", label: "Serviette", w: 900, h: 600, kw: "serviette towel bathroom serviette objets du quotidien" },
  { id: "daily-candle-0", cat: "daily", label: "Bougie", w: 893, h: 900, kw: "bougie candle light bougie objets du quotidien" },
  { id: "daily-candle-1", cat: "daily", label: "Bougie", w: 900, h: 600, kw: "bougie candle light bougie objets du quotidien" },
  { id: "daily-mug-0", cat: "daily", label: "Tasse", w: 900, h: 600, kw: "tasse coffee mug cup tasse objets du quotidien" },
  { id: "daily-mug-1", cat: "daily", label: "Tasse", w: 900, h: 598, kw: "tasse coffee mug cup tasse objets du quotidien" },
  { id: "daily-plate-0", cat: "daily", label: "Assiette", w: 900, h: 675, kw: "assiette plate dish tableware assiette objets du quotidien" },
  { id: "daily-plate-1", cat: "daily", label: "Assiette", w: 900, h: 675, kw: "assiette plate dish tableware assiette objets du quotidien" },
  { id: "daily-pan-0", cat: "daily", label: "Poêle", w: 900, h: 653, kw: "poele frying pan poele objets du quotidien" },
  { id: "daily-pan-1", cat: "daily", label: "Poêle", w: 900, h: 600, kw: "poele frying pan poele objets du quotidien" },
  { id: "daily-pot-0", cat: "daily", label: "Casserole", w: 506, h: 900, kw: "casserole cooking pot casserole objets du quotidien" },
  { id: "daily-pot-1", cat: "daily", label: "Casserole", w: 900, h: 600, kw: "casserole cooking pot casserole objets du quotidien" },
  { id: "daily-bottle-0", cat: "daily", label: "Bouteille", w: 900, h: 675, kw: "bouteille glass bottle bouteille objets du quotidien" },
  { id: "daily-bottle-1", cat: "daily", label: "Bouteille", w: 900, h: 600, kw: "bouteille glass bottle bouteille objets du quotidien" },
  { id: "daily-cutlery-0", cat: "daily", label: "Couverts", w: 900, h: 599, kw: "couverts fork knife cutlery couverts objets du quotidien" },
  { id: "daily-cutlery-1", cat: "daily", label: "Couverts", w: 900, h: 675, kw: "couverts fork knife cutlery couverts objets du quotidien" },
  { id: "daily-jar-0", cat: "daily", label: "Bocal", w: 900, h: 599, kw: "bocal glass jar bocal objets du quotidien" },
  { id: "daily-jar-1", cat: "daily", label: "Bocal", w: 900, h: 600, kw: "bocal glass jar bocal objets du quotidien" },
  { id: "daily-backpack-0", cat: "daily", label: "Sac à dos", w: 900, h: 600, kw: "sac a dos backpack bag sac a dos objets du quotidien" },
  { id: "daily-backpack-1", cat: "daily", label: "Sac à dos", w: 900, h: 600, kw: "sac a dos backpack bag sac a dos objets du quotidien" },
  { id: "daily-wallet-0", cat: "daily", label: "Portefeuille", w: 900, h: 600, kw: "portefeuille wallet money portefeuille objets du quotidien" },
  { id: "daily-wallet-1", cat: "daily", label: "Portefeuille", w: 900, h: 600, kw: "portefeuille wallet money portefeuille objets du quotidien" },
  { id: "daily-glasses-0", cat: "daily", label: "Lunettes", w: 900, h: 600, kw: "lunettes eyeglasses spectacles lunettes objets du quotidien" },
  { id: "daily-glasses-1", cat: "daily", label: "Lunettes", w: 900, h: 600, kw: "lunettes eyeglasses spectacles lunettes objets du quotidien" },
  { id: "daily-watch-0", cat: "daily", label: "Montre", w: 900, h: 596, kw: "montre wristwatch montre objets du quotidien" },
  { id: "daily-watch-1", cat: "daily", label: "Montre", w: 900, h: 600, kw: "montre wristwatch montre objets du quotidien" },
  { id: "daily-shoe-0", cat: "daily", label: "Chaussure", w: 900, h: 600, kw: "chaussure sneaker shoe chaussure objets du quotidien" },
  { id: "daily-shoe-1", cat: "daily", label: "Chaussure", w: 900, h: 600, kw: "chaussure sneaker shoe chaussure objets du quotidien" },
  { id: "daily-book-0", cat: "daily", label: "Livre", w: 900, h: 600, kw: "livre open book livre objets du quotidien" },
  { id: "daily-book-1", cat: "daily", label: "Livre", w: 650, h: 900, kw: "livre open book livre objets du quotidien" },
  { id: "daily-notebook-0", cat: "daily", label: "Carnet", w: 900, h: 600, kw: "carnet notebook paper carnet objets du quotidien" },
  { id: "daily-notebook-1", cat: "daily", label: "Carnet", w: 900, h: 600, kw: "carnet notebook paper carnet objets du quotidien" },
  { id: "daily-pencil-0", cat: "daily", label: "Crayon", w: 900, h: 600, kw: "crayon pencil writing crayon objets du quotidien" },
  { id: "daily-pencil-1", cat: "daily", label: "Crayon", w: 900, h: 600, kw: "crayon pencil writing crayon objets du quotidien" },
  { id: "daily-scissors-0", cat: "daily", label: "Ciseaux", w: 900, h: 598, kw: "ciseaux scissors ciseaux objets du quotidien" },
  { id: "daily-scissors-1", cat: "daily", label: "Ciseaux", w: 900, h: 509, kw: "ciseaux scissors ciseaux objets du quotidien" },
  { id: "daily-key-0", cat: "daily", label: "Clé", w: 900, h: 600, kw: "cle keys metal key cle objets du quotidien" },
  { id: "daily-key-1", cat: "daily", label: "Clé", w: 900, h: 543, kw: "cle keys metal key cle objets du quotidien" },
  { id: "daily-umbrella-0", cat: "daily", label: "Parapluie", w: 900, h: 600, kw: "parapluie umbrella rain parapluie objets du quotidien" },
  { id: "daily-umbrella-1", cat: "daily", label: "Parapluie", w: 900, h: 506, kw: "parapluie umbrella rain parapluie objets du quotidien" },
  { id: "daily-gift-0", cat: "daily", label: "Cadeau", w: 900, h: 644, kw: "cadeau gift box present cadeau objets du quotidien" },
  { id: "daily-gift-1", cat: "daily", label: "Cadeau", w: 900, h: 448, kw: "cadeau gift box present cadeau objets du quotidien" },
  { id: "daily-basket-0", cat: "daily", label: "Panier", w: 900, h: 600, kw: "panier wicker basket panier objets du quotidien" },
  { id: "daily-basket-1", cat: "daily", label: "Panier", w: 900, h: 600, kw: "panier wicker basket panier objets du quotidien" },
  { id: "daily-cart-0", cat: "daily", label: "Chariot", w: 900, h: 601, kw: "chariot shopping cart chariot objets du quotidien" },
  { id: "daily-cart-1", cat: "daily", label: "Chariot", w: 900, h: 600, kw: "chariot shopping cart chariot objets du quotidien" },
  { id: "daily-car-0", cat: "daily", label: "Voiture", w: 900, h: 600, kw: "voiture car automobile voiture objets du quotidien" },
  { id: "daily-car-1", cat: "daily", label: "Voiture", w: 900, h: 600, kw: "voiture car automobile voiture objets du quotidien" },
  { id: "daily-bike-0", cat: "daily", label: "Vélo", w: 900, h: 640, kw: "velo bicycle velo objets du quotidien" },
  { id: "daily-bike-1", cat: "daily", label: "Vélo", w: 900, h: 675, kw: "velo bicycle velo objets du quotidien" },
  { id: "daily-bus-0", cat: "daily", label: "Bus", w: 900, h: 570, kw: "bus city bus bus objets du quotidien" },
  { id: "daily-bus-1", cat: "daily", label: "Bus", w: 900, h: 564, kw: "bus city bus bus objets du quotidien" },
  { id: "daily-traffic-0", cat: "daily", label: "Feu tricolore", w: 900, h: 600, kw: "feu tricolore traffic light feu tricolore objets du quotidien" },
  { id: "daily-traffic-1", cat: "daily", label: "Feu tricolore", w: 900, h: 675, kw: "feu tricolore traffic light feu tricolore objets du quotidien" },
  { id: "daily-streetlamp-0", cat: "daily", label: "Lampadaire", w: 900, h: 506, kw: "lampadaire street lamp lampadaire objets du quotidien" },
  { id: "daily-streetlamp-1", cat: "daily", label: "Lampadaire", w: 900, h: 600, kw: "lampadaire street lamp lampadaire objets du quotidien" },
  { id: "daily-mailbox-0", cat: "daily", label: "Boîte aux lettres", w: 675, h: 900, kw: "boite aux lettres mailbox post boite aux lettres objets du quotidien" },
  { id: "daily-mailbox-1", cat: "daily", label: "Boîte aux lettres", w: 900, h: 600, kw: "boite aux lettres mailbox post boite aux lettres objets du quotidien" },
  { id: "daily-bench-0", cat: "daily", label: "Banc", w: 900, h: 675, kw: "banc park bench banc objets du quotidien" },
  { id: "daily-bench-1", cat: "daily", label: "Banc", w: 900, h: 600, kw: "banc park bench banc objets du quotidien" },
];

/** URL de la photo (même origine — pas de ressource externe). */
export function photoSrc(p: StockPhoto): string {
  return `/stock/${p.id}.webp`;
}
