// Modèles — suite réseaux sociaux et communication de marque.
//
// Deuxième série pour les mêmes canaux, mais d'autres besoins : raconter,
// expliquer, corriger une rumeur, remercier, annoncer un départ. Les mises en
// page choisies ici sont celles qui restaient peu employées ailleurs, pour
// que le catalogue ne penche pas vers cinq compositions dominantes.

import type { Row } from "./design-templates";

export const ROWS_SOCIAL2: Row[] = [

  /* ══════════ Instagram — récit et coulisses ══════════ */

  ["colonnes", "portrait", "chic", "Instagram", "Récit d'atelier", { sur: "Journal", titre: "Pourquoi\non a arrêté\nde livrer\nen 24 heures", sous: "Ce n'était pas tenable, et ça se voyait.", items: ["Pendant deux ans, on a promis vingt-quatre heures. On tenait, mais au prix de soirées à onze heures et d'erreurs de préparation qu'il fallait rattraper la semaine suivante. Le service client passait ses journées à s'excuser.", "On est passé à quarante-huit heures en janvier. Les retours ont chuté de deux tiers, les colis partent complets, et personne ne finit après dix-neuf heures. Aucun client ne s'est plaint du délai."], meta: "MARS 2026 — ATELIER AUBÉPINE" }],
  ["colonnes", "portrait", "terre", "Instagram", "Portrait d'artisan", { sur: "Portrait", titre: "Jean,\nquarante-deux\nans de tour", sous: "Il n'a jamais eu de site, et ne compte pas en faire un.", items: ["Il a commencé à seize ans, chez son oncle, dans le même atelier qu'aujourd'hui. La machine a changé une fois, en 1994. Le reste est d'origine, y compris le tabouret, qu'il refuse de remplacer parce qu'il est « à la bonne hauteur ».", "On lui demande souvent s'il forme quelqu'un. Il répond qu'il attend la bonne personne, et qu'il l'a peut-être trouvée : depuis septembre, un apprenti vient trois jours par semaine, et il commence à ne plus regarder ses mains."], meta: "PHOTOGRAPHIES : STUDIO VERRIER" }],
  ["colonnes", "carre", "clair", "Instagram", "Mise au point", { sur: "Mise au point", titre: "Non,\nnous n'avons\npas été\nrachetés", sous: "La rumeur circule, autant y répondre franchement.", items: ["Nous restons détenus à cent pour cent par les deux personnes qui ont créé l'atelier en 2019. Aucune part n'a été cédée, aucune discussion n'est en cours, et rien ne changerait dans notre façon de travailler si c'était le cas.", "Ce qui a changé, c'est notre distributeur pour la Belgique. C'est probablement de là que vient la confusion. Nous répondons volontiers à toute question précise en message privé."], meta: "L'ÉQUIPE — 12 AVRIL 2026" }],
  ["retro", "carre", "chaud", "Instagram", "Archive maison", { sur: "1978", titre: "Le même\ncomptoir", sous: "Il a changé trois fois de place, jamais de propriétaire." }],
  ["retro", "portrait", "terre", "Instagram", "Souvenir d'ouverture", { sur: "Il y a dix ans", titre: "Premier\njour", sous: "Deux chaises, un four, et personne pendant trois heures." }],
  ["annonce", "carre", "vif", "Instagram", "Nouveauté produit", { emoji: "🧴", gros: "NEW", titre: "Le savon\nsolide\narrive", sous: "Sans emballage plastique, saponifié à froid, tient trois mois.", items: ["Zéro plastique", "Fait à Bordeaux", "3 mois d'usage"] }],
  ["annonce", "portrait", "nature", "Instagram", "Arrivage de saison", { emoji: "🍯", gros: "RÉCOLTE", titre: "Le miel\nde châtaignier\nest arrivé", sous: "Récolté en juillet, en quantité limitée, comme chaque année.", items: ["Ruchers locaux", "Non chauffé", "Pot de 500 g"] }],
  ["annonce", "carre", "froid", "Instagram", "Nouvelle fonction", { emoji: "⚡", gros: "MAJ", titre: "Les rapports\nse planifient", sous: "Choisissez le jour, l'heure et les destinataires. Le reste se fait sans vous.", items: ["Sans surcoût", "Tous les plans", "Dispo aujourd'hui"] }],
  ["duo", "carre", "tech", "Instagram", "Deux chiffres", { gros: "2026", items: ["1 240|commandes préparées", "0|rupture de stock"] }],
  ["duo", "portrait", "vif", "Instagram", "Deux chiffres contrastés", { gros: "BILAN", items: ["+34 %|de clients qui reviennent", "-18 %|de retours produits"] }],
  ["mosaique", "carre", "pastel", "Instagram", "Message court", { titre: "On revient\nlundi", sous: "L'atelier ferme trois jours. Les messages seront lus au retour." }],
  ["mosaique", "portrait", "chaud", "Instagram", "Remerciement de fin d'année", { titre: "Merci\npour 2026", sous: "Quatre mille commandes, et pas une seule perdue en route." }],
  ["organique", "portrait", "pastel", "Instagram", "Invitation au calme", { sur: "Prenez le temps", titre: "Faites\nune chose\nà la fois", sous: "C'est le conseil le plus rebattu, et le seul qui ait jamais marché.", cta: "À relire lundi matin" }],
  ["organique", "carre", "nature", "Instagram", "Rappel bien-être", { sur: "Rappel", titre: "Buvez\nde l'eau,\nvraiment", sous: "Pas du café, pas du thé. De l'eau, un grand verre, maintenant.", cta: "C'est tout pour aujourd'hui" }],
  ["neon", "carre", "tech", "Instagram", "Annonce de direct", { gros: "LIVE", titre: "Ça commence dans dix minutes", sous: "Une heure de questions, sans montage et sans filtre." }],
  ["neon", "portrait", "vif", "Instagram", "Ouverture nocturne", { gros: "23H", titre: "Ouvert tard tous les jeudis", sous: "Cuisine jusqu'à 22 h 30, comptoir jusqu'à minuit." }],
  ["ombredure", "portrait", "vif", "Instagram", "Slogan de campagne", { sur: "Campagne", titre: "ACHETEZ\nMOINS", sous: "Nous préférons vendre une pièce qui dure dix ans que dix qui durent un an.", meta: "ATELIER BERTHIER" }],
  ["bloc", "portrait", "sombre", "Instagram", "Affiche de manifeste", { titre: "PLUS\nCHER.\nMIEUX.", sous: "Nos prix ne baisseront pas. Nos matières et nos salaires non plus.", meta: "ATELIER BERTHIER — BORDEAUX" }],
  ["coins", "carre", "chic", "Instagram", "Cadrage produit", { sur: "Nouvelle pièce", titre: "Le carnet\nrelié main", sous: "Papier ivoire 120 g, couture apparente, 160 pages.", meta: "EN LIGNE VENDREDI — 45 €" }],
  ["coins", "portrait", "sombre", "Instagram", "Cadrage portrait", { sur: "Portrait", titre: "Sofia,\nvingt ans\nde métier", sous: "Elle a formé onze apprentis. Neuf exercent encore.", meta: "SÉRIE « LES MAINS DU MÉTIER »" }],
  ["empilement", "portrait", "froid", "Instagram", "Cinq idées reçues", { titre: "Cinq idées\nreçues", sous: "Entendues cette semaine, corrigées ici.", items: ["« C'est plus cher qu'ailleurs »", "« Ça ne se répare pas »", "« C'est fabriqué en Asie »", "« Il faut commander trois mois avant »", "« C'est réservé aux professionnels »"], meta: "Réponses détaillées dans le carrousel" }],
  ["empilement", "carre", "chaud", "Instagram", "Cinq étapes du produit", { titre: "D'où\nvient\nce savon", sous: "Cinq étapes, toutes à moins de cent kilomètres.", items: ["Huile d'olive du Gers", "Lait d'ânesse de Dordogne", "Saponification à froid à Bordeaux", "Séchage quatre semaines", "Découpe et emballage à la main"], meta: "Traçabilité complète sur la fiche produit" }],
  ["bulle", "portrait", "pastel", "Instagram", "Question d'abonné", { sur: "Vous m'avez demandé", titre: "« Comment vous faites pour tenir vos prix ? »", auteur: "@camille_d", sous: "Réponse complète dans le carrousel" }],
  ["bulle", "carre", "froid", "Instagram", "Réponse à un commentaire", { sur: "Bonne question", titre: "« Pourquoi vous ne faites pas de soldes ? »", auteur: "@noe_t", sous: "Parce qu'un prix juste toute l'année vaut mieux qu'un prix gonflé onze mois" }],
  ["demi", "portrait", "sombre", "Instagram", "Annonce en deux temps", { sur: "Information", gros: "ON\nDÉMÉNAGE", titre: "L'atelier s'installe rue des Forges", sous: "Deux fois plus grand, toujours à Bordeaux, à cinq minutes à pied.", meta: "FERMETURE DU 3 AU 10 JUIN" }],
  ["demi", "carre", "chaud", "Instagram", "Annonce d'ouverture", { sur: "Ça y est", gros: "ON\nOUVRE", titre: "Le samedi 14 juin, à dix heures", sous: "Café offert toute la journée, visite de l'atelier toutes les heures.", meta: "4 RUE DES FORGES — BORDEAUX" }],
  ["panneau", "portrait", "chic", "Instagram", "Présentation de gamme", { gros: "03", sur: "Nouvelle gamme", titre: "Trois pièces,\nun seul cuir", sous: "Portefeuille, porte-cartes et trousse, taillés dans les chutes des grandes pièces.", meta: "Dès le 12 mai, en série limitée" }],
  ["panneau", "carre", "froid", "Instagram", "Présentation de service", { gros: "→", sur: "Nouveau service", titre: "La réparation\nà vie", sous: "Toute pièce vendue depuis 2019 est réparée gratuitement, sans limite de temps.", meta: "Envoi et retour à notre charge" }],
  ["centre", "carre", "chic", "Instagram", "Message sobre", { sur: "Fermeture", titre: "L'atelier\nest fermé\naujourd'hui", sous: "Nous serons de retour demain à neuf heures." }],
  ["centre", "portrait", "sombre", "Instagram", "Hommage", { sur: "En mémoire", titre: "Jean Berthier\n1948 — 2026", sous: "Il a tenu cet atelier quarante-deux ans. Nous fermons trois jours." }],
  ["diapo", "portrait", "clair", "Instagram", "Points d'information", { sur: "À savoir", titre: "Ce qui change\nau 1er juin", items: ["La livraison passe à 48 h au lieu de 24", "Les frais de port deviennent gratuits dès 60 €", "Le retrait en boutique reste immédiat", "Aucun prix n'augmente"], sous: "Les commandes déjà passées ne sont pas concernées.", meta: "Questions en commentaires" }],
  ["diapo", "carre", "froid", "Instagram", "Récapitulatif de semaine", { sur: "Cette semaine", titre: "Quatre choses\nà retenir", items: ["Les nouveautés sortent jeudi à 10 h", "La boutique ferme lundi pour inventaire", "L'atelier est visitable samedi matin", "Le service client répond jusqu'à 19 h"], sous: "Tout est aussi rappelé en story chaque matin.", meta: "@votrecompte" }],
  ["journal", "portrait", "clair", "Instagram", "Post façon journal", { sur: "LA LETTRE DE L'ATELIER", meta: "NUMÉRO 8 — AVRIL 2026", titre: "Ce qu'on a appris\nen cinq ans", sous: "Cinq ans d'atelier, quatre erreurs coûteuses, et une chose qu'on referait à l'identique.", items: ["La première erreur a été de vouloir tout produire nous-mêmes, y compris ce qu'on ne savait pas faire. Les six premiers mois de fermetures éclair sont partis à la benne. Depuis, on achète ce qu'on ne maîtrise pas.", "La deuxième a été de croire qu'un prix bas ferait le volume. Il a fait des clients qui partaient au premier concurrent moins cher, et des marges qui ne payaient pas les salaires.", "Ce qu'on referait : ouvrir petit, sans emprunt, et attendre d'avoir des clients avant d'avoir un local. Ça a coûté deux ans de lenteur, et ça nous a probablement sauvés."], cta: "PROCHAINE LETTRE EN JUIN — INSCRIPTION EN BIO" }],

  /* ══════════ LinkedIn — suite ══════════ */

  ["colonnes", "li", "clair", "LinkedIn", "Post long format", { sur: "Retour d'expérience", titre: "On a supprimé\nles entretiens\nannuels", sous: "Voilà ce que ça a donné au bout de deux ans.", items: ["L'entretien annuel servait surtout à justifier des décisions déjà prises en septembre. Personne n'y croyait, tout le monde y consacrait deux journées. Nous l'avons remplacé par un point d'une demi-heure tous les deux mois, sans formulaire.", "Deux ans plus tard : les augmentations sont décidées à date fixe et communiquées à tous, le turnover a baissé de six points, et plus personne ne découvre un reproche en février sur un fait de mai."], meta: "SOFIA BERNARD — DIRECTRICE DES OPÉRATIONS" }],
  ["colonnes", "li", "sombre", "LinkedIn", "Analyse de secteur", { sur: "Analyse", titre: "Pourquoi\nles délais\nse dégradent\npartout", sous: "Trois causes, dont deux sur lesquelles on peut agir.", items: ["La première cause est structurelle : les carnets de commandes se sont allongés pendant que les effectifs restaient stables. Rien à faire à court terme, sinon arbitrer ce qu'on refuse.", "Les deux autres sont internes : des devis validés sans vérifier la charge, et des priorités qui changent en cours de mois. Les deux se corrigent en une réunion hebdomadaire, à condition qu'elle tranche vraiment."], meta: "ANALYSE PUBLIÉE LE 12 AVRIL 2026" }],
  ["cv", "cv", "froid", "LinkedIn", "CV opérations", { gros: "AR", titre: "Aline\nRoux", sur: "RESPONSABLE LOGISTIQUE", sous: "06 00 00 00 00\naline@exemple.fr\nBordeaux\nPermis C", meta: "PARCOURS", items: ["Responsable logistique — Aubépine|2022 à aujourd'hui. Refonte du circuit de préparation, délai divisé par trois sans recrutement.", "Chef d'équipe — Groupe Roux|2018-2022. Encadrement de douze préparateurs, deux sites.", "Préparatrice de commandes — Studio Verrier|2015-2018. Poste terrain, formation des nouveaux arrivants.", "Bac professionnel logistique|Lycée des Métiers, 2015."] }],
  ["cv", "cv", "sombre", "LinkedIn", "CV direction", { gros: "MV", titre: "Marc\nVidal", sur: "DIRECTEUR GÉNÉRAL", sous: "06 00 00 00 00\nmarc@exemple.fr\nBordeaux\nAdministrateur de sociétés", meta: "PARCOURS", items: ["Directeur général — Aubépine|2021 à aujourd'hui. Quarante personnes, croissance de 18 % par an sans levée de fonds.", "Directeur des opérations — Groupe Roux|2016-2021. Trois sites, 120 personnes, redressement d'une activité déficitaire.", "Responsable de production — Studio Verrier|2011-2016. Industrialisation de deux gammes.", "École d'ingénieurs|Promotion 2011."] }],
  ["chapitre", "li", "tech", "LinkedIn", "Ouverture d'étude", { gros: "01", sur: "Étude", titre: "Le vrai coût\ndu turnover", sous: "Recrutement, intégration, perte de compétence : nous avons chiffré chaque poste sur trois ans.", meta: "ÉTUDE INTERNE — AVRIL 2026" }],
  ["chapitre", "li", "chic", "LinkedIn", "Ouverture de série", { gros: "02", sur: "Série", titre: "Diriger\nsans réunion", sous: "Deuxième volet : ce qui remplace concrètement une réunion hebdomadaire de deux heures.", meta: "SÉRIE EN QUATRE VOLETS" }],
  ["score", "li", "vif", "LinkedIn", "Comparaison chiffrée", { sur: "AVANT / APRÈS", items: ["2024", "2026"], gros: "12-2", titre: "Le délai moyen est passé de douze jours à deux", meta: "MÊME ÉQUIPE, MÊME BUDGET" }],
  ["playlist", "li", "clair", "LinkedIn", "Sélection de ressources", { emoji: "📚", titre: "Six lectures\nutiles", sous: "Ce qui m'a réellement servi cette année", items: ["Sur le pilotage d'équipe|1", "Sur le recrutement|2", "Sur la tarification|3", "Sur la logistique|4", "Sur le droit du travail|5", "Sur la comptabilité|6"], meta: "Références complètes en commentaire" }],
  ["damier", "li", "sombre", "LinkedIn", "Annonce forte", { sur: "Décision", titre: "NOS SALAIRES\nSONT PUBLICS", sous: "Grille complète, du premier au dernier échelon, consultable par tout candidat.", meta: "DEPUIS LE 1ER JANVIER 2026" }],
  ["rayures", "li", "vif", "LinkedIn", "Annonce de recrutement", { sur: "Quatre postes", titre: "ON\nRECRUTE", sous: "Opérations, technique, relation client et logistique. Salaires affichés dans chaque offre.", meta: "TOUTES LES OFFRES SUR LA PAGE ENTREPRISE" }],
  ["vagues", "li", "froid", "LinkedIn", "Annonce apaisée", { sur: "Après trois ans", titre: "Je quitte\nl'entreprise", sous: "Départ choisi, sans amertume, et une passation de deux mois pour faire les choses correctement.", meta: "MERCI À TOUTE L'ÉQUIPE" }],
  ["montagne", "li", "nature", "LinkedIn", "Objectif d'entreprise", { sur: "Objectif 2027", titre: "Zéro\nplastique\nd'ici décembre", sous: "Quatre-vingt-deux pour cent atteints, le reste dépend de nos fournisseurs.", meta: "RAPPORT RSE PUBLIÉ CHAQUE TRIMESTRE" }],
  ["coupon", "li", "chaud", "LinkedIn", "Offre professionnelle", { gros: "-30%", sur: "PREMIÈRE MISSION", titre: "Pour les structures de moins de dix personnes", sous: "Sur le diagnostic initial, valable jusqu'au 30 juin, une fois par organisation.", meta: "PME30", cta: "Conditions détaillées sur demande" }],
  ["recette", "li", "clair", "LinkedIn", "Méthode détaillée", { titre: "Une réunion\nhebdomadaire\nqui sert", meta: "30 MINUTES — 6 PERSONNES MAXIMUM", sur: "IL FAUT", cta: "ON PROCÈDE", items: ["Un ordre du jour envoyé la veille", "Une personne qui tranche", "Un relevé de décisions écrit", "Un minuteur, vraiment", "Cinq minutes de chiffres, pas plus.", "Quinze minutes d'arbitrages.", "Cinq minutes de risques à venir.", "Cinq minutes de relecture des décisions."], sous: "Si elle dépasse trente minutes, c'est qu'elle n'a pas tranché." }],
  ["miniature", "large", "tech", "LinkedIn", "Vignette d'article", { emoji: "📉", titre: "LE COÛT\nCACHÉ", meta: "ÉTUDE 2026" }],
  ["miniature", "large", "vif", "LinkedIn", "Vignette de webinaire", { emoji: "🎥", titre: "PILOTER\nSANS RÉUNION", meta: "MARDI 12 H 30" }],

  /* ══════════ Story & Reel — suite ══════════ */

  ["retro", "story", "terre", "Story & Reel", "Story archive", { sur: "2016", titre: "Le premier\nlocal", sous: "Quinze mètres carrés, et déjà trop petit." }],
  ["annonce", "story", "vif", "Story & Reel", "Story nouveauté", { emoji: "🧦", gros: "NEW", titre: "Les chaussettes\nen laine", sous: "Tricotées en France, garanties deux ans, reprisées gratuitement.", items: ["Laine mérinos", "Fait en France", "Garantie 2 ans"] }],
  ["duo", "story", "tech", "Story & Reel", "Story deux chiffres", { gros: "AVRIL", items: ["312|commandes", "48 h|délai moyen"] }],
  ["mosaique", "story", "pastel", "Story & Reel", "Story merci", { titre: "Merci\npour hier", sous: "Trois cents personnes en une journée. On n'y croyait pas." }],
  ["organique", "story", "nature", "Story & Reel", "Story respiration", { sur: "Trois minutes", titre: "Posez\nle téléphone\nune minute", sous: "Vraiment une minute. Le reste peut attendre.", cta: "À refaire ce soir" }],
  ["panneau", "story", "chic", "Story & Reel", "Story présentation", { gros: "01", sur: "Nouveauté", titre: "Le carnet\nrelié\nmain", sous: "Papier ivoire 120 g, couture apparente, 160 pages, 45 €.", meta: "En ligne vendredi à 10 h" }],
  ["centre", "story", "sombre", "Story & Reel", "Story information", { sur: "Information", titre: "Fermé\ncet après-midi", sous: "Réouverture demain à neuf heures. Les commandes en ligne ne sont pas affectées." }],
  ["coins", "story", "chic", "Story & Reel", "Story cadrage", { sur: "Coulisses", titre: "Une image,\ntrois heures\nde lumière", sous: "Aucune retouche, juste beaucoup de patience.", meta: "STUDIO VERRIER" }],
  ["empilement", "story", "chaud", "Story & Reel", "Story cinq points", { titre: "Cinq choses\nà savoir", sous: "Avant de commander pour Noël.", items: ["Commandes jusqu'au 20 décembre", "Emballage cadeau offert", "Retrait possible jusqu'au 24 à 16 h", "Retours acceptés jusqu'au 15 janvier", "Carte cadeau disponible en boutique"], meta: "Tout est aussi rappelé en bio" }],
  ["bloc", "story", "vif", "Story & Reel", "Story blocs", { titre: "TROIS\nJOURS\nSEULEMENT", sous: "Portes ouvertes de l'atelier, du vendredi au dimanche.", meta: "4 RUE DES FORGES — 10 H À 19 H" }],
  ["journal", "story", "clair", "Story & Reel", "Story lettre", { sur: "LA LETTRE", meta: "AVRIL 2026 — NUMÉRO 8", titre: "Ce qui change\nce mois-ci", sous: "Trois informations utiles, et une décision qui va se voir.", items: ["Les délais passent à quarante-huit heures, volontairement. Nous préférons annoncer deux jours et les tenir que promettre un jour et échouer une fois sur trois.", "Les frais de port deviennent gratuits dès soixante euros, contre quatre-vingts auparavant. Ce n'est pas une promotion, c'est un changement permanent.", "Enfin, l'atelier sera visitable chaque premier samedi du mois, sur inscription, par groupes de dix personnes."], cta: "INSCRIPTION À LA LETTRE EN BIO" }],
  ["recette", "story", "terre", "Story & Reel", "Story recette express", { titre: "Pâtes\naux poireaux", meta: "20 MIN — 2 PARTS — TRÈS FACILE", sur: "IL FAUT", cta: "ON FAIT", items: ["2 poireaux", "200 g de pâtes", "1 cuillère de crème", "Parmesan, poivre", "Émincez et faites fondre 10 min à couvert.", "Cuisez les pâtes, gardez un peu d'eau.", "Mélangez avec la crème et l'eau de cuisson.", "Parmesan, poivre, servez immédiatement."], sous: "Meilleur avec le blanc ET le vert des poireaux." }],
  ["cartecadeau", "story", "chaud", "Story & Reel", "Story carte cadeau", { sur: "Idée cadeau", gros: "40 €", titre: "Quand on ne sait vraiment pas quoi offrir", meta: "DISPONIBLE EN BOUTIQUE", sous: "Valable deux ans, utilisable en plusieurs fois." }],
  ["coupon", "story", "vif", "Story & Reel", "Story bon", { gros: "-10%", sur: "STORY UNIQUEMENT", titre: "Pour ceux qui regardent jusqu'au bout", sous: "Valable vingt-quatre heures, sur tout le site, une fois par personne.", meta: "STORY10", cta: "Le code expire demain à minuit" }],
  ["playlist", "story", "vif", "Story & Reel", "Story sélection", { emoji: "🔥", titre: "Les six\nqui partent\nle plus vite", sous: "Classement des trente derniers jours", items: ["Sac Chanvre|1", "Trousse Lin|2", "Ceinture cuir|3", "Carnet relié|4", "Tablier atelier|5", "Porte-clés|6"], meta: "Réassort chaque mardi" }],

  /* ══════════ YouTube — suite ══════════ */

  ["miniature", "yt", "nature", "YouTube", "Miniature jardin", { emoji: "🌱", titre: "TOUT\nSEMÉ", meta: "SANS SERRE" }],
  ["miniature", "yt", "terre", "YouTube", "Miniature bricolage", { emoji: "🪚", titre: "FAIT\nMAISON", meta: "80 € DE BOIS" }],
  ["miniature", "yt", "chic", "YouTube", "Miniature portrait", { emoji: "👤", titre: "42 ANS\nDE MÉTIER", meta: "PORTRAIT" }],
  ["miniature", "yt", "clair", "YouTube", "Miniature explication", { emoji: "❓", titre: "POURQUOI\nÇA RATE", meta: "EXPLICATION" }],
  ["neon", "yt", "tech", "YouTube", "Écran de direct", { gros: "LIVE", titre: "Questions ouvertes pendant une heure", sous: "Le tchat est ouvert, les questions sont prises dans l'ordre." }],
  ["diapo", "yt", "clair", "YouTube", "Écran de récapitulatif", { sur: "Récapitulatif", titre: "Ce qu'il faut\nretenir", items: ["Le matériel importe moins que la lumière", "Une prise préparée vaut trois prises ratées", "Le montage ne rattrape pas un mauvais son", "Publier régulièrement bat publier parfaitement"], sous: "Les liens du matériel cité sont en description.", meta: "Abonnez-vous pour la suite" }],
  ["duo", "yt", "vif", "YouTube", "Écran deux chiffres", { gros: "1 AN", items: ["52|vidéos publiées", "3|réellement rentables"] }],
  ["colonnes", "yt", "sombre", "YouTube", "Écran de texte", { sur: "Avertissement", titre: "Ce que\ncette vidéo\nne dit pas", sous: "Par honnêteté, autant le préciser avant de commencer.", items: ["Ce test a été fait sur un seul exemplaire, acheté par mes soins, sur six mois d'usage quotidien. Il ne dit rien de la fiabilité à trois ans, ni des variations entre séries de production.", "Aucune marque n'a été contactée, aucun exemplaire n'a été fourni. Si cela change un jour, ce sera annoncé dès la première seconde de la vidéo concernée."], meta: "CHAÎNE SANS PARTENARIAT DEPUIS 2021" }],
  ["banniere", "ytban", "terre", "YouTube", "Bannière artisanat", { gros: "🪵", titre: "Le bois, expliqué correctement", sous: "Techniques, outils et chantiers réels, filmés du premier au dernier geste.", cta: "Une vidéo tous les quinze jours" }],
  ["banniere", "ytban", "clair", "YouTube", "Bannière pédagogique", { gros: "📘", titre: "Comprendre avant d'apprendre", sous: "Des explications lentes, sur des sujets qu'on croit avoir compris.", cta: "Nouvelle vidéo le mardi" }],
  ["souligne", "ytban", "vif", "YouTube", "Bannière trois mots", { sur: "Cette chaîne", titre: "Tester.\nDouter.\nRefaire.", sous: "Aucun produit offert, aucun lien affilié, aucune conclusion pressée.", meta: "Nouvelle vidéo chaque jeudi" }],

  /* ══════════ Facebook & Pinterest — suite ══════════ */

  ["journal", "couv", "clair", "Facebook", "Couverture façon journal", { sur: "LE JOURNAL DU QUARTIER", meta: "NUMÉRO 12 — JUIN 2026", titre: "La rue rouvre\nà pied", sous: "Après six mois de travaux, la rue des Halles devient piétonne du lundi au samedi.", items: ["Les commerçants attendaient cette décision depuis 2019. Les premiers relevés montrent une fréquentation en hausse de vingt-trois pour cent le samedi.", "Le stationnement reste possible au parking Vauban, dont les deux premières heures deviennent gratuites, avec une navette toutes les vingt minutes.", "Les livraisons sont autorisées avant dix heures. Un bilan est prévu en décembre, en réunion publique ouverte à tous les riverains."], cta: "PROCHAIN NUMÉRO EN SEPTEMBRE" }],
  ["retro", "couv", "chaud", "Facebook", "Couverture rétro", { sur: "Depuis 1971", titre: "Le goût\nd'avant", sous: "Même four, même farine, même patron." }],
  ["annonce", "large", "nature", "Facebook", "Arrivage de saison", { emoji: "🍏", gros: "ARRIVAGE", titre: "Les pommes\nde la Combe", sous: "Cueillies cette semaine, vendues au kilo, jusqu'à épuisement.", items: ["Sans traitement", "Récolte 2026", "Vente au kilo"] }],
  ["empilement", "large", "clair", "Facebook", "Cinq informations", { titre: "Cinq infos\nde la semaine", sous: "Tout ce qu'il faut savoir avant samedi.", items: ["La boutique ferme lundi pour inventaire", "Le marché est déplacé place du Port", "Les inscriptions ouvrent mercredi", "La braderie se tient samedi", "Le parking reste gratuit tout le mois"], meta: "Plus de détails à l'accueil ou au 05 56 00 00 00" }],
  ["coins", "pin", "chic", "Pinterest", "Épingle cadrage", { sur: "Inspiration", titre: "Une pièce,\nune seule\ncouleur", sous: "Trois nuances du même ton, et rien d'autre. La lumière fait le reste.", meta: "RÉFÉRENCES DE PEINTURE EN DESCRIPTION" }],
  ["recette", "pin", "chaud", "Pinterest", "Épingle recette sucrée", { titre: "Gâteau au yaourt,\nla vraie recette", meta: "45 MIN — 8 PARTS — TRÈS FACILE", sur: "IL VOUS FAUT", cta: "ON Y VA", items: ["1 pot de yaourt nature", "2 pots de sucre", "3 pots de farine", "3 œufs, 1 sachet de levure", "Mélangez yaourt, sucre et œufs.", "Ajoutez farine et levure, sans insister.", "Versez dans un moule beurré.", "35 min à 180 °C, testez au couteau."], sous: "Le demi-pot d'huile change tout : ne le sautez pas." }],
  ["empilement", "pin", "pastel", "Pinterest", "Épingle cinq astuces", { titre: "Cinq astuces\nde rangement", sous: "Testées dans un appartement de 38 m².", items: ["Ranger par usage, pas par catégorie", "Un seul tiroir fourre-tout, assumé", "Des boîtes transparentes, toujours", "Le haut des placards pour le saisonnier", "Une règle : un entré, un sorti"], meta: "Détails et sources dans l'article" }],
  ["colonnes", "pin", "terre", "Pinterest", "Épingle article", { sur: "Article", titre: "Pourquoi\nvos plantes\nmeurent\nen hiver", sous: "Ce n'est presque jamais le froid.", items: ["Neuf fois sur dix, c'est l'excès d'eau. La plante ralentit sa croissance dès que la lumière baisse, mais on continue d'arroser au même rythme. Les racines pourrissent avant que les feuilles ne jaunissent.", "La règle est simple : en hiver, on arrose quand la terre est sèche sur trois centimètres de profondeur, pas selon le calendrier. Pour la plupart des plantes d'intérieur, cela revient à diviser la fréquence par deux ou trois."], meta: "ARTICLE COMPLET SUR LE BLOG" }],
  ["chapitre", "pin", "nature", "Pinterest", "Épingle ouverture de guide", { gros: "01", sur: "Guide", titre: "Choisir\nl'exposition", sous: "La première chose à regarder, avant l'espèce, avant le pot, avant tout le reste.", meta: "GUIDE EN SIX PARTIES" }],

];
